SSAGES: SSAGES::Chebyshev Class Reference
SSAGES::Chebyshev Class Reference
Defines the class of Chebyshev polynomials.
#include <Basis.h>
Public Member Functions
Chebyshev (unsigned int polyOrd, double boundLow, double boundUp, unsigned int nbins)
Constructor.
double ChangeVariable (double x)
Transforms variable from absolute value to [-1,1] between boundaries.
double Evaluate (double x, int n)
Calculates the output of the basis function.
double EvalGrad (double x, int n)
Calculates the gradient of the basis function.
double Weight (double x)
Calculates the gradient of the basis function.
double GetNorm (int)
Gets the norm of the basis function.
Public Member Functions inherited from SSAGES::BasisFunction
BasisFunction (unsigned int polyOrd, unsigned int nbins, bool isFinite, bool zeroOrder, double boundLow, double boundUp)
Constructor.
unsigned int GetOrder ()
Gets the order of the current polynomial.
unsigned int GetBins ()
Gets the number of bins for the discretization.
bool GetZeroOrder ()
Gets the flag for constant-order polynomials.
double GetLower ()
Gets the lower bound on the CV.
double GetUpper ()
Gets the upper bound on the CV.
double GetRange ()
Gets the magnitude of the range of bounds.
virtual ~BasisFunction ()
Destructor.
Static Public Member Functions
static Chebyshev * Build (const Json::Value &json, const std::string &path, unsigned int nbins)
Build BasisFunction from JSON value.
Static Public Member Functions inherited from SSAGES::BasisFunction
static BasisFunction * Build (const Json::Value &json, const std::string &path, unsigned int nbins)
Build BasisFunction from JSON value.
Additional Inherited Members
Protected Attributes inherited from SSAGES::BasisFunction
unsigned int polyOrd_
Order of the polynomial.
unsigned int nbins_
Number of bins.
bool isFinite_
Flag for finite-range polynomials.
bool zeroOrder_
Flag for constant-order polynomials.
double boundLow_
Lower bound on CV.
double boundUp_
Upper bound on CV.
Detailed Description
Defines the class of Chebyshev polynomials.
Definition at line 201 of file Basis.h.
Constructor & Destructor Documentation
Chebyshev()
SSAGES::Chebyshev::Chebyshev (unsigned int polyOrd, double boundLow, double boundUp, unsigned int nbins) inline
Constructor.
Parameters
polyOrd Order of Chebyshev polynomial.
boundLow Lower bounds of restraint springs.
boundUp Upper bounds of restraint springs.
nbins Number of bins.
Constructs an instance of the Chebyshev function class.
Definition at line 215 of file Basis.h.
                                                                                              :
         BasisFunction(polyOrd, nbins, true, false, boundLow, boundUp)
         {
         }
Referenced by Build().
Member Function Documentation
Build()
Chebyshev * SSAGES::Chebyshev::Build (const Json::Value & json, const std::string & path, unsigned int nbins) static
Build BasisFunction from JSON value.
Build the Chebyshev polynomial
Parameters
json JSON value node.
path Path for JSON path specification.
nbins Number of bins.
Returns
Pointer to new BasisFunction.
Definition at line 22 of file Basis.cpp.
     {
         Json::ObjectRequirement validator;
         Json::Value schema;
         Json::CharReaderBuilder rbuilder;
         Json::CharReader* reader = rbuilder.newCharReader();
         reader->parse(JsonSchema::ChebyshevBasis.c_str(),
                       JsonSchema::ChebyshevBasis.c_str() + JsonSchema::ChebyshevBasis.size(),
                       &schema, nullptr);
         validator.Parse(schema, path);
         //Validate Inputs
         validator.Validate(json, path);
         if(validator.HasErrors())
             throw BuildException(validator.GetErrors());
         return new Chebyshev(
                 json["polynomial_order"].asInt(),
                 json["lower_bound"].asDouble(),
                 json["upper_bound"].asDouble(),
                 nbin
             );
     }
References Chebyshev(), Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), and Json::ObjectRequirement::Validate().
Referenced by SSAGES::BasisFunction::Build().
ChangeVariable()
double SSAGES::Chebyshev::ChangeVariable (double x) inline
Transforms variable from absolute value to [-1,1] between boundaries.
Parameters
x Variable to transform.
Returns
Relative value between lower (-1) and upper (1) bounds on CV.
Definition at line 226 of file Basis.h.
         {
             return (x-boundLow_)*2.0/(boundUp_ - boundLow_)-1.0;
         }
References SSAGES::BasisFunction::boundLow_, and SSAGES::BasisFunction::boundUp_.
Referenced by EvalGrad(), Evaluate(), and Weight().
EvalGrad()
double SSAGES::Chebyshev::EvalGrad (double val, int order) inline virtual
Calculates the gradient of the basis function.
Parameters
val Input value for function.
order Order of the polynomial.
Returns
Gradient for function.
Reimplemented from SSAGES::BasisFunction.
Definition at line 239 of file Basis.h.
         {
             double xMod = ChangeVariable(x);
             return n == 0 ? 0.0 :
                     n == 1 ? 1.0 :
                     2.0*(Evaluate(x,n-1) + xMod * EvalGrad(x,n-1)) - EvalGrad(x,n-2);
         }
References ChangeVariable(), and Evaluate().
Evaluate()
double SSAGES::Chebyshev::Evaluate (double val, int order) inline virtual
Calculates the output of the basis function.
Parameters
val Input value for function.
order Order of the polynomial.
Returns
Output value for function.
Reimplemented from SSAGES::BasisFunction.
Definition at line 231 of file Basis.h.
         {
             double xMod = ChangeVariable(x);
             return n == 0 ? 1.0 :
                     n == 1 ? xMod :
                     2.0*xMod*Evaluate(x,n-1) - Evaluate(x,n-2);
         }
References ChangeVariable().
Referenced by EvalGrad().
GetNorm()
double SSAGES::Chebyshev::GetNorm (int order) inline virtual
Gets the norm of the basis function.
Parameters
order Order of the polynomial.
Returns
Norm of a specific order of polynomial.
Reimplemented from SSAGES::BasisFunction.
Definition at line 253 of file Basis.h.
         {
             return 2.0/M_PI;
         }
Weight()
double SSAGES::Chebyshev::Weight (double val) inline virtual
Calculates the gradient of the basis function.
Parameters
val Input value for function.
Returns
Gradient of function.
Reimplemented from SSAGES::BasisFunction.
Definition at line 247 of file Basis.h.
         {
             double xMod = ChangeVariable(x);
             return 1.0/sqrt(1.0-xMod*xMod);
         }
References ChangeVariable().
The documentation for this class was generated from the following files:
/home/michael/development/SSAGES/src/Utility/Basis.h
/home/michael/development/SSAGES/src/Utility/Basis.cpp