SSAGES: SSAGES::ParticleCoordinateCV Class Reference
SSAGES::ParticleCoordinateCV Class Reference
CVs
Collective variable on a particle coordinate.
#include <ParticleCoordinateCV.h>
Public Member Functions
ParticleCoordinateCV (const Label &atomids, Dimension dim)
Constructor.
void Initialize (const Snapshot &snapshot) override
Initialize necessary variables.
void Evaluate (const Snapshot &snapshot) override
Evaluate the CV.
double GetPeriodicValue (double Location) const override
Return value taking periodic boundary conditions into account.
double GetDifference (const double Location) const override
Return difference considering periodic boundaries.
Public Member Functions inherited from SSAGES::CollectiveVariable
CollectiveVariable ()
Constructor.
virtual ~CollectiveVariable ()
Destructor.
virtual void Initialize (const class Snapshot &)
Initialize CV.
virtual void Evaluate (const class Snapshot &)=0
Evaluate CV.
double GetValue () const
Get current value of the CV.
virtual double GetMinimumImage (double) const
Returns the minimum image of a CV based on the input location.
const std::vector< Vector3 > & GetGradient () const
Get current gradient of the CV.
const Matrix3 & GetBoxGradient () const
Get gradient contribution to box.
const std::array< double, 2 > & GetBoundaries ()
Get CV boundaries.
Static Public Member Functions
static ParticleCoordinateCV * Build (const Json::Value &json, const std::string &path)
Set up collective variable.
Static Public Member Functions inherited from SSAGES::CollectiveVariable
static CollectiveVariable * BuildCV (const Json::Value &json, const std::string &path)
Set up collective variable.
Private Attributes
Label atomids_
IDs of atoms of interest.
Dimension dim_
Index of dimension.
Additional Inherited Members
Protected Attributes inherited from SSAGES::CollectiveVariable
std::vector< Vector3 > grad_
Gradient vector dCv/dxi.
Matrix3 boxgrad_
Gradient w.r.t box vectors dCv/dHij.
double val_
Current value of CV.
std::array< double, 2 > bounds_
Bounds on CV.
Detailed Description
Collective variable on a particle coordinate.
This will return the value of either the x, y, or z coordinate, depending on the user specification for a defined particle, which is a collection of one or more atoms.
Definition at line 40 of file ParticleCoordinateCV.h.
Constructor & Destructor Documentation
ParticleCoordinateCV()
SSAGES::ParticleCoordinateCV::ParticleCoordinateCV (const Label & atomids, Dimension dim) inline
Constructor.
Parameters
atomids Atom ID's of interest.
dim Index of dimension.
Construct a particle coordinate CV. The atomids specify a vector of the atom ID's of interest, and index specifies the dimension to report (x,y,z).
Todo:
Bounds needs to be an input.
Definition at line 60 of file ParticleCoordinateCV.h.
                                                                   :
         atomids_(atomids), dim_(dim)
         {}
Member Function Documentation
Build()
static ParticleCoordinateCV* SSAGES::ParticleCoordinateCV::Build (const Json::Value & json, const std::string & path) inline static
Set up collective variable.
Parameters
json JSON input value.
path Path for JSON path specification.
Returns
Pointer to the CV built by this function. nullptr in case of unknown error.
Builds a CV from a JSON node. Returns a pointer to the built cv. If an unknown error is encountered, this function will return a nullptr, but generally it will throw a BuildException on failure.
Warning
Object lifetime is the caller's responsibility.
Definition at line 168 of file ParticleCoordinateCV.h.
         {
             Json::ObjectRequirement validator;
             Json::Value schema;
             Json::CharReaderBuilder rbuilder;
             Json::CharReader* reader = rbuilder.newCharReader();
             reader->parse(JsonSchema::ParticleCoordinateCV.c_str(),
                           JsonSchema::ParticleCoordinateCV.c_str() + JsonSchema::ParticleCoordinateCV.size(),
                           &schema, nullptr);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             Label atomids;
             for(auto& id : json["atom_ids"])
                 atomids.push_back(id.asInt());
             auto indextype = json.get("dimension","x").asString();
             Dimension index;
             if(indextype == "x")
                 index = Dimension::x;
             else if(indextype == "y")
                 index = Dimension::y;
             else if(indextype == "z")
                 index = Dimension::z;
             else
                 throw BuildException({"Could not obtain ParticleCoordinate dimension specified."});
             return new ParticleCoordinateCV(atomids, index);
         }
References Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), and Json::ObjectRequirement::Validate().
Referenced by SSAGES::CollectiveVariable::BuildCV().
Evaluate()
void SSAGES::ParticleCoordinateCV::Evaluate (const Snapshot & snapshot) inline override
Evaluate the CV.
Parameters
snapshot Current simulation snapshot.
Definition at line 97 of file ParticleCoordinateCV.h.
         {
             // Get local atom indices and compute COM.
             std::vector<int> idx;
             snapshot.GetLocalIndices(atomids_, &idx);
             // Get data from snapshot.
             auto n = snapshot.GetNumAtoms();
             const auto& masses = snapshot.GetMasses();
             // Initialize gradient.
             std::fill(grad_.begin(), grad_.end(), Vector3{0,0,0});
             grad_.resize(n, Vector3{0,0,0});
             // Compute total and center of mass.
             auto masstot = snapshot.TotalMass(idx);
             Vector3 com = snapshot.CenterOfMass(idx);
             // Assign CV value.
             switch(dim_)
             {
                 case Dimension::x:
                     val_ = com[0];
                     break;
                 case Dimension::y:
                     val_ = com[1];
                     break;
                 case Dimension::z:
                     val_ = com[2];
                     break;
             }
             // Assign gradient to appropriate atoms.
             for(auto& id : idx)
             {
                 grad_[id][0] = (dim_ == Dimension::x) ? masses[id]/masstot : 0;
                 grad_[id][1] = (dim_ == Dimension::y) ? masses[id]/masstot : 0;
                 grad_[id][2] = (dim_ == Dimension::z) ? masses[id]/masstot : 0;
             }
         }
References atomids_, SSAGES::Snapshot::CenterOfMass(), dim_, SSAGES::Snapshot::GetLocalIndices(), SSAGES::Snapshot::GetMasses(), SSAGES::Snapshot::GetNumAtoms(), SSAGES::CollectiveVariable::grad_, and SSAGES::Snapshot::TotalMass().
GetDifference()
double SSAGES::ParticleCoordinateCV::GetDifference (const double Location) const inline override virtual
Return difference considering periodic boundaries.
Parameters
Location Calculate difference of CV value to this location.
Returns
Direct difference.
As the AtomCoordinate CV does not consider periodic boundary conditions, the difference between the current value of the CV and another value is always the direct difference.
Reimplemented from SSAGES::CollectiveVariable.
Definition at line 162 of file ParticleCoordinateCV.h.
         {
             return val_ - Location;
         }
References SSAGES::CollectiveVariable::val_.
GetPeriodicValue()
double SSAGES::ParticleCoordinateCV::GetPeriodicValue (double Location) const inline override virtual
Return value taking periodic boundary conditions into account.
Parameters
Location Get wrapped value of this location.
Returns
Input value
The AtomCoordinate CV does not consider periodic boundary conditions. Thus, this function always returns the input value.
Reimplemented from SSAGES::CollectiveVariable.
Definition at line 147 of file ParticleCoordinateCV.h.
         {
             return Location;
         }
Initialize()
void SSAGES::ParticleCoordinateCV::Initialize (const Snapshot & snapshot) inline override
Initialize necessary variables.
Parameters
snapshot Current simulation snapshot.
Definition at line 68 of file ParticleCoordinateCV.h.
         {
             using std::to_string;
             auto n = atomids_.size();
             // Make sure atom ID's are on at least one processor.
             std::vector<int> found(n, 0);
             for(size_t i = 0; i < n; ++i)
             {
                 if(snapshot.GetLocalIndex(atomids_[i]) != -1)
                     found[i] = 1;
             }
             MPI_Allreduce(MPI_IN_PLACE, found.data(), n, MPI_INT, MPI_SUM, snapshot.GetCommunicator());
             unsigned ntot = std::accumulate(found.begin(), found.end(), 0, std::plus<int>());
             if(ntot != n)
                 throw BuildException({
                     "ParticleCoordinateCV: Expected to find " +
                     to_string(n) +
                     " atoms, but only found " +
                     to_string(ntot) + "."
                 });
         }
References atomids_, SSAGES::Snapshot::GetCommunicator(), and SSAGES::Snapshot::GetLocalIndex().
The documentation for this class was generated from the following file:
/home/michael/development/SSAGES/src/CVs/ParticleCoordinateCV.h