SSAGES: SSAGES::ParticlePositionCV Class Reference
SSAGES::ParticlePositionCV Class Reference
CVs
Collective variable on an particle position.
#include <ParticlePositionCV.h>
Public Member Functions
ParticlePositionCV (const Label &atomids, const Vector3 &position)
Constructor.
ParticlePositionCV (const Label &atomids, const Vector3 &position, bool dimx, bool dimy, bool dimz)
Constructor.
void Initialize (const Snapshot &snapshot) override
Initialize necessary variables.
void Evaluate (const Snapshot &snapshot) override
Evaluate the CV.
Public Member Functions inherited from SSAGES::CollectiveVariable
CollectiveVariable ()
Constructor.
virtual ~CollectiveVariable ()
Destructor.
virtual void Initialize (const class Snapshot &)
Initialize CV.
virtual void Evaluate (const class Snapshot &)=0
Evaluate CV.
double GetValue () const
Get current value of the CV.
virtual double GetMinimumImage (double) const
Returns the minimum image of a CV based on the input location.
virtual double GetPeriodicValue (double location) const
Apply periodic boundaries to a given value.
const std::vector< Vector3 > & GetGradient () const
Get current gradient of the CV.
const Matrix3 & GetBoxGradient () const
Get gradient contribution to box.
const std::array< double, 2 > & GetBoundaries ()
Get CV boundaries.
virtual double GetDifference (double location) const
Static Public Member Functions
static ParticlePositionCV * Build (const Json::Value &json, const std::string &path)
Set up collective variable.
Static Public Member Functions inherited from SSAGES::CollectiveVariable
static CollectiveVariable * BuildCV (const Json::Value &json, const std::string &path)
Set up collective variable.
Private Attributes
Label atomids_
Vector of atom ids of interest.
Vector3 point_
Target point in space.
Bool3 dim_
Each dimension determines if a constraint is applied by the CV.
Additional Inherited Members
Protected Attributes inherited from SSAGES::CollectiveVariable
std::vector< Vector3 > grad_
Gradient vector dCv/dxi.
Matrix3 boxgrad_
Gradient w.r.t box vectors dCv/dHij.
double val_
Current value of CV.
std::array< double, 2 > bounds_
Bounds on CV.
Detailed Description
Collective variable on an particle position.
This CV will return the distance of a particle (collection of atoms) from a particular point in (1,2,3)-dimensional space.
Definition at line 39 of file ParticlePositionCV.h.
Constructor & Destructor Documentation
ParticlePositionCV() [1/2]
SSAGES::ParticlePositionCV::ParticlePositionCV (const Label & atomids, const Vector3 & position) inline
Constructor.
Parameters
atomids Vector of atom ID's.
position Point in (1,2,3)D space for the distance calculation.
Construct a particle position CV.
Todo:
Bounds needs to be an input.
Definition at line 61 of file ParticlePositionCV.h.
                                                                           :
         atomids_(atomids), point_(position), dim_{true, true, true}
         {
         }
Referenced by Build().
ParticlePositionCV() [2/2]
SSAGES::ParticlePositionCV::ParticlePositionCV (const Label & atomids, const Vector3 & position, bool dimx, bool dimy, bool dimz) inline
Constructor.
Parameters
atomids Vector of atom ID's.
position Point in (1,2,3)D space for the distance calculation.
dimx If True, include x dimension.
dimy If True, include y dimension.
dimz If True, include z dimension.
Construct a particle position CV.
Todo:
Bounds needs to be an input.
Definition at line 78 of file ParticlePositionCV.h.
                                                                                                            :
         atomids_(atomids), point_(position), dim_{dimx, dimy, dimz}
         {
         }
Member Function Documentation
Build()
static ParticlePositionCV* SSAGES::ParticlePositionCV::Build (const Json::Value & json, const std::string & path) inline static
Set up collective variable.
Parameters
json JSON input value.
path Path for JSON path specification.
Returns
Pointer to the CV built by this function. nullptr in case of unknown error.
Builds a CV from a JSON node. Returns a pointer to the built cv. If an unknown error is encountered, this function will return a nullptr, but generally it will throw a BuildException on failure.
Warning
Object lifetime is the caller's responsibility.
Definition at line 148 of file ParticlePositionCV.h.
         {
             Json::ObjectRequirement validator;
             Json::Value schema;
             Json::CharReaderBuilder rbuilder;
             Json::CharReader* reader = rbuilder.newCharReader();
             reader->parse(JsonSchema::ParticlePositionCV.c_str(),
                           JsonSchema::ParticlePositionCV.c_str() + JsonSchema::ParticlePositionCV.size(),
                           &schema, nullptr);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             Label atomids;
             for(auto& id : json["atom_ids"])
                 atomids.push_back(id.asInt());
             Vector3 position;
             position[0] = json["position"][0].asDouble();
             position[1] = json["position"][1].asDouble();
             position[2] = json["position"][2].asDouble();
             ParticlePositionCV* c;
             if(json.isMember("dimension"))
             {
                 auto dimx = json["dimension"][0].asBool();
                 auto dimy = json["dimension"][1].asBool();
                 auto dimz = json["dimension"][2].asBool();
                 c = new ParticlePositionCV(atomids, position, dimx, dimy, dimz);
             }
             else
                 c = new ParticlePositionCV(atomids, position);
             return c;
         }
References Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), ParticlePositionCV(), and Json::ObjectRequirement::Validate().
Referenced by SSAGES::CollectiveVariable::BuildCV().
Evaluate()
void SSAGES::ParticlePositionCV::Evaluate (const Snapshot & snapshot) inline override
Evaluate the CV.
Parameters
snapshot Current simulation snapshot.
Definition at line 116 of file ParticlePositionCV.h.
         {
             // Get local atom indices and compute COM.
             std::vector<int> idx;
             snapshot.GetLocalIndices(atomids_, &idx);
             // Get data from snapshot.
             auto n = snapshot.GetNumAtoms();
             const auto& masses = snapshot.GetMasses();
             // Initialize gradient.
             std::fill(grad_.begin(), grad_.end(), Vector3{0,0,0});
             grad_.resize(n, Vector3{0,0,0});
             // Compute total and center of mass.
             auto masstot = snapshot.TotalMass(idx);
             Vector3 com = snapshot.CenterOfMass(idx);
             // Compute difference between point and account for requested
             // dimensions only.
             Vector3 dx = snapshot.ApplyMinimumImage(com - point_).cwiseProduct(dim_.cast<double>());
             val_ = dx.norm();
             // If distance is zero, we have nothing to do.
             if(val_ == 0)
                 return;
             for(auto& id : idx)
                 grad_[id] = dx/val_*masses[id]/masstot;
         }
References SSAGES::Snapshot::ApplyMinimumImage(), atomids_, SSAGES::Snapshot::CenterOfMass(), dim_, SSAGES::Snapshot::GetLocalIndices(), SSAGES::Snapshot::GetMasses(), SSAGES::Snapshot::GetNumAtoms(), SSAGES::CollectiveVariable::grad_, point_, SSAGES::Snapshot::TotalMass(), and SSAGES::CollectiveVariable::val_.
Initialize()
void SSAGES::ParticlePositionCV::Initialize (const Snapshot & snapshot) inline override
Initialize necessary variables.
Parameters
snapshot Current simulation snapshot.
Definition at line 87 of file ParticlePositionCV.h.
         {
             using std::to_string;
             auto n = atomids_.size();
             // Make sure atom ID's are on at least one processor.
             std::vector<int> found(n, 0);
             for(size_t i = 0; i < n; ++i)
             {
                 if(snapshot.GetLocalIndex(atomids_[i]) != -1)
                     found[i] = 1;
             }
             MPI_Allreduce(MPI_IN_PLACE, found.data(), n, MPI_INT, MPI_SUM, snapshot.GetCommunicator());
             unsigned ntot = std::accumulate(found.begin(), found.end(), 0, std::plus<int>());
             if(ntot != n)
                 throw BuildException({
                     "ParticlePositionCV: Expected to find " +
                     to_string(n) +
                     " atoms, but only found " +
                     to_string(ntot) + "."
                 });
         }
References atomids_, SSAGES::Snapshot::GetCommunicator(), and SSAGES::Snapshot::GetLocalIndex().
The documentation for this class was generated from the following file:
/home/michael/development/SSAGES/src/CVs/ParticlePositionCV.h