SSAGES: SSAGES::Legendre Class Reference
SSAGES::Legendre Class Reference
Defines the class of Legendre polynomials.
#include <Basis.h>
Public Member Functions
Legendre (unsigned int polyOrd, unsigned int nbins)
Constructor.
double Evaluate (double x, int n)
Calculates the output of the basis function.
double EvalGrad (double x, int n)
Calculates the gradient of the basis function.
double GetNorm (int n)
Gets the norm of the basis function.
Public Member Functions inherited from SSAGES::BasisFunction
BasisFunction (unsigned int polyOrd, unsigned int nbins, bool isFinite, bool zeroOrder, double boundLow, double boundUp)
Constructor.
unsigned int GetOrder ()
Gets the order of the current polynomial.
unsigned int GetBins ()
Gets the number of bins for the discretization.
bool GetZeroOrder ()
Gets the flag for constant-order polynomials.
double GetLower ()
Gets the lower bound on the CV.
double GetUpper ()
Gets the upper bound on the CV.
double GetRange ()
Gets the magnitude of the range of bounds.
virtual double Weight (double val)
Calculates the gradient of the basis function.
virtual ~BasisFunction ()
Destructor.
Static Public Member Functions
static Legendre * Build (const Json::Value &json, const std::string &path, unsigned int nbins)
Build BasisFunction from JSON value.
Static Public Member Functions inherited from SSAGES::BasisFunction
static BasisFunction * Build (const Json::Value &json, const std::string &path, unsigned int nbins)
Build BasisFunction from JSON value.
Additional Inherited Members
Protected Attributes inherited from SSAGES::BasisFunction
unsigned int polyOrd_
Order of the polynomial.
unsigned int nbins_
Number of bins.
bool isFinite_
Flag for finite-range polynomials.
bool zeroOrder_
Flag for constant-order polynomials.
double boundLow_
Lower bound on CV.
double boundUp_
Upper bound on CV.
Detailed Description
Defines the class of Legendre polynomials.
Definition at line 265 of file Basis.h.
Constructor & Destructor Documentation
Legendre()
SSAGES::Legendre::Legendre (unsigned int polyOrd, unsigned int nbins) inline
Constructor.
Parameters
polyOrd Order of Legendre polynomial.
nbins Number of bins.
Constructs an instance of the Legendre function class.
Definition at line 277 of file Basis.h.
                                                            :
         BasisFunction(polyOrd, nbins, true, false, -1.0, 1.0)
         {
         }
Referenced by Build().
Member Function Documentation
Build()
Legendre * SSAGES::Legendre::Build (const Json::Value & json, const std::string & path, unsigned int nbins) static
Build BasisFunction from JSON value.
Build the Legendre polynomial
Parameters
json JSON value node.
path Path for JSON path specification.
nbins Number of bins.
Returns
Pointer to new BasisFunction.
Definition at line 75 of file Basis.cpp.
     {
         Json::ObjectRequirement validator;
         Json::Value schema;
         Json::CharReaderBuilder rbuilder;
         Json::CharReader* reader = rbuilder.newCharReader();
         reader->parse(JsonSchema::LegendreBasis.c_str(),
                       JsonSchema::LegendreBasis.c_str() + JsonSchema::LegendreBasis.size(),
                       &schema, nullptr);
         validator.Parse(schema, path);
         //Validate Inputs
         validator.Validate(json, path);
         if(validator.HasErrors())
             throw BuildException(validator.GetErrors());
         return new Legendre(
                 json["polynomial_order"].asInt(),
                 nbin
             );
     }
References Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Legendre(), Json::ObjectRequirement::Parse(), and Json::ObjectRequirement::Validate().
Referenced by SSAGES::BasisFunction::Build().
EvalGrad()
double SSAGES::Legendre::EvalGrad (double val, int order) inline virtual
Calculates the gradient of the basis function.
Parameters
val Input value for function.
order Order of the polynomial.
Returns
Gradient for function.
Reimplemented from SSAGES::BasisFunction.
Definition at line 289 of file Basis.h.
         {
             return n == 0 ? 0.0 :
                     n == 1 ? 1.0 :
                     (2.0*n-1.0)/(double)n*(Evaluate(x,n-1) + x * EvalGrad(x,n-1)) - (n-1.0)/(double)n*EvalGrad(x,n-2);
         }
References Evaluate().
Evaluate()
double SSAGES::Legendre::Evaluate (double val, int order) inline virtual
Calculates the output of the basis function.
Parameters
val Input value for function.
order Order of the polynomial.
Returns
Output value for function.
Reimplemented from SSAGES::BasisFunction.
Definition at line 282 of file Basis.h.
         {
             return n == 0 ? 1.0 :
                     n == 1 ? x :
                     (2.0*n-1.0)/(double)n*x*Evaluate(x,n-1) - (n-1.0)/(double)n*Evaluate(x,n-2);
         }
Referenced by EvalGrad().
GetNorm()
double SSAGES::Legendre::GetNorm (int order) inline virtual
Gets the norm of the basis function.
Parameters
order Order of the polynomial.
Returns
Norm of a specific order of polynomial.
Reimplemented from SSAGES::BasisFunction.
Definition at line 296 of file Basis.h.
         {
             return n + 0.5;
         }
The documentation for this class was generated from the following files:
/home/michael/development/SSAGES/src/Utility/Basis.h
/home/michael/development/SSAGES/src/Utility/Basis.cpp