SSAGES: SSAGES::Logger Class Reference
SSAGES::Logger Class Reference
Base class for logging SSAGES data.
#include <Logger.h>
Public Member Functions
Logger (unsigned int frequency, const std::string &filename, const MPI_Comm &world, const MPI_Comm &comm)
Constructor.
virtual void PreSimulation (Snapshot *snapshot, const class CVManager &cvmanager) override
Logger call prior to simulation initiation.
virtual void PostIntegration (Snapshot *snapshot, const class CVManager &cvmanager) override
Logger call post integration.
virtual void PostSimulation (Snapshot *snapshot, const class CVManager &cvmanager) override
Logger call post simulation.
void SetCVMask (const std::vector< unsigned int > &mask)
Sets the collective variable mask.
void SetAppend (bool append)
Set append mode.
virtual ~Logger ()
Destructor.
Public Member Functions inherited from SSAGES::EventListener
EventListener (unsigned int frequency)
Constructor.
unsigned int GetFrequency () const
Get frequency of event listener.
virtual ~EventListener ()
Destructor.
Static Public Member Functions
static Logger * Build (const Json::Value &json, const MPI_Comm &world, const MPI_Comm &comm, const std::string &path)
Build a Logger from JSON node.
Static Public Member Functions inherited from SSAGES::EventListener
static unsigned int GetWalkerID (const MPI_Comm &world, const MPI_Comm &comm)
Get walker ID number of specified communicator.
static unsigned int GetNumWalkers (const MPI_Comm &world, const MPI_Comm &comm)
Get total number of walkers in the simulation.
static bool IsMasterRank (const MPI_Comm &comm)
Check if current processor is master.
Protected Attributes
mxx::comm world_
Global MPI communicator.
mxx::comm comm_
Local MPI communicator.
std::vector< unsigned int > cvmask_
Mask which identifies which CVs to log.
std::string filename_
Name of logfile.
std::ofstream log_
Log file stream.
bool append_
Append mode?
Detailed Description
Base class for logging SSAGES data.
The base class for logging useful data in SSAGES that is not necessarily written out by methods. Primarily this includes the value(s) of the collective variable(s) on the various walkers over time, the magnitude of the bias if a method supports it, and so on.
Definition at line 41 of file Logger.h.
Constructor & Destructor Documentation
Logger()
SSAGES::Logger::Logger (unsigned int frequency, const std::string & filename, const MPI_Comm & world, const MPI_Comm & comm) inline
Constructor.
Parameters
frequency Frequency of logging.
filename File for logging.
world Global MPI communicator.
comm MPI communicator of walker.
Constructs an instance of a logger.
Definition at line 69 of file Logger.h.
                                                                                                                :
         EventListener(frequency), world_(world), comm_(comm), cvmask_(), filename_(filename),
         append_(false)
         {}
Member Function Documentation
Build()
Logger * SSAGES::Logger::Build (const Json::Value & json, const MPI_Comm & world, const MPI_Comm & comm, const std::string & path) static
Build a Logger from JSON node.
Parameters
json JSON Value containing all input information.
world MPI global communicator.
comm MPI local communicator.
path Path for JSON path specification.
Returns
Pointer to the Logger built. nullptr if an unknown error occurred.
Note
Object lifetime is the caller's responsibility.
Definition at line 75 of file Logger.cpp.
     {
         ObjectRequirement validator;
         Value schema;
         CharReaderBuilder rbuilder;
         CharReader* reader = rbuilder.newCharReader();
         reader->parse(JsonSchema::Logger.c_str(),
                       JsonSchema::Logger.c_str() + JsonSchema::Logger.size(),
                       &schema, nullptr);
         validator.Parse(schema, path);
         // Validate inputs.
         validator.Validate(json, path);
         if(validator.HasErrors())
             throw BuildException(validator.GetErrors());
         auto freq = json.get("frequency", 1).asInt();
         std::string name = "cvlog.dat";
         bool ismulti = GetNumWalkers(world, comm) > 1;
         unsigned int wid = GetWalkerID(world, comm);
         if(json["output_file"].isArray())
             name = json["output_file"][wid].asString();
         else if(ismulti)
             throw std::invalid_argument(path + ": Multi-walker simulations require a separate output file for each.");
         else
             name = json["output_file"].asString();
         auto* l = new Logger(freq, name, world, comm);
         l->SetAppend(json.get("append", false).asBool());
         // Load CV mask.
         std::vector<unsigned int> cvmask;
         for(auto& cv : json["cvs"])
         {
             cvmask.push_back(CVManager::LookupCV(cv, path));
         }
         l->SetCVMask(cvmask);
         return l;
     }
References Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), and Json::ObjectRequirement::Validate().
Referenced by SSAGES::ResourceHandler::Build().
PostIntegration()
void SSAGES::Logger::PostIntegration (Snapshot * snapshot, const class CVManager & cvmanager) override virtual
Logger call post integration.
Parameters
snapshot Pointer to the simulation snapshot.
cvmanager Collective variable manager.
This function will be called after each integration step.
Implements SSAGES::EventListener.
Definition at line 55 of file Logger.cpp.
     {
         // Get necessary info.
         auto cvs = cvmanager.GetCVs(cvmask_);
         if(IsMasterRank(comm_))
         {
             log_.precision(8);
             log_ << snapshot->GetIteration() << " ";
             // Print out CV values.
             for(size_t i = 0; i < cvs.size() - 1; ++i)
                 log_ << cvs[i]->GetValue() << " ";
             log_ << cvs.back()->GetValue() << std::endl;
         }
     }
References SSAGES::CVManager::GetCVs(), and SSAGES::Snapshot::GetIteration().
PostSimulation()
void SSAGES::Logger::PostSimulation (Snapshot * snapshot, const class CVManager & cvmanager) override virtual
Logger call post simulation.
Parameters
snapshot Pointer to the simulation snapshot.
cvmanager Collective variable manager.
This function will be called after the end of the simulation run.
Implements SSAGES::EventListener.
Definition at line 71 of file Logger.cpp.
     {
     }
PreSimulation()
void SSAGES::Logger::PreSimulation (Snapshot * snapshot, const class CVManager & cvmanager) override virtual
Logger call prior to simulation initiation.
Parameters
snapshot Pointer to the simulation snapshot.
cvmanager Collective variable manager.
This function will be called before the simulation is started.
Implements SSAGES::EventListener.
Definition at line 34 of file Logger.cpp.
     {
         if(IsMasterRank(comm_))
         {
             if(append_)
                 log_.open(filename_.c_str(), std::ofstream::out | std::ofstream::app);
             else
             {
                 // Write out header.
                 log_.open(filename_.c_str(), std::ofstream::out);
                 log_ << "#";
                 log_ << "Iteration ";
                 auto cvs = cvmanager.GetCVs(cvmask_);
                 for(size_t i = 0; i < cvs.size() - 1; ++i)
                     log_ << "cv_" + std::to_string(i) << " ";
                 log_ << "cv_" + std::to_string(cvs.size() - 1) << std::endl;
             }
         }
     }
References SSAGES::CVManager::GetCVs().
SetAppend()
void SSAGES::Logger::SetAppend (bool append) inline
Set append mode.
Parameters
append Whether to enable or disable append mode.
Definition at line 112 of file Logger.h.
         {
             append_ = append;
         }
References append_.
SetCVMask()
void SSAGES::Logger::SetCVMask (const std::vector< unsigned int > & mask) inline
Sets the collective variable mask.
Sets the collective variable mask.
Parameters
mask Vector mask which contains the indices of which CV to include in the container.
This function sets the Snapshot's CV mask.
Definition at line 103 of file Logger.h.
         {
             cvmask_ = mask;
         }
References cvmask_.
The documentation for this class was generated from the following files:
/home/michael/development/SSAGES/src/Loggers/Logger.h
/home/michael/development/SSAGES/src/Loggers/Logger.cpp