SSAGES: SSAGES::GaussianPK Class Reference
SSAGES::GaussianPK Class Reference
Gaussian Function.
#include <PairwiseKernel.h>
Public Member Functions
GaussianPK (double mu, double sigma)
Constructor.
double Evaluate (double rij, double &df) const
Evaluate the pairwise kernel function.
Public Member Functions inherited from SSAGES::PairwiseKernel
virtual ~PairwiseKernel ()
Destructor.
Static Public Member Functions
static GaussianPK * Build (const Json::Value &json, const std::string &path)
Build GaussianPK from JSON value.
Static Public Member Functions inherited from SSAGES::PairwiseKernel
static PairwiseKernel * Build (const Json::Value &json, const std::string &path)
Build PairwiseKernel from JSON value.
Private Attributes
double mu_
Center of Gaussian.
double sigma_
Width of Gaussian.
Detailed Description
Gaussian Function.
A standard Gaussian function (also called a "bell curve").
Definition at line 76 of file PairwiseKernel.h.
Constructor & Destructor Documentation
GaussianPK()
SSAGES::GaussianPK::GaussianPK (double mu, double sigma) inline
Constructor.
Parameters
mu Center of Gaussian.
sigma Width of Gaussian.
Construct a GaussianPK.
Definition at line 91 of file PairwiseKernel.h.
                                             :
         mu_(mu), sigma_(sigma) {}
Referenced by Build().
Member Function Documentation
Build()
GaussianPK * SSAGES::GaussianPK::Build (const Json::Value & json, const std::string & path) static
Build GaussianPK from JSON value.
Parameters
json JSON value node.
path Path for JSON path specification.
Returns
Pointer to new GaussianPK.
Parameters
json JSON value node.
Returns
Pointer to new GaussianPK.
Definition at line 47 of file PairwiseKernel.cpp.
     {
         Json::ObjectRequirement validator;
         Json::Value schema;
         Json::CharReaderBuilder rbuilder;
         Json::CharReader* reader = rbuilder.newCharReader();
         reader->parse(JsonSchema::GaussianPK.c_str(),
                       JsonSchema::GaussianPK.c_str() + JsonSchema::GaussianPK.size(),
                       &schema, nullptr);
         validator.Parse(schema, path);
         // Validate inputs.
         validator.Validate(json, path);
         if(validator.HasErrors())
             throw BuildException(validator.GetErrors());
         return new GaussianPK(
                     json["mu"].asDouble(),
                     json["sigma"].asDouble()
                 );
     }
References GaussianPK(), Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), and Json::ObjectRequirement::Validate().
Referenced by SSAGES::PairwiseKernel::Build().
Evaluate()
double SSAGES::GaussianPK::Evaluate (double rij, double & df) const inline virtual
Evaluate the pairwise kernel function.
Parameters
rij distance between two atoms.
df Reference to variable which will store the gradient.
Returns
value of pairwise kernel function.
Implements SSAGES::PairwiseKernel.
Definition at line 94 of file PairwiseKernel.h.
         {
             const auto dx = (rij - mu_)/sigma_;
             const auto f = exp( - dx*dx/2.);
             const auto pre = - dx/sigma_;
             df = pre * f;
             return  f;
         }
References mu_, and sigma_.
The documentation for this class was generated from the following files:
/home/michael/development/SSAGES/src/Utility/PairwiseKernel.h
/home/michael/development/SSAGES/src/Utility/PairwiseKernel.cpp