SSAGES: Json::DependencyRequirement Class Reference
Json::DependencyRequirement Class Reference
Json
Requires dependencies to be met.
#include <DependencyRequirement.h>
Public Member Functions
DependencyRequirement ()
Constructor.
virtual void Reset () override
Reset Requirement.
virtual void Parse (Value json, const std::string &) override
Parse JSON input value.
virtual void Validate (const Value &json, const std::string &path) override
Validate that Requirement is met.
~DependencyRequirement ()
Destructor.
Public Member Functions inherited from Json::Requirement
bool HasErrors ()
Check if errors have occured.
std::vector< std::string > GetErrors ()
Get list of error messages.
virtual void ClearErrors ()
Clear list of error messages.
virtual bool HasNotices ()
Check if notices have been queued.
std::vector< std::string > GetNotices ()
Get list of notices.
virtual void ClearNotices ()
Clear list of notice messages.
virtual ~Requirement ()
Destructor.
Private Attributes
std::map< std::string,
std::vector< std::string > > deps_
Set of dependencies.
Additional Inherited Members
Protected Member Functions inherited from Json::Requirement
void PushError (const std::string &error)
Add error to list of error messages.
void PushNotice (const std::string &notice)
Add message to list of notices.
Detailed Description
Requires dependencies to be met.
Definition at line 36 of file DependencyRequirement.h.
Member Function Documentation
virtual void Json::DependencyRequirement::Parse (Value json, const std::string &) inline override virtual
Parse JSON input value.
Parameters
json JSON input value.
Implements Json::Requirement.
Definition at line 61 of file DependencyRequirement.h.
References deps_, and Reset().
         {
             Reset();
             auto names = json.getMemberNames();
             int i = 0;
             for(auto& value : json)
             {
                 if(value.isArray())
                 {
                     deps_[names[i]] = {};
                     for(auto& dep : value)
                     {
                         deps_[names[i]].push_back(dep.asString());
                     }
                 }
                 ++i;
             }
         }
virtual void Json::DependencyRequirement::Reset () inline override virtual
Reset Requirement.
Clear set of dependencies.
Implements Json::Requirement.
Definition at line 50 of file DependencyRequirement.h.
References Json::Requirement::ClearErrors(), Json::Requirement::ClearNotices(), and deps_.
Referenced by Parse().
         {
             deps_.clear();
             ClearErrors();
             ClearNotices();
         }
virtual void Json::DependencyRequirement::Validate (const Value & json, const std::string & path) inline override virtual
Validate that Requirement is met.
Parameters
json JSON value to be validated.
path Path for JSON path specification.
Implements Json::Requirement.
Definition at line 86 of file DependencyRequirement.h.
References deps_, and Json::Requirement::PushError().
         {
             if(!json.isObject())
             {
                 PushError(path + ": Dependency specified for non-object");
                 return;
             }
             for(auto& dep : deps_)
             {
                 auto& name = dep.first;
                 if(json.isMember(name))
                     for(const auto& val : dep.second)
                         if(!json.isMember(val))
                             PushError(path + ": \"" + name + "\" depends on \"" + val + "\"");
             }
         }
The documentation for this class was generated from the following file:
/home/cody/SSAGES/src/Validator/DependencyRequirement.h