SSAGES: SSAGES::GridTest Class Reference
SSAGES::GridTest Class Reference
Methods
Test class for the Grid.
#include <GridTest.h>
Public Member Functions
GridTest (boost::mpi::communicator &world, boost::mpi::communicator &comm, unsigned int frequency)
Constructor.
void PreSimulation (Snapshot *snapshot, const CVList &cvs) override
Pre-simulation hook.
void PostIntegration (Snapshot *snapshot, const CVList &cvs) override
Post-integration hook.
void PostSimulation (Snapshot *snapshot, const CVList &cvs) override
Post-simulation hook.
void Serialize (Json::Value &json) const override
Serialize the class.
~GridTest ()
Destructor.
Public Member Functions inherited from SSAGES::Method
Method (unsigned int frequency, boost::mpi::communicator &world, boost::mpi::communicator &comm)
Constructor.
void SetIteration (int iter)
Set Method's iteration.
void BuildGrid (const Json::Value &json, const std::string &path)
Set up the Grid.
Grid * GetGrid () const
Get the Grid.
virtual ~Method ()
Destructor.
Public Member Functions inherited from SSAGES::EventListener
EventListener (unsigned int frequency)
Constructor.
unsigned int GetFrequency () const
Get frequency of event listener.
virtual ~EventListener ()
Destructor.
Public Member Functions inherited from SSAGES::Serializable
virtual ~Serializable ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from SSAGES::Method
static Method * BuildMethod (const Json::Value &json, boost::mpi::communicator &world, boost::mpi::communicator &comm, const std::string &path)
Set up the Method.
Protected Attributes inherited from SSAGES::Method
boost::mpi::communicator _world
Global MPI communicator.
boost::mpi::communicator _comm
Local MPI communicator.
Grid * _grid
Pointer to grid.
unsigned int _iteration
Number of the method iteration.
Detailed Description
Test class for the Grid.
Definition at line 35 of file GridTest.h.
Constructor & Destructor Documentation
SSAGES::GridTest::GridTest (boost::mpi::communicator & world, boost::mpi::communicator & comm, unsigned int frequency) inline
Constructor.
Parameters
world MPI global communicator.
comm MPI local communicator.
frequency Frequency with which this method is invoked.
Definition at line 45 of file GridTest.h.
                                            :
         Method(frequency, world, comm)
         {
         }
Member Function Documentation
void SSAGES::GridTest::PostIntegration (Snapshot * snapshot, const CVList & cvs) inline override virtual
Post-integration hook.
Parameters
snapshot Current simulation snapshot.
cvs List of CVs.
Implements SSAGES::Method.
Definition at line 74 of file GridTest.h.
References SSAGES::Method::_grid, SSAGES::Method::_iteration, SSAGES::Grid::GetDimension(), SSAGES::Grid::GetIndices(), SSAGES::Grid::GetLower(), SSAGES::Grid::GetNumPoints(), SSAGES::Grid::GetPeriodic(), SSAGES::Grid::GetSpacing(), SSAGES::Grid::GetUpper(), SSAGES::Grid::GetValue(), SSAGES::Grid::PrintGrid(), and SSAGES::Grid::SetValue().
         {
             std::vector<int> Indices;
             std::vector<double> vals;
             int NDim = _grid->GetDimension();
             for(int i=0; i<NDim; i++)
             {
                 Indices.push_back(2);
                 vals.push_back(0);
             }
             double val = 10;
             val += _grid->GetValue(Indices);
             _grid->PrintGrid();
             _grid->SetValue(Indices, val);
             _grid->PrintGrid();
             std::vector<double> spacing = _grid->GetSpacing();
             std::vector<double> upper = _grid->GetUpper();
             std::vector<double> lower = _grid->GetLower();
             std::vector<bool> periodic = _grid->GetPeriodic();
             std::vector<int> numpoints = _grid->GetNumPoints();
             for(int i = 0;i<NDim;i++)
                 std::cout<<spacing[i]<<" "<<upper[i]<<" "<<lower[i]<<" "<<periodic[i]<<" "<<numpoints[i]<<std::endl;
             std::cout<<spacing.size()<<" "<<upper.size()<<" "<<lower.size()<<" "<<periodic.size()<<" "<<numpoints.size()<<std::endl;
             std::cout<<"Indices at value 0 are: ";
             Indices = _grid->GetIndices(vals);
             for(int i = 0; i<NDim; i++)
                 std::cout<<Indices[i]<<" ";
             std::cout<<std::endl;
             _iteration ++;
         }
void SSAGES::GridTest::PostSimulation (Snapshot * snapshot, const CVList & cvs) inline override virtual
Post-simulation hook.
Parameters
snapshot Current simulation snapshot.
cvs List of CVs.
Implements SSAGES::Method.
Definition at line 116 of file GridTest.h.
         {
         }
void SSAGES::GridTest::PreSimulation (Snapshot * snapshot, const CVList & cvs) inline override virtual
Pre-simulation hook.
Parameters
snapshot Current simulation snapshot.
cvs List of CVs.
Implements SSAGES::Method.
Definition at line 57 of file GridTest.h.
References SSAGES::Method::_grid, SSAGES::Method::_iteration, SSAGES::Method::_world, and SSAGES::Grid::PrintGrid().
         {
             if(!_grid)
             {
                 throw BuildException({"Method expected a grid but no grid built!"});
                 _world.abort(-1);
             }
             _grid->PrintGrid();
             _iteration = 0;
         }
void SSAGES::GridTest::Serialize (Json::Value & json) const inline override virtual
Serialize the class.
Parameters
json JSON value to which the information is stored
Store all information pertaining to this class in the given JSON value. The information can then be used to restart or analyze the simulation
Warning
Serialization not implemented yet!
Implements SSAGES::Serializable.
Definition at line 125 of file GridTest.h.
         {
             json["type"] = "GridTest";
         }
The documentation for this class was generated from the following file:
/home/cody/SSAGES/src/Methods/GridTest.h