SSAGES: SSAGES::Grid2D Class Reference
SSAGES::Grid2D Class Reference
2D Grid.
#include <Grid2D.h>
Public Member Functions
Grid2D (std::vector< double > lower, std::vector< double > upper, std::vector< int > num_points)
Constuctor.
std::vector< std::vector< int > > GetVoxel (const std::vector< double > &val) const override
Get a voxel from the Grid.
double InterpolateValue (const std::vector< double > &val) const override
Interpolate value.
double InterpolateDeriv (const std::vector< double > &val, int dim) const override
Interpolate derivative value.
Public Member Functions inherited from SSAGES::Grid
virtual ~Grid ()
Destructor.
std::vector< int > GetIndices (const std::vector< double > &val)
Return the nearest indices for given values.
std::vector< double > GetLocation (const std::vector< int > &indices) const
Get the location at the current indices.
double GetValue (const std::vector< int > &indices) const
Get the value at the current indices.
void SetValue (const std::vector< int > &indices, double value)
Set the value at the current incices.
std::vector< double > GetExtra (const std::vector< int > &indices) const
Get the extra at the current indices.
void SetExtra (const std::vector< int > &indices, std::vector< double > value)
Set the extra at the current incices.
void SetGrid (const std::vector< double > &first_values)
Set the entire grid given two vectors of values and dimension.
void SetPeriodic (const std::vector< bool > &periodic_values)
Set the entire grid given two vectors of values and dimension.
void PrintGrid () const
Write Grid to console.
std::vector< double > GetLower ()
Return lower edges of the Grid.
std::vector< double > GetUpper ()
Return upper edges of the Grid.
std::vector< bool > GetPeriodic ()
Get periodicity of the Grid.
std::vector< int > GetNumPoints ()
Get number of Grid points.
std::vector< double > GetSpacing ()
Get grid spacing.
int GetDimension ()
Get dimensionality of the Grid.
virtual void Serialize (Json::Value &json) const override
Serialize the class.
const_iterator begin () const
Get iterator to first element of the Grid.
const_iterator end () const
Get iterator one beyond last element of the Grid.
Public Member Functions inherited from SSAGES::Serializable
virtual ~Serializable ()
Destructor.
Additional Inherited Members
Public Types inherited from SSAGES::Grid
using const_iterator = std::vector< std::pair< std::vector< double >, std::vector< double >>>::const_iterator
Iterator for traversing the Grid.
Static Public Member Functions inherited from SSAGES::Grid
static Grid * BuildGrid (const Json::Value &json)
Set up the Grid.
static Grid * BuildGrid (const Json::Value &json, const std::string &path)
Set up Grid.
Protected Attributes inherited from SSAGES::Grid
std::vector< double > _lower
Lower edge of the grid.
std::vector< double > _upper
Upper edge of the grid.
std::vector< bool > _periodic
Is the grid periodic in the corresponding dimension?
std::vector< int > _num_points
Number of grid points.
std::vector< double > _spacing
Grid spacing.
int _NDim
Grid dimension.
std::vector< std::pair
< std::vector< double >
, std::vector< double > > > _flatvector
Array storing grid data.
Detailed Description
2D Grid.
Definition at line 30 of file Grid2D.h.
Constructor & Destructor Documentation
SSAGES::Grid2D::Grid2D (std::vector< double > lower, std::vector< double > upper, std::vector< int > num_points) inline
Constuctor.
Parameters
lower List of values for the lower edges of the Grid.
upper List of values for the upper edges of the Grid.
num_points List of how many Grid points in each direction.
Definition at line 42 of file Grid2D.h.
References SSAGES::Grid::_flatvector, SSAGES::Grid::_lower, SSAGES::Grid::_NDim, SSAGES::Grid::_num_points, SSAGES::Grid::_periodic, SSAGES::Grid::_spacing, SSAGES::Grid::_upper, and SSAGES::FlattenIndices().
         {
             _NDim = 2;
             for(size_t i =0; i <lower.size(); i++)
             {
                 _lower.push_back(lower[i]);
                 _upper.push_back(upper[i]);
                 _periodic.push_back(false);
                 _num_points.push_back(num_points[i]);
                 _spacing.push_back(0.0);
             }
             //Generate Grid
             for(size_t i = 0; i < _spacing.size(); i++)
                 _spacing[i] = (_upper[i] - _lower[i])/double(_num_points[i] - 1);
             // Construct flat vector
             _flatvector.resize(_num_points[0]*_num_points[1]);
             for(int i = 0; i < _num_points[0]; i++)
             {
                 for(int j = 0; j < _num_points[1]; j++)
                 {
                     int flat = FlattenIndices({i,j}, _num_points);
                     _flatvector[flat].first = std::vector<double>(3, 0.0);
                     _flatvector[flat].second.push_back(_lower[0] + _spacing[0]*i);
                     _flatvector[flat].second.push_back(_lower[1] + _spacing[1]*j);
                 }
             }
         }
Member Function Documentation
std::vector<std::vector<int> > SSAGES::Grid2D::GetVoxel (const std::vector< double > & val) const inline override virtual
Get a voxel from the Grid.
Parameters
val Position value.
Returns
Voxel
This function returns a voxel from the Grid. For each dimension, the voxel contains the next smaller and the next larger index based on the given position. In other words, the position is inside the (hyper-)cube defined by the voxel grid points.
Implements SSAGES::Grid.
Definition at line 71 of file Grid2D.h.
References SSAGES::Grid::_lower, SSAGES::Grid::_num_points, SSAGES::Grid::_periodic, and SSAGES::Grid::_spacing.
Referenced by InterpolateDeriv(), and InterpolateValue().
         {
             std::vector<int> vertices;
             std::vector<std::vector<int>> voxel;
             for(size_t i = 0; i < val.size(); i++)
             {
                 int vertex = 0;
                 vertex = int((val[i] - _lower[i])/_spacing[i]);
                 if(_periodic[i])
                 {
                     vertex = vertex % _num_points[i];
                     if(vertex<0)
                         vertex += _num_points[i];
                 }
                 if(vertex < 0 || vertex >=_num_points[i]) // out of bounds
                     throw std::out_of_range("Voxel not in grid!");
                 vertices.push_back(vertex);
             }
             //order of vertices is 0,0; 1,0; 0,1; 1,1
             int oldj = vertices[0];
             for(size_t i = 0; i < 2; i++)
             {
                 vertices[1] += i;
                 vertices[0] = oldj;
                 for(size_t j =0; j < 2; j++)
                 {
                     vertices[0] += j;
                     voxel.push_back(vertices);
                 }
             }
             return voxel;
         }
double SSAGES::Grid2D::InterpolateDeriv (const std::vector< double > & val, int dim) const inline override virtual
Interpolate derivative value.
Parameters
val Position.
dim Dimension in which respect to calculate the derivative.
Returns
Derivative of the interpolated value with respect to the given dimension.
This function determines the derivative of the interpolated value with respect to a given dimension.
See also
InterpolateValue()
Implements SSAGES::Grid.
Definition at line 139 of file Grid2D.h.
References SSAGES::Grid::_spacing, SSAGES::Grid::GetExtra(), SSAGES::Grid::GetLocation(), and GetVoxel().
         {
             std::vector<std::vector<int>> voxel = GetVoxel(val);
             std::vector<std::vector<double>> gridpos;
             std::vector<std::vector<double>> gridval;
             for(size_t v = 0; v < voxel.size(); v++)
             {
                 gridpos.push_back(GetLocation(voxel[v]));
                 gridval.push_back(GetExtra(voxel[v]));
             }
             //now, do 2d interpolation
             //order of vertices is 0,0; 1,0; 0,1; 1,1
             //note that middle two are negated so arguments are positive, since val < gridpos in
             // one of two directions.
             double ival  = 0;
             ival +=  (val[0] - gridpos[0][0])*(val[1] - gridpos[0][1]) * gridval[3][dim];
             ival += -(val[0] - gridpos[1][0])*(val[1] - gridpos[1][1]) * gridval[2][dim];
             ival += -(val[0] - gridpos[2][0])*(val[1] - gridpos[2][1]) * gridval[1][dim];
             ival +=  (val[0] - gridpos[3][0])*(val[1] - gridpos[3][1]) * gridval[0][dim];
             ival /= _spacing[0]*_spacing[1];
             return ival;
         }
double SSAGES::Grid2D::InterpolateValue (const std::vector< double > & val) const inline override virtual
Interpolate value.
Parameters
val Position.
Returns
Interpolated value.
This function returns the interpolated value at the given position. The value is a linear interpolation between the value at the next smaller and the next larger grid index, taking all dimensions of the grid into account.
Implements SSAGES::Grid.
Definition at line 111 of file Grid2D.h.
References SSAGES::Grid::_spacing, SSAGES::Grid::GetLocation(), SSAGES::Grid::GetValue(), and GetVoxel().
         {
             std::vector<std::vector<int>> voxel = GetVoxel(val);
             std::vector<std::vector<double>> gridpos;
             std::vector<double> gridval;
             for(size_t v = 0; v < voxel.size(); v++)
             {
                 gridpos.push_back(GetLocation(voxel[v]));
                 gridval.push_back(GetValue(voxel[v]));
             }
             //now, do 2d interpolation
             //order of vertices is 0,0; 1,0; 0,1; 1,1
             //note that middle two are negated so arguments are positive, since val < gridpos in
             // one of two directions.
             double ival  = 0;
             ival +=  (val[0] - gridpos[0][0])*(val[1] - gridpos[0][1]) * gridval[3];
             ival += -(val[0] - gridpos[1][0])*(val[1] - gridpos[1][1]) * gridval[2];
             ival += -(val[0] - gridpos[2][0])*(val[1] - gridpos[2][1]) * gridval[1];
             ival +=  (val[0] - gridpos[3][0])*(val[1] - gridpos[3][1]) * gridval[0];
             ival /= _spacing[0]*_spacing[1];
             return ival;
         }
The documentation for this class was generated from the following file:
/home/cody/SSAGES/src/Grids/Grid2D.h