SSAGES: SSAGES::SimEvent Class Reference
SSAGES::SimEvent Class Reference
Simulation event.
#include <SimEvent.h>
Public Member Functions
SimEvent (SimObservable *observable, int iteration, bool forceObserve=false)
Constructor.
SimObservable const * GetObservable () const
Get Sim Observable.
int GetIteration () const
Get iteration.
bool ForceObserve () const
Tell the observer that they should observe this event.
virtual ~SimEvent ()
Destructor.
Private Attributes
SimObservable * _observable
Pointer to the observable object from which the Event is originating.
int _iteration
Iteration of the simulation.
bool _forceObserve = false
Force the observation of this event.
Detailed Description
Simulation event.
Definition at line 40 of file SimEvent.h.
Constructor & Destructor Documentation
SSAGES::SimEvent::SimEvent (SimObservable * observable, int iteration, bool forceObserve = false) inline
Constructor.
Parameters
observable Pointer to the observable object.
iteration Interation.
forceObserve If True force the observers to observe this event.
Definition at line 59 of file SimEvent.h.
                 : _observable(observable), _iteration(iteration), _forceObserve(forceObserve){}
Member Function Documentation
bool SSAGES::SimEvent::ForceObserve () const inline
Tell the observer that they should observe this event.
Returns
True if Observers are forced to observe the event.
Definition at line 78 of file SimEvent.h.
References _forceObserve.
Referenced by SSAGES::SimObserver::Update().
 { return _forceObserve; }
int SSAGES::SimEvent::GetIteration () const inline
Get iteration.
Returns
Iteration.
Definition at line 72 of file SimEvent.h.
References _iteration.
Referenced by SSAGES::SimObserver::GetIteration(), and SSAGES::SimObserver::Update().
 { return _iteration; }
SimObservable const* SSAGES::SimEvent::GetObservable () const inline
Get Sim Observable.
Returns
Pointer to the observable object.
Definition at line 66 of file SimEvent.h.
References _observable.
 { return _observable; }
The documentation for this class was generated from the following file:
/home/cody/SSAGES/src/Simulations/SimEvent.h