SSAGES: SSAGES::RadiusOfGyrationCV Class Reference
SSAGES::RadiusOfGyrationCV Class Reference
CVs
Collective variable on the radius of gyration.
#include <RadiusOfGyrationCV.h>
Public Member Functions
RadiusOfGyrationCV (const Label &atomids)
Constructor.
void Initialize (const Snapshot &snapshot) override
Initialize necessary variables.
void Evaluate (const Snapshot &snapshot) override
Evaluate the CV.
virtual void Serialize (Json::Value &json) const override
Serialize this CV for restart purposes.
Public Member Functions inherited from SSAGES::CollectiveVariable
CollectiveVariable ()
Constructor.
double GetValue () const
Get current value of the CV.
virtual double GetMinimumImage (double location) const
Returns the minimum image of a CV based on the input location.
virtual double GetPeriodicValue (double location) const
Apply periodic boundaries to a given value.
const std::vector< Vector3 > & GetGradient () const
Get current gradient of the CV.
const std::array< double, 2 > & GetBoundaries ()
Get CV boundaries.
virtual double GetDifference (double location) const
Public Member Functions inherited from SSAGES::Serializable
virtual ~Serializable ()
Destructor.
Private Attributes
Label _atomids
IDs of the atoms used for Rg calculation.
Additional Inherited Members
Static Public Member Functions inherited from SSAGES::CollectiveVariable
static CollectiveVariable * BuildCV (const Json::Value &json)
Set up collective variable.
static CollectiveVariable * BuildCV (const Json::Value &json, const std::string &path)
Set up collective variable.
static void BuildCV (const Json::Value &json, CVList &cvlist, const std::string &path)
Set up CV and add it to list of CVs.
Protected Attributes inherited from SSAGES::CollectiveVariable
std::vector< Vector3 > _grad
Gradient vector dCv/dxi.
double _val
Current value of CV.
std::array< double, 2 > _bounds
Detailed Description
Collective variable on the radius of gyration.
Collective variable on radius of gyration. This will return the Rg for a group of atoms.
Definition at line 36 of file RadiusOfGyrationCV.h.
Constructor & Destructor Documentation
SSAGES::RadiusOfGyrationCV::RadiusOfGyrationCV (const Label & atomids) inline
Constructor.
Parameters
atomids IDs of the atoms defining Rg.
Construct a radius of gyration CV.
Todo:
Bounds needs to be an input
Definition at line 50 of file RadiusOfGyrationCV.h.
                                                  :
         _atomids(atomids)
         {
         }
Member Function Documentation
void SSAGES::RadiusOfGyrationCV::Evaluate (const Snapshot & snapshot) inline override
Evaluate the CV.
Parameters
snapshot Current simulation snapshot.
Definition at line 88 of file RadiusOfGyrationCV.h.
References _atomids, SSAGES::CollectiveVariable::_grad, SSAGES::CollectiveVariable::_val, SSAGES::Snapshot::ApplyMinimumImage(), SSAGES::Snapshot::CenterOfMass(), SSAGES::Snapshot::GetCommunicator(), SSAGES::Snapshot::GetLocalIndices(), SSAGES::Snapshot::GetMasses(), SSAGES::Snapshot::GetNumAtoms(), SSAGES::Snapshot::GetPositions(), and SSAGES::Snapshot::TotalMass().
         {
             // Get local atom indices and compute COM.
             std::vector<int> idx;
             snapshot.GetLocalIndices(_atomids, &idx);
             // Get data from snapshot.
             auto n = snapshot.GetNumAtoms();
             const auto& masses = snapshot.GetMasses();
             const auto& pos = snapshot.GetPositions();
             // Initialize gradient.
             std::fill(_grad.begin(), _grad.end(), Vector3{0,0,0});
             _grad.resize(n, Vector3{0,0,0});
             // Compute total and center of mass.
             auto masstot = snapshot.TotalMass(idx);
             Vector3 com = snapshot.CenterOfMass(idx, masstot);
             auto mrsq = 0.;
             for(auto& i : idx)
             {
                 Vector3 ricm = snapshot.ApplyMinimumImage(pos[i] - com);
                 mrsq += masses[i]*ricm.squaredNorm();
                 // Pre-compute part of gradient for efficiency.
                 auto mfrac = masses[i]/masstot;
                 _grad[i] = mfrac*ricm*(1.-mfrac);
             }
             MPI_Allreduce(MPI_IN_PLACE, &mrsq, 1, MPI_DOUBLE, MPI_SUM, snapshot.GetCommunicator());
             _val = std::sqrt(mrsq/masstot);
             for(auto& i : idx)
                 _grad[i] /= _val;
         }
void SSAGES::RadiusOfGyrationCV::Initialize (const Snapshot & snapshot) inline override
Initialize necessary variables.
Parameters
snapshot Current simulation snapshot.
Definition at line 59 of file RadiusOfGyrationCV.h.
References _atomids, SSAGES::Snapshot::GetCommunicator(), and SSAGES::Snapshot::GetLocalIndex().
         {
             using std::to_string;
             auto n = _atomids.size();
             // Make sure atom ID's are on at least one processor.
             std::vector<int> found(n, 0);
             for(size_t i = 0; i < n; ++i)
             {
                 if(snapshot.GetLocalIndex(_atomids[i]) != -1)
                     found[i] = 1;
             }
             MPI_Allreduce(MPI_IN_PLACE, found.data(), n, MPI_INT, MPI_SUM, snapshot.GetCommunicator());
             unsigned ntot = std::accumulate(found.begin(), found.end(), 0, std::plus<int>());
             if(ntot != n)
                 throw BuildException({
                     "RadiusOfGyrationCV: Expected to find " +
                     to_string(n) +
                     " atoms, but only found " +
                     to_string(ntot) + "."
                 });
         }
virtual void SSAGES::RadiusOfGyrationCV::Serialize (Json::Value & json) const inline override virtual
Serialize this CV for restart purposes.
Parameters
json JSON value
Implements SSAGES::Serializable.
Definition at line 128 of file RadiusOfGyrationCV.h.
References _atomids.
         {
             json["type"] = "RadiusOfGyration";
             for(auto& id : _atomids)
                 json["atom_ids"].append(id);
             for(auto& bound : _bounds)
                 json["bounds"].append(bound);       }
The documentation for this class was generated from the following file:
/home/cody/SSAGES/src/CVs/RadiusOfGyrationCV.h