SSAGES: SSAGES::Simulation Class Reference
SSAGES::Simulation Class Reference
Core
Simulation class for creating simulation and a driver object.
#include <Simulation.h>
Public Member Functions
Simulation (boost::mpi::communicator &world)
Constructor.
~Simulation ()
Destructor.
Json::Value ReadJSON (std::string jfile)
Read the JSON file.
bool BuildSimulation (const Json::Value &json, const std::string &path)
Set up the simulation.
bool BuildDriver (const Json::Value &json, const std::string &path)
Set up the driver for the simulation.
bool BuildCVs (const Json::Value &json, const std::string &path)
Set up CVs.
bool BuildConstraints (const Json::Value &json, const std::string &path)
Set up Constraints.
bool BuildMethod (const Json::Value &json, const std::string &path)
Set up Method.
bool BuildObservers (const Json::Value &json)
Set up observers.
void ReadInputFile ()
Read the MD Engine input file.
void Finalize ()
Set up listeners and hook.
void Run ()
Perform simulation run.
Protected Attributes
boost::mpi::communicator world_
The MPI world communicator.
boost::mpi::communicator comm_
The local communicator.
Driver * MDDriver_
A pointer to the driver.
int nwalkers_
Number of walkers.
std::string MDEngine_
MDEngine of choice.
std::string GlobalInput_
Global input file.
int ltot_
Magic number for message passing.
int msgw_
Magic number for message passing.
int notw_
Magic number for message passing.
Detailed Description
Simulation class for creating simulation and a driver object.
The simulation class pulls together the simulation and the driver to steer the simulation.
Definition at line 65 of file Simulation.h.
Constructor & Destructor Documentation
SSAGES::Simulation::Simulation (boost::mpi::communicator & world) inline
Constructor.
Parameters
world The MPI world communicator to use
Construct the simulation object.
Definition at line 100 of file Simulation.h.
                                                 :
         world_(world), comm_(), MDDriver_(), nwalkers_(1),
         MDEngine_(), GlobalInput_(),
         ltot_(81), msgw_(51), notw_(ltot_ - msgw_)
         {
         }
Member Function Documentation
bool SSAGES::Simulation::BuildConstraints (const Json::Value & json, const std::string & path) inline
Set up Constraints.
Parameters
json JSON value containing input information.
path Path for JSON path specification.
Returns
True if all constraints have been successfully built, else return False.
Definition at line 431 of file Simulation.h.
References SSAGES::DumpErrorsToConsole(), and SSAGES::BuildException::GetErrors().
         {
             // Build CV(s).
             try{
                 MDDriver_->BuildConstraints(json.get("constraints", Json::arrayValue), path);
             } catch(BuildException& e) {
                 DumpErrorsToConsole(e.GetErrors(), notw_);
                 return false;
             } catch(std::exception& e) {
                 DumpErrorsToConsole({e.what()}, notw_);
                 return false;
             }
             return true;
         }
bool SSAGES::Simulation::BuildCVs (const Json::Value & json, const std::string & path) inline
Set up CVs.
Parameters
json JSON value containing input information.
path JSON path specification.
Returns
True if CVs have been set up correctly, else return False .
Set up the collective variables (CV) used in the Metadynamics simulation.
Definition at line 403 of file Simulation.h.
References SSAGES::DumpErrorsToConsole(), and SSAGES::BuildException::GetErrors().
         {
             // Test if MDDriver has been built
             if (!MDDriver_) {
                 throw std::runtime_error("Simulation driver needs to be built before CVs.");
             }
             // Build CV(s).
             try{
                 MDDriver_->BuildCVs(json.get("CVs", Json::arrayValue), path);
             } catch(BuildException& e) {
                 DumpErrorsToConsole(e.GetErrors(), notw_);
                 return false;
             } catch(std::exception& e) {
                 DumpErrorsToConsole({e.what()}, notw_);
                 return false;
             }
             return true;
         }
bool SSAGES::Simulation::BuildDriver (const Json::Value & json, const std::string & path) inline
Set up the driver for the simulation.
Parameters
json JSON value containing input information.
path JSON path specification.
Returns
True if Driver was set up correctly, else return False .
Set up the Driver for the Metadynamics simulation.
Definition at line 199 of file Simulation.h.
References SSAGES::DumpErrorsToConsole(), SSAGES::BuildException::GetErrors(), Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ArrayRequirement::Parse(), and Json::ArrayRequirement::Validate().
         {
             ArrayRequirement validator;
             Value schema;
             Value JsonDrivers;
             Value JsonDriver;
             Reader reader;
             bool success_build = true;
             reader.parse(JsonSchema::driver, schema);
             validator.Parse(schema, path);
             JsonDrivers = json.get("driver",Json::arrayValue);
             try
             {
                 // Validate inputs.
                 validator.Validate(JsonDrivers, path);
                 if(validator.HasErrors())
                 {
                     throw BuildException(validator.GetErrors());
                 }
             } catch(BuildException& e) {
                 DumpErrorsToConsole(e.GetErrors(), notw_);
                 return false;
             } catch(std::exception& e) {
                 DumpErrorsToConsole({e.what()}, notw_);
                 return false;
             }
             // Determine walker ID using JSON file and split
             // communicator accordingly.
             int i = 0;
             int totalproc = 0;
             int wid = 0;
             for(auto& m : JsonDrivers)
             {
                 int currentnumproc = m.get("number processors", 1).asInt();
                 if ((int)world_.rank() >= totalproc && (int)world_.rank() < currentnumproc + totalproc)
                 {
                     wid = i;
                     JsonDriver = m;
                 }
                 totalproc += currentnumproc;
                 i++;
             }
             nwalkers_ = JsonDrivers.size();
             comm_ = world_.split(wid);
             if(world_.size() != totalproc)
             {
                 if(world_.rank() == 0)
                 {
                     std::cerr << "The number of processors for each driver (walker) must sum "
                     << "to the total processors for the mpi call." << std::endl;
                     std::cerr<<world_.size()<<" vs "<<totalproc<<std::endl;
                 }
                 return false;
             }
             // Get the engine.
             MDEngine_ = JsonDriver.get("type", "none").asString();
             // Use input from JSON to determine MDEngine of choice as well as other parameters
             #ifdef ENABLE_LAMMPS
             if(MDEngine_ == "LAMMPS")
             {
                 LammpsDriver* en = new LammpsDriver(world_, comm_, wid);
                 if(!(MDDriver_ = static_cast<Driver*>(en)))
                 {
                         std::cerr << "Unable to dynamic cast engine on node "<<world_.rank()<<" Error occurred" << std::endl;
                         success_build = false;
                 }
             }
             else
             #endif
             #ifdef ENABLE_GROMACS
             if(MDEngine_ == "Gromacs")
             {
                 GromacsDriver* en = new GromacsDriver(world_, comm_, wid);
                 if(!(MDDriver_ = static_cast<Driver*>(en)))
                 {
                     std::cout << "Unable to static cast engine on node " << world_.rank() << std::endl;
                     success_build = false;
                 }
             }
             else
             #endif
             #ifdef ENABLE_QBOX
             if(MDEngine_ == "Qbox")
             {
                 QboxDriver* en = new QboxDriver(world_, comm_, wid);
                 if(!(MDDriver_ = static_cast<Driver*>(en)))
                 {
                     std::cout << "Unable to static cast engine on node " << world_.rank() << std::endl;
                     success_build = false;
                 }
             }
             else
             #endif
             #ifdef ENABLE_OPENMD
             if(MDEngine_ == "OpenMD")
             {
                 auto en = new OpenMDDriver(world_, comm_, wid);
                 if(!(MDDriver_ = static_cast<Driver*>(en)))
                 {
                     std::cout << "Unable to static cast engine on node " << world_.rank() << std::endl;
                     success_build = false;
                 }
             }
             else
             #endif
             {
                 DumpErrorsToConsole({"Unknown MD Engine [" + MDEngine_ + "] specified."},notw_);
                 success_build = false;
             }
             if (!success_build) {
                 // If building the MDEngine failed, don't bother about the rest.
                 return success_build;
             }
             // Build the driver
             try{
                 MDDriver_->BuildDriver(JsonDriver, path + "/" + std::to_string(wid));
             } catch(BuildException& e) {
                 DumpErrorsToConsole(e.GetErrors(), notw_);
                 success_build = false;
             } catch(std::exception& e) {
                 DumpErrorsToConsole({e.what()}, notw_);
                 success_build = false;
             }
             // Build the CVs
             if(JsonDriver.isMember("CVs"))
             {
                 if(!BuildCVs(JsonDriver, "#/CVs"))
                     success_build = false;
             }
             else
             {
                 if(!BuildCVs(json,"#/CVs"))
                     success_build = false;
             }
             // Build the method
             if (JsonDriver.isMember("method"))
             {
                 if(!BuildMethod(JsonDriver, "#/Methods"))
                     success_build = false;
             }
             else if (json.isMember("method"))
             {
                 if(!BuildMethod(json,"#/Methods"))
                     success_build = false;
             }
             if(JsonDriver.isMember("observers"))
             {
                 if(!BuildObservers(JsonDriver))
                     success_build = false;
             }
             else if (json.isMember("observers"))
             {
                 if(!BuildObservers(json))
                     success_build = false;
             }
             // Build the constraints if they exist
             if(JsonDriver.isMember("constraints"))
             {
                 if(!BuildConstraints(JsonDriver, "#/Constraints"))
                     success_build = false;
             }
             else if (json.isMember("constraints"))
             {
                 if(!BuildConstraints(json, "#/Constraints"))
                     success_build = false;
             }
             if(comm_.rank()==0)
             {
                 if(success_build)
                     std::cout << std::setw(notw_) << std::right << "\033[32mMDEngine " << wid <<  " pass!\033[0m\n";
                 else
                     std::cout << std::setw(notw_) << std::right << "\033[32mMDEngine " << wid <<  " FAIL!\033[0m\n";
             }
             return success_build;
         }
bool SSAGES::Simulation::BuildMethod (const Json::Value & json, const std::string & path) inline
Set up Method.
Parameters
json JSON value containing input information.
path JSON path specification.
Returns
True if Method has been set up correctly, else return False .
Set up the Metadynamics method to be used in the simulation.
Definition at line 455 of file Simulation.h.
References SSAGES::DumpErrorsToConsole(), and SSAGES::BuildException::GetErrors().
         {
             // Test if MDDriver has been built.
             if (!MDDriver_) {
                 throw std::runtime_error("Simulation Driver needs to be built before Methods.");
             }
             // Build method(s).
             try{
                 MDDriver_->BuildMethod(json.get("method", Json::objectValue), path);
             } catch(BuildException& e) {
                 DumpErrorsToConsole(e.GetErrors(), notw_);
                 return false;
             } catch(std::exception& e) {
                 DumpErrorsToConsole({e.what()}, notw_);
                 return false;
             }
             return true;
         }
bool SSAGES::Simulation::BuildObservers (const Json::Value & json) inline
Set up observers.
Parameters
json JSON value containing input information.
Returns
True if Method has been set up correctly, else return False .
Set up the JSON observer to be used in creating restarts for the simulation.
Definition at line 484 of file Simulation.h.
References SSAGES::DumpErrorsToConsole(), and SSAGES::BuildException::GetErrors().
         {
             // Check that MDDriver has been built.
             if (!MDDriver_) {
                 throw std::runtime_error(
                     "Simulation Driver needs to be built before Observers."
                 );
             }
             // Build method(s).
             try{
                 MDDriver_->BuildObservers(json.get("observers", Json::objectValue), nwalkers_);
             } catch(BuildException& e) {
                 DumpErrorsToConsole(e.GetErrors(), notw_);
                 return false;
             } catch(std::exception& e) {
                 DumpErrorsToConsole({e.what()}, notw_);
                 return false;
             }
             return true;
         }
bool SSAGES::Simulation::BuildSimulation (const Json::Value & json, const std::string & path) inline
Set up the simulation.
Parameters
json JSON value containing the input information.
path Path for JSON path specification.
Returns
True if simulation was set up correctly, else return False .
This function sets up the simulation based on the JSON input information read in before using Simulation::ReadJSON().
Definition at line 159 of file Simulation.h.
References SSAGES::DumpErrorsToConsole(), SSAGES::BuildException::GetErrors(), Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), and Json::ObjectRequirement::Validate().
         {
             ObjectRequirement validator;
             Value schema;
             Reader reader;
             reader.parse(JsonSchema::Simulation, schema);
             validator.Parse(schema, path);
             try
             {
                 // Validate inputs.
                 validator.Validate(json, path);
                 if(validator.HasErrors())
                 {
                     throw BuildException(validator.GetErrors());
                 }
             } catch(BuildException& e) {
                 DumpErrorsToConsole(e.GetErrors(), notw_);
                 return false;
             } catch(std::exception& e) {
                 DumpErrorsToConsole({e.what()}, notw_);
                 return false;
             }
             GlobalInput_ = json.get("inputfile","none").asString();
             return true;
         }
void SSAGES::Simulation::ReadInputFile () inline
Read the MD Engine input file.
Read the input file for the MD engine used in the simulation and broadcast the necessary information to all MPI instances.
Definition at line 512 of file Simulation.h.
References SSAGES::GetFileContents().
         {
             // Check that MDDriver has been built
             if (!MDDriver_) {
                 throw std::runtime_error(
                     "Trying to read input file before Simulation Driver was built."
                 );
             }
             std::string contents ="";
             std::string localInput = MDDriver_->GetInputFile();
             if(GlobalInput_ != "none" && localInput == "none")
             {
                 MDDriver_->SetInputFile(GlobalInput_);
                 if(world_.rank() == 0)
                 {
                     std::cout<<"Global input file found, first using: "<<GlobalInput_<<std::endl;
                     contents = GetFileContents(GlobalInput_.c_str());
                 }
             }
             mpi::broadcast(world_, contents, 0);
             // Each node reads in specified input file
             if(localInput != "none")
             {
                 if(comm_.rank() == 0)
                 {
                     std::cout<<"No/overloaded global input file, node " <<world_.rank()<<" using: "<<localInput<<std::endl;
                     contents = GetFileContents(localInput.c_str());
                 }
                 mpi::broadcast(comm_, contents, 0);
             }
             MDDriver_->ExecuteInputFile(contents);
         }
Json::Value SSAGES::Simulation::ReadJSON (std::string jfile) inline
Read the JSON file.
Parameters
jfile File name of the JSON file
Returns
JSON Value containing all input information.
With this function, the MPI head node will read in the JSON file and broadcast to other nodes the necessary information. The JSON file will include the Engine input file name(s).
Definition at line 123 of file Simulation.h.
References SSAGES::DumpErrorsToConsole(), SSAGES::JSONLoader::LoadFile(), and SSAGES::PrintBoldNotice().
         {
             Value root;
             JSONLoader loader;
             if(world_.rank() == 0)
                 PrintBoldNotice(" > Validating JSON...", msgw_, world_);
             try{
                 root = loader.LoadFile(jfile, world_);
             } catch(std::exception& e) {
                 DumpErrorsToConsole({e.what()}, notw_);
                 world_.abort(-1);
             } catch(int& k) {
                 std::string err = strerror(k);
                 DumpErrorsToConsole({"File IO error: " + err}, notw_);
                 world_.abort(-1);
             }
                 if(world_.rank() == 0)
                     std::cout << std::setw(notw_) << std::right << "\033[32mOK!\033[0m\n";
             return root;
         }
The documentation for this class was generated from the following file:
/home/cody/SSAGES/src/Simulations/Simulation.h