SSAGES: SSAGES::PairwiseKernel Class Reference
SSAGES::PairwiseKernel Class Reference abstract
Core
Pairwise kernel base class.
#include <PairwiseKernel.h>
Public Member Functions
virtual double Evaluate (double rij, double &df) const =0
Evaluate the pairwise kernel function.
virtual ~PairwiseKernel ()
Destructor.
Static Public Member Functions
static PairwiseKernel * Build (const Json::Value &json, const std::string &path)
Build PairwiseKernel from JSON value.
Detailed Description
Pairwise kernel base class.
Pairwise functions are useful for a variety of collective variables. Several classes of these functions exist.
Gaussian functions are useful for collective variables that focus on a certain value. Unlike a delta function, they interpolate provide a continuous function and gradient for biasing.
Switching functions are useful for collective variables that are discrete in nature. They interpolate the discrete values and provide a continuous gradient for biasing.
Definition at line 44 of file PairwiseKernel.h.
Member Function Documentation
Build()
PairwiseKernel * SSAGES::PairwiseKernel::Build (const Json::Value & json, const std::string & path) static
Build PairwiseKernel from JSON value.
Parameters
json JSON value node.
path Path for JSON path specification.
Returns
Pointer to new PairwiseKernel.
Definition at line 30 of file PairwiseKernel.cpp.
References SSAGES::GaussianPK::Build(), and SSAGES::RationalSwitchPK::Build().
Referenced by SSAGES::PairwiseCV::Build(), SSAGES::GaussianPK::Evaluate(), and SSAGES::RationalSwitchPK::Evaluate().
     {
         auto type = json.get("type", "none").asString();
         if(type == "gaussian")
             return GaussianPK::Build(json, path);
         else if(type == "rationalswitch")
             return RationalSwitchPK::Build(json, path);
         else
             throw std::invalid_argument("Invalid pairwise kernel type \"" + type + "\".");
     }
Evaluate()
virtual double SSAGES::PairwiseKernel::Evaluate (double rij, double & df) const pure virtual
Evaluate the pairwise kernel function.
Parameters
rij distance between two atoms.
df Reference to variable which will store the gradient.
Returns
value of pairwise kernel function.
Implemented in SSAGES::RationalSwitchPK, and SSAGES::GaussianPK.
Referenced by SSAGES::PairwiseCV::Evaluate().
The documentation for this class was generated from the following files:
/home/cody/Projects/SSAGES-public/src/Utility/PairwiseKernel.h
/home/cody/Projects/SSAGES-public/src/Utility/PairwiseKernel.cpp