SSAGES: Json::RequirementLoader Class Reference
Json::RequirementLoader Class Reference
Json
Helper class to load Requirement.
#include <RequirementLoader.h>
Public Member Functions
std::unique_ptr< Requirement > LoadRequirement (const Value &json)
Load specific requirement.
std::unique_ptr< Requirement > LoadExtended (const Value &json)
Extended Requirement loader.
std::unique_ptr< Requirement > LoadRequirement (const ValueType &type)
Load Requirement based on Value Type.
Detailed Description
Helper class to load Requirement.
Definition at line 38 of file RequirementLoader.h.
Member Function Documentation
std::unique_ptr< Requirement > Json::RequirementLoader::LoadExtended (const Value & json)
Extended Requirement loader.
Parameters
json JSON value specifying the type of Requirement.
Returns
Unique pointer to the Requirement.
Definition at line 77 of file RequirementLoader.cpp.
Referenced by Json::ObjectRequirement::Parse().
     {
         std::unique_ptr<Requirement> item = nullptr;
         if(json.isObject() && json.isMember("allOf") && json["allOf"].isArray())
             item = std::move(std::unique_ptr<Requirement>(new AllOfRequirement()));
         else if(json.isObject() && json.isMember("anyOf") && json["anyOf"].isArray())
             item = std::move(std::unique_ptr<Requirement>(new AnyOfRequirement()));
         else if(json.isObject() && json.isMember("oneOf") && json["oneOf"].isArray())
             item = std::move(std::unique_ptr<Requirement>(new OneOfRequirement()));
         return item;
     }
std::unique_ptr< Requirement > Json::RequirementLoader::LoadRequirement (const Value & json)
Load specific requirement.
Parameters
json JSON value specifying the type of Requirement.
Returns
Unique pointer to the Requirement.
Definition at line 42 of file RequirementLoader.cpp.
Referenced by Json::OneOfRequirement::Parse(), Json::NotRequirement::Parse(), Json::AllOfRequirement::Parse(), Json::AnyOfRequirement::Parse(), Json::ArrayRequirement::Parse(), and Json::ObjectRequirement::Parse().
     {
         std::unique_ptr<Requirement> item = nullptr;
         // Load up apitemriate requirement type.
         if(json["type"].asString() == "string")
             item = std::move(std::unique_ptr<Requirement>(new StringRequirement()));
         else if(json["type"].asString() == "integer")
             item = std::move(std::unique_ptr<Requirement>(new IntegerRequirement()));
         else if(json["type"].asString() == "number")
             item = std::move(std::unique_ptr<Requirement>(new NumberRequirement()));
         else if(json["type"].asString() == "object")
             item = std::move(std::unique_ptr<Requirement>(new ObjectRequirement()));
         else if(json["type"].asString() == "array")
             item = std::move(std::unique_ptr<Requirement>(new ArrayRequirement()));
         else if(json["type"].asString() == "boolean")
             item = std::move(std::unique_ptr<Requirement>(new BooleanRequirement()));
         else if(json["type"].asString() == "null")
             item = std::move(std::unique_ptr<Requirement>(new NullRequirement()));
         else if(json["allOf"].isArray())
             item = std::move(std::unique_ptr<Requirement>(new AllOfRequirement()));
         else if(json["anyOf"].isArray())
             item = std::move(std::unique_ptr<Requirement>(new AnyOfRequirement()));
         else if(json["oneOf"].isArray())
             item = std::move(std::unique_ptr<Requirement>(new OneOfRequirement()));
         else if(json["enum"].isArray())
             item = std::move(std::unique_ptr<Requirement>(new EnumRequirement()));
         else if(json["not"].isObject())
             item = std::move(std::unique_ptr<Requirement>(new NotRequirement()));
         // last resort.
         else if(json.isObject())
             item = std::move(std::unique_ptr<Requirement>(new ObjectRequirement()));
         return item;
     }
std::unique_ptr< Requirement > Json::RequirementLoader::LoadRequirement (const ValueType & type)
Load Requirement based on Value Type.
Parameters
type Value Type specifying the Requirement.
Returns
Unique pointer to the Requirement.
Return a Requirement based on the given Value Type.
Definition at line 90 of file RequirementLoader.cpp.
     {
         std::unique_ptr<Requirement> item = nullptr;
         switch(type)
         {
             case nullValue:
                 item = std::move(std::unique_ptr<Requirement>(new NullRequirement()));
                 break;
             case intValue:
                 item = std::move(std::unique_ptr<Requirement>(new IntegerRequirement()));
                 break;
             case realValue:
                 item = std::move(std::unique_ptr<Requirement>(new NumberRequirement()));
                 break;
             case stringValue:
                 item = std::move(std::unique_ptr<Requirement>(new StringRequirement()));
                 break;
             case booleanValue:
                 item = std::move(std::unique_ptr<Requirement>(new BooleanRequirement()));
                 break;
             case arrayValue:
                 item = std::move(std::unique_ptr<Requirement>(new ArrayRequirement()));
                 break;
             case objectValue:
                 item = std::move(std::unique_ptr<Requirement>(new ObjectRequirement()));
                 break;
             default:
                 item = nullptr;
         }
         return item;
     }
The documentation for this class was generated from the following files:
/home/cody/Projects/SSAGES-public/src/Validator/RequirementLoader.h
/home/cody/Projects/SSAGES-public/src/Validator/RequirementLoader.cpp