SSAGES: SSAGES::COPSSImage Class Reference
SSAGES::COPSSImage Class Reference
Public Member Functions
COPSSImage (boost::mpi::communicator &comm, unsigned int frequency, double einner, int ion_type_start, std::vector< double > atomTypeRadius)
void force_pol (Snapshot *, size_t, size_t, size_t)
void PreSimulation (Snapshot *, const CVList &) override
Method call prior to simulation initiation.
void PostIntegration (Snapshot *snapshot, const CVList &) override
Method call post integration.
void PostSimulation (Snapshot *, const CVList &) override
Method call post simulation.
void Serialize (Json::Value &) const override
Serialize the class.
Public Member Functions inherited from SSAGES::Constraint
Constraint (unsigned int frequency, boost::mpi::communicator &comm)
Public Member Functions inherited from SSAGES::EventListener
EventListener (unsigned int frequency)
Constructor.
unsigned int GetFrequency () const
Get frequency of event listener.
virtual ~EventListener ()
Destructor.
Public Member Functions inherited from SSAGES::Serializable
virtual ~Serializable ()
Destructor.
Public Attributes
double _e
double _ginv
double Rxkj
double Rykj
double Rzkj
double Rkj2
double rkj
double Rxij
double Ryij
double Rzij
double Rij2
double rij
double ukj
double vkj
double wkj
double aux1
double aux2
double auxv_x_integ
double auxv_y_integ
double auxv_z_integ
double aux3_integ
double aux3Sqrt_integ
double auxv_x_delta
double auxv_y_delta
double auxv_z_delta
double aux3_delta
double aux3Sqrt_delta
double aa
Private Attributes
double _einner
Dielectric constant of polarizable particles.
int _ion_type_start
Where non polarizable particles start.
double _eouter
Dielectric constant of outside continuum.
double _qqrd2e
unit conversion constant
double xlo = 0.0
double xhi = 1.0
int ngauss = 5
double _xg0 [5] = {-0.9061798459386640,-0.5384693101056831,0.00000000000000000,0.5384693101056831,0.9061798459386640}
double _wg0 [5] = {0.2369268850561891,0.4786286704993665,0.5688888888888889,0.4786286704993665,0.2369268850561891}
std::vector< double > _atomTypeRadius
Additional Inherited Members
Static Public Member Functions inherited from SSAGES::Constraint
static Constraint * BuildConstraint (const Json::Value &json, boost::mpi::communicator &comm)
static Constraint * BuildConstraint (const Json::Value &json, boost::mpi::communicator &comm, const std::string &path)
static void BuildConstraint (const Json::Value &json, ConstraintList &clist, boost::mpi::communicator &comm, const std::string &path)
Protected Attributes inherited from SSAGES::Constraint
boost::mpi::communicator _comm
Detailed Description
Definition at line 35 of file COPSSImage.h.
Member Function Documentation
void SSAGES::COPSSImage::PostIntegration (Snapshot * snapshot, const CVList & cvs) override virtual
Method call post integration.
Parameters
snapshot Pointer to the simulation snapshot.
cvs List of CVs.
This function will be called at the end of each integration step.
Implements SSAGES::Constraint.
Definition at line 36 of file COPSSImage.cpp.
References _einner, _eouter, _ion_type_start, _qqrd2e, SSAGES::Snapshot::GetAtomTypes(), SSAGES::Snapshot::GetCharges(), SSAGES::Snapshot::GetForces(), SSAGES::Snapshot::GetNumAtoms(), and SSAGES::Snapshot::GetPositions().
     {
         // Gather information
         auto& types = snapshot->GetAtomTypes();
             size_t _nlocal = snapshot->GetNumAtoms();
         #ifdef _DEBUG_SNAPSHOT
         fprintf(stdout, "Image method start runnning ... \n");
         auto& forces = snapshot->GetForces();
         auto& positions = snapshot->GetPositions();
         auto& charges = snapshot->GetCharges();
         fprintf(stdout, "check ids: ");
         for (size_t i = 0; i < _nlocal; i++)
         {
             fprintf(stdout, "%d\n; ", ids[i]);
         }
         fprintf(stdout, "check positions: ");
         for (size_t i=0; i< _nlocal; i++)
         {
             for (size_t j=0; j<3; j++)
             {
                 fprintf(stdout,"%f; ", positions[i][j]);
             }
         }
         fprintf(stdout, "\ncheck forces: ");
         for (size_t i=0; i< _nlocal; i++)
         {
             for (size_t j=0; j<3; j++)
             {
                 fprintf(stdout,"%f; ", forces[i][j]);
             }
         }
         fprintf(stdout, "\ncheck types: ");
         for (size_t i=0; i< _nlocal; i++)
         {
             fprintf(stdout, "%d; ", types[i]);
         }
         fprintf(stdout, "\ncheck charges: ");
         for (size_t i=0; i< _nlocal; i++)
         {
             fprintf(stdout, "%f; ", charges[i]);
         }
         fprintf(stdout, "\ncheck radius: ");
         for (size_t i=0; i< _nlocal; i++)
         {
                 fprintf(stdout,"%f; ", _atomTypeRadius[types[i]-1]);
         }
         fprintf(stdout, "\ncheck nlocal: %d\n", _nlocal);
         fprintf(stdout, "check eouter: %f\n", _eouter);
         fprintf(stdout, "check qqrd2e: %f\n", _qqrd2e);
         fprintf(stdout, "check einner: %f\n", _einner);
         fprintf(stdout, "check ion-type-start: %d\n", _ion_type_start);
         #endif
         //iterate over all permutations {i;j;k}, j has to be polarizable
         for (size_t j=0; j < _nlocal; j++) if( types[j] < _ion_type_start )
         {
             for(size_t i=0; i < _nlocal; i++) if(i != j)
                 {
                  for(size_t k=0; k < _nlocal; k++) if (k != j)
                      {
                     //Interaction: [I] <---- [J] <-------[k]
                     //F[i] = f{i;j;k}
                     //F[j] = -(f{i;j;k} + f{k;j;i})
                     //F[k] = f{k;j;i}
                     if (i == k)
                     {
                         force_pol(snapshot, i, j, k);
                     }
                     else if (i < k)
                     {
                         force_pol(snapshot, i, j, k);
                         force_pol(snapshot, k, j, i);
                     }
                 }
             }
         }
     }
void SSAGES::COPSSImage::PostSimulation (Snapshot * snapshot, const CVList & cvs) override virtual
Method call post simulation.
Parameters
snapshot Pointer to the simulation snapshot.
cvs List of CVs.
This function will be called after the simulation has finished.
Implements SSAGES::Constraint.
Definition at line 128 of file COPSSImage.cpp.
     {
     //nothing to be done in post simulation
     }
void SSAGES::COPSSImage::PreSimulation (Snapshot * snapshot, const CVList & cvs) override virtual
Method call prior to simulation initiation.
Parameters
snapshot Pointer to the simulation snapshot.
cvs List of CVs.
This function will be called before the simulation is started.
Implements SSAGES::Constraint.
Definition at line 31 of file COPSSImage.cpp.
     {
     //nothing to be done in presimulation
     }
void SSAGES::COPSSImage::Serialize (Json::Value & json) const inline override virtual
Serialize the class.
Parameters
json JSON value to which the information is stored
Store all information pertaining to this class in the given JSON value. The information can then be used to restart or analyze the simulation
Implements SSAGES::Serializable.
Definition at line 100 of file COPSSImage.h.
 {};
The documentation for this class was generated from the following files:
/home/cody/SSAGES/src/Constraints/COPSSImage.h
/home/cody/SSAGES/src/Constraints/COPSSImage.cpp