SSAGES: Json::ArrayRequirement Class Reference
Json::ArrayRequirement Class Reference
Json
Array of Requirements.
#include <ArrayRequirement.h>
Public Member Functions
ArrayRequirement ()
Constructor.
virtual void ClearErrors () override
Clear list of error messages for all Requirements.
virtual void ClearNotices () override
Clear notices for all Requirements.
virtual void Reset () override
Reset array.
virtual void Parse (Value json, const std::string &path) override
Parse JSON value and fill array.
virtual void Validate (const Value &json, const std::string &path) override
Validate json value.
Public Member Functions inherited from Json::Requirement
bool HasErrors ()
Check if errors have occured.
std::vector< std::string > GetErrors ()
Get list of error messages.
virtual bool HasNotices ()
Check if notices have been queued.
std::vector< std::string > GetNotices ()
Get list of notices.
virtual ~Requirement ()
Destructor.
Private Member Functions
template<class T >
bool IsUnique (T X)
Test if set is unique.
Private Attributes
RequireList _items
List of Requirements.
std::unique_ptr< Requirement > _item
Single Requirement.
bool _addItems
True if items can be added.
bool _setMin
True if minimum has been set.
bool _setMax
True if maximum has been set.
bool _unique
True if all Requirements are unique.
int _min
Minimum value.
int _max
Maximum value.
Additional Inherited Members
Protected Member Functions inherited from Json::Requirement
void PushError (const std::string &error)
Add error to list of error messages.
void PushNotice (const std::string &notice)
Add message to list of notices.
Detailed Description
Array of Requirements.
Definition at line 43 of file ArrayRequirement.h.
Member Function Documentation
template<class T > bool Json::ArrayRequirement::IsUnique (T X) inline private
Test if set is unique.
Template Parameters
T Container class.
Parameters
X Container containing Requirements.
Returns
True if no element in the container is duplicate.
Definition at line 64 of file ArrayRequirement.h.
Referenced by Validate().
         {
           std::set<T> Y(X.begin(), X.end());
           return X.size() == Y.size();
         }
virtual void Json::ArrayRequirement::Parse (Value json, const std::string & path) inline override virtual
Parse JSON value and fill array.
Parameters
json JSON input value.
path Path for JSON path specification.
This function parses the JSON input value and creates new Requirements for all values in the "items" branch.
Implements Json::Requirement.
Definition at line 125 of file ArrayRequirement.h.
References _addItems, _item, _items, _max, _min, _setMax, _setMin, _unique, Json::RequirementLoader::LoadRequirement(), and Reset().
Referenced by SSAGES::CollectiveVariable::BuildCV(), SSAGES::Simulation::BuildDriver(), and SSAGES::SimObserver::BuildObservers().
         {
             Reset();
             RequirementLoader loader;
             if(json.isMember("items") && json["items"].isObject())
             {
                 if((_item = loader.LoadRequirement(json["items"])))
                     _item->Parse(json["items"], path);
             }
             else if(json.isMember("items") && json["items"].isArray())
             {
                 for(auto& item : json["items"])
                 {
                     if(auto iptr = loader.LoadRequirement(item))
                     {
                         _items.push_back(std::move(iptr));
                         _items.back()->Parse(item, path);
                     }
                 }
             }
             if(json.isMember("additionalItems") && json["additionalItems"].isBool())
                 _addItems = json["additionalItems"].asBool();
             if(json.isMember("minItems") && json["minItems"].isInt())
             {
                 _setMin = true;
                 _min = json["minItems"].asInt();
             }
             if(json.isMember("maxItems") && json["maxItems"].isInt())
             {
                 _setMax = true;
                 _max = json["maxItems"].asInt();
             }
             if(json.isMember("uniqueItems") && json["uniqueItems"].isBool())
                 _unique = json["uniqueItems"].asBool();
         }
virtual void Json::ArrayRequirement::Validate (const Value & json, const std::string & path) inline override virtual
Validate json value.
Parameters
json JSON value to be validated.
path Path for JSON path specification.
Implements Json::Requirement.
Definition at line 171 of file ArrayRequirement.h.
References _addItems, _item, _items, _max, _min, _setMax, _setMin, _unique, Json::Requirement::GetErrors(), Json::Requirement::GetNotices(), IsUnique(), Json::Requirement::PushError(), and Json::Requirement::PushNotice().
Referenced by SSAGES::CollectiveVariable::BuildCV(), SSAGES::Simulation::BuildDriver(), and SSAGES::SimObserver::BuildObservers().
         {
             if(!json.isArray())
             {
                 PushError(path + ": Must be of type \"array\"");
                 return;
             }
             if(_item != nullptr)
             {
                 int i = 0;
                 for(const auto& item : json)
                 {
                     _item->Validate(item, path + "/" + std::to_string(i));
                     ++i;
                 }
                 // Merge errors.
                 for(const auto& error : _item->GetErrors())
                     PushError(error);
                 for(const auto& notice : _item->GetNotices())
                     PushNotice(notice);
             }
             if(_items.size() != 0)
             {
                 if(!_addItems && json.size() >  _items.size())
                     PushError(path + ": There cannot be any additional items in the array");
                 int iv = std::min((int)_items.size(), (int)json.size());
                 for(int i = 0; i < iv; ++i)
                 {
                     _items[i]->Validate(json[i], path);
                     // Merge errors.
                     for(const auto& error : _items[i]->GetErrors())
                         PushError(error);
                     for(const auto& notice : _items[i]->GetNotices())
                         PushNotice(notice);
                 }
             }
             if(_setMin && (int)json.size() < _min)
                 PushError(path + ": There must be at least " + std::to_string(_min) + " elements in the array");
             if(_setMax && (int)json.size() > _max)
                 PushError(path + ": There must be no more than " + std::to_string(_max) + " elements in the array");
             if(_unique && !IsUnique(json))
                 PushError(path + ": Entries must be unique");
         }
The documentation for this class was generated from the following file:
/home/cody/SSAGES/src/Validator/ArrayRequirement.h