SSAGES: SSAGES::MockMethod Class Reference
SSAGES::MockMethod Class Reference
Methods
Mock Sampling.
#include <MockMethod.h>
Public Member Functions
MockMethod (boost::mpi::communicator &world, boost::mpi::communicator &comm, unsigned int frequency)
Constructor.
void PreSimulation (Snapshot *, const CVList &) override
Pre-simulation hook.
void PostIntegration (Snapshot *snapshot, const CVList &cvs) override
Post-integration hook.
void PostSimulation (Snapshot *, const CVList &) override
Post-simulation hook.
~MockMethod ()
Destructor.
Public Member Functions inherited from SSAGES::Method
Method (unsigned int frequency, boost::mpi::communicator &world, boost::mpi::communicator &comm)
Constructor.
void SetIteration (int iter)
Set Method's iteration.
virtual ~Method ()
Destructor.
Public Member Functions inherited from SSAGES::EventListener
EventListener (unsigned int frequency)
Constructor.
unsigned int GetFrequency () const
Get frequency of event listener.
virtual ~EventListener ()
Destructor.
Public Member Functions inherited from SSAGES::Serializable
virtual void Serialize (Json::Value &json) const =0
Serialize the class.
virtual ~Serializable ()
Destructor.
Private Attributes
std::ofstream myout_
Output stream.
Additional Inherited Members
Static Public Member Functions inherited from SSAGES::Method
static Method * BuildMethod (const Json::Value &json, boost::mpi::communicator &world, boost::mpi::communicator &comm, const std::string &path)
Set up the Method.
Protected Attributes inherited from SSAGES::Method
boost::mpi::communicator world_
Global MPI communicator.
boost::mpi::communicator comm_
Local MPI communicator.
unsigned int iteration_
Number of the method iteration.
Detailed Description
Mock Sampling.
Definition at line 35 of file MockMethod.h.
Constructor & Destructor Documentation
SSAGES::MockMethod::MockMethod (boost::mpi::communicator & world, boost::mpi::communicator & comm, unsigned int frequency) inline
Constructor.
Parameters
world MPI global communicator.
comm MPI local communicator.
frequency Frequency with which this method is invoked.
Definition at line 47 of file MockMethod.h.
References myout_.
                                            :
         Method(frequency,world,comm)
         {
             myout_.open("foo.out");
         }
Member Function Documentation
void SSAGES::MockMethod::PostIntegration (Snapshot * snapshot, const CVList & cvs) inline override virtual
Post-integration hook.
Parameters
snapshot Current simulation snapshot.
cvs List of CVs.
Implements SSAGES::Method.
Definition at line 65 of file MockMethod.h.
References SSAGES::Snapshot::GetCommunicator(), SSAGES::Snapshot::GetForces(), and SSAGES::Snapshot::GetWalkerID().
         {
             using std::setw;
             using std::right;
             using std::setprecision;
             std::cout << snapshot->GetWalkerID()
             << " " << snapshot->GetCommunicator().rank() << std::endl;
             auto& v = snapshot->GetForces();
             v[0][0] = 1.000000*v[0][0];
             /*
             // An example of acquiring and printing some data from the snapshot.
             std::cout
             << setw(8) << right << snapshot->GetIteration() << std::fixed
             << setw(13) << right << setprecision(4) << snapshot->GetVolume()
             << setw(13) << right << setprecision(7) << snapshot->GetPressure()
             << setw(13) << right << setprecision(7) << snapshot->GetEnergy()
             << " // SSAGES mock method"
             << std::endl; */
             for(auto& cv : cvs)
                 std::cout << cv->GetValue() << std::endl;
         }
The documentation for this class was generated from the following file:
/home/cody/SSAGES/src/Methods/MockMethod.h