SSAGES: SSAGES::LammpsDriver Class Reference
SSAGES::LammpsDriver Class Reference
Driver for LAMMPS simulations.
#include <LammpsDriver.h>
Public Member Functions
LammpsDriver (mpi::communicator &world_comm, mpi::communicator &local_comm, int walkerID)
Constructor.
virtual void Run () override
Run simulation.
virtual void ExecuteInputFile (std::string contents) override
Run LAMMPS input file.
virtual void BuildDriver (const Json::Value &json, const std::string &path) override
Set up the driver.
virtual void Serialize (Json::Value &json) const override
Serialize the class.
Public Member Functions inherited from SSAGES::Driver
Driver (boost::mpi::communicator &world, boost::mpi::communicator &comm, int walkerID)
Constructor.
virtual ~Driver ()
Destructor.
std::string GetInputFile ()
Get the input file contents.
void SetInputFile (const std::string filename)
Set the input file.
void BuildCVs (const Json::Value &json, const std::string &path)
Build CVs.
void BuildConstraints (const Json::Value &json, const std::string &path)
void BuildMethod (const Json::Value &json, const std::string &path)
Build method(s).
void BuildObservers (const Json::Value &json, int nwalks)
Build observer(s).
void BuildGrid (const Json::Value &json, const std::string &path)
Build the grid.
void Finalize ()
Finalize the setup.
virtual void AcceptVisitor (Visitor &v) const override
Accept a visitor.
Public Member Functions inherited from SSAGES::SimObservable
virtual void AddObserver (SimObserver *observer)
Add simulation observer.
virtual void RemoveObserver (SimObserver *observer)
Remove simulation observer.
void NotifyObservers (const SimEvent &event)
Notify registered observers of a change.
virtual ~SimObservable ()
Destructor.
Public Member Functions inherited from SSAGES::Visitable
virtual ~Visitable ()
Destructor.
Public Member Functions inherited from SSAGES::Serializable
virtual ~Serializable ()
Destructor.
Private Attributes
std::shared_ptr< LAMMPS > _lammps
Pointer to the local instance of lammps.
int _MDsteps
The number of MD engine steps you would like to perform.
std::string _logfile
The lammps logfile.
Additional Inherited Members
Protected Member Functions inherited from SSAGES::SimObservable
void SerializeObservers (Json::Value &json) const
Serialize observers.
Protected Attributes inherited from SSAGES::Driver
boost::mpi::communicator _world
MPI global communicator.
boost::mpi::communicator _comm
MPI local communicator.
const int _wid
The node id that this driver belongs to.
Hook * _hook
The hook that hooks into the MD simulation engine.
Snapshot * _snapshot
The snapshot of your system.
Method * _method
The Method that will be used.
CVList _CVs
The CVs that will be used.
ObserverList _observers
The observers that will be used for this driver.
ConstraintList _constraints
std::string _inputfile
Local input file.
std::string _restartname
MD engine Restart file name.
bool _readrestart
Read a restart file.
std::random_device _rd
Random number generators for setting seeds.
std::mt19937 _gen
Alternative random number generator.
Detailed Description
Driver for LAMMPS simulations.
Definition at line 42 of file LammpsDriver.h.
Constructor & Destructor Documentation
SSAGES::LammpsDriver::LammpsDriver (mpi::communicator & world_comm, mpi::communicator & local_comm, int walkerID) inline
Constructor.
Parameters
world_comm MPI global communicator.
local_comm MPI local communicator.
walkerID ID of the walker assigned to this driver.
Definition at line 63 of file LammpsDriver.h.
                                    :
         Driver(world_comm, local_comm, walkerID), _lammps(), _MDsteps(), _logfile()
         {
         };
Member Function Documentation
virtual void SSAGES::LammpsDriver::BuildDriver (const Json::Value & json, const std::string & path) inline override virtual
Set up the driver.
Parameters
json JSON value containing input information.
path Path for JSON path specification.
Implements SSAGES::Driver.
Definition at line 145 of file LammpsDriver.h.
References Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), and Json::ObjectRequirement::Validate().
         {
             Value schema;
             ObjectRequirement validator;
             Reader reader;
             reader.parse(JsonSchema::LAMMPSDriver, schema);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             _MDsteps = json.get("MDSteps",1).asInt();
             _inputfile = json.get("inputfile","none").asString();
             _restartname = json.get("restart file", "none").asString();
             _readrestart = json.get("read restart", false).asBool();
             if(_readrestart && _restartname == "none")
                 throw BuildException({"You want to run from a restart but no file name provided (see 'restart file' in LAMMPS's schema for more informationz)"});
             // Silence of the lammps.
             char **largs = (char**) malloc(sizeof(char*) * 5);
             for(int i = 0; i < 5; ++i)
                 largs[i] = (char*) malloc(sizeof(char) * 1024);
             sprintf(largs[0], " ");
             sprintf(largs[1], "-screen");
             sprintf(largs[2], "none");
             sprintf(largs[3], "-log");
             _logfile = json.get("logfile", "none").asString();
             if(_logfile != "none")
                 sprintf(largs[4], "%s-MPI_ID-%d",_logfile.c_str(), _wid);
             else
                 sprintf(largs[4], "none");
             _lammps = std::make_shared<LAMMPS>(5, largs, MPI_Comm(_comm));
             // Free.
             for(int i = 0; i < 5; ++i)
                 free(largs[i]);
             free(largs);
         }
virtual void SSAGES::LammpsDriver::ExecuteInputFile (std::string contents) inline override virtual
Run LAMMPS input file.
Parameters
contents Content of the LAMMPS input file.
This function exectures the contents of the given LAMMPS input file line by line and gathers the fix/hook.
Implements SSAGES::Driver.
Definition at line 84 of file LammpsDriver.h.
References SSAGES::SimObserver::GetFrequency(), and SSAGES::JSONObserver::GetPrefix().
         {
             // Go through lammps.
             std::uniform_int_distribution<> dis(1, 999999);
             std::string token;
             std::istringstream ss(contents);
             bool reading_restart = false;
             if(_restartname != "none" && _readrestart)
             {
                 _lammps->input->one(("read_restart " + _restartname + " remap").c_str());
                 while(std::getline(ss, token, '\n'))
                     if(token.find("#RESTART") != std::string::npos)
                         reading_restart = true;
             }
             // need these 2 lines
             ss.clear(); // clear the `failbit` and `eofbit`
             ss.seekg(0); // rewind
             while(std::getline(ss, token, '\n'))
             {
                 if(token.find("#RESTART") != std::string::npos)
                     reading_restart = false;
                 if(_readrestart && reading_restart)
                     continue;
                 _lammps->input->one(token.c_str());
             }
             // Initialize and create the restart parameters
             for(auto* o : _observers)
             {
                 if(o->GetName() == "JSON")
                 {
                     _readrestart = true;
                     JSONObserver* obs = static_cast<JSONObserver*>(o);
                     std::string filename1 = obs->GetPrefix() + "_" + std::to_string(_wid) + ".restart";
                     std::string filename2 = obs->GetPrefix() + "_" + std::to_string(_wid) + "b.restart";
                     _lammps->input->one(("restart  " + std::to_string(obs->GetFrequency()) + " " + filename1 + " " + filename2).c_str());
                 }
             }
             auto fid = _lammps->modify->find_fix("ssages");
             if(fid < 0)
                 throw BuildException({"Could not find ssages fix in given input file!"});
             if(!(_hook = dynamic_cast<Hook*>(_lammps->modify->fix[fid])))
             {
                 throw BuildException({"Unable to dynamic cast hook on node " + std::to_string(_world.rank())});
             }
         }
virtual void SSAGES::LammpsDriver::Serialize (Json::Value & json) const inline override virtual
Serialize the class.
Parameters
json JSON value to which the information is stored
Store all information pertaining to this class in the given JSON value. The information can then be used to restart or analyze the simulation
Reimplemented from SSAGES::Driver.
Definition at line 191 of file LammpsDriver.h.
         {
             // Call parent first.
             Driver::Serialize(json);
             json["MDSteps"] = _MDsteps;
             json["logfile"] = _logfile;
             json["type"] = "LAMMPS";
             //if true on first file
             if(_lammps->output->restart_toggle)
             {
                 json["restart file"] = std::string(_lammps->output->restart2a);
             }
             else
             {
                 json["restart file"] = std::string(_lammps->output->restart2b);
             }
         }
The documentation for this class was generated from the following file:
/home/cody/SSAGES/src/Drivers/LammpsDriver.h