SSAGES: SSAGES::BFS Class Reference
SSAGES::BFS Class Reference
Methods
Basis Function Sampling Algorithm.
#include <BasisFunc.h>
Public Member Functions
BFS (const MPI_Comm &world, const MPI_Comm &comm, Grid< unsigned int > *h, Grid< std::vector< double >> *f, Grid< double > *b, const std::vector< BasisFunction * > &functions, const std::vector< double > &restraint, const std::vector< double > &boundUp, const std::vector< double > &boundLow, unsigned int cyclefreq, unsigned int frequency, const std::string bnme, const double temperature, const double tol, const double weight, bool converge)
Constructor.
void PreSimulation (Snapshot *snapshot, const class CVManager &cvmanager) override
Pre-simulation hook.
void PostIntegration (Snapshot *snapshot, const class CVManager &cvmanager) override
Post-integration hook.
void PostSimulation (Snapshot *snapshot, const class CVManager &cvmanager) override
Post-simulation hook.
void SetIteration (const int iter)
Set the current iteration.
void SetBasis (const std::vector< double > &coeff, std::vector< double > &unbias)
Set the values for the basis.
~BFS ()
Destructor.
Public Member Functions inherited from SSAGES::Method
Method (unsigned int frequency, const MPI_Comm &world, const MPI_Comm &comm)
Constructor.
void SetCVMask (const std::vector< unsigned int > &mask)
Sets the collective variable mask.
virtual ~Method ()
Destructor.
Public Member Functions inherited from SSAGES::EventListener
EventListener (unsigned int frequency)
Constructor.
unsigned int GetFrequency () const
Get frequency of event listener.
virtual ~EventListener ()
Destructor.
Static Public Member Functions
static BFS * Build (const Json::Value &json, const MPI_Comm &world, const MPI_Comm &comm, const std::string &path)
Build a derived method from JSON node.
Static Public Member Functions inherited from SSAGES::Method
static Method * BuildMethod (const Json::Value &json, const MPI_Comm &world, const MPI_Comm &comm, const std::string &path)
Build a derived method from JSON node.
Static Public Member Functions inherited from SSAGES::EventListener
static unsigned int GetWalkerID (const MPI_Comm &world, const MPI_Comm &comm)
Get walker ID number of specified communicator.
static unsigned int GetNumWalkers (const MPI_Comm &world, const MPI_Comm &comm)
Get total number of walkers in the simulation.
static bool IsMasterRank (const MPI_Comm &comm)
Check if current processor is master.
Private Member Functions
void ProjectBias (const CVList &cvs, const double beta)
The functions which calculates the updated bias and coefficients and then stores them.
void InBounds (const CVList &cvs)
A function which checks to see if the CVs are still in bounds.
void PrintBias (const CVList &cvs, const double beta)
Prints the current bias to a defined file from the JSON.
Private Attributes
Grid< unsigned int > * h_
Grid of visited states.
Grid< double > * b_
Stored bias potential.
Grid< std::vector< double > > * f_
Stored gradients.
std::vector< double > unbias_
The biased histogram of states.
std::vector< double > coeffArr_
The coefficient array for restart runs.
BasisEvaluator evaluator_
The basis evaluator class.
std::vector< double > restraint_
Spring constants for restrained system.
std::vector< double > boundUp_
Upper position of the spring restraint.
std::vector< double > boundLow_
Lower position of the spring restraint.
unsigned int cyclefreq_
Frequency of coefficient updates.
unsigned int cyclefreqTmp_
Temporary cyclefrequency that ensures sweeps are of proper length for restrained simulations.
unsigned int step_
Step counter for the cyclefrequency.
unsigned int mpiid_
The node that the current system belongs to, primarily for printing and debugging.
double weight_
Weighting for potentially faster sampling.
double temperature_
Self-defined temperature.
double tol_
The tolerance criteria for the system .
bool bounds_
A variable to check to see if the simulation is in bounds or not.
bool convergeExit_
A check to see if you want the system to end when it reaches the convergence criteria.
std::string bnme_
unsigned int iteration_
Iteration counter.
Additional Inherited Members
Protected Attributes inherited from SSAGES::Method
mxx::comm world_
Global MPI communicator.
mxx::comm comm_
Local MPI communicator.
std::vector< unsigned int > cvmask_
Mask which identifies which CVs to act on.
Detailed Description
Basis Function Sampling Algorithm.
Implementation of the Basis Function Sampling Method based on [WHITMER2014190602].
Definition at line 38 of file BasisFunc.h.
Constructor & Destructor Documentation
SSAGES::BFS::BFS (const MPI_Comm & world, const MPI_Comm & comm, Grid< unsigned int > * h, Grid< std::vector< double >> * f, Grid< double > * b, const std::vector< BasisFunction * > & functions, const std::vector< double > & restraint, const std::vector< double > & boundUp, const std::vector< double > & boundLow, unsigned int cyclefreq, unsigned int frequency, const std::string bnme, const double temperature, const double tol, const double weight, bool converge) inline
Constructor.
Parameters
world MPI global communicator.
comm MPI local communicator.
h Grid containing histogram.
f Grid containing histogram.
b Grid containing histogram.
functions Vector of basis functions.
restraint Restraint spring constants.
boundUp Upper bounds of restraint springs.
boundLow Lower bounds of restraint springs.
cyclefreq Cycle frequency.
frequency Frequency with which this Method is applied.
bnme Basis file name.
temperature Automatically set temperature.
tol Threshold for tolerance criterion.
weight Weight for improved sampling.
converge If True quit on convergence.
Constructs an instance of the Basis function sampling method. The coefficients describe the basis projection of the system. This is updated once every cyclefreq_. For now, only the Legendre polynomial is implemented. Others will be added later.
Definition at line 181 of file BasisFunc.h.
References PostIntegration(), PostSimulation(), and PreSimulation().
                            :
         Method(frequency, world, comm),
         h_(h),  b_(b), f_(f), unbias_(), coeffArr_(), evaluator_(functions),
         restraint_(restraint), boundUp_(boundUp), boundLow_(boundLow),
         cyclefreq_(cyclefreq), mpiid_(0), weight_(weight),
         temperature_(temperature), tol_(tol),
         convergeExit_(converge), bnme_(bnme), iteration_(0)
         {
         }
Member Function Documentation
BFS * SSAGES::BFS::Build (const Json::Value & json, const MPI_Comm & world, const MPI_Comm & comm, const std::string & path) static
Build a derived method from JSON node.
Parameters
json JSON Value containing all input information.
world MPI global communicator.
comm MPI local communicator.
path Path for JSON path specification.
Returns
Pointer to the Method built. nullptr if an unknown error occurred.
This function builds a registered method from a JSON node. The difference between this function and "Build" is that this automatically determines the appropriate derived type based on the JSON node information.
Note
Object lifetime is the caller's responsibility.
Definition at line 308 of file BasisFunc.cpp.
References Json::Requirement::GetErrors(), SSAGES::GridBase< T >::GetNumPoints(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), and Json::ObjectRequirement::Validate().
Referenced by SetBasis().
     {
         ObjectRequirement validator;
         Value schema;
         CharReaderBuilder rbuilder;
         CharReader* reader = rbuilder.newCharReader();
         reader->parse(JsonSchema::BFSMethod.c_str(),
                       JsonSchema::BFSMethod.c_str() + JsonSchema::BFSMethod.size(),
                       &schema, nullptr);
         validator.Parse(schema, path);
         //Validate Inputs
         validator.Validate(json, path);
         if(validator.HasErrors())
             throw BuildException(validator.GetErrors());
         std::vector<double> restrCV(0);
         for(auto& restr : json["CV_restraint_spring_constants"])
             restrCV.push_back(restr.asDouble());
         std::vector<double> boundLow(0);
         for(auto& bndl : json["CV_restraint_minimums"])
             boundLow.push_back(bndl.asDouble());
         std::vector<double> boundUp(0);
         for(auto& bndu : json["CV_restraint_maximums"])
             boundUp.push_back(bndu.asDouble());
         auto cyclefreq = json.get("cycle_frequency", 100000).asInt();
         auto freq = json.get("frequency", 1).asInt();
         auto wght = json.get("weight", 1.0).asDouble();
         auto bnme = json.get("basis_filename", "").asString();
         auto temp = json.get("temperature", 0.0).asDouble();
         auto tol  = json.get("tolerance", 1e-6).asDouble();
         auto conv = json.get("convergence_exit", false).asBool();
         Grid<unsigned int> *h = Grid<unsigned int>::BuildGrid(
                                         json.get("grid", Json::Value()) );
         Grid<std::vector<double>> *f = Grid<std::vector<double>>::BuildGrid(
                                         json.get("grid", Json::Value()) );
         Grid<double> *b = Grid<double>::BuildGrid(
                                         json.get("grid", Json::Value()) );
         size_t ii = 0;
         std::vector<BasisFunction*> functions;
         for(auto& m : json["basis_functions"])
         {
             auto *bf = BasisFunction::Build(m, path, b->GetNumPoints(ii));
             functions.push_back(bf);
             ii++;
         }
         // If restraints were not specified then set them equal to zero
         if (restrCV.size() == 0) {
             // Choose simplest array that should have equivalent size
             for(size_t i = 0; i<functions.size(); i++)
                 restrCV.push_back(0); // Push back value of 0
         }
         // This also needs to be the same for upper bounds and lower bounds
         if (boundLow.size() == 0) {
             // Choose simplest array that should have equivalent size
             for(size_t i = 0; i<functions.size(); i++)
                 boundLow.push_back(0); // Push back value of 0
         }
         // This also needs to be the same for upper bounds and lower bounds
         if (boundUp.size() == 0) {
             // Choose simplest array that should have equivalent size
             for(size_t i = 0; i<functions.size(); i++)
                 boundUp.push_back(0); // Push back value of 0
         }
         // Check to make sure that the arrays for boundaries and restraints are of the same length
         if (boundUp.size() != boundLow.size() && boundLow.size() != restrCV.size()) {
             std::cerr<<"ERROR: Number of restraint boundaries do not match number of spring constants."<<std::endl;
             std::cerr<<"Boundary size is " << boundUp.size() << " boundary low size is " << boundLow.size() << " restraints size is" << restrCV.size() << std::endl;
             MPI_Abort(world, EXIT_FAILURE);
         }
         auto* m = new BFS(world, comm, h, f, b, functions, restrCV, boundUp, boundLow,
                             cyclefreq, freq, bnme, temp, tol, wght,
                             conv);
         if(json.isMember("iteration"))
             m->SetIteration(json.get("iteration",0).asInt());
         // Check if previously saved grids exist. If so, check that data match and load grids.
         std::ifstream restrFile;
         restrFile.open("restart"+bnme+".out");
         if(restrFile.is_open())
         {
             std::string line;
             std::vector<double> coeff;
             std::vector<double> unbias;
             bool coeffFlag = false;
             bool basisFlag = false;
             std::cout << "Attempting to load data from a previous run of BFS." << std::endl;
             while(!std::getline(restrFile,line).eof())
             {
                 if(line.find("COEFFICIENTS") != std::string::npos) {
                     std::getline(restrFile,line);
                     coeffFlag = true;
                 }
                 else if (line.find("HISTOGRAM") != std::string::npos) {
                     std::getline(restrFile,line);
                     basisFlag = true;
                     coeffFlag = false;
                 }
                 if(coeffFlag) {
                     coeff.push_back(std::stod(line));
                 }
                 else if (basisFlag) {
                     unbias.push_back(std::stod(line));
                 }
             }
             m->SetBasis(coeff, unbias);
             restrFile.close();
         }
         return m;
     }
void SSAGES::BFS::InBounds (const CVList & cvs) private
A function which checks to see if the CVs are still in bounds.
Parameters
cvs List of CVs to check
Definition at line 272 of file BasisFunc.cpp.
     {
         std::vector<double> x (cvs.size(),0);
         //This is calculating the derivatives for the bias force
         for (size_t j = 0; j < cvs.size(); ++j)
         {
             x[j] = cvs[j]->GetValue();
             double min = h_->GetLower(j);
             double max = h_->GetUpper(j);
             if(!h_->GetPeriodic(j))
             {
                 // In order to prevent the index for the histogram from going out of bounds a check is in place
                 if(x[j] > max && bounds_)
                 {
                     //std::cout<<"WARNING: CV is above the maximum boundary."<<std::endl;
                     //std::cout<<"Statistics will not be gathered during this interval"<<std::endl;
                     bounds_ = false;
                     break;
                 }
                 else if(x[j] < min && bounds_)
                 {
                     //std::cout<<"WARNING: CV is below the minimum boundary."<<std::endl;
                     //std::cout<<"Statistics will not be gathered during this interval"<<std::endl;
                     bounds_ = false;
                     break;
                 }
                 else if(x[j] < max && x[j] > min && !bounds_)
                 {
                     //std::cout<<"CV has returned in between bounds. Run is resuming"<<std::endl;
                     bounds_ = true;
                 }
             }
         }
     }
void SSAGES::BFS::PostIntegration (Snapshot * snapshot, const class CVManager & cvmanager) override virtual
Post-integration hook.
Parameters
snapshot Simulation snapshot.
cvmanager Collective variable manager.
Implements SSAGES::Method.
Definition at line 81 of file BasisFunc.cpp.
References SSAGES::CVManager::GetCVs(), SSAGES::Snapshot::GetForces(), SSAGES::Snapshot::GetIteration(), SSAGES::Snapshot::GetKb(), and SSAGES::Snapshot::GetVirial().
Referenced by BFS().
     {
         auto cvs = cvmanager.GetCVs(cvmask_);
         std::vector<double> x(cvs.size(),0);
         /*The binned cv space is updated at every step
          *After a certain number of steps has been passed, the system updates a
          *bias projection based on the visited histogram states
          */
         for(size_t i = 0; i < cvs.size(); ++i)
         {
             x[i] = cvs[i]->GetValue();
         }
         // The histogram is updated based on the index
         InBounds(cvs);
         if (bounds_) {h_->at(x) += 1;}
         else {cyclefreq_++;}
         // Update the basis projection after the requisite number of steps
         int steps = snapshot->GetIteration()-step_;
         if(steps  % cyclefreq_ == 0) {
             step_ = snapshot->GetIteration();
             cyclefreq_ = cyclefreqTmp_;
             double beta;
             beta = 1.0 / (temperature_ * snapshot->GetKb());
             // For systems with poorly defined temperature (ie: 1 particle) the
             // user needs to define their own temperature. This is a hack that
             // will be removed in future versions.
             iteration_+= 1;
             ProjectBias(cvs,beta);
             std::cout<<"Node: ["<<mpiid_<<"]"<<std::setw(10)<<"\tSweep: "<<iteration_<<std::endl;
         }
         // This gets the bias force from the grid
         std::vector<double> bias_grad(cvs.size(),0);
         if (bounds_)
         {
             auto& bias = f_->at(x);
             for (size_t ii = 0; ii<bias.size(); ii++)
                 bias_grad[ii] = bias[ii];
         }
         else
         {
             // This is where the wall potentials are going to be thrown into the method if the system is not a periodic CV
             for(size_t j = 0; j < cvs.size(); ++j)
             {
                 if(!h_->GetPeriodic(j))
                 {
                     if(x[j] > boundUp_[j])
                         bias_grad[j] = -restraint_[j] * (x[j] - boundUp_[j]);
                     else if(x[j] < boundLow_[j])
                         bias_grad[j] = restraint_[j] * (x[j] - boundLow_[j]);
                 }
             }
         }
         // Take each CV and add its biased forces to the atoms using the chain rule
         auto& forces = snapshot->GetForces();
         auto& virial = snapshot->GetVirial();
         for(size_t i = 0; i < cvs.size(); ++i)
         {
             auto& grad = cvs[i]->GetGradient();
             auto& boxgrad = cvs[i]->GetBoxGradient();
             /* Update the forces in snapshot by adding in the force bias from each
              *CV to each atom based on the gradient of the CV.
              */
             for (size_t j = 0; j < forces.size(); ++j)
                 forces[j] += bias_grad[i]*grad[j];
             virial -= bias_grad[i]*boxgrad;
         }
     }
void SSAGES::BFS::PostSimulation (Snapshot * snapshot, const class CVManager & cvmanager) override virtual
Post-simulation hook.
Parameters
snapshot Simulation snapshot.
cvmanager Collective variable manager.
Implements SSAGES::Method.
Definition at line 160 of file BasisFunc.cpp.
Referenced by BFS().
     {
         std::cout<<"Run has finished"<<std::endl;
     }
void SSAGES::BFS::PreSimulation (Snapshot * snapshot, const class CVManager & cvmanager) override virtual
Pre-simulation hook.
Parameters
snapshot Simulation snapshot.
cvmanager Collective variable manager.
Implements SSAGES::Method.
Definition at line 36 of file BasisFunc.cpp.
References SSAGES::CVManager::GetCVs(), and SSAGES::Snapshot::GetWalkerID().
Referenced by BFS().
     {
         auto cvs = cvmanager.GetCVs(cvmask_);
         // For print statements and file I/O, the walker IDs are used
         mpiid_ = snapshot->GetWalkerID();
         // Make sure the iteration index is set correctly
         iteration_ = 0;
         step_ = 0;
         // Set the temporary sweep frequency to the same as the input
         cyclefreqTmp_ = cyclefreq_;
         // There are a few error messages / checks that are in place with
         // defining CVs and grids
         if(h_->GetDimension() != cvs.size())
         {
             std::cerr<<"ERROR: Grid dimensions doesn't match number of CVS."<<std::endl;
             MPI_Abort(world_, EXIT_FAILURE);
         }
         // This is to check for non-periodic bounds. It comes into play in the update bias function
         bounds_ = true;
         unbias_.resize(h_->size(),0);
         std::fill(unbias_.begin(),unbias_.end(),1.0);
         // Initialize the mapping for the hist function
         for (auto &val : *h_) {
             val = 0;
         }
         // Reset the values in the force grid
         for (auto &val : *f_) {
             for (size_t i = 0; i <val.size(); i++) {
                 val[i] = 0;
             }
         }
         // Reset the values in the bias potential grid
         for (auto &val : *b_) {
             val = 0;
         }
     }
void SSAGES::BFS::PrintBias (const CVList & cvs, const double beta) private
Prints the current bias to a defined file from the JSON.
Parameters
cvs List of collective variables.
beta Scale parameter.
Definition at line 227 of file BasisFunc.cpp.
References SSAGES::Grid< T >::begin().
     {
         // The filenames will have a standard name, with a user-defined suffix
         std::string filename1 = "basis"+bnme_+".out";
         std::string filename2 = "restart"+bnme_+".out";
         std::ofstream basisout;
         std::ofstream coeffout;
         basisout.precision(5);
         coeffout.precision(5);
         basisout.open(filename1.c_str());
         coeffout.open(filename2.c_str());
         // The CV values, PMF projection, PMF, and biased histogram are output for the user
         basisout << "The information stored in this file is the output of a Basis Function Sampling run" << std::endl;
         basisout << "CV Values" << std::setw(15*cvs.size()) << "Basis Set Bias" << std::setw(15) << "PMF Estimate" << std::endl;
         coeffout << "The information stored in this file is for the purpose of restarting simulations with BFS" << std::endl;
         coeffout << "***COEFFICIENTS***" << std::endl;
         size_t j = 0;
         for(Grid<double>::iterator it = b_->begin(); it != b_->end(); ++it, ++j)
         {
             for(size_t k = 0; k < cvs.size(); ++k)
             {
                 // Evaluate the CV values for printing purposes
                 basisout << it.coordinate(k) << std::setw(15);
             }
             basisout << -(*it) << std::setw(15) <<
                         -1.0/beta*log(unbias_[j]) <<
                         std::endl;
         }
         std::vector<double> coeff = evaluator_.GetCoeff();
         for (auto& val : coeff) {
             coeffout << val << std::endl;
         }
         coeffout << "***HISTOGRAM***" << std::endl;
         for (auto& val : unbias_) {
             coeffout << val << std::endl;
         }
         basisout.close();
         coeffout.close();
     }
void SSAGES::BFS::ProjectBias (const CVList & cvs, const double beta) private
The functions which calculates the updated bias and coefficients and then stores them.
Parameters
cvs List of CVs onto which the bias is projected
beta Thermodynamic beta (1/kT)
Definition at line 166 of file BasisFunc.cpp.
References SSAGES::Grid< T >::begin(), and SSAGES::GridBase< T >::data().
     {
         double sum  = 0.0;
         // For multiple walkers, the struct is unpacked
         Grid<unsigned int> histlocal(*h_);
         // Summed between all walkers
         MPI_Allreduce(histlocal.data(), h_->data(), h_->size(), MPI_INT, MPI_SUM, world_);
         h_->syncGrid();
         // Construct the biased histogram
         size_t i = 0;
         for (Grid<unsigned int>::iterator it2 = h_->begin(); it2 != h_->end(); ++it2, ++i)
         {
             /* The evaluation of the biased histogram which projects the histogram to the
              * current bias of CV space.
              */
             unbias_[i] += (*it2) * exp(beta * b_->at(it2.coordinates()));
         }
         // Reset histogram
         for (auto &val : *h_) {
             val = 0;
         }
         // Create the log array and send that to the integrator
         std::vector<double> z (unbias_.size(),0);
         for (i = 0; i < unbias_.size(); i++)
             // Make sure the log of the biased histogram is a number
             z[i] = 1.0/beta*log(unbias_[i] * weight_);
         //Update the coefficients and determine the difference from the previous iteration
         sum = evaluator_.UpdateCoeff(z,h_);
         coeffArr_ = evaluator_.GetCoeff();
         //Update both the gradient and the bias on the grids
         evaluator_.UpdateBias(b_,f_);
         if(IsMasterRank(world_)) {
             // Write coeff at this step, but only one walker
             std::cout<<"Coefficient difference is: " <<sum<<std::endl;
             PrintBias(cvs,beta);
         }
         // The convergence tolerance and whether the user wants to exit are incorporated here
         if(sum < tol_)
         {
             std::cout<<"System has converged"<<std::endl;
             if(convergeExit_)
             {
                 std::cout<<"User has elected to exit. System is now exiting"<<std::endl;
                 exit(EXIT_SUCCESS);
             }
         }
     }
void SSAGES::BFS::SetBasis (const std::vector< double > & coeff, std::vector< double > & unbias) inline
Set the values for the basis.
Parameters
coeff List of coefficients.
unbias List of unbiased values.
This function is used to set starting values at the beginning of a run. For example when continuing from a restart value.
Definition at line 247 of file BasisFunc.h.
References Build(), and SSAGES::BasisEvaluator::SetCoeff().
         {
             evaluator_.SetCoeff(coeff);
             unbias_ = unbias;
         }
void SSAGES::BFS::SetIteration (const int iter) inline
Set the current iteration.
Parameters
iter New value for the current iteration.
This function is used to set the current iteration, for example when continuing from a restart.
Definition at line 234 of file BasisFunc.h.
         {
             iteration_ = iter;
         }
Member Data Documentation
Grid<double>* SSAGES::BFS::b_ private
Stored bias potential.
The sum of basis functions that adds up to the bias potential of the surface
Definition at line 52 of file BasisFunc.h.
std::string SSAGES::BFS::bnme_ private
The option to name both the basis and coefficient files will be given Basis filename
Definition at line 151 of file BasisFunc.h.
BasisEvaluator SSAGES::BFS::evaluator_ private
The basis evaluator class.
A class which holds the basis functions and updates the coefficients at each cycle
Definition at line 76 of file BasisFunc.h.
Grid<std::vector<double> >* SSAGES::BFS::f_ private
Stored gradients.
The gradients corresponding to each point on the grid
Definition at line 58 of file BasisFunc.h.
Grid<unsigned int>* SSAGES::BFS::h_ private
Grid of visited states.
Grid is stored locally.
Definition at line 46 of file BasisFunc.h.
std::vector<double> SSAGES::BFS::restraint_ private
Spring constants for restrained system.
The system uses this to determine if the system is to be restrained on the defined interval. The user inputs the spring constants if the system is not periodic.
Definition at line 84 of file BasisFunc.h.
double SSAGES::BFS::temperature_ private
Self-defined temperature.
In the case of the MD engine using a poorly defined temperature, the option to throw it into the method is available. If not provided it takes the value from the engine.
Definition at line 118 of file BasisFunc.h.
std::vector<double> SSAGES::BFS::unbias_ private
The biased histogram of states.
The biased histogram of states has the form hist_*exp(phi*beta), where phi is the bias potential and beta is the inverse of the temperature. It is defined globally.
Definition at line 66 of file BasisFunc.h.
double SSAGES::BFS::weight_ private
Weighting for potentially faster sampling.
Weighting can be used to potentially sample faster, however it can cause the simulation to explode. By default this value will be set to 1.0
Definition at line 110 of file BasisFunc.h.
The documentation for this class was generated from the following files:
/home/cody/SSAGES-public/src/Methods/BasisFunc.h
/home/cody/SSAGES-public/src/Methods/BasisFunc.cpp