SSAGES: SSAGES::ParticleSeparationCV Class Reference
SSAGES::ParticleSeparationCV Class Reference
CVs
Collective variable on the distance between two particles' centers of mass.
#include <ParticleSeparationCV.h>
Public Member Functions
ParticleSeparationCV (const Label &group1, const Label &group2)
Constructor.
ParticleSeparationCV (const Label &group1, const Label &group2, bool dimx, bool dimy, bool dimz)
Constructor.
void Initialize (const Snapshot &snapshot) override
Initialize necessary variables.
void Evaluate (const Snapshot &snapshot) override
Evaluate the CV.
Public Member Functions inherited from SSAGES::CollectiveVariable
CollectiveVariable ()
Constructor.
virtual ~CollectiveVariable ()
Destructor.
virtual void Initialize (const class Snapshot &)
Initialize CV.
virtual void Evaluate (const class Snapshot &)=0
Evaluate CV.
double GetValue () const
Get current value of the CV.
virtual double GetMinimumImage (double) const
Returns the minimum image of a CV based on the input location.
virtual double GetPeriodicValue (double location) const
Apply periodic boundaries to a given value.
const std::vector< Vector3 > & GetGradient () const
Get current gradient of the CV.
const Matrix3 & GetBoxGradient () const
Get gradient contribution to box.
const std::array< double, 2 > & GetBoundaries ()
Get CV boundaries.
virtual double GetDifference (double location) const
Static Public Member Functions
static ParticleSeparationCV * Build (const Json::Value &json, const std::string &path)
Set up collective variable.
Static Public Member Functions inherited from SSAGES::CollectiveVariable
static CollectiveVariable * BuildCV (const Json::Value &json, const std::string &path)
Set up collective variable.
Private Attributes
Label group1_
Atom ID's of group 1.
Label group2_
Atom ID's of group 2.
Bool3 dim_
Each dimension determines if it is applied by the CV.
Additional Inherited Members
Protected Attributes inherited from SSAGES::CollectiveVariable
std::vector< Vector3 > grad_
Gradient vector dCv/dxi.
Matrix3 boxgrad_
Gradient w.r.t box vectors dCv/dHij.
double val_
Current value of CV.
std::array< double, 2 > bounds_
Bounds on CV.
Detailed Description
Collective variable on the distance between two particles' centers of mass.
Collective variable on two particle positions. This CV will return the distance between two specific atom groups of the simulation.
Definition at line 39 of file ParticleSeparationCV.h.
Constructor & Destructor Documentation
ParticleSeparationCV() [1/2]
SSAGES::ParticleSeparationCV::ParticleSeparationCV (const Label & group1, const Label & group2) inline
Constructor.
Parameters
group1 Vector of atom ID's of the first particle.
group2 Vector of atom ID's of the second particle.
Construct a paarticle separation CV.
Todo:
bounds needs to be an input.
Definition at line 58 of file ParticleSeparationCV.h.
                                                                        :
         group1_(group1), group2_(group2), dim_{true, true, true}
         {}
Referenced by Build().
ParticleSeparationCV() [2/2]
SSAGES::ParticleSeparationCV::ParticleSeparationCV (const Label & group1, const Label & group2, bool dimx, bool dimy, bool dimz) inline
Constructor.
Parameters
group1 Vector of atom ID's of the first particle.
group2 Vector of atom ID's of the second particle.
dimx If True, include x dimension.
dimy If True, include y dimension.
dimz If True, include z dimension.
Construct a particle separation CV.
Todo:
Bounds needs to be an input.
Definition at line 74 of file ParticleSeparationCV.h.
                                                                                                         :
         group1_(group1), group2_(group2), dim_{dimx, dimy, dimz}
         {}
Member Function Documentation
Build()
static ParticleSeparationCV* SSAGES::ParticleSeparationCV::Build (const Json::Value & json, const std::string & path) inline static
Set up collective variable.
Parameters
json JSON input value.
path Path for JSON path specification.
Returns
Pointer to the CV built by this function. nullptr in case of unknown error.
Builds a CV from a JSON node. Returns a pointer to the built cv. If an unknown error is encountered, this function will return a nullptr, but generally it will throw a BuildException on failure.
Warning
Object lifetime is the caller's responsibility.
Definition at line 167 of file ParticleSeparationCV.h.
         {
             Json::ObjectRequirement validator;
             Json::Value schema;
             Json::CharReaderBuilder rbuilder;
             Json::CharReader* reader = rbuilder.newCharReader();
             reader->parse(JsonSchema::ParticleSeparationCV.c_str(),
                           JsonSchema::ParticleSeparationCV.c_str() + JsonSchema::ParticleSeparationCV.size(),
                           &schema, nullptr);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             std::vector<int> group1, group2;
             for(auto& s : json["group1"])
                 group1.push_back(s.asInt());
             for(auto& s : json["group2"])
                 group2.push_back(s.asInt());
             ParticleSeparationCV* c;
             if(json.isMember("dimension"))
             {
                 auto fixx = json["dimension"][0].asBool();
                 auto fixy = json["dimension"][1].asBool();
                 auto fixz = json["dimension"][2].asBool();
                 c = new ParticleSeparationCV(group1, group2, fixx, fixy, fixz);
             }
             else
                 c = new ParticleSeparationCV(group1, group2);
             return c;
         }
References Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), ParticleSeparationCV(), and Json::ObjectRequirement::Validate().
Referenced by SSAGES::CollectiveVariable::BuildCV().
Evaluate()
void SSAGES::ParticleSeparationCV::Evaluate (const Snapshot & snapshot) inline override
Evaluate the CV.
Parameters
snapshot Current simulation snapshot.
Definition at line 128 of file ParticleSeparationCV.h.
         {
             // Get local atom indices.
             std::vector<int> idx1, idx2;
             snapshot.GetLocalIndices(group1_, &idx1);
             snapshot.GetLocalIndices(group2_, &idx2);
             // Get data from snapshot.
             auto n = snapshot.GetNumAtoms();
             const auto& masses = snapshot.GetMasses();
             // Initialize gradient.
             std::fill(grad_.begin(), grad_.end(), Vector3{0,0,0});
             grad_.resize(n, Vector3{0,0,0});
             boxgrad_ = Matrix3::Zero();
             // Get centers of mass.
             auto mtot1 = snapshot.TotalMass(idx1);
             auto mtot2 = snapshot.TotalMass(idx2);
             Vector3 com1 = snapshot.CenterOfMass(idx1);
             Vector3 com2 = snapshot.CenterOfMass(idx2);
             // Account for pbc.
             Vector3 rij = snapshot.ApplyMinimumImage(com1 - com2).cwiseProduct(dim_.cast<double>());
             // Compute gradient.
             val_ = rij.norm();
             for(auto& id : idx1)
             {
                 grad_[id] = rij/val_*masses[id]/mtot1;
                 boxgrad_ += grad_[id]*rij.transpose();
             }
             for(auto& id : idx2)
                 grad_[id] = -rij/val_*masses[id]/mtot2;
         }
References SSAGES::Snapshot::ApplyMinimumImage(), SSAGES::CollectiveVariable::boxgrad_, SSAGES::Snapshot::CenterOfMass(), dim_, SSAGES::Snapshot::GetLocalIndices(), SSAGES::Snapshot::GetMasses(), SSAGES::Snapshot::GetNumAtoms(), SSAGES::CollectiveVariable::grad_, group1_, group2_, SSAGES::Snapshot::TotalMass(), and SSAGES::CollectiveVariable::val_.
Initialize()
void SSAGES::ParticleSeparationCV::Initialize (const Snapshot & snapshot) inline override
Initialize necessary variables.
Parameters
snapshot Current simulation snapshot.
Definition at line 82 of file ParticleSeparationCV.h.
         {
             using std::to_string;
             auto n1 = group1_.size(), n2 = group2_.size();
             // Make sure atom ID's are on at least one processor.
             std::vector<int> found1(n1, 0), found2(n2, 0);
             for(size_t i = 0; i < n1; ++i)
             {
                 if(snapshot.GetLocalIndex(group1_[i]) != -1)
                     found1[i] = 1;
             }
             for(size_t i = 0; i < n2; ++i)
             {
                 if(snapshot.GetLocalIndex(group2_[i]) != -1)
                     found2[i] = 1;
             }
             MPI_Allreduce(MPI_IN_PLACE, found1.data(), n1, MPI_INT, MPI_SUM, snapshot.GetCommunicator());
             MPI_Allreduce(MPI_IN_PLACE, found2.data(), n2, MPI_INT, MPI_SUM, snapshot.GetCommunicator());
             unsigned ntot1 = std::accumulate(found1.begin(), found1.end(), 0, std::plus<int>());
             unsigned ntot2 = std::accumulate(found2.begin(), found2.end(), 0, std::plus<int>());
             if(ntot1 != n1)
                 throw BuildException({
                     "ParticleSeparationCV: Expected to find " +
                     to_string(n1) +
                     " atoms in particle 1, but only found " +
                     to_string(ntot1) + "."
                 });
             if(ntot2 != n2)
                 throw BuildException({
                     "ParticleSeparationCV: Expected to find " +
                     to_string(n2) +
                     " atoms in particle 2, but only found " +
                     to_string(ntot2) + "."
                 });
         }
References SSAGES::Snapshot::GetCommunicator(), SSAGES::Snapshot::GetLocalIndex(), group1_, and group2_.
The documentation for this class was generated from the following file:
/home/michael/development/SSAGES/src/CVs/ParticleSeparationCV.h