SSAGES: SSAGES::AngleCV Class Reference
SSAGES::AngleCV Class Reference
Collective variable to calculate angle.
#include <AngleCV.h>
Public Member Functions
AngleCV (int atomid1, int atomid2, int atomid3)
Constructor.
void Initialize (const Snapshot &snapshot) override
Initialize necessary variables.
void Evaluate (const Snapshot &snapshot) override
Evaluate the CV.
Public Member Functions inherited from SSAGES::CollectiveVariable
CollectiveVariable ()
Constructor.
virtual ~CollectiveVariable ()
Destructor.
virtual void Initialize (const class Snapshot &)
Initialize CV.
virtual void Evaluate (const class Snapshot &)=0
Evaluate CV.
double GetValue () const
Get current value of the CV.
virtual double GetMinimumImage (double) const
Returns the minimum image of a CV based on the input location.
virtual double GetPeriodicValue (double location) const
Apply periodic boundaries to a given value.
const std::vector< Vector3 > & GetGradient () const
Get current gradient of the CV.
const Matrix3 & GetBoxGradient () const
Get gradient contribution to box.
const std::array< double, 2 > & GetBoundaries ()
Get CV boundaries.
virtual double GetDifference (double location) const
Static Public Member Functions
static AngleCV * Build (const Json::Value &json, const std::string &path)
Set up collective variable.
Static Public Member Functions inherited from SSAGES::CollectiveVariable
static CollectiveVariable * BuildCV (const Json::Value &json, const std::string &path)
Set up collective variable.
Private Attributes
Label atomids_
Vector of 3 atom ID's of interest.
Additional Inherited Members
Protected Attributes inherited from SSAGES::CollectiveVariable
std::vector< Vector3 > grad_
Gradient vector dCv/dxi.
Matrix3 boxgrad_
Gradient w.r.t box vectors dCv/dHij.
double val_
Current value of CV.
std::array< double, 2 > bounds_
Bounds on CV.
Detailed Description
Collective variable to calculate angle.
Definition at line 35 of file AngleCV.h.
Constructor & Destructor Documentation
AngleCV()
SSAGES::AngleCV::AngleCV (int atomid1, int atomid2, int atomid3) inline
Constructor.
Parameters
atomid1 ID of the first atom defining the angle.
atomid2 ID of the second atom defining the angle.
atomid3 ID of the third atom defining the angle.
Construct an dihedral CV.
Todo:
Bounds needs to be an input and periodic boundary conditions
Definition at line 53 of file AngleCV.h.
                                                        :
         atomids_({atomid1, atomid2, atomid3})
         {
             bounds_ = {{0,M_PI}};
         }
Referenced by Build().
Member Function Documentation
Build()
static AngleCV* SSAGES::AngleCV::Build (const Json::Value & json, const std::string & path) inline static
Set up collective variable.
Parameters
json JSON input value.
path Path for JSON path specification.
Returns
Pointer to the CV built by this function. nullptr in case of unknown error.
Builds a CV from a JSON node. Returns a pointer to the built cv. If an unknown error is encountered, this function will return a nullptr, but generally it will throw a BuildException on failure.
Warning
Object lifetime is the caller's responsibility.
Definition at line 137 of file AngleCV.h.
         {
             Json::ObjectRequirement validator;
             Json::Value schema;
             Json::CharReaderBuilder rbuilder;
             Json::CharReader* reader = rbuilder.newCharReader();
             reader->parse(JsonSchema::AngleCV.c_str(),
                           JsonSchema::AngleCV.c_str() + JsonSchema::AngleCV.size(),
                           &schema, nullptr);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             std::vector<int> atomids;
             for(auto& s : json["atom_ids"])
                 atomids.push_back(s.asInt());
             return new AngleCV(atomids[0], atomids[1], atomids[2]);
         }
References AngleCV(), Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), and Json::ObjectRequirement::Validate().
Referenced by SSAGES::CollectiveVariable::BuildCV().
Evaluate()
void SSAGES::AngleCV::Evaluate (const Snapshot & snapshot) inline override
Evaluate the CV.
Parameters
snapshot Current simulation snapshot.
Definition at line 85 of file AngleCV.h.
         {
             // Get data from snapshot.
             auto n = snapshot.GetNumAtoms();
             const auto& pos = snapshot.GetPositions();
             auto& comm = snapshot.GetCommunicator();
             // Initialize gradient.
             std::fill(grad_.begin(), grad_.end(), Vector3{0,0,0});
             grad_.resize(n, Vector3{0,0,0});
             Vector3 xi{0, 0, 0}, xj{0, 0, 0}, xk{0, 0, 0};
             auto iindex = snapshot.GetLocalIndex(atomids_[0]);
             auto jindex = snapshot.GetLocalIndex(atomids_[1]);
             auto kindex = snapshot.GetLocalIndex(atomids_[2]);
             if(iindex != -1) xi = pos[iindex];
             if(jindex != -1) xj = pos[jindex];
             if(kindex != -1) xk = pos[kindex];
             // By performing a reduce, we actually collect all. This can
             // be converted to a more intelligent allgater on rank then bcast.
             MPI_Allreduce(MPI_IN_PLACE, xi.data(), 3, MPI_DOUBLE, MPI_SUM, comm);
             MPI_Allreduce(MPI_IN_PLACE, xj.data(), 3, MPI_DOUBLE, MPI_SUM, comm);
             MPI_Allreduce(MPI_IN_PLACE, xk.data(), 3, MPI_DOUBLE, MPI_SUM, comm);
             // Two vectors
             auto rij = snapshot.ApplyMinimumImage(xi - xj);
             auto rkj = snapshot.ApplyMinimumImage(xk - xj);
             auto dotP = rij.dot(rkj);
             auto nrij = rij.norm();
             auto nrkj = rkj.norm();
             auto dotPnn = dotP/(nrij*nrkj);
             val_ = acos(dotPnn);
             // Calculate gradients
             auto prefactor = -1.0/(sqrt(1. - dotPnn*dotPnn)*nrij*nrkj);
             Vector3 gradi{0, 0, 0}, gradk{0, 0, 0};
             if(iindex != -1) gradi = prefactor*(rkj - dotP*rij/(nrij*nrij));
             if(kindex != -1) gradk = prefactor*(rij - dotP*rkj/(nrkj*nrkj));
             MPI_Allreduce(MPI_IN_PLACE, gradi.data(), 3, MPI_DOUBLE, MPI_SUM, comm);
             MPI_Allreduce(MPI_IN_PLACE, gradk.data(), 3, MPI_DOUBLE, MPI_SUM, comm);
             if(iindex != -1) grad_[iindex] = gradi;
             if(kindex != -1) grad_[kindex] = gradk;
             if(jindex != -1) grad_[jindex] = -gradi - gradk;
         }
References SSAGES::Snapshot::ApplyMinimumImage(), atomids_, SSAGES::Snapshot::GetCommunicator(), SSAGES::Snapshot::GetLocalIndex(), SSAGES::Snapshot::GetNumAtoms(), SSAGES::Snapshot::GetPositions(), SSAGES::CollectiveVariable::grad_, and SSAGES::CollectiveVariable::val_.
Initialize()
void SSAGES::AngleCV::Initialize (const Snapshot & snapshot) inline override
Initialize necessary variables.
Parameters
snapshot Current simulation snapshot.
Definition at line 63 of file AngleCV.h.
         {
             using std::to_string;
             std::vector<int> found;
             snapshot.GetLocalIndices(atomids_, &found);
             int nfound = found.size();
             MPI_Allreduce(MPI_IN_PLACE, &nfound, 1, MPI_INT, MPI_SUM, snapshot.GetCommunicator());
             if(nfound != 3)
                 throw BuildException({
                     "TorsionalCV: Expected to find " +
                     to_string(3) +
                     " atoms, but only found " +
                     to_string(nfound) + "."
                 });
         }
References atomids_, SSAGES::Snapshot::GetCommunicator(), and SSAGES::Snapshot::GetLocalIndices().
The documentation for this class was generated from the following file:
/home/michael/development/SSAGES/src/CVs/AngleCV.h