SSAGES: SSAGES::TorsionalCV Class Reference
SSAGES::TorsionalCV Class Reference
CVs
Collective variable on the torsion angles.
#include <TorsionalCV.h>
Public Member Functions
TorsionalCV (int atomid1, int atomid2, int atomid3, int atomid4, bool periodic)
Constructor.
void Initialize (const Snapshot &snapshot) override
Initialize necessary variables.
void Evaluate (const Snapshot &snapshot) override
Evaluate the CV.
double GetPeriodicValue (double Location) const override
Return value taking periodic boundary conditions into account.
double GetDifference (const double Location) const override
Get difference taking periodic boundary conditions into account.
double GetMinimumImage (const double Location) const override
Returns the minimum image of a CV based on the input location.
Public Member Functions inherited from SSAGES::CollectiveVariable
CollectiveVariable ()
Constructor.
virtual ~CollectiveVariable ()
Destructor.
virtual void Initialize (const class Snapshot &)
Initialize CV.
virtual void Evaluate (const class Snapshot &)=0
Evaluate CV.
double GetValue () const
Get current value of the CV.
const std::vector< Vector3 > & GetGradient () const
Get current gradient of the CV.
const Matrix3 & GetBoxGradient () const
Get gradient contribution to box.
const std::array< double, 2 > & GetBoundaries ()
Get CV boundaries.
Static Public Member Functions
static TorsionalCV * Build (const Json::Value &json, const std::string &path)
Set up collective variable.
Static Public Member Functions inherited from SSAGES::CollectiveVariable
static CollectiveVariable * BuildCV (const Json::Value &json, const std::string &path)
Set up collective variable.
Private Attributes
Label atomids_
Vector of 4 atom ID's of interest.
bool periodic_
If True, use periodic boundary conditions.
Additional Inherited Members
Protected Attributes inherited from SSAGES::CollectiveVariable
std::vector< Vector3 > grad_
Gradient vector dCv/dxi.
Matrix3 boxgrad_
Gradient w.r.t box vectors dCv/dHij.
double val_
Current value of CV.
std::array< double, 2 > bounds_
Bounds on CV.
Detailed Description
Collective variable on the torsion angles.
Collective variable on an proper dihedral. This will return the angle between two planes as defined in [VANSCHAIK1993751]. Singularities are avoided as described in [BLONDEL19961132].
Definition at line 42 of file TorsionalCV.h.
Constructor & Destructor Documentation
SSAGES::TorsionalCV::TorsionalCV (int atomid1, int atomid2, int atomid3, int atomid4, bool periodic) inline
Constructor.
Parameters
atomid1 ID of the first atom defining the dihedral angle.
atomid2 ID of the second atom defining the dihedral angle.
atomid3 ID of the third atom defining the dihedral angle.
atomid4 ID of the forth atom defining the dihedral angle.
periodic If True consider periodic boundary conditions.
Construct an dihedral CV.
Todo:
Bounds needs to be an input and periodic boundary conditions
Definition at line 64 of file TorsionalCV.h.
References periodic_.
Referenced by Build().
                                                                                        :
         atomids_({atomid1, atomid2, atomid3, atomid4}), periodic_(periodic)
         {
         }
Member Function Documentation
static TorsionalCV* SSAGES::TorsionalCV::Build (const Json::Value & json, const std::string & path) inline static
Set up collective variable.
Parameters
json JSON input value.
path Path for JSON path specification.
Returns
Pointer to the CV built by this function. nullptr in case of unknown error.
Builds a CV from a JSON node. Returns a pointer to the built cv. If an unknown error is encountered, this function will return a nullptr, but generally it will throw a BuildException on failure.
Warning
Object lifetime is the caller's responsibility.
Definition at line 229 of file TorsionalCV.h.
References Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), TorsionalCV(), and Json::ObjectRequirement::Validate().
Referenced by SSAGES::CollectiveVariable::BuildCV().
         {
             Json::ObjectRequirement validator;
             Json::Value schema;
             Json::CharReaderBuilder rbuilder;
             Json::CharReader* reader = rbuilder.newCharReader();
             reader->parse(JsonSchema::TorsionalCV.c_str(),
                           JsonSchema::TorsionalCV.c_str() + JsonSchema::TorsionalCV.size(),
                           &schema, nullptr);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             std::vector<int> atomids;
             for(auto& s : json["atom_ids"])
                 atomids.push_back(s.asInt());
             auto periodic = json.get("periodic", true).asBool();
             return new TorsionalCV(atomids[0], atomids[1], atomids[2], atomids[3], periodic);
         }
void SSAGES::TorsionalCV::Evaluate (const Snapshot & snapshot) inline override
Evaluate the CV.
Parameters
snapshot Current simulation snapshot.
Definition at line 95 of file TorsionalCV.h.
References SSAGES::Snapshot::ApplyMinimumImage(), SSAGES::Snapshot::GetCommunicator(), SSAGES::Snapshot::GetLocalIndex(), SSAGES::Snapshot::GetNumAtoms(), SSAGES::Snapshot::GetPositions(), SSAGES::CollectiveVariable::grad_, and SSAGES::CollectiveVariable::val_.
         {
             // Get data from snapshot.
             auto n = snapshot.GetNumAtoms();
             const auto& pos = snapshot.GetPositions();
             auto& comm = snapshot.GetCommunicator();
             // Initialize gradient.
             std::fill(grad_.begin(), grad_.end(), Vector3{0,0,0});
             grad_.resize(n, Vector3{0,0,0});
             Vector3 xi{0, 0, 0}, xj{0, 0, 0}, xk{0, 0, 0}, xl{0, 0, 0};
             auto iindex = snapshot.GetLocalIndex(atomids_[0]);
             auto jindex = snapshot.GetLocalIndex(atomids_[1]);
             auto kindex = snapshot.GetLocalIndex(atomids_[2]);
             auto lindex = snapshot.GetLocalIndex(atomids_[3]);
             if(iindex != -1) xi = pos[iindex];
             if(jindex != -1) xj = pos[jindex];
             if(kindex != -1) xk = pos[kindex];
             if(lindex != -1) xl = pos[lindex];
             // By performing a reduce, we actually collect all. This can
             // be converted to a more intelligent allgater on rank then bcast.
             MPI_Allreduce(MPI_IN_PLACE, xi.data(), 3, MPI_DOUBLE, MPI_SUM, comm);
             MPI_Allreduce(MPI_IN_PLACE, xj.data(), 3, MPI_DOUBLE, MPI_SUM, comm);
             MPI_Allreduce(MPI_IN_PLACE, xk.data(), 3, MPI_DOUBLE, MPI_SUM, comm);
             MPI_Allreduce(MPI_IN_PLACE, xl.data(), 3, MPI_DOUBLE, MPI_SUM, comm);
             //Calculate pertinent vectors
             auto F = snapshot.ApplyMinimumImage(xi - xj);
             auto G = snapshot.ApplyMinimumImage(xj - xk);
             auto H = snapshot.ApplyMinimumImage(xl - xk);
             auto A = F.cross(G);
             auto B = H.cross(G);
             auto y = B.cross(A).dot(G.normalized());
             auto x = A.dot(B);
             val_ = atan2(y, x);
             auto Zed = F.dot(G.normalized())/A.dot(A);
             auto Ned = H.dot(G.normalized())/B.dot(B);
             Vector3 gradi{0,0,0}, gradl{0,0,0};
             if(iindex != -1) gradi = -G.norm()*A/A.dot(A);
             if(lindex != -1) gradl = G.norm()*B/B.dot(B);
             MPI_Allreduce(MPI_IN_PLACE, gradi.data(), 3, MPI_DOUBLE, MPI_SUM, comm);
             MPI_Allreduce(MPI_IN_PLACE, gradl.data(), 3, MPI_DOUBLE, MPI_SUM, comm);
             if(iindex != -1) grad_[iindex] = gradi;
             if(lindex != -1) grad_[lindex] = gradl;
             if(jindex != -1) grad_[jindex] = Zed*A - Ned*B - gradi;
             if(kindex != -1) grad_[kindex] = Ned*B  - Zed*A - gradl;
         }
double SSAGES::TorsionalCV::GetDifference (const double Location) const inline override virtual
Get difference taking periodic boundary conditions into account.
Parameters
Location Input value
Returns
Wrapped or unwrapped difference depending on whether periodic boundaries are used.
If periodic boundaries are used, this function calculates the difference and wraps the result into the range (-pi, pi). Otherwise, the simple difference is returned.
Reimplemented from SSAGES::CollectiveVariable.
Definition at line 188 of file TorsionalCV.h.
References GetPeriodicValue(), and SSAGES::CollectiveVariable::val_.
         {
             double PeriodicDiff = val_ - Location;
             if(!periodic_)
                 return PeriodicDiff;
             PeriodicDiff = GetPeriodicValue(PeriodicDiff);
             if(PeriodicDiff > M_PI)
                 PeriodicDiff -= 2.0*M_PI;
             else if(PeriodicDiff < -M_PI)
                 PeriodicDiff += 2.0*M_PI;
             return PeriodicDiff;
         }
double SSAGES::TorsionalCV::GetMinimumImage (const double Location) const inline override virtual
Returns the minimum image of a CV based on the input location.
Parameters
Location Value against which the minimum image is calculated.
Returns
Minimum image of the CV
Takes the input location and applies the periodic boundary conditions to return a minimum image of the CV.
Reimplemented from SSAGES::CollectiveVariable.
Definition at line 213 of file TorsionalCV.h.
References SSAGES::CollectiveVariable::val_.
         {
             double PeriodicDiff = val_ - Location;
             if(!periodic_)
                 return val_;
             if(PeriodicDiff > M_PI)
                 return (val_ - 2.0*M_PI);
             else if(PeriodicDiff < -M_PI)
                 return (val_ + 2.0*M_PI);
             return val_;
         }
double SSAGES::TorsionalCV::GetPeriodicValue (double Location) const inline override virtual
Return value taking periodic boundary conditions into account.
Parameters
Location Input value.
Returns
Wrapped or unwrapped input value depending on whether periodic boundaries are used.
If periodic boundaries are used, this function wraps the input value into the range (-pi, pi). Otherwise the input value is returned unmodified.
Reimplemented from SSAGES::CollectiveVariable.
Definition at line 161 of file TorsionalCV.h.
Referenced by GetDifference().
         {
             if(!periodic_)
                 return Location;
             int n = (int)(Location/(2.0*M_PI));
             double PeriodicLocation;
             PeriodicLocation = Location - n*M_PI;
             if(PeriodicLocation < -M_PI)
                 PeriodicLocation += 2.0*M_PI;
             else if (PeriodicLocation > M_PI)
                 PeriodicLocation -= 2.0*M_PI;
             return PeriodicLocation;
         }
void SSAGES::TorsionalCV::Initialize (const Snapshot & snapshot) inline override
Initialize necessary variables.
Parameters
snapshot Current simulation snapshot.
Definition at line 73 of file TorsionalCV.h.
References SSAGES::Snapshot::GetCommunicator(), and SSAGES::Snapshot::GetLocalIndices().
         {
             using std::to_string;
             std::vector<int> found;
             snapshot.GetLocalIndices(atomids_, &found);
             int nfound = found.size();
             MPI_Allreduce(MPI_IN_PLACE, &nfound, 1, MPI_INT, MPI_SUM, snapshot.GetCommunicator());
             if(nfound != 4)
                 throw BuildException({
                     "TorsionalCV: Expected to find " +
                     to_string(4) +
                     " atoms, but only found " +
                     to_string(nfound) + "."
                 });
         }
The documentation for this class was generated from the following file:
/home/cody/SSAGES-public/src/CVs/TorsionalCV.h