SSAGES: SSAGES::CVManager Class Reference
SSAGES::CVManager Class Reference
Collective variable manager.
#include <CVManager.h>
Public Member Functions
void AddCV (CollectiveVariable *cv)
Adds a CV to the CV manager.
void ClearCVs ()
Clears CVs from CV manager.
CVList GetCVs (const std::vector< unsigned int > &mask=std::vector< unsigned int >()) const
Get CV iterator.
Static Public Member Functions
static void AddCVtoMap (const std::string &name, unsigned int id)
Register CV name with map.
static int LookupCV (const Json::Value &cv, const std::string &path)
Get CV id from map.
Private Attributes
std::vector< CollectiveVariable * > cvs_
List of collective variables.
Static Private Attributes
static std::map< std::string, unsigned int > cvmap_ = {}
Map between CV names and ID's.
Detailed Description
Collective variable manager.
CVManager is a class used to manage collective variables (CVs) and how they are exposed to methods. A metohd may wish to bias on a subset of available CVs. The CVManager provides a seamless interface to masking unwanted CVs and providing a suitable iterator which can be used to iterate through the desired CVs.
CVManager is also responsible for maintaining the lifetime of the CV objects it contains.
Definition at line 42 of file CVManager.h.
Member Function Documentation
AddCV()
void SSAGES::CVManager::AddCV (CollectiveVariable * cv) inline
Adds a CV to the CV manager.
Parameters
cv Pointer to collective variable.
Definition at line 58 of file CVManager.h.
         {
             if(std::find(cvs_.begin(), cvs_.end(), cv) == cvs_.end())
                 cvs_.push_back(cv);
         }
References cvs_.
AddCVtoMap()
static void SSAGES::CVManager::AddCVtoMap (const std::string & name, unsigned int id) inline static
Register CV name with map.
Parameters
name Name of CV to register.
id ID to associate with name.
Note
If a previous name is already used, it will override the old entry.
Definition at line 101 of file CVManager.h.
         {
             cvmap_[name] = id;
         }
References cvmap_.
Referenced by SSAGES::ResourceHandler::Build().
ClearCVs()
void SSAGES::CVManager::ClearCVs () inline
Clears CVs from CV manager.
Note
This destroys all CVs stored in the CV manager!
Definition at line 68 of file CVManager.h.
         {
             for(auto& cv : cvs_)
                 delete cv;
             cvs_.clear();
         }
References cvs_.
GetCVs()
CVList SSAGES::CVManager::GetCVs (const std::vector< unsigned int > & mask = std::vector<unsigned int>()) const inline
Get CV iterator.
Parameters
mask Vector mask which contains the indices of which CV to include in the container.
Returns
CVList containing pointers to requested CVs.
Definition at line 81 of file CVManager.h.
         {
             if(mask.empty())
                 return cvs_;
             // Pack from mask.
             std::vector<CollectiveVariable*> cvs;
             for(auto& i : mask)
                 cvs.push_back(cvs_[i]);
             return cvs;
         }
References cvs_.
Referenced by SSAGES::DirectForwardFlux::CheckForInterfaceCrossings(), SSAGES::Logger::PostIntegration(), SSAGES::ABF::PostIntegration(), SSAGES::ANN::PostIntegration(), SSAGES::BFS::PostIntegration(), SSAGES::CFF::PostIntegration(), SSAGES::DirectForwardFlux::PostIntegration(), SSAGES::ElasticBand::PostIntegration(), SSAGES::FiniteTempString::PostIntegration(), SSAGES::Meta::PostIntegration(), SSAGES::Swarm::PostIntegration(), SSAGES::Umbrella::PostIntegration(), SSAGES::Hook::PostIntegrationHook(), SSAGES::Hook::PostSimulationHook(), SSAGES::Logger::PreSimulation(), SSAGES::ABF::PreSimulation(), SSAGES::ANN::PreSimulation(), SSAGES::BFS::PreSimulation(), SSAGES::CFF::PreSimulation(), SSAGES::ForwardFlux::PreSimulation(), SSAGES::Meta::PreSimulation(), SSAGES::StringMethod::PreSimulation(), SSAGES::Umbrella::PreSimulation(), and SSAGES::Hook::PreSimulationHook().
LookupCV()
static int SSAGES::CVManager::LookupCV (const Json::Value & cv, const std::string & path) inline static
Get CV id from map.
Parameters
cv JSON Value (CV) to look up.
path Path for JSON path specification.
Returns
ID of CV.
Definition at line 112 of file CVManager.h.
         {
             int id = -1;
             if (cv.isString())
             {
                 auto name = cv.asString();
                 if(cvmap_.find(name) == cvmap_.end())
                 {
                     throw BuildException({path + ": CV mask name \"" + name + "\" does not exist."});
                 }
                 id = cvmap_.at(name);
             }
             else if(cv.isIntegral())
             {
                 id = cv.asInt();
                 if(id < 0 || id >= static_cast<int>(cvmap_.size()))
                 {
                     throw BuildException({path + ": CV mask index of " + std::to_string(id) + " does not exist. " +
                                           "Index must be nonnegative and less than " + std::to_string(cvmap_.size()) + "."});
                 }
             }
             else
             {
                 throw BuildException({path + ": CV mask must contain strings or nonnegative integers."});
             }
             return id;
         }
References cvmap_.
Referenced by SSAGES::ResourceHandler::Build().
The documentation for this class was generated from the following files:
/home/michael/development/SSAGES/src/CVs/CVManager.h
/home/michael/development/SSAGES/src/CVs/CollectiveVariable.cpp