SSAGES: SSAGES::BoxVolumeCV Class Reference
SSAGES::BoxVolumeCV Class Reference
CVs
Collective variable on the volume of a box.
#include <BoxVolumeCV.h>
Public Member Functions
BoxVolumeCV ()
Constructor.
void Initialize (const Snapshot &) override
Initialize the CV.
void Evaluate (const Snapshot &snapshot) override
Evaluate the CV.
Public Member Functions inherited from SSAGES::CollectiveVariable
CollectiveVariable ()
Constructor.
virtual ~CollectiveVariable ()
Destructor.
virtual void Initialize (const class Snapshot &)
Initialize CV.
virtual void Evaluate (const class Snapshot &)=0
Evaluate CV.
double GetValue () const
Get current value of the CV.
virtual double GetMinimumImage (double) const
Returns the minimum image of a CV based on the input location.
virtual double GetPeriodicValue (double location) const
Apply periodic boundaries to a given value.
const std::vector< Vector3 > & GetGradient () const
Get current gradient of the CV.
const Matrix3 & GetBoxGradient () const
Get gradient contribution to box.
const std::array< double, 2 > & GetBoundaries ()
Get CV boundaries.
virtual double GetDifference (double location) const
Static Public Member Functions
static BoxVolumeCV * Build (const Json::Value &json, const std::string &path)
Set up collective variable.
Static Public Member Functions inherited from SSAGES::CollectiveVariable
static CollectiveVariable * BuildCV (const Json::Value &json, const std::string &path)
Set up collective variable.
Additional Inherited Members
Protected Attributes inherited from SSAGES::CollectiveVariable
std::vector< Vector3 > grad_
Gradient vector dCv/dxi.
Matrix3 boxgrad_
Gradient w.r.t box vectors dCv/dHij.
double val_
Current value of CV.
std::array< double, 2 > bounds_
Bounds on CV.
Detailed Description
Collective variable on the volume of a box.
Collective variable on the volume of a box.
Definition at line 36 of file BoxVolumeCV.h.
Member Function Documentation
Build()
static BoxVolumeCV* SSAGES::BoxVolumeCV::Build (const Json::Value & json, const std::string & path) inline static
Set up collective variable.
Parameters
json JSON input value.
path Path for JSON path specification.
Returns
Pointer to the CV built by this function. nullptr in case of unknown error.
Builds a CV from a JSON node. Returns a pointer to the built cv. If an unknown error is encountered, this function will return a nullptr, but generally it will throw a BuildException on failure.
Warning
Object lifetime is the caller's responsibility.
Definition at line 65 of file BoxVolumeCV.h.
         {
             Json::ObjectRequirement validator;
             Json::Value schema;
             Json::CharReaderBuilder rbuilder;
             Json::CharReader* reader = rbuilder.newCharReader();
             reader->parse(JsonSchema::BoxVolumeCV.c_str(),
                           JsonSchema::BoxVolumeCV.c_str() + JsonSchema::BoxVolumeCV.size(),
                           &schema, nullptr);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             return new BoxVolumeCV();
         }
References BoxVolumeCV(), Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), and Json::ObjectRequirement::Validate().
Referenced by SSAGES::CollectiveVariable::BuildCV().
Evaluate()
void SSAGES::BoxVolumeCV::Evaluate (const Snapshot & snapshot) inline override
Evaluate the CV.
Parameters
snapshot Current simulation snapshot.
Definition at line 52 of file BoxVolumeCV.h.
         {
             // Fill empty gradient.
             auto n = snapshot.GetNumAtoms();
             std::fill(grad_.begin(), grad_.end(), Vector3{0,0,0});
             grad_.resize(n, Vector3{0,0,0});
             val_ = snapshot.GetVolume();
             if(snapshot.GetCommunicator().rank() == 0)
                 boxgrad_ = val_*Matrix3::Identity();
         }
References SSAGES::CollectiveVariable::boxgrad_, SSAGES::Snapshot::GetCommunicator(), SSAGES::Snapshot::GetNumAtoms(), SSAGES::Snapshot::GetVolume(), SSAGES::CollectiveVariable::grad_, and SSAGES::CollectiveVariable::val_.
The documentation for this class was generated from the following file:
/home/michael/development/SSAGES/src/CVs/BoxVolumeCV.h