SSAGES: SSAGES::BasisFunction Class Reference
SSAGES::BasisFunction Class Reference
Abstract class for all BasisFunction inheritance.
#include <Basis.h>
Public Member Functions
BasisFunction (unsigned int polyOrd, unsigned int nbins, bool isFinite, bool zeroOrder, double boundLow, double boundUp)
Constructor.
unsigned int GetOrder ()
Gets the order of the current polynomial.
unsigned int GetBins ()
Gets the number of bins for the discretization.
bool GetZeroOrder ()
Gets the flag for constant-order polynomials.
double GetLower ()
Gets the lower bound on the CV.
double GetUpper ()
Gets the upper bound on the CV.
double GetRange ()
Gets the magnitude of the range of bounds.
virtual double GetNorm (int order)
Gets the norm of the basis function.
virtual double Evaluate (double val, int order)
Calculates the output of the basis function.
virtual double EvalGrad (double val, int order)
Calculates the gradient of the basis function.
virtual double Weight (double val)
Calculates the gradient of the basis function.
virtual ~BasisFunction ()
Destructor.
Static Public Member Functions
static BasisFunction * Build (const Json::Value &json, const std::string &path, unsigned int nbins)
Build BasisFunction from JSON value.
Protected Attributes
unsigned int polyOrd_
Order of the polynomial.
unsigned int nbins_
Number of bins.
bool isFinite_
Flag for finite-range polynomials.
bool zeroOrder_
Flag for constant-order polynomials.
double boundLow_
Lower bound on CV.
double boundUp_
Upper bound on CV.
Detailed Description
Abstract class for all BasisFunction inheritance.
Definition at line 61 of file Basis.h.
Constructor & Destructor Documentation
SSAGES::BasisFunction::BasisFunction (unsigned int polyOrd, unsigned int nbins, bool isFinite, bool zeroOrder, double boundLow, double boundUp) inline
Constructor.
Parameters
polyOrd Order of polynomial.
nbins Number of bins.
isFinite Flag for finite-range polynomials.
zeroOrder Flag for constant-order polynomials.
boundLow Lower bounds of restraint springs.
boundUp Upper bounds of restraint springs.
Constructs an instance of the Basis function class, which can have multiple different inherited forms.
Definition at line 84 of file Basis.h.
                                       :
         polyOrd_(polyOrd), nbins_(nbins), isFinite_(isFinite), zeroOrder_(zeroOrder),
         boundLow_(boundLow), boundUp_(boundUp)
         {
         }
Member Function Documentation
BasisFunction * SSAGES::BasisFunction::Build (const Json::Value & json, const std::string & path, unsigned int nbins) static
Build BasisFunction from JSON value.
Parameters
json JSON value node.
path Path for JSON path specification.
nbins Number of bins.
Returns
Pointer to new BasisFunction.
Definition at line 9 of file Basis.cpp.
References SSAGES::Chebyshev::Build(), SSAGES::Legendre::Build(), and SSAGES::Fourier::Build().
     {
         auto type = json.get("type","none").asString();
         if(type == "Legendre")
             return Legendre::Build(json, path, nbins);
         else if (type == "Chebyshev")
             return Chebyshev::Build(json, path, nbins);
         else if (type == "Fourier")
             return Fourier::Build(json, path, nbins);
         else
             throw std::invalid_argument("Invalid basis set type \"" + type + "\".");
     }
virtual double SSAGES::BasisFunction::EvalGrad (double val, int order) inline virtual
Calculates the gradient of the basis function.
Parameters
val Input value for function.
order Order of the polynomial.
Returns
Gradient for function.
Reimplemented in SSAGES::Fourier, SSAGES::Legendre, and SSAGES::Chebyshev.
Definition at line 169 of file Basis.h.
{
             UNUSED(val);
             UNUSED(order);
             return 0;
         }
virtual double SSAGES::BasisFunction::Evaluate (double val, int order) inline virtual
Calculates the output of the basis function.
Parameters
val Input value for function.
order Order of the polynomial.
Returns
Output value for function.
Reimplemented in SSAGES::Fourier, SSAGES::Legendre, and SSAGES::Chebyshev.
Definition at line 156 of file Basis.h.
{
             UNUSED(val);
             UNUSED(order);
             return 0;
         }
unsigned int SSAGES::BasisFunction::GetBins () inline
Gets the number of bins for the discretization.
Returns
Number of bins.
Definition at line 105 of file Basis.h.
 {return nbins_;}
double SSAGES::BasisFunction::GetLower () inline
Gets the lower bound on the CV.
Returns
Lower bound on CV.
Definition at line 117 of file Basis.h.
Referenced by SSAGES::BasisEvaluator::BasisInit().
 {return boundLow_;}
virtual double SSAGES::BasisFunction::GetNorm (int order) inline virtual
Gets the norm of the basis function.
Parameters
order Order of the polynomial.
Returns
Norm of a specific order of polynomial.
Reimplemented in SSAGES::Fourier, SSAGES::Legendre, and SSAGES::Chebyshev.
Definition at line 144 of file Basis.h.
{
             UNUSED(order);
             return 0;
         }
unsigned int SSAGES::BasisFunction::GetOrder () inline
Gets the order of the current polynomial.
Returns
Order of current polynomial.
Definition at line 99 of file Basis.h.
Referenced by SSAGES::BasisEvaluator::CoeffInit().
 {return polyOrd_;}
double SSAGES::BasisFunction::GetRange () inline
Gets the magnitude of the range of bounds.
Returns
Magnitude of range of bounds on CV.
Definition at line 129 of file Basis.h.
         {
             if(isFinite_)
                 return boundUp_ - boundLow_;
             // No infinitely bounded basis functions are included currently so this is going to return nothing for right now
             else
                 return 0.0;
         }
double SSAGES::BasisFunction::GetUpper () inline
Gets the upper bound on the CV.
Returns
Upper bound on CV.
Definition at line 123 of file Basis.h.
 {return boundUp_;}
bool SSAGES::BasisFunction::GetZeroOrder () inline
Gets the flag for constant-order polynomials.
Returns
Flag for constant-order polynomials.
Definition at line 111 of file Basis.h.
 {return zeroOrder_;}
virtual double SSAGES::BasisFunction::Weight (double val) inline virtual
Calculates the gradient of the basis function.
Parameters
val Input value for function.
Returns
Gradient of function.
Reimplemented in SSAGES::Chebyshev.
Definition at line 181 of file Basis.h.
{
             UNUSED(val);
             return 1;
         }
The documentation for this class was generated from the following files:
/home/cody/SSAGES-public/src/Utility/Basis.h
/home/cody/SSAGES-public/src/Utility/Basis.cpp