SSAGES: SSAGES::CoordinationNumberCV Class Reference
SSAGES::CoordinationNumberCV Class Reference
CVs
Collective variable on coordination number between two groups of atoms.
#include <CoordinationNumberCV.h>
Public Member Functions
CoordinationNumberCV (const Label &group1, const Label &group2, SwitchingFunction &&sf)
Constructor.
void Initialize (const Snapshot &snapshot) override
Initialize necessary variables.
void Evaluate (const Snapshot &snapshot) override
Evaluate the CV.
void Serialize (Json::Value &json) const override
Serialize this CV for restart purposes.
Public Member Functions inherited from SSAGES::CollectiveVariable
CollectiveVariable ()
Constructor.
double GetValue () const
Get current value of the CV.
virtual double GetMinimumImage (double) const
Returns the minimum image of a CV based on the input location.
virtual double GetPeriodicValue (double location) const
Apply periodic boundaries to a given value.
const std::vector< Vector3 > & GetGradient () const
Get current gradient of the CV.
const Matrix3 & GetBoxGradient () const
Get gradient contribution to box.
const std::array< double, 2 > & GetBoundaries ()
Get CV boundaries.
virtual double GetDifference (double location) const
Public Member Functions inherited from SSAGES::Serializable
virtual ~Serializable ()
Destructor.
Private Attributes
Label group1_
IDs of the first group of atoms.
Label group2_
IDs of the second group of atoms.
SwitchingFunction sf_
Switching function used for coordination number.
Additional Inherited Members
Static Public Member Functions inherited from SSAGES::CollectiveVariable
static CollectiveVariable * BuildCV (const Json::Value &json)
Set up collective variable.
static CollectiveVariable * BuildCV (const Json::Value &json, const std::string &path)
Set up collective variable.
static void BuildCV (const Json::Value &json, CVList &cvlist, const std::string &path)
Set up CV and add it to list of CVs.
Protected Attributes inherited from SSAGES::CollectiveVariable
std::vector< Vector3 > grad_
Gradient vector dCv/dxi.
Matrix3 boxgrad_
Gradient w.r.t box vectors dCv/dHij.
double val_
Current value of CV.
std::array< double, 2 > bounds_
Bounds on CV.
Detailed Description
Collective variable on coordination number between two groups of atoms.
Collective variable on coordination number between two groups of atoms. To ensure a continuously differentiable function, there are various switching functions from which to choose from.
Definition at line 93 of file CoordinationNumberCV.h.
Constructor & Destructor Documentation
SSAGES::CoordinationNumberCV::CoordinationNumberCV (const Label & group1, const Label & group2, SwitchingFunction && sf) inline
Constructor.
Parameters
group1 IDs of the first group of atoms.
group2 IDs of the second group of atoms.
Construct a CoordinationNumberCV.
Definition at line 109 of file CoordinationNumberCV.h.
                                                                                                :
         group1_(group1), group2_(group2), sf_(sf)
         {
         }
Member Function Documentation
void SSAGES::CoordinationNumberCV::Evaluate (const Snapshot & snapshot) inline override
Evaluate the CV.
Parameters
snapshot Current simulation snapshot.
Definition at line 164 of file CoordinationNumberCV.h.
References SSAGES::Snapshot::ApplyMinimumImage(), SSAGES::SwitchingFunction::Evaluate(), SSAGES::Snapshot::GetAtomIDs(), SSAGES::Snapshot::GetCommunicator(), SSAGES::Snapshot::GetLocalIndex(), SSAGES::Snapshot::GetLocalIndices(), SSAGES::Snapshot::GetNumAtoms(), SSAGES::Snapshot::GetPositions(), SSAGES::CollectiveVariable::grad_, group1_, group2_, sf_, and SSAGES::CollectiveVariable::val_.
         {
             // Get local atom indices.
             std::vector<int> idx1, idx2;
             snapshot.GetLocalIndices(group1_, &idx1);
             snapshot.GetLocalIndices(group2_, &idx2);
             // Get data from snapshot.
             auto n = snapshot.GetNumAtoms();
             auto& atomids = snapshot.GetAtomIDs();
             auto& positions = snapshot.GetPositions();
             // Initialize gradient.
             std::fill(grad_.begin(), grad_.end(), Vector3{0,0,0});
             grad_.resize(n, Vector3{0,0,0});
             // The nastiness begins. We essentially need to compute
             // pairwise distances between the atoms. For now, let's
             // gather the atomic coordinates of group2_
             // on all relevant processors. Can be improved later.
             auto& comm = snapshot.GetCommunicator();
             std::vector<int> pcounts(comm.size(), 0), icounts(comm.size(), 0);
             std::vector<int> pdispls(comm.size()+1, 0), idispls(comm.size()+1, 0);
             pcounts[comm.rank()] = 3*idx2.size();
             icounts[comm.rank()] = idx2.size();
             // Reduce counts.
             MPI_Allreduce(MPI_IN_PLACE, pcounts.data(), pcounts.size(), MPI_INT, MPI_SUM, comm);
             MPI_Allreduce(MPI_IN_PLACE, icounts.data(), icounts.size(), MPI_INT, MPI_SUM, comm);
             std::partial_sum(pcounts.begin(), pcounts.end(), pdispls.begin() + 1);
             std::partial_sum(icounts.begin(), icounts.end(), idispls.begin() + 1);
             // Fill up mass and position vectors.
             std::vector<double> pos(3*idx2.size(), 0);
             std::vector<int> ids(idx2.size(), 0);
             for(size_t i = 0; i < idx2.size(); ++i)
             {
                 auto& idx = idx2[i];
                 auto& p = positions[idx];
                 pos[3*i+0] = p[0];
                 pos[3*i+1] = p[1];
                 pos[3*i+2] = p[2];
                 ids[i] = atomids[idx];
             }
             // Create receiving vectors.
             std::vector<double> gpos(pdispls.back(), 0);
             std::vector<int> gids(idispls.back(), 0);
             // Gather data.
             MPI_Allgatherv(pos.data(), pos.size(), MPI_DOUBLE, gpos.data(), pcounts.data(), pdispls.data(), MPI_DOUBLE, comm);
             MPI_Allgatherv(ids.data(), ids.size(), MPI_INT, gids.data(), icounts.data(), idispls.data(), MPI_INT, comm);
             val_ = 0;
             double df = 0.;
             for(auto& i : idx1)
             {
                 auto& p = positions[i];
                 for(size_t j = 0; j < group2_.size(); ++j)
                 {
                     Vector3 rij = {p[0] - gpos[3*j], p[1] - gpos[3*j+1], p[2] - gpos[3*j+2]};
                     snapshot.ApplyMinimumImage(rij);
                     auto r = rij.norm();
                     val_ +=  sf_.Evaluate(r, df);
                     grad_[i] += df*rij/r;
                     auto lidx = snapshot.GetLocalIndex(gids[j]);
                     if(lidx != -1)
                         grad_[lidx] -= df*rij/r;
                 }
             }
             // Reduce val.
             MPI_Allreduce(MPI_IN_PLACE, &val_, 1, MPI_DOUBLE, MPI_SUM, comm);
         }
void SSAGES::CoordinationNumberCV::Initialize (const Snapshot & snapshot) inline override
Initialize necessary variables.
Parameters
snapshot Current simulation snapshot.
Definition at line 118 of file CoordinationNumberCV.h.
References SSAGES::Snapshot::GetCommunicator(), SSAGES::Snapshot::GetLocalIndex(), group1_, and group2_.
         {
             using std::to_string;
             auto n1 = group1_.size(), n2 = group2_.size();
             // Make sure atom ID's are on at least one processor.
             std::vector<int> found1(n1, 0), found2(n2, 0);
             for(size_t i = 0; i < n1; ++i)
             {
                 if(snapshot.GetLocalIndex(group1_[i]) != -1)
                     found1[i] = 1;
             }
             for(size_t i = 0; i < n2; ++i)
             {
                 if(snapshot.GetLocalIndex(group2_[i]) != -1)
                     found2[i] = 1;
             }
             MPI_Allreduce(MPI_IN_PLACE, found1.data(), n1, MPI_INT, MPI_SUM, snapshot.GetCommunicator());
             MPI_Allreduce(MPI_IN_PLACE, found2.data(), n2, MPI_INT, MPI_SUM, snapshot.GetCommunicator());
             unsigned ntot1 = std::accumulate(found1.begin(), found1.end(), 0, std::plus<int>());
             unsigned ntot2 = std::accumulate(found2.begin(), found2.end(), 0, std::plus<int>());
             if(ntot1 != n1)
                 throw BuildException({
                     "CoordinationNumberCV: Expected to find " +
                     to_string(n1) +
                     " atoms in group 1, but only found " +
                     to_string(ntot1) + "."
                 });
             if(ntot2 != n2)
                 throw BuildException({
                     "CoordinationNumberCV: Expected to find " +
                     to_string(n2) +
                     " atoms in group 2, but only found " +
                     to_string(ntot2) + "."
                 });
         }
void SSAGES::CoordinationNumberCV::Serialize (Json::Value & json) const inline override virtual
Serialize this CV for restart purposes.
Parameters
json JSON value
Implements SSAGES::Serializable.
Definition at line 246 of file CoordinationNumberCV.h.
         {
             json["type"] = "CoordinationNumber";
         }
The documentation for this class was generated from the following file:
/home/cody/SSAGES/src/CVs/CoordinationNumberCV.h