SSAGES: SSAGES::RationalSwitchPK Class Reference
SSAGES::RationalSwitchPK Class Reference
Rational Switching Function.
#include <PairwiseKernel.h>
Public Member Functions
RationalSwitchPK (double d0, double r0, int n, int m)
Constructor.
double Evaluate (double rij, double &df) const override
Evaluate the pairwise kernel function.
Public Member Functions inherited from SSAGES::PairwiseKernel
virtual ~PairwiseKernel ()
Destructor.
Static Public Member Functions
static RationalSwitchPK * Build (const Json::Value &json, const std::string &path)
Build RationalSwitchPK from JSON value.
Static Public Member Functions inherited from SSAGES::PairwiseKernel
static PairwiseKernel * Build (const Json::Value &json, const std::string &path)
Build PairwiseKernel from JSON value.
Private Attributes
double d0_
Minimum linear shift value.
double r0_
Cutoff distance.
int n_
Exponent of numerator in switching function (controls stiffness).
int m_
Exponent of denominator in switching function (controls stiffness).
Detailed Description
Rational Switching Function.
A switching function of a rational form.
Definition at line 120 of file PairwiseKernel.h.
Constructor & Destructor Documentation
RationalSwitchPK()
SSAGES::RationalSwitchPK::RationalSwitchPK (double d0, double r0, int n, int m) inline
Constructor.
Parameters
d0 Minimum linear shift value.
r0 Cutoff distance.
m An exponent of the switching function.
n An exponent of the switching function.
Construct a GaussianPK.
Definition at line 139 of file PairwiseKernel.h.
                                                              :
         d0_(d0), r0_(r0), n_(n), m_(m) {}
Referenced by Build().
Member Function Documentation
Build()
RationalSwitchPK * SSAGES::RationalSwitchPK::Build (const Json::Value & json, const std::string & path) static
Build RationalSwitchPK from JSON value.
Parameters
json JSON value node.
path Path for JSON path specification.
Returns
Pointer to new RationalSwitchPK.
Parameters
json JSON value node.
Returns
Pointer to new RationalSwitchPK.
Definition at line 77 of file PairwiseKernel.cpp.
     {
         Json::ObjectRequirement validator;
         Json::Value schema;
         Json::CharReaderBuilder rbuilder;
         Json::CharReader* reader = rbuilder.newCharReader();
         reader->parse(JsonSchema::RationalSwitchPK.c_str(),
                       JsonSchema::RationalSwitchPK.c_str() + JsonSchema::RationalSwitchPK.size(),
                       &schema, nullptr);
         validator.Parse(schema, path);
         // Validate inputs.
         validator.Validate(json, path);
         if(validator.HasErrors())
             throw BuildException(validator.GetErrors());
         return new RationalSwitchPK(
                     json["d0"].asDouble(),
                     json["r0"].asDouble(),
                     json["n"].asInt(),
                     json["m"].asInt()
                 );
     }
References Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), RationalSwitchPK(), and Json::ObjectRequirement::Validate().
Referenced by SSAGES::PairwiseKernel::Build().
Evaluate()
double SSAGES::RationalSwitchPK::Evaluate (double rij, double & df) const inline override virtual
Evaluate the pairwise kernel function.
Parameters
rij distance between two atoms.
df Reference to variable which will store the gradient.
Returns
value of pairwise kernel function.
Implements SSAGES::PairwiseKernel.
Definition at line 142 of file PairwiseKernel.h.
         {
             const auto xarg = (rij - d0_)/r0_;
             const auto xn = std::pow(xarg, n_);
             const auto xm = std::pow(xarg, m_);
             const auto f = (1.-xn)/(1.-xm);
             df = f/(d0_-rij)*(n_*xn/(1.-xn)+m_*xm/(xm-1.));
             return  f;
         }
References d0_, m_, n_, and r0_.
The documentation for this class was generated from the following files:
/home/michael/development/SSAGES/src/Utility/PairwiseKernel.h
/home/michael/development/SSAGES/src/Utility/PairwiseKernel.cpp