SSAGES: Json::AnyOfRequirement Class Reference
Json::AnyOfRequirement Class Reference
Requires that at least one of a list of Requirements hold.
#include <AnyOfRequirement.h>
Public Member Functions
AnyOfRequirement ()
Constructor.
virtual void ClearErrors () override
Clear list of error messages for all Requirements.
virtual void ClearNotices () override
Clear list of notices for all Requirements.
virtual void Reset () override
Reset all Requirements.
virtual void Parse (Value json, const std::string &path) override
Parse JSON value and create list of Requirements.
virtual void Validate (const Value &json, const std::string &path) override
Validate that at least one Requirement holds.
Public Member Functions inherited from Json::Requirement
bool HasErrors ()
Check if errors have occured.
std::vector< std::string > GetErrors ()
Get list of error messages.
virtual bool HasNotices ()
Check if notices have been queued.
std::vector< std::string > GetNotices ()
Get list of notices.
virtual ~Requirement ()
Destructor.
Private Attributes
RequireList reqs_
List of Requirements.
Additional Inherited Members
Protected Member Functions inherited from Json::Requirement
void PushError (const std::string &error)
Add error to list of error messages.
void PushNotice (const std::string &notice)
Add message to list of notices.
Detailed Description
Requires that at least one of a list of Requirements hold.
Definition at line 37 of file AnyOfRequirement.h.
Member Function Documentation
Parse()
virtual void Json::AnyOfRequirement::Parse (Value json, const std::string & path) inline override virtual
Parse JSON value and create list of Requirements.
Parameters
json JSON input value.
path Path for JSON path specification.
This function parses the given JSON value and creates a new Requirement for each value in the "anyOf" branch. The new Requirements are appended to the list of Requirements.
Implements Json::Requirement.
Definition at line 81 of file AnyOfRequirement.h.
         {
             Reset();
             RequirementLoader loader;
             auto& head = json.isMember("anyOf") ? json["anyOf"] : json;
             for(auto& val : head)
                 if(auto req = loader.LoadRequirement(val))
                 {
                     reqs_.push_back(std::move(req));
                     reqs_.back()->Parse(val, path);
                 }
         }
References Json::RequirementLoader::LoadRequirement(), reqs_, and Reset().
Validate()
virtual void Json::AnyOfRequirement::Validate (const Value & json, const std::string & path) inline override virtual
Validate that at least one Requirement holds.
Parameters
json JSON value to validate.
path Path for JSON path specification.
Implements Json::Requirement.
Definition at line 102 of file AnyOfRequirement.h.
         {
             for(auto& r : reqs_)
             {
                 r->Validate(json, path);
                 if(!r->HasErrors())
                     return;
             }
             // Collect errors.
             for(auto& r : reqs_)
             {
                 if(r->HasErrors())
                     for(const auto& error : r->GetErrors())
                         PushError(error);
                 if(r->HasNotices())
                     for(const auto& notice : r->GetNotices())
                         PushNotice(notice);
             }
         }
References Json::Requirement::PushError(), Json::Requirement::PushNotice(), and reqs_.
The documentation for this class was generated from the following file:
/home/michael/development/SSAGES/src/Validator/AnyOfRequirement.h