SSAGES: SSAGES::CollectiveVariable Class Reference
SSAGES::CollectiveVariable Class Reference
CVs
Abstract class for a collective variable.
#include <CollectiveVariable.h>
Public Member Functions
CollectiveVariable ()
Constructor.
double GetValue () const
Get current value of the CV.
virtual double GetMinimumImage (double) const
Returns the minimum image of a CV based on the input location.
virtual double GetPeriodicValue (double location) const
Apply periodic boundaries to a given value.
const std::vector< Vector3 > & GetGradient () const
Get current gradient of the CV.
const Matrix3 & GetBoxGradient () const
Get gradient contribution to box.
const std::array< double, 2 > & GetBoundaries ()
Get CV boundaries.
virtual double GetDifference (double location) const
Public Member Functions inherited from SSAGES::Serializable
virtual void Serialize (Json::Value &json) const =0
Serialize the class.
virtual ~Serializable ()
Destructor.
Static Public Member Functions
static CollectiveVariable * BuildCV (const Json::Value &json)
Set up collective variable.
static CollectiveVariable * BuildCV (const Json::Value &json, const std::string &path)
Set up collective variable.
static void BuildCV (const Json::Value &json, CVList &cvlist, const std::string &path)
Set up CV and add it to list of CVs.
Protected Attributes
std::vector< Vector3 > grad_
Gradient vector dCv/dxi.
Matrix3 boxgrad_
Gradient w.r.t box vectors dCv/dHij.
double val_
Current value of CV.
std::array< double, 2 > bounds_
Bounds on CV.
Detailed Description
Abstract class for a collective variable.
Definition at line 40 of file CollectiveVariable.h.
Member Function Documentation
CollectiveVariable * SSAGES::CollectiveVariable::BuildCV (const Json::Value & json) static
Set up collective variable.
Parameters
json JSON input value.
Returns
Pointer to the CV built by this function. nullptr in case of unknown error.
Builds a CV from a JSON node. Returns a pointer to the built cv. If an unknown error is encountered, this function will return a nullptr, but generally it will throw a BuildException on failure.
Warning
Object lifetime is the caller's responsibility.
Definition at line 44 of file CollectiveVariable.cpp.
Referenced by SSAGES::Driver::BuildCVs().
     {
         return BuildCV(json, "#/CVs");
     }
CollectiveVariable * SSAGES::CollectiveVariable::BuildCV (const Json::Value & json, const std::string & path) static
Set up collective variable.
Parameters
json JSON input value.
path Path for JSON path specification.
Returns
Pointer to the CV built by this function. nullptr in case of unknown error.
This function overloads CollectiveVariable::BuildCV(const Json::Value&).
Definition at line 49 of file CollectiveVariable.cpp.
References Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), and Json::ObjectRequirement::Validate().
     {
         ObjectRequirement validator;
         Value schema;
         Reader reader;
         CollectiveVariable* cv = nullptr;
         // Random device for seed generation.
         // std::random_device rd;
         // auto maxi = std::numeric_limits<int>::max();
         // auto seed = json.get("seed", rd() % maxi).asUInt();
         // Get move type.
         std::string type = json.get("type", "none").asString();
         if(type == "ParticleCoordinate")
         {
             reader.parse(JsonSchema::ParticleCoordinateCV, schema);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             Label atomids;
             for(auto& id : json["atom_ids"])
                 atomids.push_back(id.asInt());
             auto indextype = json.get("dimension","x").asString();
             Dimension index;
             if(indextype == "x")
                 index = Dimension::x;
             else if(indextype == "y")
                 index = Dimension::y;
             else if(indextype == "z")
                 index = Dimension::z;
             else
                 throw BuildException({"Could not obtain ParticleCoordinate dimension specified."});
             auto* c = new ParticleCoordinateCV(atomids, index);
             cv = static_cast<CollectiveVariable*>(c);
         }
         else if(type == "ParticlePosition")
         {
             reader.parse(JsonSchema::ParticlePositionCV, schema);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             Label atomids;
             for(auto& id : json["atom_ids"])
                 atomids.push_back(id.asInt());
             Vector3 position;
             position[0] = json["position"][0].asDouble();
             position[1] = json["position"][1].asDouble();
             position[2] = json["position"][2].asDouble();
             auto fixx = json["fix"][0].asBool();
             auto fixy = json["fix"][1].asBool();
             auto fixz = json["fix"][2].asBool();
             auto* c = new ParticlePositionCV(atomids, position, fixx, fixy, fixz);
             cv = static_cast<CollectiveVariable*>(c);
         }
         else if(type == "Torsional")
         {
             reader.parse(JsonSchema::TorsionalCV, schema);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             std::vector<int> atomids;
             for(auto& s : json["atom_ids"])
                 atomids.push_back(s.asInt());
             auto periodic = json.get("periodic", true).asBool();
             auto* c = new TorsionalCV(atomids[0], atomids[1], atomids[2], atomids[3], periodic);
             cv = static_cast<CollectiveVariable*>(c);
         }
         else if(type == "ParticleSeparation")
         {
             reader.parse(JsonSchema::ParticleSeparationCV, schema);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             std::vector<int> group1, group2;
             for(auto& s : json["group1"])
                 group1.push_back(s.asInt());
             for(auto& s : json["group2"])
                 group2.push_back(s.asInt());
             ParticleSeparationCV* c;
             if(json.isMember("dimension"))
             {
                 auto fixx = json["dimension"][0].asBool();
                 auto fixy = json["dimension"][1].asBool();
                 auto fixz = json["dimension"][2].asBool();
                 c = new ParticleSeparationCV(group1, group2, fixx, fixy, fixz);
             }
             else
             {
                 c = new ParticleSeparationCV(group1, group2);
             }
             cv = static_cast<CollectiveVariable*>(c);
         }
         else if(type == "Angle")
         {
             reader.parse(JsonSchema::AngleCV, schema);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             std::vector<int> atomids;
             for(auto& s : json["atom_ids"])
                 atomids.push_back(s.asInt());
             auto* c = new AngleCV(atomids[0], atomids[1], atomids[2]);
             cv = static_cast<CollectiveVariable*>(c);
         }
         else if(type == "GyrationTensor")
         {
             reader.parse(JsonSchema::GyrationTensorCV, schema);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             std::vector<int> atomids;
             for(auto& s : json["atom_ids"])
                 atomids.push_back(s.asInt());
             GyrationTensor component = Rg;
             auto comp = json["component"].asString();
             if(comp == "Rg")
                 component = Rg;
             else if(comp == "principal1")
                 component = principal1;
             else if(comp == "principal2")
                 component = principal2;
             else if(comp == "principal3")
                 component = principal3;
             else if(comp == "asphericity")
                 component = asphericity;
             else if(comp == "acylindricity")
                 component = acylindricity;
             else if(comp == "shapeaniso")
                 component = shapeaniso;
             auto* c = new GyrationTensorCV(atomids, component);
             cv = static_cast<CollectiveVariable*>(c);
         }
         else if(type == "RMSD")
         {
             reader.parse(JsonSchema::RMSDCV, schema);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             std::vector<int> atomids;
             for(auto& s : json["atom ids"])
                 atomids.push_back(s.asInt());
             auto reference = json.get("reference"," ").asString();
             auto* c = new RMSDCV(atomids, reference, json.get("use_range", false).asBool());
             cv = static_cast<CollectiveVariable*>(c);
         }
         else if(type == "RouseMode")
         {
             reader.parse(JsonSchema::RouseModeCV, schema);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             std::vector<Label> groups;
             for (auto& group : json["groups"]) {
                 groups.push_back({});
                 for (auto& id : group) {
                     groups.back().push_back(id.asInt());
                 }
             }
             auto mode = json.get("mode",0).asInt();
             auto* c = new RouseModeCV( groups, mode);
             cv = static_cast<CollectiveVariable*>(c);
         }
         else if(type == "CoordinationNumber")
         {
             reader.parse(JsonSchema::CoordinationNumberCV, schema);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             std::vector<int> group1, group2;
             for(auto& s : json["group1"])
                 group1.push_back(s.asInt());
             for(auto& s : json["group2"])
                 group2.push_back(s.asInt());
             auto* c = new CoordinationNumberCV(group1, group2, SwitchingFunction::Build(json["switching"]));
             cv = static_cast<CollectiveVariable*>(c);
         }
         else if(type == "BoxVolume")
         {
             reader.parse(JsonSchema::BoxVolumeCV, schema);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             auto* c = new BoxVolumeCV();
             cv = static_cast<CollectiveVariable*>(c);
         }
         else
         {
             throw BuildException({path + ": Unknown CV type specified."+type+" is not a valid type!"});
         }
         return cv;
     }
void SSAGES::CollectiveVariable::BuildCV (const Json::Value & json, CVList & cvlist, const std::string & path) static
Set up CV and add it to list of CVs.
Parameters
json JSON input value.
cvlist List of CVs to which the new CV will added.
path Path for JSON path specification.
Builds CVs and adds them to the List of CV.
Definition at line 314 of file CollectiveVariable.cpp.
References Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ArrayRequirement::Parse(), and Json::ArrayRequirement::Validate().
     {
         ArrayRequirement validator;
         Value schema;
         Reader reader;
         reader.parse(JsonSchema::CVs, schema);
         validator.Parse(schema, path);
         // Validate high level schema.
         validator.Validate(json, path);
         if(validator.HasErrors())
             throw BuildException(validator.GetErrors());
         // Loop through CVs.
         int i = 0;
         for(auto& m : json)
         {
             cvlist.push_back(BuildCV(m, path + "/" + std::to_string(i)));
             ++i;
         }
     }
const std::array<double, 2>& SSAGES::CollectiveVariable::GetBoundaries () inline
Get CV boundaries.
Returns
List of lower and upper boundaries of the CV.
Returns the boundaries of the CV. These represent the bounds within which the CV is expected to be constrained. There is no requirement on the method to respect the values returned here.
Definition at line 153 of file CollectiveVariable.h.
References bounds_.
         {
             return bounds_;
         }
virtual double SSAGES::CollectiveVariable::GetDifference (double location) const inline virtual
Get difference between current CV value and a given value, taking periodic boundaries into account.
Parameters
location Value whose distance from the current CV value should be calculated.
Returns
Difference taking periodic boundaries into account.
Returns the difference betwen the current cv value and Location: (value_ - Location) respecting periodic boundary conditions of the CV, if the CV has periodic boundary conditions. For example Torsional angle has boundaries at pi and -pi, in which the difference beteen the angles is 0 not 2pi
Reimplemented in SSAGES::TorsionalCV, and SSAGES::ParticleCoordinateCV.
Definition at line 170 of file CollectiveVariable.h.
References val_.
         {
             return val_ - location;
         }
const std::vector<Vector3>& SSAGES::CollectiveVariable::GetGradient () const inline
Get current gradient of the CV.
Returns
Per-atom gradient of the CV.
Returns the current value of the CV gradient. This should be an n length vector, where n is the number of atoms in the snapshot. Each element in the vector is the derivative of the CV with respect to the atom's coordinate (dCV/dxi).
Definition at line 129 of file CollectiveVariable.h.
References grad_.
         {
             return grad_;
         }
virtual double SSAGES::CollectiveVariable::GetMinimumImage (double) const inline virtual
Returns the minimum image of a CV based on the input location.
Returns
Minimum image of the CV
Takes the input location and applies the periodic boundary conditions to return a minimum image of the CV.
Reimplemented in SSAGES::TorsionalCV.
Definition at line 100 of file CollectiveVariable.h.
References val_.
         {
             return val_;
         }
virtual double SSAGES::CollectiveVariable::GetPeriodicValue (double location) const inline virtual
Apply periodic boundaries to a given value.
Parameters
location Value to which the periodic boundaries should be applied.
Returns
Correct value.
Takes location and applies periodic boundaries of the CV on it and returns a correct value. Example would be torsional angle which has bounds at pi and -pi. If location = 2pi, GetPeriodicValue(location) would return 0.
Reimplemented in SSAGES::TorsionalCV, and SSAGES::ParticleCoordinateCV.
Definition at line 115 of file CollectiveVariable.h.
         {
             return location;
         }
double SSAGES::CollectiveVariable::GetValue () const inline
Get current value of the CV.
Returns
Current value of the CV.
Returns the current value of the CV which has been computed before via the call to CollectiveVariable::Evaluate().
Definition at line 88 of file CollectiveVariable.h.
References val_.
         {
             return val_;
         }
The documentation for this class was generated from the following files:
/home/cody/SSAGES/src/CVs/CollectiveVariable.h
/home/cody/SSAGES/src/CVs/CollectiveVariable.cpp