SSAGES: SSAGES::Method Class Reference
SSAGES::Method Class Reference abstract
Methods
Interface for Method implementations.
#include <Method.h>
Public Member Functions
Method (unsigned int frequency, boost::mpi::communicator &world, boost::mpi::communicator &comm)
Constructor.
void SetIteration (int iter)
Set Method's iteration.
virtual void PreSimulation (Snapshot *snapshot, const CVList &cvs) override=0
Method call prior to simulation initiation.
virtual void PostIntegration (Snapshot *snapshot, const CVList &cvs) override=0
Method call post integration.
virtual void PostSimulation (Snapshot *snapshot, const CVList &cvs) override=0
Method call post simulation.
virtual ~Method ()
Destructor.
Public Member Functions inherited from SSAGES::EventListener
EventListener (unsigned int frequency)
Constructor.
unsigned int GetFrequency () const
Get frequency of event listener.
virtual ~EventListener ()
Destructor.
Public Member Functions inherited from SSAGES::Serializable
virtual void Serialize (Json::Value &json) const =0
Serialize the class.
virtual ~Serializable ()
Destructor.
Static Public Member Functions
static Method * BuildMethod (const Json::Value &json, boost::mpi::communicator &world, boost::mpi::communicator &comm, const std::string &path)
Set up the Method.
Protected Attributes
boost::mpi::communicator world_
Global MPI communicator.
boost::mpi::communicator comm_
Local MPI communicator.
unsigned int iteration_
Number of the method iteration.
Detailed Description
Interface for Method implementations.
This class is designed to be the base class on which all Metadynamics methods are based.
Definition at line 41 of file Method.h.
Constructor & Destructor Documentation
SSAGES::Method::Method (unsigned int frequency, boost::mpi::communicator & world, boost::mpi::communicator & comm) inline
Constructor.
Parameters
frequency Frequency of sampling.
world MPI world communicator.
comm MPI local communicator.
Frequency of sampling must be specified by all methods.
Definition at line 59 of file Method.h.
                                         :
         EventListener(frequency), world_(world), comm_(comm),
         iteration_(0){}
Member Function Documentation
Method * SSAGES::Method::BuildMethod (const Json::Value & json, boost::mpi::communicator & world, boost::mpi::communicator & comm, const std::string & path) static
Set up the Method.
Parameters
json JSON Value containing all input information.
world MPI global communicator.
comm MPI local communicator.
path Path for JSON path specification.
Returns
Pointer to the Method built. nullptr if an unknown error occurred.
This function builds a method from a JSON node. It will return a nullptr when an unknown error occurred, but generally it will throw a BuildException on failure.
Note
Object lifetime is the caller's responsibility.
Definition at line 44 of file Method.cpp.
References Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), SetIteration(), SSAGES::Umbrella::SetLogStep(), and Json::ObjectRequirement::Validate().
Referenced by SSAGES::Driver::BuildMethod().
     {
         ObjectRequirement validator;
         Value schema;
         Reader reader;
         Method* method = nullptr;
         // Get method type.
         std::string type = json.get("type", "none").asString();
         if(type == "Umbrella")
         {
             reader.parse(JsonSchema::UmbrellaMethod, schema);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             std::vector<double> ksprings;
             for(auto& s : json["ksprings"])
                 ksprings.push_back(s.asDouble());
             std::vector<double> centers0, centers1;
             auto timesteps = json.get("timesteps", 0).asInt();
             if(json.isMember("centers"))
             {
                 for(auto& s : json["centers"])
                     centers0.push_back(s.asDouble());
             }
             else if(json.isMember("centers0") && json.isMember("centers1") && json.isMember("timesteps"))
             {
                 for(auto& s : json["centers0"])
                     centers0.push_back(s.asDouble());
                 for(auto& s : json["centers1"])
                     centers1.push_back(s.asDouble());
             }
             else
                 throw BuildException({"Either \"centers\" or \"timesteps\", \"centers0\" and \"centers1\" must be defined for umbrella."});
             if(ksprings.size() != centers0.size())
                 throw BuildException({"Need to define a spring for every center or a center for every spring!"});
             auto freq = json.get("frequency", 1).asInt();
             auto name = json.get("file name","none").asString();
             Umbrella* m = nullptr;
             if(timesteps == 0)
                 m = new Umbrella(world, comm, ksprings, centers0, name, freq);
             else
                 m = new Umbrella(world, comm, ksprings, centers0, centers1, timesteps, name, freq);
             if(json.isMember("iteration"))
                 m->SetIteration(json.get("iteration",0).asInt());
             if(json.isMember("log every"))
                 m->SetLogStep(json.get("log every",0).asInt());
             method = static_cast<Method*>(m);
         }
         else if(type == "Metadynamics")
         {
             reader.parse(JsonSchema::MetadynamicsMethod, schema);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             std::vector<double> widths;
             for(auto& s : json["widths"])
                 widths.push_back(s.asDouble());
             auto height = json.get("height", 1.0).asDouble();
             auto hillfreq = json.get("hill_frequency", 1).asInt();
             auto freq = json.get("frequency", 1).asInt();
             auto* m = new Meta(world, comm, height, widths, hillfreq, freq);
             method = static_cast<Method*>(m);
         }
         else if(type == "ABF")
         {
             reader.parse(JsonSchema::ABFMethod, schema);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             std::vector<double> minsCV;
             for(auto& mins : json["CV_lower_bounds"])
                 minsCV.push_back(mins.asDouble());
             std::vector<double> maxsCV;
             for(auto& maxs : json["CV_upper_bounds"])
                 maxsCV.push_back(maxs.asDouble());
             std::vector<double> binsCV;
             for(auto& bins : json["CV_bins"])
                 binsCV.push_back(bins.asDouble());
             std::vector<double> minsrestCV;
             for(auto& mins : json["CV_restraint_minimums"])
                 minsrestCV.push_back(mins.asDouble());
             std::vector<double> maxsrestCV;
             for(auto& maxs : json["CV_restraint_maximums"])
                 maxsrestCV.push_back(maxs.asDouble());
             std::vector<double> springkrestCV;
             for(auto& bins : json["CV_restraint_spring_constants"])
                 springkrestCV.push_back(bins.asDouble());
             std::vector<bool> isperiodic;
             for(auto& isperCV : json["CV_isperiodic"])
                 isperiodic.push_back(isperCV.asBool());
             std::vector<double> minperboundaryCV;
             for(auto& minsperCV : json["CV_periodic_boundary_lower_bounds"])
                 minperboundaryCV.push_back(minsperCV.asDouble());
             std::vector<double> maxperboundaryCV;
             for(auto& maxsperCV : json["CV_periodic_boundary_upper_bounds"])
                 maxperboundaryCV.push_back(maxsperCV.asDouble());
             if(!(minsCV.size()      == maxsCV.size() &&
                  maxsCV.size()      == binsCV.size() &&
                  binsCV.size()      == minsrestCV.size() &&
                  minsrestCV.size()      == maxsrestCV.size() &&
                  maxsrestCV.size()      == springkrestCV.size() &&
                  springkrestCV.size()   == isperiodic.size()))
             throw BuildException({"CV lower bounds, upper bounds, bins, restrain minimums, restrains maximums, spring constants and periodicity info must all have the size == number of CVs defined."});
             bool anyperiodic=false;
             for(size_t i = 0; i<isperiodic.size(); ++i)
                 if(isperiodic[i])
                     {
                     anyperiodic = true;
                     if(!(isperiodic.size()          == minperboundaryCV.size() &&
                            minperboundaryCV.size()  == maxperboundaryCV.size()))
                     throw BuildException({"If any CV is defined as periodic, please define the full upper and lower bound vectors. They should both have the same number of entries as CV lower bounds, upper bounds... Entries corresponding to non-periodic CVs will not be used."});
                     }
             int FBackupInterv = json.get("backup_frequency", 1000).asInt();
             double unitconv = json.get("unit_conversion", 0).asDouble();
             double timestep = json.get("timestep",2).asDouble();
             double min = json.get("minimum_count",100).asDouble();
             bool massweigh = json.get("mass_weighing",false).asBool();
             std::vector<std::vector<double>> histdetails;
             std::vector<std::vector<double>> restraint;
             std::vector<std::vector<double>> periodicboundaries;
             std::vector<double> temp1(3);
             std::vector<double> temp2(3);
             std::vector<double> temp3(2);
             for(size_t i=0; i<minsCV.size(); ++i)
                 {
                 temp1 = {minsCV[i], maxsCV[i], binsCV[i]};
                 temp2 = {minsrestCV[i], maxsrestCV[i], springkrestCV[i]};
                 histdetails.push_back(temp1);
                 restraint.push_back(temp2);
                 if(anyperiodic)
                     {
                     temp3 = {minperboundaryCV[i], maxperboundaryCV[i]};
                     periodicboundaries.push_back(temp3);
                     }
                 }
             auto freq = json.get("frequency", 1).asInt();
             std::string filename = json.get("filename", "F_out").asString();
             auto* m = new ABF(world, comm, restraint, isperiodic, periodicboundaries, min, massweigh, filename, histdetails, FBackupInterv, unitconv, timestep, freq);
             method = static_cast<Method*>(m);
             if(json.isMember("F") && json.isMember("N"))
                 {
                 Eigen::VectorXd F;
                 std::vector<int> N;
                 F.resize(json["F"].size());
                 for(int i = 0; i < (int)json["F"].size(); ++i)
                     F[i] = json["F"][i].asDouble();
                 for(auto& n : json["N"])
                     N.push_back(n.asInt());
                 m->SetHistogram(F,N);
                 }
             if(json.isMember("iteration"))
                 m->SetIteration(json.get("iteration",0).asInt());
         }
         else if(type == "ForwardFlux")
         {
             reader.parse(JsonSchema::ForwardFluxMethod, schema);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             double ninterfaces = json.get("nInterfaces", 2).asDouble();
             std::vector<double> interfaces;
             for(auto& s : json["interfaces"])
                 interfaces.push_back(s.asDouble());
             std::vector<unsigned int> M;
             for(auto& s : json["trials"])
                 M.push_back(s.asInt());
             if ((ninterfaces != interfaces.size()) || (ninterfaces != M.size())){
                 throw BuildException({"The size of \"interfaces\" and \"trials\" must be equal to \"nInterfaces\". See documentation for more information"});
             }
             unsigned int N0Target = json.get("N0Target", 1).asInt();
             bool initialFluxFlag = json.get("computeInitialFlux", true).asBool();
             bool saveTrajectories = json.get("saveTrajectories", true).asBool();
             unsigned int currentInterface = json.get("currentInterface", 0).asInt();
             unsigned int freq = json.get("frequency", 1).asInt();
             std::string flavor = json.get("flavor", "none").asString();
             std::string output_directory = json.get("outputDirectoryName", "FFSoutput").asString();
             if(flavor == "DirectForwardFlux"){
                 auto *m = new DirectForwardFlux(world, comm, ninterfaces, interfaces, N0Target, M, initialFluxFlag, saveTrajectories, currentInterface, output_directory, freq);
                 method = static_cast<Method*>(m);
             } else {
                 throw BuildException({"Unknow flavor of forward flux. The options are \"DirectForwardFlux\""});
             }
         }
         else if(type == "String")
         {
             reader.parse(JsonSchema::StringMethod, schema);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             std::vector<double> centers;
             for(auto& s : json["centers"])
                 centers.push_back(s.asDouble());
             auto maxiterator = json.get("max_iterations", 0).asInt();
             std::vector<double> ksprings;
             for(auto& s : json["ksprings"])
                 ksprings.push_back(s.asDouble());
             auto freq = json.get("frequency", 1).asInt();
             // Get stringmethod flavor.
             std::string flavor = json.get("flavor", "none").asString();
             if(flavor == "FTS")
             {
                 reader.parse(JsonSchema::FTSMethod, schema);
                 validator.Parse(schema, path);
                 // Validate inputs.
                 validator.Validate(json, path);
                 if(validator.HasErrors())
                     throw BuildException(validator.GetErrors());
                 auto isteps = json.get("block_iterations", 2000).asInt();
                 auto tau = json.get("time_step", 0.1).asDouble();
                 auto kappa = json.get("kappa", 0.1).asDouble();
                 auto springiter = json.get("umbrella_iterations",2000).asDouble();
                 auto* m = new FiniteTempString(world, comm, centers,
                                     maxiterator, isteps,
                                     tau, ksprings, kappa,
                                     springiter, freq);
                 if(json.isMember("tolerance"))
                 {
                     std::vector<double> tol;
                     for(auto& s : json["tolerance"])
                         tol.push_back(s.asDouble());
                     m->SetTolerance(tol);
                 }
                 method = static_cast<Method*>(m);
             }
             else if(flavor == "ElasticBand")
             {
                 reader.parse(JsonSchema::ElasticBandMethod, schema);
                 validator.Parse(schema, path);
                 // Validate inputs.
                 validator.Validate(json, path);
                 if(validator.HasErrors())
                     throw BuildException(validator.GetErrors());
                 auto eqsteps = json.get("equilibration_steps", 20).asInt();
                 auto evsteps = json.get("evolution_steps", 5).asInt();
                 auto stringspring = json.get("kstring", 10.0).asDouble();
                 auto isteps = json.get("block_iterations", 100).asInt();
                 auto tau = json.get("time_step", 0.1).asDouble();
                 auto* m = new ElasticBand(world, comm, centers,
                                     maxiterator, isteps,
                                     tau, ksprings, eqsteps,
                                     evsteps, stringspring, freq);
                 if(json.isMember("tolerance"))
                 {
                     std::vector<double> tol;
                     for(auto& s : json["tolerance"])
                         tol.push_back(s.asDouble());
                     m->SetTolerance(tol);
                 }
                 method = static_cast<Method*>(m);
             }
             else if(flavor == "SWARM")
             {
                 reader.parse(JsonSchema::SwarmMethod, schema);
                 validator.Parse(schema, path);
                 //Validate input
                 validator.Validate(json, path);
                 if(validator.HasErrors())
                     throw BuildException(validator.GetErrors());
                 auto InitialSteps = json.get("initial_steps", 2500).asInt();
                 auto HarvestLength = json.get("harvest_length", 10).asInt();
                 auto NumberTrajectories = json.get("number_of_trajectories", 250).asInt();
                 auto SwarmLength = json.get("swarm_length", 20).asInt();
                 auto* m = new Swarm(world, comm, centers, maxiterator, ksprings, freq, InitialSteps, HarvestLength, NumberTrajectories, SwarmLength);
                 method = static_cast<Method*>(m);
                 if(json.isMember("tolerance"))
                 {
                     std::vector<double> tol;
                     for(auto& s : json["tolerance"])
                         tol.push_back(s.asDouble());
                     m->SetTolerance(tol);
                 }
                 method = static_cast<Method*>(m);
             }
             else
             {
                 throw BuildException({flavor + " is unknown string method type. Please specify correct flavor"});
             }
             if(json.isMember("iteration"))
                 method->SetIteration(json.get("iteration",0).asInt());
         }
         else if(type == "Basis")
         {
             reader.parse(JsonSchema::BFSMethod, schema);
             validator.Parse(schema, path);
             //Validate Inputs
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             std::vector<unsigned int> coefsCV(0);
             for(auto& coefs : json["CV_coefficients"])
                 coefsCV.push_back(coefs.asInt());
             std::vector<double> restrCV(0);
             for(auto& restr : json["CV_restraint_spring_constants"])
                 restrCV.push_back(restr.asDouble());
             std::vector<double> boundLow(0);
             for(auto& bndl : json["CV_restraint_minimums"])
                 boundLow.push_back(bndl.asDouble());
             std::vector<double> boundUp(0);
             for(auto& bndu : json["CV_restraint_maximums"])
                 boundUp.push_back(bndu.asDouble());
             auto cyclefreq = json.get("cycle_frequency", 100000).asInt();
             auto freq = json.get("frequency", 1).asInt();
             auto wght = json.get("weight", 1.0).asDouble();
             auto bnme = json.get("basis_filename", "").asString();
             auto cnme = json.get("coeff_filename", "").asString();
             auto temp = json.get("temperature", 0.0).asDouble();
             auto tol  = json.get("tolerance", 1e-6).asDouble();
             auto conv = json.get("convergence_exit", false).asBool();
             Histogram<int> *histlocal = Histogram<int>::BuildHistogram(
                                             json.get("grid", Json::Value()) );
             Histogram<int> *histglobal = Histogram<int>::BuildHistogram(
                                             json.get("grid", Json::Value()) );
             auto* m = new Basis(world, comm, histlocal, histglobal, coefsCV, restrCV, boundUp, boundLow,
                                 cyclefreq, freq, bnme, cnme, temp, tol, wght,
                                 conv);
             method = static_cast<Method*>(m);
             if(json.isMember("iteration"))
                 m->SetIteration(json.get("iteration",0).asInt());
             if(json.isMember("coefficients") && json.isMember("bias hist"))
             {
                 std::vector<double> coeff;
                 std::vector<double> unbias;
                 for(auto& c : json["coefficients"])
                     coeff.push_back(c.asDouble());
                 for(auto& u : json["bias hist"])
                     unbias.push_back(u.asDouble());
                 m->SetBasis(coeff, unbias);
             }
         }
         else
         {
             throw BuildException({path + ": Unknown method type specified."});
         }
         return method;
     }
virtual void SSAGES::Method::PostIntegration (Snapshot * snapshot, const CVList & cvs) override pure virtual
Method call post integration.
Parameters
snapshot Pointer to the simulation snapshot.
cvs List of CVs.
This function will be called after each integration step.
Implements SSAGES::EventListener.
Implemented in SSAGES::ForwardFlux, SSAGES::StringMethod, SSAGES::Basis, SSAGES::ABF, SSAGES::Meta, SSAGES::Umbrella, SSAGES::Swarm, SSAGES::FiniteTempString, SSAGES::ElasticBand, SSAGES::DirectForwardFlux, and SSAGES::MockMethod.
virtual void SSAGES::Method::PostSimulation (Snapshot * snapshot, const CVList & cvs) override pure virtual
Method call post simulation.
Parameters
snapshot Pointer to the simulation snapshot.
cvs List of CVs.
This function will be called after the end of the simulation run.
Implements SSAGES::EventListener.
Implemented in SSAGES::ForwardFlux, SSAGES::StringMethod, SSAGES::Basis, SSAGES::ABF, SSAGES::Meta, SSAGES::Umbrella, and SSAGES::MockMethod.
virtual void SSAGES::Method::PreSimulation (Snapshot * snapshot, const CVList & cvs) override pure virtual
Method call prior to simulation initiation.
Parameters
snapshot Pointer to the simulation snapshot.
cvs List of CVs.
This function will be called before the simulation is started.
Implements SSAGES::EventListener.
Implemented in SSAGES::ForwardFlux, SSAGES::StringMethod, SSAGES::Basis, SSAGES::ABF, SSAGES::Meta, SSAGES::Umbrella, and SSAGES::MockMethod.
void SSAGES::Method::SetIteration (int iter) inline
Set Method's iteration.
Parameters
iter int value for what the method iteration should be.
Definition at line 69 of file Method.h.
References iteration_.
Referenced by BuildMethod().
 {iteration_ = iter;}
The documentation for this class was generated from the following files:
/home/cody/SSAGES/src/Methods/Method.h
/home/cody/SSAGES/src/Methods/Method.cpp