SSAGES: SSAGES::EventListener Class Reference
SSAGES::EventListener Class Reference abstract
Core
Base abstract class for listening in to events fired by "Hook".
#include <EventListener.h>
Public Member Functions
EventListener (unsigned int frequency)
Constructor.
unsigned int GetFrequency () const
Get frequency of event listener.
virtual void PreSimulation (Snapshot *snapshot, const class CVManager &cvmanager)=0
Method call prior to simulation initiation.
virtual void PostIntegration (Snapshot *snapshot, const class CVManager &cvmanager)=0
Method call post integration.
virtual void PostSimulation (Snapshot *snapshot, const class CVManager &cvmanager)=0
Method call post simulation.
virtual ~EventListener ()
Destructor.
Static Public Member Functions
static unsigned int GetWalkerID (const MPI_Comm &world, const MPI_Comm &comm)
Get walker ID number of specified communicator.
static unsigned int GetNumWalkers (const MPI_Comm &world, const MPI_Comm &comm)
Get total number of walkers in the simulation.
static bool IsMasterRank (const MPI_Comm &comm)
Check if current processor is master.
Private Attributes
unsigned int frequency_
Frequency for listening.
Detailed Description
Base abstract class for listening in to events fired by "Hook".
Definition at line 35 of file EventListener.h.
Constructor & Destructor Documentation
SSAGES::EventListener::EventListener (unsigned int frequency) inline
Constructor.
Parameters
frequency Frequency for listening.
Definition at line 45 of file EventListener.h.
                                               :
         frequency_(frequency)
         {
         }
Member Function Documentation
unsigned int SSAGES::EventListener::GetFrequency () const inline
Get frequency of event listener.
Returns
Frequency of event listener.
Definition at line 54 of file EventListener.h.
References frequency_, PostIntegration(), PostSimulation(), and PreSimulation().
 { return frequency_; }
static unsigned int SSAGES::EventListener::GetNumWalkers (const MPI_Comm & world, const MPI_Comm & comm) inline static
Get total number of walkers in the simulation.
Parameters
world MPI communicator for the whole simulation.
comm MPI communicator for the local walker.
Returns
Total number of walkers in the simulation.
Definition at line 100 of file EventListener.h.
         {
             return mxx::comm(world).size()/mxx::comm(comm).size();
         }
static unsigned int SSAGES::EventListener::GetWalkerID (const MPI_Comm & world, const MPI_Comm & comm) inline static
Get walker ID number of specified communicator.
Parameters
world MPI communicator for the whole simulation.
comm MPI communicator for the local walker.
Returns
Walker ID number.
Definition at line 89 of file EventListener.h.
         {
             return mxx::comm(world).rank()/mxx::comm(comm).size();
         }
static bool SSAGES::EventListener::IsMasterRank (const MPI_Comm & comm) inline static
Check if current processor is master.
Parameters
comm MPI communicator to check.
Returns
Whether the current MPI rank is the first in the communicator.
Definition at line 110 of file EventListener.h.
Referenced by SSAGES::DirectForwardFlux::CheckForInterfaceCrossings(), SSAGES::DirectForwardFlux::InitializeQueue(), SSAGES::ANN::PostIntegration(), and SSAGES::ANN::TrainNetwork().
         {
             return mxx::comm(comm).rank() == 0;
         }
virtual void SSAGES::EventListener::PostIntegration (Snapshot * snapshot, const class CVManager & cvmanager) pure virtual
Method call post integration.
Parameters
snapshot Pointer to the simulation snapshot.
cvmanager Collective variable manager.
This function will be called at the end of each integration step.
Implemented in SSAGES::ForwardFlux, SSAGES::ABF, SSAGES::BFS, SSAGES::StringMethod, SSAGES::Meta, SSAGES::Umbrella, SSAGES::ANN, SSAGES::Swarm, SSAGES::FiniteTempString, SSAGES::ElasticBand, SSAGES::Logger, SSAGES::Method, and SSAGES::DirectForwardFlux.
Referenced by GetFrequency().
virtual void SSAGES::EventListener::PostSimulation (Snapshot * snapshot, const class CVManager & cvmanager) pure virtual
Method call post simulation.
Parameters
snapshot Pointer to the simulation snapshot.
cvmanager Collective variable manager.
This function will be called after the simulation has finished.
Implemented in SSAGES::ForwardFlux, SSAGES::ABF, SSAGES::BFS, SSAGES::StringMethod, SSAGES::Meta, SSAGES::Umbrella, SSAGES::ANN, SSAGES::Logger, and SSAGES::Method.
Referenced by GetFrequency().
virtual void SSAGES::EventListener::PreSimulation (Snapshot * snapshot, const class CVManager & cvmanager) pure virtual
Method call prior to simulation initiation.
Parameters
snapshot Pointer to the simulation snapshot.
cvmanager Collective variable manager.
This function will be called before the simulation is started.
Implemented in SSAGES::ForwardFlux, SSAGES::ABF, SSAGES::BFS, SSAGES::StringMethod, SSAGES::Meta, SSAGES::Umbrella, SSAGES::ANN, SSAGES::Logger, and SSAGES::Method.
Referenced by GetFrequency().
The documentation for this class was generated from the following file:
/home/cody/SSAGES-public/src/EventListener.h