SSAGES: SSAGES::Fourier Class Reference
SSAGES::Fourier Class Reference
Defines the class of Fourier polynomials.
#include <Basis.h>
Public Member Functions
Fourier (unsigned int polyOrd, double boundLow, double boundUp, unsigned int nbins)
Constructor.
double Evaluate (double x, int n)
Calculates the output of the basis function.
double EvalGrad (double x, int n)
Calculates the gradient of the basis function.
double GetNorm (int)
Gets the norm of the basis function.
Public Member Functions inherited from SSAGES::BasisFunction
BasisFunction (unsigned int polyOrd, unsigned int nbins, bool isFinite, bool zeroOrder, double boundLow, double boundUp)
Constructor.
unsigned int GetOrder ()
Gets the order of the current polynomial.
unsigned int GetBins ()
Gets the number of bins for the discretization.
bool GetZeroOrder ()
Gets the flag for constant-order polynomials.
double GetLower ()
Gets the lower bound on the CV.
double GetUpper ()
Gets the upper bound on the CV.
double GetRange ()
Gets the magnitude of the range of bounds.
virtual double Weight (double val)
Calculates the gradient of the basis function.
virtual ~BasisFunction ()
Destructor.
Static Public Member Functions
static Fourier * Build (const Json::Value &json, const std::string &path, unsigned int nbins)
Build BasisFunction from JSON value.
Static Public Member Functions inherited from SSAGES::BasisFunction
static BasisFunction * Build (const Json::Value &json, const std::string &path, unsigned int nbins)
Build BasisFunction from JSON value.
Additional Inherited Members
Protected Attributes inherited from SSAGES::BasisFunction
unsigned int polyOrd_
Order of the polynomial.
unsigned int nbins_
Number of bins.
bool isFinite_
Flag for finite-range polynomials.
bool zeroOrder_
Flag for constant-order polynomials.
double boundLow_
Lower bound on CV.
double boundUp_
Upper bound on CV.
Detailed Description
Defines the class of Fourier polynomials.
Definition at line 307 of file Basis.h.
Constructor & Destructor Documentation
SSAGES::Fourier::Fourier (unsigned int polyOrd, double boundLow, double boundUp, unsigned int nbins) inline
Constructor.
Parameters
polyOrd Order of Fourier polynomial.
boundLow Lower bounds of restraint springs.
boundUp Upper bounds of restraint springs.
nbins Number of bins.
Constructs an instance of the Fourier function class.
Definition at line 321 of file Basis.h.
                                                                                            :
         BasisFunction(polyOrd, nbins, true, true, boundLow, boundUp)
         {
         }
Member Function Documentation
Fourier * SSAGES::Fourier::Build (const Json::Value & json, const std::string & path, unsigned int nbins) static
Build BasisFunction from JSON value.
Build the Fourier polynomial
Parameters
json JSON value node.
path Path for JSON path specification.
nbins Number of bins.
Returns
Pointer to new BasisFunction.
Definition at line 49 of file Basis.cpp.
References Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), and Json::ObjectRequirement::Validate().
Referenced by SSAGES::BasisFunction::Build().
     {
         Json::ObjectRequirement validator;
         Json::Value schema;
         Json::CharReaderBuilder rbuilder;
         Json::CharReader* reader = rbuilder.newCharReader();
         reader->parse(JsonSchema::FourierBasis.c_str(),
                       JsonSchema::FourierBasis.c_str() + JsonSchema::FourierBasis.size(),
                       &schema, nullptr);
         validator.Parse(schema, path);
         //Validate Inputs
         validator.Validate(json, path);
         if(validator.HasErrors())
             throw BuildException(validator.GetErrors());
         return new Fourier(
                 json["polynomial_order"].asInt(),
                 json["lower_bound"].asDouble(),
                 json["upper_bound"].asDouble(),
                 nbin
             );
     }
double SSAGES::Fourier::EvalGrad (double val, int order) inline virtual
Calculates the gradient of the basis function.
Parameters
val Input value for function.
order Order of the polynomial.
Returns
Gradient for function.
Reimplemented from SSAGES::BasisFunction.
Definition at line 336 of file Basis.h.
         {
             return n == 0 ? 0.0 :
                     n % 2 == 0 ? (-2.0*floor(double(n)*0.5)*M_PI/(boundUp_-boundLow_))*(std::sin(2.0*floor(double(n)*0.5)*M_PI*x/(boundUp_-boundLow_))) :
                      (2.0*floor(double(n)*0.5)*M_PI/(boundUp_-boundLow_))*std::cos(2.0*floor(double(n)*0.5)*M_PI*x/(boundUp_-boundLow_));
         }
double SSAGES::Fourier::Evaluate (double val, int order) inline virtual
Calculates the output of the basis function.
Parameters
val Input value for function.
order Order of the polynomial.
Returns
Output value for function.
Reimplemented from SSAGES::BasisFunction.
Definition at line 329 of file Basis.h.
         {
             return n == 0 ? 0.5 :
                     n % 2 == 1 ? std::sin(2.0*floor(double(n)*0.5)*M_PI*x/(boundUp_-boundLow_)) :
                       std::cos(2.0*floor(double(n)*0.5)*M_PI*x/(boundUp_-boundLow_));
         }
double SSAGES::Fourier::GetNorm (int order) inline virtual
Gets the norm of the basis function.
Parameters
order Order of the polynomial.
Returns
Norm of a specific order of polynomial.
Reimplemented from SSAGES::BasisFunction.
Definition at line 343 of file Basis.h.
         {
             //Assumes the period of the function is the range of the CV
             return 2.0/(boundUp_-boundLow_);
         }
The documentation for this class was generated from the following files:
/home/cody/SSAGES-public/src/Utility/Basis.h
/home/cody/SSAGES-public/src/Utility/Basis.cpp