SSAGES: SSAGES::Basis Class Reference
SSAGES::Basis Class Reference
Methods
Basis Function Sampling Algorithm.
#include <BasisFunc.h>
Public Member Functions
Basis (boost::mpi::communicator &world, boost::mpi::communicator &comm, Histogram< int > *histlocal, Histogram< int > *histglobal, const std::vector< unsigned int > &polyord, const std::vector< double > &restraint, const std::vector< double > &boundUp, const std::vector< double > &boundLow, unsigned int cyclefreq, unsigned int frequency, const std::string bnme, const std::string cnme, const double temperature, const double tol, const double weight, bool converge)
Constructor.
void PreSimulation (Snapshot *snapshot, const CVList &cvs) override
Pre-simulation hook.
void PostIntegration (Snapshot *snapshot, const CVList &cvs) override
Post-integration hook.
void PostSimulation (Snapshot *snapshot, const CVList &cvs) override
Post-simulation hook.
void SetIteration (const int iter)
Set the current iteration.
void SetBasis (const std::vector< double > &coeff, std::vector< double > &unbias)
Set the values for the basis.
void Serialize (Json::Value &json) const override
Serialize the class.
~Basis ()
Destructor.
Public Member Functions inherited from SSAGES::Method
Method (unsigned int frequency, boost::mpi::communicator &world, boost::mpi::communicator &comm)
Constructor.
void SetIteration (int iter)
Set Method's iteration.
virtual ~Method ()
Destructor.
Public Member Functions inherited from SSAGES::EventListener
EventListener (unsigned int frequency)
Constructor.
unsigned int GetFrequency () const
Get frequency of event listener.
virtual ~EventListener ()
Destructor.
Public Member Functions inherited from SSAGES::Serializable
virtual ~Serializable ()
Destructor.
Private Member Functions
void UpdateBias (const CVList &cvs, const double)
Updates the bias projection of the PMF.
void CalcBiasForce (const CVList &cvs)
Computes the bias force.
void PrintBias (const CVList &cvs, const double beta)
Prints the current bias to a defined file from the JSON.
void BasisInit (const CVList &cvs)
Initializes the look up tables for polynomials.
Private Attributes
std::vector< Map > hist_
Histogram of visited states.
Histogram< int > * histlocal_
Locally defined histogram array for easy mpi operations.
Histogram< int > * histglobal_
Globally defined histogram array for easy mpi operations.
std::vector< Map > coeff_
Globally located coefficient values.
std::vector< double > unbias_
The biased histogram of states.
std::vector< double > coeff_arr_
The coefficient array for restart runs.
std::vector< BasisLUT > LUT_
The Basis set lookup table, also defined globally.
std::vector< double > derivatives_
Derivatives of the bias potential.
std::vector< unsigned int > polyords_
The order of the basis polynomials.
std::vector< int > nbins_
Storing number of bins for simplicity and readability of code.
std::vector< double > restraint_
Spring constants for restrained system.
std::vector< double > boundUp_
Upper position of the spring restraint.
std::vector< double > boundLow_
Lower position of the spring restraint.
unsigned int cyclefreq_
Frequency of coefficient updates.
unsigned int mpiid_
The node that the current system belongs to, primarily for printing and debugging.
double weight_
Weighting for potentially faster sampling.
double temperature_
Self-defined temperature.
double tol_
The tolerance criteria for the system .
bool bounds_
A variable to check to see if the simulation is in bounds or not.
bool converge_exit_
A check to see if you want the system to end when it reaches the convergence criteria.
std::ofstream basisout_
Output stream for basis projection data.
std::ofstream coeffout_
Output stream for coefficients (for reading purposes)
std::string bnme_
std::string cnme_
Coefficient filename.
Additional Inherited Members
Static Public Member Functions inherited from SSAGES::Method
static Method * BuildMethod (const Json::Value &json, boost::mpi::communicator &world, boost::mpi::communicator &comm, const std::string &path)
Set up the Method.
Protected Attributes inherited from SSAGES::Method
boost::mpi::communicator world_
Global MPI communicator.
boost::mpi::communicator comm_
Local MPI communicator.
unsigned int iteration_
Number of the method iteration.
Detailed Description
Basis Function Sampling Algorithm.
Implementation of the Basis Function Sampling Method based on [4].
Definition at line 90 of file BasisFunc.h.
Constructor & Destructor Documentation
SSAGES::Basis::Basis (boost::mpi::communicator & world, boost::mpi::communicator & comm, Histogram< int > * histlocal, Histogram< int > * histglobal, const std::vector< unsigned int > & polyord, const std::vector< double > & restraint, const std::vector< double > & boundUp, const std::vector< double > & boundLow, unsigned int cyclefreq, unsigned int frequency, const std::string bnme, const std::string cnme, const double temperature, const double tol, const double weight, bool converge) inline
Constructor.
Parameters
world MPI global communicator.
comm MPI local communicator.
polyord Order of Legendre polynomials.
restraint Restraint spring constants.
boundUp Upper bounds of restraint springs.
boundLow Lower bounds of restraint springs.
cyclefreq Cycle frequency.
frequency Frequency with which this Method is applied.
bnme Basis file name.
cnme Coefficient file name.
temperature Automatically set temperature.
tol Threshold for tolerance criterion.
weight Weight for improved sampling.
converge If True quit on convergence.
Constructs an instance of the Basis function sampling method. The coefficients describes the basis projection of the system. This is updated once every cyclefreq_. For now, only the Legendre polynomial is implemented. Others will be added later.
Definition at line 255 of file BasisFunc.h.
                             :
         Method(frequency, world, comm), hist_(), histlocal_(histlocal), histglobal_(histglobal),
         coeff_(), unbias_(), coeff_arr_(), LUT_(), derivatives_(), polyords_(polyord),
         nbins_(), restraint_(restraint), boundUp_(boundUp), boundLow_(boundLow),
         cyclefreq_(cyclefreq), mpiid_(0), weight_(weight),
         temperature_(temperature), tol_(tol),
         converge_exit_(converge), bnme_(bnme), cnme_(cnme)
         {
         }
Member Function Documentation
void SSAGES::Basis::BasisInit (const CVList & cvs) private
Initializes the look up tables for polynomials.
Parameters
cvs List of collective variables.
Definition at line 236 of file BasisFunc.cpp.
References LUT_, nbins_, and polyords_.
Referenced by PreSimulation().
     {
         for( size_t k = 0; k < cvs.size(); k++)
         {
             size_t ncoeff = polyords_[k]+1;
             std::vector<double> dervs(nbins_[k]*ncoeff,0);
             std::vector<double> vals(nbins_[k]*ncoeff,0);
             std::vector<double> x(nbins_[k],0);
             /*As the values for Legendre polynomials can be defined recursively, \
              *both the derivatives and values are defined at the same time,
              */
             for (int i = 0; i < nbins_[k]; ++i)
             {
                 x[i] = 2.0*(i + 0.5)/(double)(nbins_[k]) - 1.0;
                 vals[i] = 1.0;
                 dervs[i] = 0.0;
             }
             for (int i = 0; i < nbins_[k]; ++i)
             {
                 vals[i+nbins_[k]] = x[i];
                 dervs[i+nbins_[k]] = 1.0;
             }
             for (size_t j = 2; j < ncoeff; j++)
             {
                 for (int i = 0; i < nbins_[k]; i++)
                 {
                     //Evaluate the values of the Legendre polynomial at each bin
                     vals[i+j*nbins_[k]] = ((double) ( 2*j - 1 ) * x[i] * vals[i+(j-1)*nbins_[k]]
                     - (double) (j - 1) * vals[i+(j-2)*nbins_[k]]) / (double) (j);
                     //Evaluate the derivatives of the Legendre polynomial at each bin
                     dervs[i+j*nbins_[k]] = ((double) ( 2*j - 1 ) * ( vals[i+(j-1)*nbins_[k]] + x[i] * dervs[i+(j-1)*nbins_[k]] )
                     - (double) (j - 1) * dervs[i+(j-2)*nbins_[k]]) / (double) (j);
                 }
             }
             BasisLUT TempLUT(vals,dervs);
             LUT_.push_back(TempLUT);
         }
     }
void SSAGES::Basis::CalcBiasForce (const CVList & cvs) private
Computes the bias force.
Parameters
cvs List of collective variables.
Definition at line 468 of file BasisFunc.cpp.
References boundLow_, bounds_, boundUp_, coeff_, derivatives_, SSAGES::GridBase< T >::GetIndices(), SSAGES::GridBase< T >::GetLower(), SSAGES::GridBase< T >::GetPeriodic(), SSAGES::GridBase< T >::GetUpper(), hist_, histlocal_, LUT_, nbins_, and restraint_.
Referenced by PostIntegration().
     {
         // Reset derivatives
         std::fill(derivatives_.begin(), derivatives_.end(), 0);
         std::vector<double> x(cvs.size(),0);
         std::vector<int> idx(cvs.size(),0);
         double temp = 1.0;
         size_t ii = 0;
         //This is calculating the derivatives for the bias force
         for (size_t j = 0; j < cvs.size(); ++j)
         {
             x[j] = cvs[j]->GetValue();
             double min = histlocal_->GetLower(j);
             double max = histlocal_->GetUpper(j);
             if(!histlocal_->GetPeriodic(j))
             {
                 // In order to prevent the index for the histogram from going out of bounds a check is in place
                 if(x[j] > max && bounds_)
                 {
                     std::cout<<"::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::"<<std::endl;
                     std::cout<<"WARNING: CV is above the maximum boundary."<<std::endl;
                     std::cout<<"Statistics will not be gathered during this interval"<<std::endl;
                     std::cout<<"::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::"<<std::endl;
                     bounds_ = false;
                 }
                 else if(x[j] < min && bounds_)
                 {
                     std::cout<<"::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::"<<std::endl;
                     std::cout<<"WARNING: CV is below the minimum boundary."<<std::endl;
                     std::cout<<"Statistics will not be gathered during this interval"<<std::endl;
                     std::cout<<"::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::"<<std::endl;
                     bounds_ = false;
                 }
                 else if(x[j] < max && x[j] > min && !bounds_)
                 {
                     std::cout<<"::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::"<<std::endl;
                     std::cout<<"CV has returned in between bounds. Run is resuming"<<std::endl;
                     std::cout<<"::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::"<<std::endl;
                     bounds_ = true;
                 }
             }
         }
         // Only apply soft wall potential in the event that it has left the boundaries
         if(bounds_)
         {
             idx = histlocal_->GetIndices(x);
             for(size_t i = 0; i < cvs.size(); ++i)
                 ii += (idx[i])*std::pow(nbins_[i],i);
             for (size_t i = 1; i < coeff_.size(); ++i)
             {
                 for (size_t j = 0; j < cvs.size(); ++j)
                 {
                     temp = 1.0;
                     for (size_t k = 0; k < cvs.size(); ++k)
                     {
                         temp *= j == k ?  LUT_[k].derivs[hist_[ii].map[k] + coeff_[i].map[k]*(nbins_[k])] * 2.0 / (histlocal_->GetUpper(j) - histlocal_->GetLower(j))
                                        :  LUT_[k].values[hist_[ii].map[k] + coeff_[i].map[k]*(nbins_[k])];
                     }
                     derivatives_[j] -= coeff_[i].value * temp;
                 }
             }
         }
         // This is where the wall potentials are going to be thrown into the method if the system is not a periodic CV
         for(size_t j = 0; j < cvs.size(); ++j)
         {
             // Are these used?
             // double min = histlocal_->GetLower(j);
             // double max = histlocal_->GetUpper(j);
             if(!histlocal_->GetPeriodic(j))
             {
                 if(x[j] > boundUp_[j])
                     derivatives_[j] -= restraint_[j] * (x[j] - boundUp_[j]);
                 else if(x[j] < boundLow_[j])
                     derivatives_[j] -= restraint_[j] * (x[j] - boundLow_[j]);
             }
         }
     }
void SSAGES::Basis::PostIntegration (Snapshot * snapshot, const CVList & cvs) override virtual
Post-integration hook.
Parameters
snapshot Simulation snapshot.
cvs List of CVs.
Implements SSAGES::Method.
Definition at line 151 of file BasisFunc.cpp.
References bounds_, CalcBiasForce(), cyclefreq_, derivatives_, SSAGES::Snapshot::GetForces(), SSAGES::GridBase< T >::GetIndices(), SSAGES::Snapshot::GetIteration(), SSAGES::Snapshot::GetKb(), SSAGES::Snapshot::GetTemperature(), SSAGES::Snapshot::GetVirial(), hist_, histlocal_, SSAGES::Method::iteration_, mpiid_, nbins_, temperature_, and UpdateBias().
     {
         std::vector<double> x(cvs.size(),0);
         std::vector<int> idx(cvs.size(),0);
         int ii = 0;
         /*The binned cv space is updated at every step
          *After a certain number of steps has been passed, the system updates a
          *bias projection based on the visited histogram states
          */
         for(size_t i = 0; i < cvs.size(); ++i)
         {
             x[i] = cvs[i]->GetValue();
         }
         if(bounds_)
         {
             // Convert the CV value to its discretized value through the grid tool
             idx = histlocal_->GetIndices(x);
             // Map the grid index to the form of the hist and unbias mapping
             for(size_t i = 0; i < cvs.size(); ++i)
             {
                 ii += (idx[i])*std::pow(nbins_[i],i);
             }
             // The histogram is updated based on the index
             hist_[ii].value++;
             // Update the basis projection after a predefined number of steps
             if(snapshot->GetIteration()  % cyclefreq_ == 0) {
                 double beta;
                 beta = 1.0 / (snapshot->GetTemperature() * snapshot->GetKb());
                 // For systems with poorly defined temperature (ie: 1 particle) the user needs to define their own temperature. This is a hack that will be removed in future versions.
                 if(snapshot->GetTemperature() == 0)
                 {
                     beta = temperature_;
                     if(temperature_ == 0)
                     {
                         std::cout<<std::endl;
                         std::cerr<<"::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::"<<std::endl;
                         std::cerr<<"ERROR: Input temperature needs to be defined for this simulation"<<std::endl;
                         std::cerr<<"Exiting on node ["<<mpiid_<<"]"<<std::endl;
                         std::cout<<"::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::"<<std::endl;
                         exit(EXIT_FAILURE);
                     }
                 }
                 iteration_+= 1;
                 UpdateBias(cvs,beta);
                 std::cout<<"Node: ["<<mpiid_<<"]"<<std::setw(10)<<"\tSweep: "<<iteration_<<std::endl;
             }
         }
         // This calculates the bias force based on the existing basis projection.
         CalcBiasForce(cvs);
         // Take each CV and add its biased forces to the atoms using the chain rule
         auto& forces = snapshot->GetForces();
         auto& virial = snapshot->GetVirial();
         for(size_t i = 0; i < cvs.size(); ++i)
         {
             auto& grad = cvs[i]->GetGradient();
             auto& boxgrad = cvs[i]->GetBoxGradient();
             /* Update the forces in snapshot by adding in the force bias from each
              *CV to each atom based on the gradient of the CV.
              */
             for (size_t j = 0; j < forces.size(); ++j)
                 forces[j] += derivatives_[i]*grad[j];
             virial -= derivatives_[i]*boxgrad;
         }
     }
void SSAGES::Basis::PostSimulation (Snapshot * snapshot, const CVList & cvs) override virtual
Post-simulation hook.
Parameters
snapshot Simulation snapshot.
cvs List of CVs.
Implements SSAGES::Method.
Definition at line 228 of file BasisFunc.cpp.
     {
         std::cout<<"Run has finished"<<std::endl;
     }
void SSAGES::Basis::PreSimulation (Snapshot * snapshot, const CVList & cvs) override virtual
Pre-simulation hook.
Parameters
snapshot Simulation snapshot.
cvs List of CVs.
Resize the polynomial vector so that it doesn't crash here
And now reinitialize the vector
Implements SSAGES::Method.
Definition at line 30 of file BasisFunc.cpp.
References BasisInit(), bounds_, coeff_, coeff_arr_, derivatives_, SSAGES::GridBase< T >::GetDimension(), SSAGES::GridBase< T >::GetNumPoints(), SSAGES::Snapshot::GetWalkerID(), hist_, histlocal_, SSAGES::Method::iteration_, mpiid_, nbins_, polyords_, unbias_, and SSAGES::Method::world_.
     {
         // Open file for writing and allocate derivatives vector
         size_t coeff_size = 1, bin_size = 1;
         // For print statements and file I/O, the walker IDs are used
         mpiid_ = snapshot->GetWalkerID();
         // Make sure the iteration index is set correctly
         iteration_ = 0;
         if(!histlocal_)
         {
             std::cerr<<"::::::::::::::::::::::::::::::::::::::::::::::::::::::"<<std::endl;
             std::cerr<<"ERROR: Method expected a histogram but none built."<<std::endl;
             std::cerr<<"Exiting on node ["<<mpiid_<<"]"<<std::endl;
             std::cerr<<"::::::::::::::::::::::::::::::::::::::::::::::::::::::"<<std::endl;
             world_.abort(EXIT_FAILURE);
         }
         // There are a few error messages / checks that are in place with defining CVs and grids
         else
         {
             if(histlocal_->GetDimension() != cvs.size())
             {
                 std::cerr<<"::::::::::::::::::::::::::::::::::::::::::::::::::::::"<<std::endl;
                 std::cerr<<"ERROR: Histogram dimensions doesn't match number of CVS."<<std::endl;
                 std::cerr<<"Exiting on node ["<<mpiid_<<"]"<<std::endl;
                 std::cerr<<"::::::::::::::::::::::::::::::::::::::::::::::::::::::"<<std::endl;
                 world_.abort(EXIT_FAILURE);
             }
             else if(cvs.size() != polyords_.size())
             {
                 std::cout<<cvs.size()<<std::endl;
                 std::cout<<polyords_.size()<<std::endl;
                 std::cout<<"::::::::::::::::::::::::::::::::::::::::::::::::::::::"<<std::endl;
                 std::cout<<"WARNING: The number of polynomial orders is not the same"<<std::endl;
                 std::cout<<"as the number of CVs"<<std::endl;
                 std::cout<<"The simulation will take the first defined input"<<std::endl;
                 std::cout<<"as the same for all CVs. ["<<polyords_[0]<<"]"<<std::endl;
                 std::cout<<"::::::::::::::::::::::::::::::::::::::::::::::::::::::"<<std::endl;
                 polyords_.resize(cvs.size());
                 for(size_t i = 0; i < cvs.size(); ++i)
                 {
                     polyords_[i] = polyords_[0];
                 }
             }
         }
         // Setting the number of bins here for simplicity
         nbins_.resize(cvs.size());
         for(size_t i = 0; i < cvs.size(); ++i)
             nbins_[i] = histlocal_->GetNumPoints(i);
         // This is to check for non-periodic bounds. It comes into play in the update bias function
         bounds_ = true;
         for(size_t i = 0; i < cvs.size(); ++i)
         {
             bin_size   *= nbins_[i];
             coeff_size *= polyords_[i]+1;
         }
         derivatives_.resize(cvs.size());
         unbias_.resize(bin_size,0);
         coeff_arr_.resize(coeff_size,0);
         std::vector<int> idx(cvs.size(), 0);
         std::vector<int> jdx(cvs.size(), 0);
         Map temp_map(idx,0.0);
         // Initialize the mapping for the hist function
         for(size_t i = 0; i < bin_size; ++i)
         {
             for(size_t j = 0; j < idx.size(); ++j)
             {
                 if(idx[j] > 0 && idx[j] % (nbins_[j]) == 0)
                 {
                     if(j != cvs.size() - 1)
                     {
                         idx[j+1]++;
                         idx[j] = 0;
                     }
                 }
                 temp_map.map[j] = idx[j];
                 temp_map.value  = 0.0;
             }
             // Resize histogram vectors to correct size
             hist_.push_back(temp_map);
             idx[0]++;
         }
         //Initialize the mapping for the coeff function
         for(size_t i = 0; i < coeff_size; ++i)
         {
             for(size_t j = 0; j < jdx.size(); ++j)
             {
                 if(jdx[j] > 0 && jdx[j] % (polyords_[j]+1) == 0)
                 {
                     if(j != cvs.size() - 1)
                     {
                         jdx[j+1]++;
                         jdx[j] = 0;
                     }
                 }
                 temp_map.map[j] = jdx[j];
                 temp_map.value  = 0;
             }
             coeff_.push_back(temp_map);
             coeff_[i].value = coeff_arr_[i];
             jdx[0]++;
         }
         //Initialize the look-up table.
         BasisInit(cvs);
     }
void SSAGES::Basis::PrintBias (const CVList & cvs, const double beta) private
Prints the current bias to a defined file from the JSON.
Parameters
cvs List of collective variables.
beta Scale parameter.
Definition at line 403 of file BasisFunc.cpp.
References basisout_, bnme_, cnme_, coeff_, coeffout_, SSAGES::GridBase< T >::GetLower(), SSAGES::GridBase< T >::GetUpper(), hist_, histlocal_, SSAGES::Method::iteration_, LUT_, nbins_, and unbias_.
Referenced by UpdateBias().
     {
         std::vector<double> bias(hist_.size(), 0);
         std::vector<double> x(cvs.size(), 0);
         double temp = 1.0;
         double pos = 0;
         /* Since the coefficients are the only piece that needs to be
          *updated, the bias is only evaluated when printing
          */
         for(size_t i = 0; i < hist_.size(); ++i)
         {
             for(size_t j = 1; j < coeff_.size(); ++j)
             {
                 for(size_t k = 0; k < cvs.size(); ++k)
                 {
                     temp *=  LUT_[k].values[hist_[i].map[k] + coeff_[j].map[k] * (nbins_[k])];
                 }
                 bias[i] += coeff_[j].value*temp;
                 temp  = 1.0;
             }
         }
         // The filenames will have a standard name, with a user-defined suffix
         std::string filename1 = "basis"+bnme_+".out";
         std::string filename2 = "coeff"+cnme_+".out";
         basisout_.precision(5);
         coeffout_.precision(5);
         basisout_.open(filename1.c_str());
         coeffout_.open(filename2.c_str());
         // The CV values, PMF projection, PMF, and biased histogram are output for the user
         coeffout_ << iteration_  <<std::endl;
         basisout_ << "CV Values" << std::setw(35*cvs.size()) << "Basis Set Bias" << std::setw(35) << "PMF Estimate" << std::setw(35) << "Biased Histogram" << std::endl;
         for(size_t j = 0; j < unbias_.size(); ++j)
         {
             for(size_t k = 0; k < cvs.size(); ++k)
             {
                 // Evaluate the CV values for printing purposes
                 pos = (hist_[j].map[k]+0.5)*(histlocal_->GetUpper(k) - histlocal_->GetLower(k)) * 1.0 /(double)( nbins_[k]) + histlocal_->GetLower(k);
                 basisout_ << pos << std::setw(35);
             }
             basisout_ << -bias[j] << std::setw(35);
             if(unbias_[j])
                 basisout_ << -log(unbias_[j]) / beta << std::setw(35);
             else
                 basisout_ << "0" << std::setw(35);
             basisout_ << unbias_[j];
             basisout_ << std::endl;
         }
         for(size_t k = 0; k < coeff_.size(); ++k)
         {
             coeffout_ <<coeff_[k].value << std::endl;
         }
         basisout_ << std::endl;
         basisout_.close();
         coeffout_.close();
     }
void SSAGES::Basis::Serialize (Json::Value & json) const inline override virtual
Serialize the class.
Parameters
json JSON value to which the information is stored
Store all information pertaining to this class in the given JSON value. The information can then be used to restart or analyze the simulation
Warning
Serialization is not implemented yet!
Implements SSAGES::Serializable.
Definition at line 331 of file BasisFunc.h.
References bnme_, boundLow_, boundUp_, cnme_, coeff_arr_, converge_exit_, cyclefreq_, SSAGES::Method::iteration_, polyords_, restraint_, temperature_, tol_, unbias_, and weight_.
         {
             json["type"] = "Basis";
             for(auto& p: polyords_)
                 json["CV_coefficients"].append(p);
             for(auto& k: restraint_)
                 json["CV_restraint_spring_constants"].append(k);
             for(auto& u: boundUp_)
                 json["CV_restraint_maximums"].append(u);
             for(auto& l: boundLow_)
                 json["CV_restraint_minimums"].append(l);
             for(auto& b: unbias_)
                 json["bias_hist"].append(b);
             for(auto& c: coeff_arr_)
                 json["coefficients"].append(c);
             json["tolerance"] = tol_;
             json["convergence_exit"] = converge_exit_;
             json["basis_filename"] = bnme_;
             json["coeff_filename"] = cnme_;
             json["iteration"] = iteration_;
             json["cycle_frequency"] = cyclefreq_;
             json["weight"] = weight_;
             json["temperature"] = temperature_;
         }
void SSAGES::Basis::SetBasis (const std::vector< double > & coeff, std::vector< double > & unbias) inline
Set the values for the basis.
Parameters
coeff List of coefficients.
unbias List of unbiased values.
This function is used to set starting values at the beginning of a run. For example when continuing from a restart value.
Definition at line 321 of file BasisFunc.h.
References coeff_arr_, and unbias_.
         {
             coeff_arr_ = coeff;
             unbias_ = unbias;
         }
void SSAGES::Basis::SetIteration (const int iter) inline
Set the current iteration.
Parameters
iter New value for the current iteration.
This function is used to set the current iteration, for example when continuing from a restart.
Definition at line 308 of file BasisFunc.h.
References SSAGES::Method::iteration_.
         {
             iteration_ = iter;
         }
void SSAGES::Basis::UpdateBias (const CVList & cvs, const double beta) private
Updates the bias projection of the PMF.
Parameters
cvs List of collective variables.
beta Temperature equivalent.
Definition at line 281 of file BasisFunc.cpp.
References SSAGES::Histogram< T >::begin(), coeff_, coeff_arr_, converge_exit_, cyclefreq_, SSAGES::GridBase< T >::data(), SSAGES::Histogram< T >::end(), hist_, histglobal_, histlocal_, LUT_, nbins_, PrintBias(), SSAGES::GridBase< T >::size(), tol_, unbias_, weight_, and SSAGES::Method::world_.
Referenced by PostIntegration().
     {
         std::vector<double> x(cvs.size(), 0);
         std::vector<double> coeffTemp(coeff_.size(), 0);
         double sum  = 0.0;
         double bias = 0.0;
         double basis = 1.0;
         // For multiple walkers, the struct is unpacked
         Histogram<int>::iterator it;
         size_t id1d = 0;
         for(it = histlocal_->begin(); it != histlocal_->end(); ++it, ++id1d) {
             *it = (int)hist_[id1d].value;
         }
         // Summed between all walkers
         MPI_Allreduce(histlocal_->data(), histglobal_->data(), histlocal_->size(), MPI_INT, MPI_SUM, world_);
         // And then it is repacked into the struct
         id1d = 0;
         for(it = histlocal_->begin(); it != histlocal_->end(); ++it, ++id1d) {
             hist_[id1d].value = *it;
         }
         // Construct the biased histogram
         for(size_t i = 0; i < hist_.size(); ++i)
         {
             auto& hist = hist_[i];
             // This is to make sure that the CV projects across the entire surface
             if(hist.value == 0) {hist.value = 1;}
             // The loop builds the previous basis projection for each bin of the histogram
             for(size_t k = 1; k < coeff_.size(); ++k)
             {
                 auto& coeff = coeff_[k];
                 for(size_t l = 0; l < cvs.size(); ++l)
                 {
                     // The previous bias is only calculated after each sweep has happened
                     basis *= LUT_[l].values[hist.map[l] + coeff.map[l]*(nbins_[l])];
                 }
                 bias += coeff.value*basis;
                 basis = 1.0;
             }
             /* The evaluation of the biased histogram which projects the histogram to the
              * current bias of CV space.
              */
             unbias_[i] += hist.value * exp(bias) * weight_ / (double)(cyclefreq_);
             bias = 0.0;
         }
         // The coefficients and histograms are reset after evaluating the biased histogram values
         for(size_t i = 0; i < coeff_.size(); ++i)
         {
             coeffTemp[i] = coeff_[i].value;
             coeff_[i].value = 0.0;
         }
         Histogram<int>::iterator hgit = histglobal_->begin();
         id1d = 0;
         for(it = histlocal_->begin(); it != histlocal_->end(); ++it, hgit++) {
                 hist_[id1d].value = 0.0;
                 *it = 0;
                 *hgit = 0;
                 ++id1d;
         }
         // The loop that evaluates the new coefficients by integrating the CV space
         for(size_t i = 1; i < coeff_.size(); ++i)
         {
             auto& coeff = coeff_[i];
             // The method uses a standard integration with trap rule weights
             for(size_t j = 0; j < hist_.size(); ++j)
             {
                 auto& hist = hist_[j];
                 double weight = std::pow(2.0,cvs.size());
                 // This adds in a trap-rule type weighting which lowers error significantly at the boundaries
                 for(size_t k = 0; k < cvs.size(); ++k)
                 {
                     if(hist.map[k] == 0 || hist.map[k] == nbins_[k]-1)
                         weight /= 2.0;
                 }
                 /*The numerical integration of the biased histogram across the entirety of CV space
                  *All calculations include the normalization as well
                  */
                 for(size_t l = 0; l < cvs.size(); l++)
                 {
                     basis *= LUT_[l].values[hist.map[l] + coeff.map[l]*(nbins_[l])];
                     basis *=  1.0 / (nbins_[l])*(2 * coeff.map[l] + 1.0);
                 }
                 coeff.value += basis * log(unbias_[j]) * weight/std::pow(2.0,cvs.size());
                 basis = 1.0;
             }
             coeffTemp[i] -= coeff.value;
             coeff_arr_[i] = coeff.value;
             sum += coeffTemp[i]*coeffTemp[i];
         }
         if(world_.rank() == 0)
             // Write coeff at this step, but only one walker
             PrintBias(cvs,beta);
         // The convergence tolerance and whether the user wants to exit are incorporated here
         if(sum < tol_)
         {
             std::cout<<"System has converged"<<std::endl;
             if(converge_exit_)
             {
                 std::cout<<"User has elected to exit. System is now exiting"<<std::endl;
                 exit(EXIT_SUCCESS);
             }
         }
     }
Member Data Documentation
std::string SSAGES::Basis::bnme_ private
The option to name both the basis and coefficient files will be given Basis filename
Definition at line 227 of file BasisFunc.h.
Referenced by PrintBias(), and Serialize().
std::vector<Map> SSAGES::Basis::coeff_ private
Globally located coefficient values.
As coefficients are updated at the same time, the coefficients should only be defined globally.
Definition at line 119 of file BasisFunc.h.
Referenced by CalcBiasForce(), PreSimulation(), PrintBias(), and UpdateBias().
std::vector<double> SSAGES::Basis::derivatives_ private
Derivatives of the bias potential.
The derivatives of the bias potential imposed on the system. They are evaluated by using the lookup table.
Definition at line 140 of file BasisFunc.h.
Referenced by CalcBiasForce(), PostIntegration(), and PreSimulation().
std::vector<Map> SSAGES::Basis::hist_ private
Histogram of visited states.
Histogram is stored locally. It is a 1D vector that holds N dimensional data over the number of walkers using a row major mapping.
Definition at line 100 of file BasisFunc.h.
Referenced by CalcBiasForce(), PostIntegration(), PreSimulation(), PrintBias(), and UpdateBias().
Histogram<int>* SSAGES::Basis::histglobal_ private
Globally defined histogram array for easy mpi operations.
Note
Needs lots of memory.
Definition at line 112 of file BasisFunc.h.
Referenced by UpdateBias(), and ~Basis().
Histogram<int>* SSAGES::Basis::histlocal_ private
Locally defined histogram array for easy mpi operations.
Note
It does take up more memory.
Definition at line 106 of file BasisFunc.h.
Referenced by CalcBiasForce(), PostIntegration(), PreSimulation(), PrintBias(), UpdateBias(), and ~Basis().
std::vector<double> SSAGES::Basis::restraint_ private
Spring constants for restrained system.
The system uses this to determine if the system is to be restrained on the defined interval. The user inputs the spring constants if the system is not periodic.
Definition at line 154 of file BasisFunc.h.
Referenced by CalcBiasForce(), and Serialize().
double SSAGES::Basis::temperature_ private
Self-defined temperature.
In the case of the MD engine using a poorly defined temperature, the option to throw it into the method is available. If not provided it takes the value from the engine.
Definition at line 182 of file BasisFunc.h.
Referenced by PostIntegration(), and Serialize().
std::vector<double> SSAGES::Basis::unbias_ private
The biased histogram of states.
The biased histogram of states has the form hist_*exp(phi*beta), where phi is the bias potential and beta is the inverse of the temperature. It is defined globally.
Definition at line 127 of file BasisFunc.h.
Referenced by PreSimulation(), PrintBias(), Serialize(), SetBasis(), and UpdateBias().
double SSAGES::Basis::weight_ private
Weighting for potentially faster sampling.
Weighting can be used to potentially sample faster, however it can cause the simulation to explode. By default this value will be set to 1.0
Definition at line 174 of file BasisFunc.h.
Referenced by Serialize(), and UpdateBias().
The documentation for this class was generated from the following files:
/home/cody/SSAGES/src/Methods/BasisFunc.h
/home/cody/SSAGES/src/Methods/BasisFunc.cpp