SSAGES: SSAGES::COPSS Class Reference
SSAGES::COPSS Class Reference
Public Member Functions
COPSS (boost::mpi::communicator &comm, unsigned int frequency)
void PreSimulation (Snapshot *, const CVList &) override
Method call prior to simulation initiation.
void PostIntegration (Snapshot *snapshot, const CVList &) override
Method call post integration.
void PostSimulation (Snapshot *, const CVList &) override
Method call post simulation.
void Serialize (Json::Value &) const override
Serialize the class.
Public Member Functions inherited from SSAGES::Constraint
Constraint (unsigned int frequency, boost::mpi::communicator &comm)
Public Member Functions inherited from SSAGES::EventListener
EventListener (unsigned int frequency)
Constructor.
unsigned int GetFrequency () const
Get frequency of event listener.
virtual ~EventListener ()
Destructor.
Public Member Functions inherited from SSAGES::Serializable
virtual ~Serializable ()
Destructor.
Private Attributes
std::ofstream _myout
Additional Inherited Members
Static Public Member Functions inherited from SSAGES::Constraint
static Constraint * BuildConstraint (const Json::Value &json, boost::mpi::communicator &comm)
static Constraint * BuildConstraint (const Json::Value &json, boost::mpi::communicator &comm, const std::string &path)
static void BuildConstraint (const Json::Value &json, ConstraintList &clist, boost::mpi::communicator &comm, const std::string &path)
Protected Attributes inherited from SSAGES::Constraint
boost::mpi::communicator _comm
Detailed Description
Definition at line 31 of file COPSS.h.
Member Function Documentation
void SSAGES::COPSS::PostIntegration (Snapshot * snapshot, const CVList & cvs) inline override virtual
Method call post integration.
Parameters
snapshot Pointer to the simulation snapshot.
cvs List of CVs.
This function will be called at the end of each integration step.
Implements SSAGES::Constraint.
Definition at line 49 of file COPSS.h.
References SSAGES::Snapshot::GetCommunicator(), SSAGES::Snapshot::GetForces(), and SSAGES::Snapshot::GetWalkerID().
         {
             using std::setw;
             using std::right;
             using std::setprecision;
             _myout << snapshot->GetWalkerID()
             << " " << snapshot->GetCommunicator().rank() << std::endl;
             auto& f = snapshot->GetForces();
             f[0][0] = 1.000000*f[0][0];
         }
void SSAGES::COPSS::PostSimulation (Snapshot * snapshot, const CVList & cvs) inline override virtual
Method call post simulation.
Parameters
snapshot Pointer to the simulation snapshot.
cvs List of CVs.
This function will be called after the simulation has finished.
Implements SSAGES::Constraint.
Definition at line 63 of file COPSS.h.
         {
             _myout <<" Post simulation"<<std::endl;
         }
void SSAGES::COPSS::PreSimulation (Snapshot * snapshot, const CVList & cvs) inline override virtual
Method call prior to simulation initiation.
Parameters
snapshot Pointer to the simulation snapshot.
cvs List of CVs.
This function will be called before the simulation is started.
Implements SSAGES::Constraint.
Definition at line 44 of file COPSS.h.
         {
             _myout<<"In PreSimulation"<<std::endl;
         }
void SSAGES::COPSS::Serialize (Json::Value & json) const inline override virtual
Serialize the class.
Parameters
json JSON value to which the information is stored
Store all information pertaining to this class in the given JSON value. The information can then be used to restart or analyze the simulation
Implements SSAGES::Serializable.
Definition at line 68 of file COPSS.h.
         {
         }
The documentation for this class was generated from the following file:
/home/cody/SSAGES/src/Constraints/COPSS.h