SSAGES: SSAGES::Umbrella Class Reference
SSAGES::Umbrella Class Reference
Methods
Umbrella sampling method.
#include <Umbrella.h>
Public Member Functions
Umbrella (const MPI_Comm &world, const MPI_Comm &comm, const std::vector< double > &kspring, const std::vector< double > &centers, std::string name, unsigned int frequency)
Constructor.
Umbrella (const MPI_Comm &world, const MPI_Comm &comm, const std::vector< double > &kspring, const std::vector< double > &centers0, const std::vector< double > &centers1, size_t timesteps, std::string name, unsigned int frequency)
Constructor.
void PreSimulation (Snapshot *snapshot, const class CVManager &cvmanager) override
Method call prior to simulation initiation.
void PostIntegration (Snapshot *snapshot, const class CVManager &cvmanager) override
Method call post integration.
void PostSimulation (Snapshot *snapshot, const class CVManager &cvmanager) override
Method call post simulation.
void SetOutputFrequency (int outfreq)
Set output frequency.
void SetAppend (bool append)
Set append mode.
Public Member Functions inherited from SSAGES::Method
Method (unsigned int frequency, const MPI_Comm &world, const MPI_Comm &comm)
Constructor.
void SetCVMask (const std::vector< unsigned int > &mask)
Sets the collective variable mask.
virtual ~Method ()
Destructor.
Public Member Functions inherited from SSAGES::EventListener
EventListener (unsigned int frequency)
Constructor.
unsigned int GetFrequency () const
Get frequency of event listener.
virtual ~EventListener ()
Destructor.
Static Public Member Functions
static Umbrella * Build (const Json::Value &json, const MPI_Comm &world, const MPI_Comm &comm, const std::string &path)
Build a derived method from JSON node.
Static Public Member Functions inherited from SSAGES::Method
static Method * BuildMethod (const Json::Value &json, const MPI_Comm &world, const MPI_Comm &comm, const std::string &path)
Build a derived method from JSON node.
Static Public Member Functions inherited from SSAGES::EventListener
static unsigned int GetWalkerID (const MPI_Comm &world, const MPI_Comm &comm)
Get walker ID number of specified communicator.
static unsigned int GetNumWalkers (const MPI_Comm &world, const MPI_Comm &comm)
Get total number of walkers in the simulation.
static bool IsMasterRank (const MPI_Comm &comm)
Check if current processor is master.
Private Member Functions
double GetCurrentCenter (size_t iteration, size_t i)
Get the current center of the umbrella at a given iteration.
void PrintUmbrella (const CVList &cvs, size_t iteration)
Print umbrella values.
Private Attributes
std::vector< double > kspring_
Vector of spring constants.
size_t time_
Amount of time over which to scale centers.
std::string filename_
Output filename.
int outfreq_
Frequency of outputting data.
std::ofstream umbrella_
Output stream for umbrella data.
bool append_
Append to output files?
std::vector< double > centers0_
std::vector< double > centers1_
Additional Inherited Members
Protected Attributes inherited from SSAGES::Method
mxx::comm world_
Global MPI communicator.
mxx::comm comm_
Local MPI communicator.
std::vector< unsigned int > cvmask_
Mask which identifies which CVs to act on.
Detailed Description
Umbrella sampling method.
Umbrella sampling method to constrain an arbitrary number of CVs at specified equilibrium distances.
Definition at line 35 of file Umbrella.h.
Constructor & Destructor Documentation
Umbrella() [1/2]
SSAGES::Umbrella::Umbrella (const MPI_Comm & world, const MPI_Comm & comm, const std::vector< double > & kspring, const std::vector< double > & centers, std::string name, unsigned int frequency) inline
Constructor.
Parameters
world MPI global communicator.
comm MPI local communicator.
kspring List of spring constants.
centers List of spring equilibrium positions.
name Filename.
frequency Frequency with which this method is applied.
Create instance of umbrella with spring constants "kspring", and centers "centers". Note the sizes of the vectors should be commensurate with the number of CVs.
Definition at line 98 of file Umbrella.h.
                                          :
         Method(frequency, world, comm), kspring_(kspring), centers0_(centers),
         centers1_(centers), time_(0), filename_(name), outfreq_(1), append_(false)
         {
         }
Umbrella() [2/2]
SSAGES::Umbrella::Umbrella (const MPI_Comm & world, const MPI_Comm & comm, const std::vector< double > & kspring, const std::vector< double > & centers0, const std::vector< double > & centers1, size_t timesteps, std::string name, unsigned int frequency) inline
Constructor.
Parameters
world MPI global communicator.
comm MPI local communicator.
kspring List of spring constants.
centers0 List of starting spring equilibrium positions.
centers1 List of ending spring equilibrium positions.
timesteps Number of timesteps over which to scale centers.
name Filename.
frequency Frequency with which this method is applied.
Create instance of umbrella with spring constants "kspring", and centers "centers". Note the sizes of the vectors should be commensurate with the number of CVs.
Definition at line 124 of file Umbrella.h.
                                          :
         Method(frequency, world, comm), kspring_(kspring), centers0_(centers0),
         centers1_(centers1), time_(timesteps), filename_(name), outfreq_(1)
         {
         }
Member Function Documentation
Build()
Umbrella * SSAGES::Umbrella::Build (const Json::Value & json, const MPI_Comm & world, const MPI_Comm & comm, const std::string & path) static
Build a derived method from JSON node.
Parameters
json JSON Value containing all input information.
world MPI global communicator.
comm MPI local communicator.
path Path for JSON path specification.
Returns
Pointer to the Method built. nullptr if an unknown error occurred.
This function builds a registered method from a JSON node. The difference between this function and "Build" is that this automatically determines the appropriate derived type based on the JSON node information.
Note
Object lifetime is the caller's responsibility.
Definition at line 112 of file Umbrella.cpp.
     {
         ObjectRequirement validator;
         Value schema;
         CharReaderBuilder rbuilder;
         CharReader* reader = rbuilder.newCharReader();
         reader->parse(JsonSchema::UmbrellaMethod.c_str(),
                       JsonSchema::UmbrellaMethod.c_str() + JsonSchema::UmbrellaMethod.size(),
                       &schema, nullptr);
         validator.Parse(schema, path);
         // Validate inputs.
         validator.Validate(json, path);
         if(validator.HasErrors())
             throw BuildException(validator.GetErrors());
         unsigned int wid = GetWalkerID(world, comm);
         unsigned int wcount = GetNumWalkers(world, comm);
         bool ismulti = wcount > 1;
         std::vector<std::vector<double>> ksprings;
         for(auto& s : json["ksprings"])
         {
             std::vector<double> kspring;
             if(s.isArray())
                 for(auto& k : s)
                     kspring.push_back(k.asDouble());
             else
                 kspring.push_back(s.asDouble());
             ksprings.push_back(kspring);
         }
         std::vector<std::vector<double>> centers0, centers1;
         if(json.isMember("centers"))
         {
             for(auto& s : json["centers"])
             {
                 std::vector<double> center;
                 if(s.isArray())
                     for(auto& k : s)
                         center.push_back(k.asDouble());
                 else
                     center.push_back(s.asDouble());
                 centers0.push_back(center);
             }
         }
         else if(json.isMember("centers0") && json.isMember("centers1") && json.isMember("timesteps"))
         {
             for(auto& s : json["centers0"])
             {
                 std::vector<double> center;
                 if(s.isArray())
                     for(auto& k : s)
                         center.push_back(k.asDouble());
                 else
                     center.push_back(s.asDouble());
                 centers0.push_back(center);
             }
             for(auto& s : json["centers1"])
             {
                 std::vector<double> center;
                 if(s.isArray())
                     for(auto& k : s)
                         center.push_back(k.asDouble());
                 else
                     center.push_back(s.asDouble());
                 centers1.push_back(center);
             }
         }
         else
             throw BuildException({"Either \"centers\" or \"timesteps\", \"centers0\" and \"centers1\" must be defined for umbrella."});
         if(ksprings[0].size() != centers0[0].size())
             throw BuildException({"Need to define a spring for every center or a center for every spring!"});
         // If only one set of center/ksprings are specified. Fill it up for multi.
         if(ismulti)
         {
             if(ksprings.size() == 1)
                 for(size_t i = 1; i < wcount; ++i)
                     ksprings.push_back(ksprings[0]);
             else if(ksprings.size() != wcount)
                 throw std::invalid_argument(path + ": Multi-walker simulations requires that the number of \"ksprings\" match the number of walkers.");
             if(centers0.size() == 1)
                 for(size_t i = 1; i < wcount; ++i)
                     centers0.push_back(centers0[0]);
             else if(centers0.size() != wcount)
                 throw std::invalid_argument(path + ": Multi-walker simulations requires that the number of \"centers\"/\"centers0\" match the number of walkers.");
             if(centers1.size() == 1)
                 for(size_t i = 1; i < wcount; ++i)
                     centers1.push_back(centers1[0]);
             else if(centers1.size()) // centers1 is optional.
                 throw std::invalid_argument(path + ": Multi-walker simulations requires that the number of \"centers1\" match the number of walkers.");
         }
         auto freq = json.get("frequency", 1).asInt();
         size_t timesteps = 0;
         if(json.isMember("timesteps"))
         {
             if(json["timesteps"].isArray())
                 timesteps = json["timesteps"][wid].asUInt();
             else
                 timesteps = json["timesteps"].asUInt();
         }
         std::string name = "umbrella.dat";
         if(json["output_file"].isArray())
             name = json["output_file"][wid].asString();
         else if(ismulti)
             throw std::invalid_argument(path + ": Multi-walker simulations require a separate output file for each.");
         else
             name = json["output_file"].asString();
         Umbrella* m = nullptr;
         if(timesteps == 0)
             m = new Umbrella(world, comm, ksprings[wid], centers0[wid], name, freq);
         else
             m = new Umbrella(world, comm, ksprings[wid], centers0[wid], centers1[wid], timesteps, name, freq);
         m->SetOutputFrequency(json.get("output_frequency",0).asInt());
         m->SetAppend(json.get("append", false).asBool());
         return m;
     }
References Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), SetAppend(), SetOutputFrequency(), and Json::ObjectRequirement::Validate().
GetCurrentCenter()
double SSAGES::Umbrella::GetCurrentCenter (size_t iteration, size_t i) inline private
Get the current center of the umbrella at a given iteration.
Parameters
iteration Current iteration of the Snapshot.
i index (iterator) for CV.
Returns
Center of umbrella at current iteration
Definition at line 68 of file Umbrella.h.
         {
             // We are at the end.
             if(iteration >= time_) return centers1_[i];
             // Scale linearly.
             return (centers1_[i] - centers0_[i])/time_*iteration + centers0_[i];
         }
References centers0_, and time_.
PostIntegration()
void SSAGES::Umbrella::PostIntegration (Snapshot * snapshot, const class CVManager & cvmanager) override virtual
Method call post integration.
Parameters
snapshot Pointer to the simulation snapshot.
cvmanager Collective variable manager.
This function will be called after each integration step.
Implements SSAGES::Method.
Definition at line 57 of file Umbrella.cpp.
     {
         // Get necessary info.
         auto cvs = cvmanager.GetCVs(cvmask_);
         auto& forces = snapshot->GetForces();
         auto& virial = snapshot->GetVirial();
         for(size_t i = 0; i < cvs.size(); ++i)
         {
             // Get current CV and gradient.
             auto& cv = cvs[i];
             auto& grad = cv->GetGradient();
             auto& boxgrad = cv->GetBoxGradient();
             // Compute dV/dCV.
             auto center = GetCurrentCenter(snapshot->GetIteration(), i);
             auto D = kspring_[i]*cv->GetDifference(center);
             // Update forces.
             for(size_t j = 0; j < forces.size(); ++j)
                 forces[j] -= D*grad[j];
             // Update virial.
             virial += D*boxgrad;
         }
         if(snapshot->GetIteration() % outfreq_ == 0)
             PrintUmbrella(cvs, snapshot->GetIteration());
     }
References SSAGES::CVManager::GetCVs(), SSAGES::Snapshot::GetForces(), SSAGES::Snapshot::GetIteration(), and SSAGES::Snapshot::GetVirial().
PostSimulation()
void SSAGES::Umbrella::PostSimulation (Snapshot * snapshot, const class CVManager & cvmanager) override virtual
Method call post simulation.
Parameters
snapshot Pointer to the simulation snapshot.
cvmanager Collective variable manager.
This function will be called after the end of the simulation run.
Implements SSAGES::Method.
Definition at line 86 of file Umbrella.cpp.
     {
         if(IsMasterRank(comm_))
             umbrella_.close();
     }
PreSimulation()
void SSAGES::Umbrella::PreSimulation (Snapshot * snapshot, const class CVManager & cvmanager) override virtual
Method call prior to simulation initiation.
Parameters
snapshot Pointer to the simulation snapshot.
cvmanager Collective variable manager.
This function will be called before the simulation is started.
Implements SSAGES::Method.
Definition at line 33 of file Umbrella.cpp.
     {
         if(IsMasterRank(comm_))
         {
             if(append_)
                 umbrella_.open(filename_.c_str(), std::ofstream::out | std::ofstream::app);
             else
             {
                 // Write out header.
                 umbrella_.open(filename_.c_str(), std::ofstream::out);
                 umbrella_ << "#";
                 umbrella_ << "Iteration ";
                 auto cvs = cvmanager.GetCVs(cvmask_);
                 for(size_t i = 0; i < cvs.size(); ++i)
                     umbrella_ << "cv_" + std::to_string(i) << " ";
                 for(size_t i = 0; i < cvs.size() - 1; ++i)
                     umbrella_ << "center_" + std::to_string(i) << " ";
                 umbrella_ << "center_" + std::to_string(cvs.size() - 1) << std::endl;
             }
         }
     }
References SSAGES::CVManager::GetCVs().
PrintUmbrella()
void SSAGES::Umbrella::PrintUmbrella (const CVList & cvs, size_t iteration) private
Print umbrella values.
Parameters
cvs List of CVs.
iteration Current iteration.
Definition at line 92 of file Umbrella.cpp.
     {
         if(IsMasterRank(comm_))
         {
             umbrella_.precision(8);
             umbrella_ << iteration << " ";
             // Print out CV values first.
             for(auto& cv : cvs)
                 umbrella_ << cv->GetValue() << " ";
             // Print out target (center) of each CV.
             for(size_t i = 0; i < cvs.size() - 1; ++i)
                 umbrella_ << GetCurrentCenter(iteration, i) << " ";
             umbrella_ << GetCurrentCenter(iteration, cvs.size() - 1);
             umbrella_ << std::endl;
         }
     }
SetAppend()
void SSAGES::Umbrella::SetAppend (bool append) inline
Set append mode.
Parameters
append Whether to enable or disable append mode.
Definition at line 159 of file Umbrella.h.
         {
             append_ = append;
         }
References append_.
Referenced by Build().
SetOutputFrequency()
void SSAGES::Umbrella::SetOutputFrequency (int outfreq) inline
Set output frequency.
Parameters
outfreq New value for output frequency.
Definition at line 150 of file Umbrella.h.
         {
             outfreq_ = outfreq;
         }
References outfreq_.
Referenced by Build().
Member Data Documentation
centers0_
std::vector<double> SSAGES::Umbrella::centers0_ private
Vector of equilibrium distances.
Definition at line 43 of file Umbrella.h.
Referenced by GetCurrentCenter().
The documentation for this class was generated from the following files:
/home/michael/development/SSAGES/src/Methods/Umbrella.h
/home/michael/development/SSAGES/src/Methods/Umbrella.cpp