SSAGES: SSAGES::Snapshot Class Reference
SSAGES::Snapshot Class Reference
Class containing a snapshot of the current simulation in time.
#include <Snapshot.h>
Public Member Functions
Snapshot (const MPI_Comm &comm, unsigned int wid)
Constructor.
size_t GetIteration () const
Get the current iteration.
size_t GetTargetIterations () const
Get target iterations.
double GetTemperature () const
Get current temperature.
double GetEnergy () const
Get per-particle energy.
const Matrix3 & GetHMatrix () const
Get system H-matrix.
const Matrix3 & GetVirial () const
Get box virial.
Matrix3 & GetVirial ()
Get box virial.
const Vector3 & GetOrigin () const
Get origin of the system.
const Bool3 & IsPeriodic () const
Get periodicity of three dimensions.
double GetVolume () const
Get system volume.
double GetKb () const
Get system Kb.
double GetDielectric () const
Get dielectric constant.
double Getqqrd2e () const
Get qqrd2e value.
const mxx::comm & GetCommunicator () const
Get communicator for walker.
unsigned GetWalkerID () const
Get walker ID.
unsigned GetNumAtoms () const
Get number of atoms in this snapshot.
void SetIteration (size_t iteration)
Set the iteration.
void SetTargetIterations (int target)
Set target iterations.
void SetTemperature (double temperature)
Change the temperature.
void SetEnergy (double energy)
Change the energy.
void SetHMatrix (const Matrix3 &hmat)
Change the Box H-matrix.
void SetVirial (const Matrix3 &virial)
Change the box virial.
void SetOrigin (const Vector3 &origin)
Change the box origin.
void SetPeriodicity (const Bool3 &isperiodic)
Change the periodicity of the system.
void SetKb (double kb)
Change the kb.
void SetDielectric (double dielectric)
Set the dielectric constant.
void Setqqrd2e (double qqrd2e)
Set the value for qqrd2e.
void SetNumAtoms (unsigned int natoms)
Set number of atoms in this snapshot.
const std::vector< Vector3 > & GetPositions () const
Access the particle positions.
std::vector< Vector3 > & GetPositions ()
Access the particle positions.
const std::vector< Integer3 > & GetImageFlags () const
Access the particles image flags.
std::vector< Integer3 > & GetImageFlags ()
Access the particles image flags.
const std::vector< Vector3 > & GetVelocities () const
Access the particle velocities.
std::vector< Vector3 > & GetVelocities ()
Access the particle velocities.
const std::vector< Vector3 > & GetForces () const
Access the per-particle forces.
std::vector< Vector3 > & GetForces ()
Access the per-particle forces.
const std::vector< double > & GetMasses () const
Const access to the particle masses.
std::vector< double > & GetMasses ()
Const access to the particle masses.
Vector3 ScaleVector (const Vector3 &v) const
Scale a vector into fractional coordinates.
Vector3 UnwrapVector (const Vector3 &v, const Integer3 &image) const
Unwrap a vector's real coordinates according to its image replica count.
void ApplyMinimumImage (Vector3 *v) const
Apply minimum image to a vector.
Vector3 ApplyMinimumImage (const Vector3 &v) const
Apply minimum image to a vector.
double TotalMass (const Label &indices) const
Compute the total mass of a group of particles based on index.
Vector3 CenterOfMass (const Label &indices) const
Vector3 CenterOfMass (const Label &indices, double mtot) const
std::vector< Vector3 > UnwrapPositions (const Label &indices) const
Unwrap the particle positions, based on first position.
const Label & GetAtomIDs () const
Access the atom IDs.
Label & GetAtomIDs ()
Access the atom IDs.
int GetLocalIndex (int id) const
Gets the local atom index corresponding to an atom ID.
void GetLocalIndices (const Label &ids, Label *indices) const
const std::vector< double > & GetCharges () const
Access the atom charges.
std::vector< double > & GetCharges ()
Access the atom charges.
const Label & GetAtomTypes () const
Access the atom types.
Label & GetAtomTypes ()
Access the atom types.
const std::vector< std::vector< double > > & GetSigmas () const
Access the atom sigmas.
std::vector< std::vector< double > > & GetSigmas ()
Access the atom sigmas.
const std::string & GetSnapshotID () const
Access the snapshot ID.
std::string & GetSnapshotID ()
Access the snapshot ID.
bool HasChanged () const
Query if Snapshot was modified.
void Changed (bool state)
Set the "changed" flag of the Snapshot.
std::vector< double > SerializePositions ()
Return the serialized positions across all local cores.
std::vector< double > SerializeVelocities ()
Return the serialized velocities across all local cores.
std::vector< int > SerializeIDs ()
Return the serialized IDs across all local cores.
~Snapshot ()
Destructor.
Private Attributes
mxx::comm comm_
Local snapshot (walker) communicator.
unsigned int wid_
Walker ID.
unsigned int nlocal_
Number of atoms located on this snapshot.
std::string ID_
ID string.
Matrix3 H_
Parrinello-Rahman box H-matrix.
Matrix3 Hinv_
Parinello-Rahman box inverse.
Matrix3 virial_
Virial tensor.
Vector3 origin_
Box origin.
Bool3 isperiodic_
Periodicity of box.
std::vector< Vector3 > positions_
Positions.
std::vector< Integer3 > images_
Unwrapped positions.
std::vector< Vector3 > velocities_
Velocities.
std::vector< Vector3 > forces_
Forces.
std::vector< double > masses_
Masses.
std::vector< double > charges_
Charges.
Label atomids_
List of Atom IDs.
Label types_
List of Atom types.
std::vector< std::vector< double > > sigma_
Sigma.
size_t iteration_
Iteration of Simulation.
size_t targetiter_
Iteration target of simulation.
double temperature_
Current temperature.
double energy_
Average per-particle energy.
double kb_
Kb from the MD driver.
double dielectric_
Dielectric.
double qqrd2e_
qqrd2e
bool changed_
TRUE is Simulation state changed
Detailed Description
Class containing a snapshot of the current simulation in time.
This contains information on the particle positions, velocities, etc... and additional information on the state of the system.
Definition at line 47 of file Snapshot.h.
Constructor & Destructor Documentation
SSAGES::Snapshot::Snapshot (const MPI_Comm & comm, unsigned int wid) inline
Constructor.
Parameters
comm MPI communicator
wid Walker ID
Initialize a snapshot with MPI communicator and a correpsonding walker ID.
Definition at line 96 of file Snapshot.h.
References atomids_, energy_, forces_, images_, isperiodic_, iteration_, kb_, masses_, positions_, temperature_, types_, and velocities_.
                                                          :
         comm_(comm), wid_(wid), H_(), Hinv_(), virial_(Matrix3::Zero()),
         origin_({0,0,0}), isperiodic_({true, true, true}), positions_(0),
         images_(0), velocities_(0), forces_(0), masses_(0), atomids_(0),
         types_(0), iteration_(0), temperature_(0), energy_(0), kb_(0)
         {}
Member Function Documentation
void SSAGES::Snapshot::ApplyMinimumImage (Vector3 * v) const inline
Apply minimum image to a vector.
Parameters
v Vector of interest
Definition at line 422 of file Snapshot.h.
References SSAGES::roundf().
Referenced by CenterOfMass(), SSAGES::AngleCV::Evaluate(), SSAGES::TorsionalCV::Evaluate(), SSAGES::PairwiseCV::Evaluate(), SSAGES::ParticlePositionCV::Evaluate(), SSAGES::RouseModeCV::Evaluate(), SSAGES::GyrationTensorCV::Evaluate(), SSAGES::ParticleSeparationCV::Evaluate(), and UnwrapPositions().
         {
             Vector3 scaled = Hinv_*(*v);
             for(int i = 0; i < 3; ++i)
                 scaled[i] -= isperiodic_[i]*roundf(scaled[i]);
             *v = H_*scaled;
         }
Vector3 SSAGES::Snapshot::ApplyMinimumImage (const Vector3 & v) const inline
Apply minimum image to a vector.
Parameters
v Vector of interest
Returns
Return new vector.
Definition at line 437 of file Snapshot.h.
References SSAGES::roundf().
         {
             Vector3 scaled = Hinv_*v;
             for(int i = 0; i < 3; ++i)
                 scaled[i] -= isperiodic_[i]*roundf(scaled[i]);
             return H_*scaled;
         }
Vector3 SSAGES::Snapshot::CenterOfMass (const Label & indices) const inline
Compute center of mass of a group of atoms based on idex with provided Total mass.
Parameters
indices IDs of particles of interest.
Returns
Vector3 Center of mass of particles.
Definition at line 470 of file Snapshot.h.
References TotalMass().
Referenced by SSAGES::ParticleCoordinateCV::Evaluate(), SSAGES::ParticlePositionCV::Evaluate(), SSAGES::RouseModeCV::Evaluate(), SSAGES::GyrationTensorCV::Evaluate(), and SSAGES::ParticleSeparationCV::Evaluate().
         {
             // Get total mass.
             auto mtot = TotalMass(indices);
             return CenterOfMass(indices, mtot);
         }
Vector3 SSAGES::Snapshot::CenterOfMass (const Label & indices, double mtot) const inline
Compute center of mass of a group of atoms based on idex with provided Total mass.
Parameters
indices IDs of particles of interest.
mtot Total mass of particle group.
Returns
Vector3 Center of mass of particles.
Note
Each processor passes in the local indices of the atoms of interest and this function will collect the data and compute the center of mass.
Definition at line 487 of file Snapshot.h.
References ApplyMinimumImage(), and comm_.
         {
             // Store coorinates and masses in vectors to gather.
             std::vector<double> pos, mass, gpos, gmass;
             std::vector<int> pcounts(comm_.size(), 0), mcounts(comm_.size(), 0);
             std::vector<int> pdispls(comm_.size()+1, 0), mdispls(comm_.size()+1, 0);
             pcounts[comm_.rank()] = 3*indices.size();
             mcounts[comm_.rank()] = indices.size();
             // Reduce counts.
             MPI_Allreduce(MPI_IN_PLACE, pcounts.data(), pcounts.size(), MPI_INT, MPI_SUM, comm_);
             MPI_Allreduce(MPI_IN_PLACE, mcounts.data(), mcounts.size(), MPI_INT, MPI_SUM, comm_);
             // Compute displacements.
             std::partial_sum(pcounts.begin(), pcounts.end(), pdispls.begin() + 1);
             std::partial_sum(mcounts.begin(), mcounts.end(), mdispls.begin() + 1);
             // Fill up mass and position vectors.
             for(auto& idx : indices)
             {
                 auto& p = positions_[idx];
                 pos.push_back(p[0]);
                 pos.push_back(p[1]);
                 pos.push_back(p[2]);
                 mass.push_back(masses_[idx]);
             }
             // Re-size receiving vectors.
             gpos.resize(pdispls.back(), 0);
             gmass.resize(mdispls.back(), 0);
             // All-gather data.
             MPI_Allgatherv(pos.data(), pos.size(), MPI_DOUBLE, gpos.data(), pcounts.data(), pdispls.data(), MPI_DOUBLE, comm_);
             MPI_Allgatherv(mass.data(), mass.size(), MPI_DOUBLE, gmass.data(), mcounts.data(), mdispls.data(), MPI_DOUBLE, comm_);
             // Loop through atoms and compute mass weighted sum.
             // We march linearly through list and find nearest image
             // to each successive particle to properly unwrap object.
             Vector3 ppos = {gpos[0], gpos[1], gpos[2]}; // Previous unwrapped position.
             Vector3 cpos = ppos;
             Vector3 xcm = gmass[0]*cpos;
             for(size_t i = 1, j = 3; i < gmass.size(); ++i, j += 3)
             {
                 cpos = {gpos[j], gpos[j+1], gpos[j+2]};
                 cpos = ApplyMinimumImage(cpos - ppos) + ppos;
                 xcm += gmass[i]*cpos;
                 ppos = cpos;
             }
             return xcm/mtot;
         }
void SSAGES::Snapshot::Changed (bool state) inline
Set the "changed" flag of the Snapshot.
Parameters
state State to which the "changed" flag is set
Definition at line 706 of file Snapshot.h.
Referenced by SSAGES::Hook::PostIntegrationHook(), SSAGES::Hook::PostSimulationHook(), and SSAGES::Hook::PreSimulationHook().
 { changed_ = state; }
const Label& SSAGES::Snapshot::GetAtomIDs () const inline
Access the atom IDs.
Returns
List of atom IDs
Definition at line 602 of file Snapshot.h.
References atomids_.
Referenced by SSAGES::ForwardFlux::AppendTrajectoryFile(), SSAGES::PairwiseCV::Evaluate(), SSAGES::RMSDCV::Evaluate(), SSAGES::RMSDCV::Initialize(), SSAGES::ForwardFlux::ReadFFSConfiguration(), and SSAGES::ForwardFlux::WriteFFSConfiguration().
 { return atomids_; }
Label& SSAGES::Snapshot::GetAtomIDs () inline
Access the atom IDs.
Returns
List of atom IDs
Definition at line 605 of file Snapshot.h.
References atomids_.
         {
             changed_ = true;
             return atomids_;
         }
const Label& SSAGES::Snapshot::GetAtomTypes () const inline
Access the atom types.
Returns
List of atom types
Definition at line 661 of file Snapshot.h.
References types_.
 { return types_; }
Label& SSAGES::Snapshot::GetAtomTypes () inline
Access the atom types.
Returns
List of atom types
Definition at line 664 of file Snapshot.h.
References types_.
         {
             changed_ = true;
             return types_;
         }
const std::vector<double>& SSAGES::Snapshot::GetCharges () const inline
Access the atom charges.
Returns
List of atom charges
Definition at line 648 of file Snapshot.h.
References charges_.
 { return charges_; }
std::vector<double>& SSAGES::Snapshot::GetCharges () inline
Access the atom charges.
Returns
List of atom charges
Definition at line 651 of file Snapshot.h.
References charges_.
         {
             changed_ = true;
             return charges_;
         }
const mxx::comm& SSAGES::Snapshot::GetCommunicator () const inline
Get communicator for walker.
Returns
Communicator containing processors for simulation instance (walker).
Access the communicator containing the set of processors that belong to a single simulation box.
Definition at line 188 of file Snapshot.h.
References comm_.
Referenced by SSAGES::BoxVolumeCV::Evaluate(), SSAGES::AngleCV::Evaluate(), SSAGES::TorsionalCV::Evaluate(), SSAGES::PairwiseCV::Evaluate(), SSAGES::GyrationTensorCV::Evaluate(), SSAGES::AlphaRMSDCV::Evaluate(), SSAGES::AntiBetaRMSDCV::Evaluate(), SSAGES::ParallelBetaRMSDCV::Evaluate(), SSAGES::AngleCV::Initialize(), SSAGES::PairwiseCV::Initialize(), SSAGES::ParticleCoordinateCV::Initialize(), SSAGES::TorsionalCV::Initialize(), SSAGES::RouseModeCV::Initialize(), SSAGES::ParticleSeparationCV::Initialize(), SSAGES::ParticlePositionCV::Initialize(), SSAGES::GyrationTensorCV::Initialize(), SSAGES::AlphaRMSDCV::Initialize(), SSAGES::AntiBetaRMSDCV::Initialize(), and SSAGES::ParallelBetaRMSDCV::Initialize().
         {
             return comm_;
         }
double SSAGES::Snapshot::GetDielectric () const inline
Get dielectric constant.
Returns
dielectric constant.
Definition at line 173 of file Snapshot.h.
References dielectric_.
 { return dielectric_; }
double SSAGES::Snapshot::GetEnergy () const inline
Get per-particle energy.
Returns
Current average per-particle energy
Definition at line 125 of file Snapshot.h.
References energy_.
 { return energy_; }
const std::vector<Vector3>& SSAGES::Snapshot::GetForces () const inline
Access the per-particle forces.
Returns
List of per-particle forces
Definition at line 366 of file Snapshot.h.
References forces_.
Referenced by SSAGES::ElasticBand::PostIntegration(), SSAGES::FiniteTempString::PostIntegration(), SSAGES::Swarm::PostIntegration(), SSAGES::ANN::PostIntegration(), SSAGES::Umbrella::PostIntegration(), SSAGES::Meta::PostIntegration(), SSAGES::BFS::PostIntegration(), SSAGES::ABF::PostIntegration(), and SSAGES::ForwardFlux::ReadFFSConfiguration().
 { return forces_; }
std::vector<Vector3>& SSAGES::Snapshot::GetForces () inline
Access the per-particle forces.
Returns
List of per-particle forces
Definition at line 369 of file Snapshot.h.
References forces_.
         {
             changed_ = true;
             return forces_;
         }
const Matrix3& SSAGES::Snapshot::GetHMatrix () const inline
Get system H-matrix.
Returns
Parrinello-Rahman H-matrix of simulation box
Definition at line 131 of file Snapshot.h.
References H_.
 { return H_; }
const std::vector<Integer3>& SSAGES::Snapshot::GetImageFlags () const inline
Access the particles image flags.
Returns
List of particle image flags
Definition at line 340 of file Snapshot.h.
References images_.
Referenced by SSAGES::RMSDCV::Evaluate().
 { return images_; }
std::vector<Integer3>& SSAGES::Snapshot::GetImageFlags () inline
Access the particles image flags.
Returns
List of particle image flags
Definition at line 343 of file Snapshot.h.
References images_.
         {
             changed_ = true;
             return images_;
         }
size_t SSAGES::Snapshot::GetIteration () const inline
Get the current iteration.
Returns
Current Iteration
Definition at line 107 of file Snapshot.h.
References iteration_.
Referenced by SSAGES::Logger::PostIntegration(), SSAGES::ANN::PostIntegration(), SSAGES::Umbrella::PostIntegration(), SSAGES::Meta::PostIntegration(), SSAGES::BFS::PostIntegration(), and SSAGES::Hook::PostIntegrationHook().
 {return iteration_; }
double SSAGES::Snapshot::GetKb () const inline
Get system Kb.
Returns
Kb of the current simulation box
Definition at line 167 of file Snapshot.h.
References kb_.
Referenced by SSAGES::BFS::PostIntegration(), and SSAGES::ANN::PreSimulation().
 { return kb_; }
int SSAGES::Snapshot::GetLocalIndex (int id) const inline
Gets the local atom index corresponding to an atom ID.
Parameters
id Atom ID.
Returns
Local atom index or -1 if not found.
Definition at line 616 of file Snapshot.h.
Referenced by SSAGES::AngleCV::Evaluate(), SSAGES::TorsionalCV::Evaluate(), SSAGES::PairwiseCV::Evaluate(), SSAGES::AlphaRMSDCV::Evaluate(), SSAGES::AntiBetaRMSDCV::Evaluate(), SSAGES::ParallelBetaRMSDCV::Evaluate(), GetLocalIndices(), SSAGES::PairwiseCV::Initialize(), SSAGES::ParticleCoordinateCV::Initialize(), SSAGES::RouseModeCV::Initialize(), SSAGES::ParticleSeparationCV::Initialize(), SSAGES::ParticlePositionCV::Initialize(), SSAGES::GyrationTensorCV::Initialize(), SSAGES::FiniteTempString::PostIntegration(), and SSAGES::Swarm::PostIntegration().
         {
             auto s = std::find(atomids_.begin(), atomids_.end(), id);
             if(s == atomids_.end())
                 return -1;
             else
                 return s - atomids_.begin();
         }
void SSAGES::Snapshot::GetLocalIndices (const Label & ids, Label * indices) const inline
Gets the local atom indices corresponding to atom IDs in the vector.
Parameters
ids Vector of atom ID's.
indices Pointer to container for local atom indices.
Note
If atom does not exist on processor, it will be ignored.
Definition at line 634 of file Snapshot.h.
References GetLocalIndex().
Referenced by SSAGES::ParticleCoordinateCV::Evaluate(), SSAGES::PairwiseCV::Evaluate(), SSAGES::ParticlePositionCV::Evaluate(), SSAGES::RouseModeCV::Evaluate(), SSAGES::GyrationTensorCV::Evaluate(), SSAGES::ParticleSeparationCV::Evaluate(), SSAGES::AngleCV::Initialize(), SSAGES::TorsionalCV::Initialize(), SSAGES::AlphaRMSDCV::Initialize(), SSAGES::AntiBetaRMSDCV::Initialize(), SSAGES::ParallelBetaRMSDCV::Initialize(), and SSAGES::RouseModeCV::setMasses().
         {
             for(auto& id : ids)
             {
                 auto idx = GetLocalIndex(id);
                 if(idx != -1)
                     indices->push_back(idx);
             }
         }
const std::vector<double>& SSAGES::Snapshot::GetMasses () const inline
Const access to the particle masses.
Returns
List of Masses
Note that the Masses can be either stored as per-atom or per-type depending on the Lammps Atom type used.
Definition at line 382 of file Snapshot.h.
References masses_.
Referenced by SSAGES::ParticleCoordinateCV::Evaluate(), SSAGES::ParticlePositionCV::Evaluate(), SSAGES::RouseModeCV::Evaluate(), SSAGES::GyrationTensorCV::Evaluate(), SSAGES::ParticleSeparationCV::Evaluate(), SSAGES::RMSDCV::Evaluate(), SSAGES::RMSDCV::Initialize(), and SSAGES::ABF::PostIntegration().
 { return masses_; }
std::vector<double>& SSAGES::Snapshot::GetMasses () inline
Const access to the particle masses.
Returns
List of Masses
Note that the Masses can be either stored as per-atom or per-type depending on the Lammps Atom type used.
Definition at line 385 of file Snapshot.h.
References masses_.
         {
             changed_ = true;
             return masses_;
         }
unsigned SSAGES::Snapshot::GetNumAtoms () const inline
Get number of atoms in this snapshot.
Returns
Number of atoms in this snapshot
Definition at line 204 of file Snapshot.h.
References nlocal_.
Referenced by SSAGES::ABF::CalcBiasForce(), SSAGES::BoxVolumeCV::Evaluate(), SSAGES::AngleCV::Evaluate(), SSAGES::TorsionalCV::Evaluate(), SSAGES::ParticleCoordinateCV::Evaluate(), SSAGES::PairwiseCV::Evaluate(), SSAGES::ParticlePositionCV::Evaluate(), SSAGES::RouseModeCV::Evaluate(), SSAGES::GyrationTensorCV::Evaluate(), SSAGES::ParticleSeparationCV::Evaluate(), SSAGES::AlphaRMSDCV::Evaluate(), SSAGES::AntiBetaRMSDCV::Evaluate(), SSAGES::ParallelBetaRMSDCV::Evaluate(), and SSAGES::ABF::PostIntegration().
 { return nlocal_; }
const Vector3& SSAGES::Snapshot::GetOrigin () const inline
Get origin of the system.
Returns
Vector containing coordinates of box origin.
Definition at line 149 of file Snapshot.h.
References origin_.
 { return origin_; }
const std::vector<Vector3>& SSAGES::Snapshot::GetPositions () const inline
Access the particle positions.
Returns
List of particle positions
Definition at line 327 of file Snapshot.h.
References positions_.
Referenced by SSAGES::ForwardFlux::AppendTrajectoryFile(), SSAGES::AngleCV::Evaluate(), SSAGES::TorsionalCV::Evaluate(), SSAGES::PairwiseCV::Evaluate(), SSAGES::GyrationTensorCV::Evaluate(), SSAGES::RMSDCV::Evaluate(), SSAGES::AlphaRMSDCV::Evaluate(), SSAGES::AntiBetaRMSDCV::Evaluate(), SSAGES::ParallelBetaRMSDCV::Evaluate(), SSAGES::MockCV::Initialize(), SSAGES::RMSDCV::Initialize(), SSAGES::FiniteTempString::PostIntegration(), SSAGES::Swarm::PostIntegration(), SSAGES::ABF::PreSimulation(), SSAGES::ForwardFlux::ReadFFSConfiguration(), and SSAGES::ForwardFlux::WriteFFSConfiguration().
 { return positions_; }
std::vector<Vector3>& SSAGES::Snapshot::GetPositions () inline
Access the particle positions.
Returns
List of particle positions
Definition at line 330 of file Snapshot.h.
References positions_.
         {
             changed_ = true;
             return positions_;
         }
double SSAGES::Snapshot::Getqqrd2e () const inline
Get qqrd2e value.
Returns
Value of qqrd2e.
Definition at line 179 of file Snapshot.h.
References qqrd2e_.
 { return qqrd2e_; }
const std::vector<std::vector<double> >& SSAGES::Snapshot::GetSigmas () const inline
Access the atom sigmas.
Returns
List of atom sigmas
Definition at line 674 of file Snapshot.h.
References sigma_.
 { return sigma_; }
std::vector<std::vector<double> >& SSAGES::Snapshot::GetSigmas () inline
Access the atom sigmas.
Returns
List of atom sigmas
Definition at line 677 of file Snapshot.h.
References sigma_.
         {
             changed_ = true;
             return sigma_;
         }
const std::string& SSAGES::Snapshot::GetSnapshotID () const inline
Access the snapshot ID.
Returns
Snapshot ID
Definition at line 687 of file Snapshot.h.
References ID_.
 { return ID_; }
std::string& SSAGES::Snapshot::GetSnapshotID () inline
Access the snapshot ID.
Returns
Snapshot ID
Definition at line 690 of file Snapshot.h.
References ID_.
         {
             changed_ = true;
             return ID_;
         }
size_t SSAGES::Snapshot::GetTargetIterations () const inline
Get target iterations.
Returns
Target Iterations
Definition at line 113 of file Snapshot.h.
References targetiter_.
Referenced by SSAGES::Meta::PreSimulation().
 {return targetiter_; }
double SSAGES::Snapshot::GetTemperature () const inline
Get current temperature.
Returns
System temperature
Definition at line 119 of file Snapshot.h.
References temperature_.
 {return temperature_; }
const std::vector<Vector3>& SSAGES::Snapshot::GetVelocities () const inline
Access the particle velocities.
Returns
List of particle velocities
Definition at line 353 of file Snapshot.h.
References velocities_.
Referenced by SSAGES::ForwardFlux::AppendTrajectoryFile(), SSAGES::Swarm::PostIntegration(), SSAGES::ABF::PostIntegration(), SSAGES::ForwardFlux::ReadFFSConfiguration(), and SSAGES::ForwardFlux::WriteFFSConfiguration().
 { return velocities_; }
std::vector<Vector3>& SSAGES::Snapshot::GetVelocities () inline
Access the particle velocities.
Returns
List of particle velocities
Definition at line 356 of file Snapshot.h.
References velocities_.
         {
             changed_ = true;
             return velocities_;
         }
const Matrix3& SSAGES::Snapshot::GetVirial () const inline
Get box virial.
Returns
Virial tensor of the simulation box.
Definition at line 137 of file Snapshot.h.
References virial_.
Referenced by SSAGES::ANN::PostIntegration(), SSAGES::Umbrella::PostIntegration(), SSAGES::Meta::PostIntegration(), and SSAGES::BFS::PostIntegration().
 { return virial_; }
Matrix3& SSAGES::Snapshot::GetVirial () inline
Get box virial.
Returns
Virial tensor of the simulation box.
Definition at line 143 of file Snapshot.h.
References virial_.
 { return virial_; }
double SSAGES::Snapshot::GetVolume () const inline
Get system volume.
Returns
Volume of the current simulation box
Definition at line 161 of file Snapshot.h.
Referenced by SSAGES::BoxVolumeCV::Evaluate().
 { return H_.determinant(); }
unsigned SSAGES::Snapshot::GetWalkerID () const inline
Get walker ID.
Returns
ID of the Walker
Definition at line 197 of file Snapshot.h.
References wid_.
Referenced by SSAGES::StringMethod::PreSimulation(), and SSAGES::BFS::PreSimulation().
 { return wid_; }
bool SSAGES::Snapshot::HasChanged () const inline
Query if Snapshot was modified.
Returns
True if Snapshot was modified, else return False
Definition at line 700 of file Snapshot.h.
References changed_.
Referenced by SSAGES::Hook::PostIntegrationHook(), SSAGES::Hook::PostSimulationHook(), and SSAGES::Hook::PreSimulationHook().
 { return changed_; }
const Bool3& SSAGES::Snapshot::IsPeriodic () const inline
Get periodicity of three dimensions.
Returns
Three dimensional boolean containing periodicity of each dimension.
Definition at line 155 of file Snapshot.h.
References isperiodic_.
 {return isperiodic_; }
Vector3 SSAGES::Snapshot::ScaleVector (const Vector3 & v) const inline
Scale a vector into fractional coordinates.
Parameters
v Vector of interest
Returns
Scaled vector in fractional coordinates
Definition at line 396 of file Snapshot.h.
References origin_.
         {
             return Hinv_*(v-origin_);
         }
std::vector<int> SSAGES::Snapshot::SerializeIDs () inline
Return the serialized IDs across all local cores.
Returns
IDs across all local cores.
Definition at line 783 of file Snapshot.h.
References comm_, and nlocal_.
Referenced by SSAGES::FiniteTempString::PostIntegration(), and SSAGES::Swarm::PostIntegration().
         {
             std::vector<int> mcounts(comm_.size(), 0);
             std::vector<int> mdispls(comm_.size()+1, 0);
             mcounts[comm_.rank()] = nlocal_;
             // Reduce counts.
             MPI_Allreduce(MPI_IN_PLACE, mcounts.data(), mcounts.size(), MPI_INT, MPI_SUM, comm_);
             // Compute displacements.
             std::partial_sum(mcounts.begin(), mcounts.end(), mdispls.begin() + 1);
             // Re-size receiving vectors.
             std::vector<int> IDs;
             IDs.resize(mdispls.back(), 0);
             // All-gather data.
             MPI_Allgatherv(atomids_.data(), atomids_.size(), MPI_INT, IDs.data(), mcounts.data(), mdispls.data(), MPI_INT, comm_);
             return IDs;
         }
std::vector<double> SSAGES::Snapshot::SerializePositions () inline
Return the serialized positions across all local cores.
Returns
Positions across all local cores.
Definition at line 712 of file Snapshot.h.
References comm_, and nlocal_.
Referenced by SSAGES::FiniteTempString::PostIntegration(), and SSAGES::Swarm::PostIntegration().
         {
             std::vector<int> pcounts(comm_.size(), 0);
             std::vector<int> pdispls(comm_.size()+1, 0);
             pcounts[comm_.rank()] = 3*nlocal_;
             // Reduce counts.
             MPI_Allreduce(MPI_IN_PLACE, pcounts.data(), pcounts.size(), MPI_INT, MPI_SUM, comm_);
             // Compute displacements.
             std::partial_sum(pcounts.begin(), pcounts.end(), pdispls.begin() + 1);
             // Re-size receiving vectors.
             std::vector<double> positions;
             positions.resize(pdispls.back(), 0);
             std::vector<double> ptemp;
             for(auto& p : positions_)
             {
                 ptemp.push_back(p[0]);
                 ptemp.push_back(p[1]);
                 ptemp.push_back(p[2]);
             }
             // All-gather data.
             MPI_Allgatherv(ptemp.data(), ptemp.size(), MPI_DOUBLE, positions.data(), pcounts.data(), pdispls.data(), MPI_DOUBLE, comm_);
             return positions;
         }
std::vector<double> SSAGES::Snapshot::SerializeVelocities () inline
Return the serialized velocities across all local cores.
Returns
Velocities across all local cores.
Definition at line 748 of file Snapshot.h.
References comm_, and nlocal_.
Referenced by SSAGES::Swarm::PostIntegration().
         {
             std::vector<int> vcounts(comm_.size(), 0);
             std::vector<int> vdispls(comm_.size()+1, 0);
             vcounts[comm_.rank()] = 3*nlocal_;
             // Reduce counts.
             MPI_Allreduce(MPI_IN_PLACE, vcounts.data(), vcounts.size(), MPI_INT, MPI_SUM, comm_);
             // Compute displacements.
             std::partial_sum(vcounts.begin(), vcounts.end(), vdispls.begin() + 1);
             // Re-size receiving vectors.
             std::vector<double> velocities;
             velocities.resize(vdispls.back(), 0);
             std::vector<double> vtemp;
             for(auto& v : velocities_)
             {
                 vtemp.push_back(v[0]);
                 vtemp.push_back(v[1]);
                 vtemp.push_back(v[2]);
             }
             // All-gather data.
             MPI_Allgatherv(vtemp.data(), vtemp.size(), MPI_DOUBLE, velocities.data(), vcounts.data(), vdispls.data(), MPI_DOUBLE, comm_);
             return velocities;
         }
void SSAGES::Snapshot::SetDielectric (double dielectric) inline
Set the dielectric constant.
Parameters
dielectric Value for the dielectric constant.
Definition at line 301 of file Snapshot.h.
         {
             dielectric_ = dielectric;
             changed_ = true;
         }
void SSAGES::Snapshot::SetEnergy (double energy) inline
Change the energy.
Parameters
energy New value for the energy
Definition at line 240 of file Snapshot.h.
         {
             energy_ = energy;
             changed_ = true;
         }
void SSAGES::Snapshot::SetHMatrix (const Matrix3 & hmat) inline
Change the Box H-matrix.
Parameters
hmat New H-matrix for the system
Definition at line 250 of file Snapshot.h.
         {
             H_ = hmat;
             Hinv_ = hmat.inverse();
             changed_ = true;
         }
void SSAGES::Snapshot::SetIteration (size_t iteration) inline
Set the iteration.
Parameters
iteration New value for the iteration
Definition at line 210 of file Snapshot.h.
         {
             iteration_ = iteration;
             changed_ = true;
         }
void SSAGES::Snapshot::SetKb (double kb) inline
Change the kb.
Parameters
kb New value for the kb
Definition at line 291 of file Snapshot.h.
         {
             kb_ = kb;
             changed_ = true;
         }
void SSAGES::Snapshot::SetNumAtoms (unsigned int natoms) inline
Set number of atoms in this snapshot.
Parameters
natoms Number of atoms in this snapshot
Definition at line 321 of file Snapshot.h.
 { nlocal_ = natoms; }
void SSAGES::Snapshot::SetOrigin (const Vector3 & origin) inline
Change the box origin.
Parameters
origin New origin for the system
Definition at line 271 of file Snapshot.h.
         {
             origin_ = origin;
             changed_ = true;
         }
void SSAGES::Snapshot::SetPeriodicity (const Bool3 & isperiodic) inline
Change the periodicity of the system.
Parameters
isperiodic Periodicity of three dimensions
Definition at line 281 of file Snapshot.h.
         {
             isperiodic_ = isperiodic;
             changed_ = true;
         }
void SSAGES::Snapshot::Setqqrd2e (double qqrd2e) inline
Set the value for qqrd2e.
Parameters
qqrd2e Value for qqrd2e.
Definition at line 311 of file Snapshot.h.
         {
             qqrd2e_ = qqrd2e;
             changed_ = true;
         }
void SSAGES::Snapshot::SetTargetIterations (int target) inline
Set target iterations.
Parameters
target New value for target iterations
Definition at line 220 of file Snapshot.h.
         {
             targetiter_ = target;
             changed_ = true;
         }
void SSAGES::Snapshot::SetTemperature (double temperature) inline
Change the temperature.
Parameters
temperature New value for the temperature
Definition at line 230 of file Snapshot.h.
         {
             temperature_ = temperature;
             changed_ = true;
         }
void SSAGES::Snapshot::SetVirial (const Matrix3 & virial) inline
Change the box virial.
Parameters
virial New virial tensor for the system.
Definition at line 261 of file Snapshot.h.
         {
             virial_ = virial;
             changed_ = true;
         }
double SSAGES::Snapshot::TotalMass (const Label & indices) const inline
Compute the total mass of a group of particles based on index.
Parameters
indices IDs of particles of interest.
Returns
double Total mass of particles.
Note
This function reduces the mass across the communicator associated with the snapshot.
Definition at line 455 of file Snapshot.h.
Referenced by CenterOfMass(), SSAGES::ParticleCoordinateCV::Evaluate(), SSAGES::ParticlePositionCV::Evaluate(), SSAGES::ParticleSeparationCV::Evaluate(), SSAGES::GyrationTensorCV::Evaluate(), and SSAGES::RouseModeCV::setMasses().
         {
             auto mtot = 0.;
             for(auto& i : indices)
                 mtot += masses_[i];
             MPI_Allreduce(MPI_IN_PLACE, &mtot, 1, MPI_DOUBLE, MPI_SUM, comm_);
             return mtot;
         }
std::vector<Vector3> SSAGES::Snapshot::UnwrapPositions (const Label & indices) const inline
Unwrap the particle positions, based on first position.
Parameters
indices IDs of particles of interest.
Returns
Unwrapped particle positions.
Note
This function unwraps positions in reference to the first position.
Each processor passes in the local indices of the atoms of interest and this function will collect the data and return unwrapped coordinates.
Definition at line 549 of file Snapshot.h.
References ApplyMinimumImage(), and comm_.
         {
             // Store coordinates in vectors to gather.
             std::vector<Vector3> upos;
             std::vector<double> pos, gpos;
             std::vector<int> pcounts(comm_.size(), 0);
             std::vector<int> pdispls(comm_.size()+1, 0);
             pcounts[comm_.rank()] = 3*indices.size();
             // Reduce counts.
             MPI_Allreduce(MPI_IN_PLACE, pcounts.data(), pcounts.size(), MPI_INT, MPI_SUM, comm_);
             // Compute displacements.
             std::partial_sum(pcounts.begin(), pcounts.end(), pdispls.begin() + 1);
             // Fill up position vectors.
             for(auto& idx : indices)
             {
                 auto& p = positions_[idx];
                 pos.push_back(p[0]);
                 pos.push_back(p[1]);
                 pos.push_back(p[2]);
             }
             // Re-size receiving vectors.
             gpos.resize(pdispls.back(), 0);
             // All-gather data.
             MPI_Allgatherv(pos.data(), pos.size(), MPI_DOUBLE, gpos.data(), pcounts.data(), pdispls.data(), MPI_DOUBLE, comm_);
             // Loop through atoms and unwrap positions.
             // We march linearly through list and find nearest image
             // to each successive particle to properly unwrap object.
             Vector3 ppos = {gpos[0], gpos[1], gpos[2]}; // Previous unwrapped position.
             Vector3 cpos = ppos;
             upos.push_back(cpos); // Used as reference position.
             for(size_t i = 1; i < gpos.size(); ++i)
             {
                 cpos = {gpos[3*i], gpos[3*i+1], gpos[3*i+2]};
                 cpos = ApplyMinimumImage(cpos - ppos) + ppos;
                 upos.push_back(cpos);
                 ppos = cpos;
             }
             return upos;
         }
Vector3 SSAGES::Snapshot::UnwrapVector (const Vector3 & v, const Integer3 & image) const inline
Unwrap a vector's real coordinates according to its image replica count.
Parameters
v Vector of interest
image Integer vector representing mirror images in the three dimensions.
Returns
Vector3 Unwrapped vector in real coordinates. This function takes a set of (wrapped) coordinates and returns the unwrapped coordinates.
Note
This function does not require the initial coordinates to be within the simulation box.
Definition at line 413 of file Snapshot.h.
Referenced by SSAGES::RMSDCV::Evaluate().
         {
             return H_*image.cast<double>()+v;
         }
The documentation for this class was generated from the following file:
/home/cody/SSAGES-public/src/Snapshot.h