SSAGES: SSAGES::JSONLoader Class Reference
SSAGES::JSONLoader Class Reference
Core
Class for loading JSON content from files.
#include <JSONLoader.h>
Public Member Functions
JSONLoader ()
Constructor.
Json::Value LoadFile (const std::string &filename, boost::mpi::communicator &world)
Load file and return JSON tree.
Private Attributes
std::vector< std::unique_ptr
< JSONLoaderPlugin > > plugins_
List of plugins.
Detailed Description
Class for loading JSON content from files.
Definition at line 42 of file JSONLoader.h.
Constructor & Destructor Documentation
SSAGES::JSONLoader::JSONLoader () inline
Constructor.
The constructer automatically inserts the IncludePlugin into the list of plugins.
Definition at line 54 of file JSONLoader.h.
References plugins_.
                      : plugins_(0)
         {
             plugins_.push_back(std::unique_ptr<JSONLoaderPlugin>(new IncludePlugin()));
         }
Member Function Documentation
Json::Value SSAGES::JSONLoader::LoadFile (const std::string & filename, boost::mpi::communicator & world) inline
Load file and return JSON tree.
Parameters
filename Name of the JSON file to load.
world MPI global communicator.
Returns
JSON Value containing the contents of the file.
This function loads JSON content from a given file. For each plugin in plugins_ the filter defined with this plugin will be applied to the contents loaded from the file.
Definition at line 69 of file JSONLoader.h.
References SSAGES::GetFileContents(), SSAGES::GetFilePath(), and plugins_.
Referenced by SSAGES::Simulation::ReadJSON().
         {
             std::string contents, path;
             if(world.rank() == 0)
             {
                 contents = GetFileContents(filename.c_str());
                 path = GetFilePath(filename);
             }
             mpi::broadcast(world, contents, 0);
             mpi::broadcast(world, path, 0);
             for(auto& plugin : plugins_)
                 plugin->ApplyFilter(contents, path);
             // Read JSON.
             Json::Reader reader;
             Json::Value root;
             if(!reader.parse(contents, root))
                 throw std::invalid_argument(
                     filename + ": " + reader.getFormattedErrorMessages()
                 );
             return root;
         }
The documentation for this class was generated from the following file:
/home/cody/SSAGES/src/JSON/JSONLoader.h