SSAGES: Json::ObjectRequirement Class Reference
Json::ObjectRequirement Class Reference
Requirements on an object.
#include <ObjectRequirement.h>
Public Member Functions
ObjectRequirement ()
Constructor.
~ObjectRequirement ()
Destructor.
virtual void ClearErrors () override
Clear errors on all Requirements.
virtual void ClearNotices () override
Clear notices on all Requirements.
virtual void Reset () override
Reset Requirement.
virtual void Parse (Value json, const std::string &path) override
Parse JSON value to generate Requirement(s).
virtual void Validate (const Value &json, const std::string &path) override
Validate JSON value.
Public Member Functions inherited from Json::Requirement
bool HasErrors ()
Check if errors have occured.
std::vector< std::string > GetErrors ()
Get list of error messages.
virtual bool HasNotices ()
Check if notices have been queued.
std::vector< std::string > GetNotices ()
Get list of notices.
virtual ~Requirement ()
Destructor.
Private Attributes
std::map< std::string, std::unique_ptr< Requirement > > properties_
Map of properties the object needs to have.
std::map< std::string, std::unique_ptr< Requirement > > patternProps_
Map of patterns the object needs to match.
RequireList extended_
List of requirements.
std::unique_ptr< DependencyRequirement > dependency_
Dependency requirement.
std::vector< std::string > required_
List of requirements.
bool moreProps_
If True, more properties need to be set.
bool setMin_
If True lower bound is active.
bool setMax_
If True upper bound is active.
unsigned int min_
Lower bound.
unsigned int max_
Upper bound.
Additional Inherited Members
Protected Member Functions inherited from Json::Requirement
void PushError (const std::string &error)
Add error to list of error messages.
void PushNotice (const std::string &notice)
Add message to list of notices.
Detailed Description
Requirements on an object.
Definition at line 46 of file ObjectRequirement.h.
Member Function Documentation
Parse()
virtual void Json::ObjectRequirement::Parse (Value json, const std::string & path) inline override virtual
Parse JSON value to generate Requirement(s).
Parameters
json JSON input value.
path Path for JSON path specification.
Implements Json::Requirement.
Definition at line 142 of file ObjectRequirement.h.
         {
             Reset();
             RequirementLoader loader;
             // Additional properties.
             if(json.isMember("additionalProperties"))
             {
                 if(json["additionalProperties"].isBool())
                     moreProps_ = json["additionalProperties"].asBool();
                 else if(json["additionalProperties"].isObject())
                     json["properties"]["additionalProperties"] = json["additionalProperties"];
             }
             // properties.
             if(json.isMember("properties") && json["properties"].isObject())
             {
                 auto& props = json["properties"];
                 auto names = props.getMemberNames();
                 int i = 0;
                 for(auto& prop : props)
                 {
                     if(auto property = loader.LoadRequirement(prop))
                     {
                         properties_[names[i]] = std::move(property);
                         properties_[names[i]]->Parse(prop, path + "/" + names[i]);
                     }
                     ++i;
                 }
             }
             // Pattern properties. TODO: eliminate redundant code!!
             if(json.isMember("patternProperties") && json["patternProperties"].isObject())
             {
                 auto& props = json["patternProperties"];
                 auto names = props.getMemberNames();
                 int i = 0;
                 for(auto& prop : props)
                 {
                     if(prop.isObject())
                     {
                         if(auto property = loader.LoadRequirement(prop))
{
                             patternProps_[names[i]] = std::move(property);
                             patternProps_[names[i]]->Parse(prop, path + "/" + names[i]);
                         }
                     }
                     ++i;
                 }
             }
             // Required properties.
             if(json.isMember("required") && json["required"].isArray())
             {
                 for(auto& requirement : json["required"])
                     required_.push_back(requirement.asString());
             }
             // Min property count.
             if(json.isMember("minProperties") && json["minProperties"].isUInt())
             {
                 setMin_ = true;
                 min_ = json["minProperties"].asInt();
             }
             // Max property count.
             if(json.isMember("maxProperties") && json["maxProperties"].isUInt())
             {
                 setMax_ = true;
                 max_ = json["maxProperties"].asInt();
             }
             // Dependencies
             if(json.isMember("dependencies") && json["dependencies"].isObject())
             {
                 dependency_ = std::unique_ptr<DependencyRequirement>(new DependencyRequirement());
                 dependency_->Parse(json["dependencies"], path);
             }
             // Extended properties.
             for(auto& prop : json)
             {
                 if(auto req  = loader.LoadExtended(prop))
                 {
                     extended_.push_back(std::move(req));
                     extended_.back()->Parse(prop, path);
                 }
             }
         }
References dependency_, extended_, Json::RequirementLoader::LoadExtended(), Json::RequirementLoader::LoadRequirement(), max_, min_, moreProps_, patternProps_, properties_, required_, Reset(), setMax_, and setMin_.
Referenced by SSAGES::BoxVolumeCV::Build(), SSAGES::GaussianPK::Build(), SSAGES::Logger::Build(), SSAGES::AngleCV::Build(), SSAGES::ParticlePositionCV::Build(), SSAGES::RationalSwitchPK::Build(), SSAGES::Umbrella::Build(), SSAGES::ParticleSeparationCV::Build(), SSAGES::ParticleCoordinateCV::Build(), SSAGES::ResourceHandler::Build(), SSAGES::Meta::Build(), SSAGES::RouseModeCV::Build(), SSAGES::PairwiseCV::Build(), SSAGES::ANN::Build(), SSAGES::StringMethod::Build(), SSAGES::TorsionalCV::Build(), SSAGES::AlphaRMSDCV::Build(), SSAGES::BFS::Build(), SSAGES::GyrationTensorCV::Build(), SSAGES::AntiBetaRMSDCV::Build(), SSAGES::ABF::Build(), SSAGES::ParallelBetaRMSDCV::Build(), SSAGES::Chebyshev::Build(), SSAGES::Legendre::Build(), SSAGES::Fourier::Build(), SSAGES::ForwardFlux::Build(), SSAGES::Grid< Eigen::VectorXd >::BuildGrid(), and SSAGES::Method::BuildMethod().
Validate()
virtual void Json::ObjectRequirement::Validate (const Value & json, const std::string & path) inline override virtual
Validate JSON value.
Parameters
json JSON value to be validated.
path Path for JSON path specification.
Implements Json::Requirement.
Definition at line 239 of file ObjectRequirement.h.
         {
             if(!json.isObject())
             {
                 PushError(path + ": Must be of type \"object\"");
                 return;
             }
             if(setMin_ && json.size() < min_)
                 PushError(path + ": Object must contain at least " + std::to_string(min_) + " properties");
             if(setMax_ && json.size() > max_)
                 PushError(path + ": Object must contain at most " + std::to_string(max_) + " properties");
             // Check dependencies.
             if(dependency_ != nullptr)
             {
                 dependency_->Validate(json, path);
                 if(dependency_->HasErrors())
                     for(const auto& error : dependency_->GetErrors())
                         PushError(error);
                 if(dependency_->HasNotices())
                     for(const auto& notice : dependency_->GetNotices())
                         PushNotice(notice);
             }
             // Copy so we can pop items off the list.
             auto rprops = required_;
             auto names = json.getMemberNames();
             int i = 0;
             for(auto& prop : json)
             {
                 Requirement* requirement = nullptr;
                 auto it = properties_.find(names[i]);
                 if(it != properties_.end())
                     requirement = it->second.get();
                 else if(patternProps_.size() != 0)
                 {
                     for(auto& pattern : patternProps_)
                     {
                         auto regex = std::regex(pattern.first, std::regex::ECMAScript);
                         if(std::regex_search(names[i], regex))
                             requirement = pattern.second.get();
                     }
                 }
                 if(!requirement && properties_.find("additionalProperties") != properties_.end())
                     requirement = properties_["additionalProperties"].get();
                 if(requirement)
                 {
                     requirement->Validate(prop, path + "/" + names[i]);
                     if(requirement->HasErrors())
                         for(const auto& error : requirement->GetErrors())
                             PushError(error);
                     if(requirement->HasNotices())
                         for(const auto& notice : requirement->GetNotices())
                             PushNotice(notice);
                 }
                 else if(!moreProps_)
                     PushError(path + ": Invalid property \"" + names[i] + "\" specified");
                 rprops.erase(std::remove(rprops.begin(), rprops.end(),names[i]),rprops.end());
                 ++i;
             }
             if(required_.size() && rprops.size() != 0)
             {
                 std::string msg = std::accumulate(rprops.begin(), rprops.end(), std::string(),
                     [](const std::string& a, const std::string& b) -> std::string {
                         return a + (a.length() > 0 ? ", " : "") + b;
                 });
                 PushError(path + ": Missing properties: " + msg);
             }
             // Validate extended.
             for(auto& requirement : extended_)
             {
                 requirement->Validate(json, path);
                 if(requirement->HasErrors())
                         for(const auto& error : requirement->GetErrors())
                             PushError(error);
                 if(requirement->HasNotices())
                     for(const auto& notice : requirement->GetNotices())
                         PushNotice(notice);
             }
         }
References dependency_, extended_, Json::Requirement::GetErrors(), Json::Requirement::GetNotices(), Json::Requirement::HasErrors(), Json::Requirement::HasNotices(), max_, min_, moreProps_, patternProps_, properties_, Json::Requirement::PushError(), Json::Requirement::PushNotice(), required_, setMax_, setMin_, and Json::Requirement::Validate().
Referenced by SSAGES::BoxVolumeCV::Build(), SSAGES::GaussianPK::Build(), SSAGES::Logger::Build(), SSAGES::AngleCV::Build(), SSAGES::ParticlePositionCV::Build(), SSAGES::RationalSwitchPK::Build(), SSAGES::Umbrella::Build(), SSAGES::ParticleSeparationCV::Build(), SSAGES::ParticleCoordinateCV::Build(), SSAGES::ResourceHandler::Build(), SSAGES::Meta::Build(), SSAGES::RouseModeCV::Build(), SSAGES::PairwiseCV::Build(), SSAGES::ANN::Build(), SSAGES::StringMethod::Build(), SSAGES::TorsionalCV::Build(), SSAGES::AlphaRMSDCV::Build(), SSAGES::BFS::Build(), SSAGES::GyrationTensorCV::Build(), SSAGES::AntiBetaRMSDCV::Build(), SSAGES::ABF::Build(), SSAGES::ParallelBetaRMSDCV::Build(), SSAGES::Chebyshev::Build(), SSAGES::Legendre::Build(), SSAGES::Fourier::Build(), SSAGES::ForwardFlux::Build(), SSAGES::Grid< Eigen::VectorXd >::BuildGrid(), and SSAGES::Method::BuildMethod().
The documentation for this class was generated from the following file:
/home/michael/development/SSAGES/src/Validator/ObjectRequirement.h