SSAGES: SSAGES::PairwiseCV Class Reference
SSAGES::PairwiseCV Class Reference
CVs
Generalized collective variable based on pairwise properties of atoms.
#include <PairwiseCV.h>
Public Member Functions
PairwiseCV (const Label &group1, const Label &group2, PairwiseKernel *pk)
Constructor.
void Initialize (const Snapshot &snapshot) override
Initialize necessary variables.
void Evaluate (const Snapshot &snapshot) override
Evaluate the CV.
~PairwiseCV ()
Destructor.
Public Member Functions inherited from SSAGES::CollectiveVariable
CollectiveVariable ()
Constructor.
virtual ~CollectiveVariable ()
Destructor.
virtual void Initialize (const class Snapshot &)
Initialize CV.
virtual void Evaluate (const class Snapshot &)=0
Evaluate CV.
double GetValue () const
Get current value of the CV.
virtual double GetMinimumImage (double) const
Returns the minimum image of a CV based on the input location.
virtual double GetPeriodicValue (double location) const
Apply periodic boundaries to a given value.
const std::vector< Vector3 > & GetGradient () const
Get current gradient of the CV.
const Matrix3 & GetBoxGradient () const
Get gradient contribution to box.
const std::array< double, 2 > & GetBoundaries ()
Get CV boundaries.
virtual double GetDifference (double location) const
Static Public Member Functions
static PairwiseCV * Build (const Json::Value &json, const std::string &path)
Set up collective variable.
Static Public Member Functions inherited from SSAGES::CollectiveVariable
static CollectiveVariable * BuildCV (const Json::Value &json, const std::string &path)
Set up collective variable.
Private Attributes
Label group1_
IDs of the first group of atoms.
Label group2_
IDs of the second group of atoms.
PairwiseKernel * pk_
Pairwise kernel function used for CV.
Additional Inherited Members
Protected Attributes inherited from SSAGES::CollectiveVariable
std::vector< Vector3 > grad_
Gradient vector dCv/dxi.
Matrix3 boxgrad_
Gradient w.r.t box vectors dCv/dHij.
double val_
Current value of CV.
std::array< double, 2 > bounds_
Bounds on CV.
Detailed Description
Generalized collective variable based on pairwise properties of atoms.
Collective variable on pairwise properties between two groups of atoms. To ensure generality of usage, there are various pairwise kernel functions from which to choose.
Definition at line 40 of file PairwiseCV.h.
Constructor & Destructor Documentation
PairwiseCV()
SSAGES::PairwiseCV::PairwiseCV (const Label & group1, const Label & group2, PairwiseKernel * pk) inline
Constructor.
Parameters
group1 IDs of the first group of atoms.
group2 IDs of the second group of atoms.
pk pairwise kernel (function) to use.
Construct a PairwiseCV.
Definition at line 57 of file PairwiseCV.h.
                                                                                  :
         group1_(group1), group2_(group2), pk_(pk)
         {
         }
Referenced by Build().
Member Function Documentation
Build()
static PairwiseCV* SSAGES::PairwiseCV::Build (const Json::Value & json, const std::string & path) inline static
Set up collective variable.
Parameters
json JSON input value.
path Path for JSON path specification.
Returns
Pointer to the CV built by this function. nullptr in case of unknown error.
Builds a CV from a JSON node. Returns a pointer to the built cv. If an unknown error is encountered, this function will return a nullptr, but generally it will throw a BuildException on failure.
Warning
Object lifetime is the caller's responsibility.
Definition at line 200 of file PairwiseCV.h.
         {
             Json::ObjectRequirement validator;
             Json::Value schema;
             Json::CharReaderBuilder rbuilder;
             Json::CharReader* reader = rbuilder.newCharReader();
             reader->parse(JsonSchema::PairwiseCV.c_str(),
                           JsonSchema::PairwiseCV.c_str() + JsonSchema::PairwiseCV.size(),
                           &schema, nullptr);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             std::vector<int> group1, group2;
             for(auto& s : json["group1"])
                 group1.push_back(s.asInt());
             for(auto& s : json["group2"])
                 group2.push_back(s.asInt());
             return new PairwiseCV(group1, group2, PairwiseKernel::Build(json["kernel"], path));
         }
References SSAGES::PairwiseKernel::Build(), Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), PairwiseCV(), Json::ObjectRequirement::Parse(), and Json::ObjectRequirement::Validate().
Referenced by SSAGES::CollectiveVariable::BuildCV().
Evaluate()
void SSAGES::PairwiseCV::Evaluate (const Snapshot & snapshot) inline override
Evaluate the CV.
Parameters
snapshot Current simulation snapshot.
Definition at line 112 of file PairwiseCV.h.
         {
             // Get local atom indices.
             std::vector<int> idx1, idx2;
             snapshot.GetLocalIndices(group1_, &idx1);
             snapshot.GetLocalIndices(group2_, &idx2);
             // Get data from snapshot.
             auto n = snapshot.GetNumAtoms();
             auto& atomids = snapshot.GetAtomIDs();
             auto& positions = snapshot.GetPositions();
             auto& comm = snapshot.GetCommunicator();
             // Initialize gradient.
             std::fill(grad_.begin(), grad_.end(), Vector3{0,0,0});
             grad_.resize(n, Vector3{0,0,0});
             boxgrad_ = Matrix3::Zero();
             // Fill eigen matrix with coordinate data.
             std::vector<double> pos1(3*idx1.size()), pos2(3*idx2.size());
             std::vector<int> id1(idx1.size()), id2(idx2.size());
             for(size_t i = 0; i < idx1.size(); ++i)
             {
                 pos1[3*i+0] = positions[idx1[i]][0];
                 pos1[3*i+1] = positions[idx1[i]][1];
                 pos1[3*i+2] = positions[idx1[i]][2];
                 id1[i] = atomids[idx1[i]];
             }
             for(size_t i = 0; i < idx2.size(); ++i)
             {
                 pos2[3*i+0] = positions[idx2[i]][0];
                 pos2[3*i+1] = positions[idx2[i]][1];
                 pos2[3*i+2] = positions[idx2[i]][2];
                 id2[i] = atomids[idx2[i]];
             }
             // Gather across all procs.
             pos1 = mxx::allgatherv(pos1.data(), pos1.size(), comm);
             pos2 = mxx::allgatherv(pos2.data(), pos2.size(), comm);
             id1 = mxx::allgatherv(id1.data(), id1.size(), comm);
             id2 = mxx::allgatherv(id2.data(), id2.size(), comm);
             // Create Eigen map for ease of use.
             using Map = Eigen::Map<Eigen::Matrix<double, Eigen::Dynamic, 3, Eigen::RowMajor>>;
             Map gpos1(pos1.data(), group1_.size(), 3), gpos2(pos2.data(), group2_.size(), 3);
             val_ = 0;
             double df = 0.;
             // Compute gradient and value.
             for(size_t i = 0; i < group1_.size(); ++i)
             {
                 auto t1 = id1[i];
                 const auto& pi = gpos1.row(i);
                 for(size_t j = 0; j < group2_.size(); ++j)
                 {
                     auto t2 = id2[j];
                     const auto& pj = gpos2.row(j);
                     // Skip identical pairs.
                     if(t1 == t2)
                         continue;
                     // Compute distance and pairwise function.
                     Vector3 rij = pi - pj;
                     snapshot.ApplyMinimumImage(&rij);
                     auto r = rij.norm();
                     val_ +=  pk_->Evaluate(r, df);
                     // Get local indices and sum gradients.
                     auto lid1 = snapshot.GetLocalIndex(t1);
                     if(lid1 != -1)
                         grad_[lid1] += df*rij/r;
                     auto lid2 = snapshot.GetLocalIndex(t2);
                     if(lid2 != -1)
                         grad_[lid2] -= df*rij/r;
                     // Only sum box gradient on a single proc.
                     if(comm.rank() == 0)
                         boxgrad_ += df*rij/r*rij.transpose();
                 }
             }
         }
References SSAGES::Snapshot::ApplyMinimumImage(), SSAGES::CollectiveVariable::boxgrad_, SSAGES::PairwiseKernel::Evaluate(), SSAGES::Snapshot::GetAtomIDs(), SSAGES::Snapshot::GetCommunicator(), SSAGES::Snapshot::GetLocalIndex(), SSAGES::Snapshot::GetLocalIndices(), SSAGES::Snapshot::GetNumAtoms(), SSAGES::Snapshot::GetPositions(), SSAGES::CollectiveVariable::grad_, group1_, group2_, pk_, and SSAGES::CollectiveVariable::val_.
Initialize()
void SSAGES::PairwiseCV::Initialize (const Snapshot & snapshot) inline override
Initialize necessary variables.
Parameters
snapshot Current simulation snapshot.
Definition at line 66 of file PairwiseCV.h.
         {
             using std::to_string;
             auto n1 = group1_.size(), n2 = group2_.size();
             // Make sure atom ID's are on at least one processor.
             std::vector<int> found1(n1, 0), found2(n2, 0);
             for(size_t i = 0; i < n1; ++i)
             {
                 if(snapshot.GetLocalIndex(group1_[i]) != -1)
                     found1[i] = 1;
             }
             for(size_t i = 0; i < n2; ++i)
             {
                 if(snapshot.GetLocalIndex(group2_[i]) != -1)
                     found2[i] = 1;
             }
             MPI_Allreduce(MPI_IN_PLACE, found1.data(), n1, MPI_INT, MPI_SUM, snapshot.GetCommunicator());
             MPI_Allreduce(MPI_IN_PLACE, found2.data(), n2, MPI_INT, MPI_SUM, snapshot.GetCommunicator());
             unsigned ntot1 = std::accumulate(found1.begin(), found1.end(), 0, std::plus<int>());
             unsigned ntot2 = std::accumulate(found2.begin(), found2.end(), 0, std::plus<int>());
             if(ntot1 != n1)
                 throw BuildException({
                     "Pairwise: Expected to find " +
                     to_string(n1) +
                     " atoms in group 1, but only found " +
                     to_string(ntot1) + "."
                 });
             if(ntot2 != n2)
                 throw BuildException({
                     "Pairwise: Expected to find " +
                     to_string(n2) +
                     " atoms in group 2, but only found " +
                     to_string(ntot2) + "."
                 });
         }
References SSAGES::Snapshot::GetCommunicator(), SSAGES::Snapshot::GetLocalIndex(), group1_, and group2_.
The documentation for this class was generated from the following file:
/home/michael/development/SSAGES/src/CVs/PairwiseCV.h