SSAGES: SSAGES::Histogram< T > Class Template Reference
SSAGES::Histogram< T > Class Template Reference
Core
Basic Histogram.
#include <Histogram.h>
Classes
class HistIterator
Custom Iterator.
Public Types
typedef HistIterator< T > iterator
Custom iterator over a histogram.
typedef HistIterator< const T > const_iterator
Custom constant iterator over a histogram.
Public Member Functions
Histogram (std::vector< int > numPoints, std::vector< double > lower, std::vector< double > upper, std::vector< bool > isPeriodic)
Constructor.
void Serialize (Json::Value &json) const override
Serialize the class.
iterator begin ()
Return iterator at first bin of histogram.
iterator end ()
Return iterator after last valid bin.
std::vector< T >::const_iterator begin () const
Return const iterator at first bin of histogram.
std::vector< T >::const_iterator end () const
Return const iterator after last valid bin.
Public Member Functions inherited from SSAGES::GridBase< T >
size_t GetDimension () const
Get the dimension.
const std::vector< int > & GetNumPoints () const
Get the number of points for all dimensions.
int GetNumPoints (size_t dim) const
Get the number of points for a specific dimension.
const std::vector< double > & GetLower () const
Return the lower edges of the Grid.
double GetLower (size_t dim) const
Get the lower edge for a specific dimension.
const std::vector< double > & GetUpper () const
Return the upper edges of the Grid.
double GetUpper (size_t dim) const
Get the upper edge for a specific dimension.
const std::vector< bool > & GetPeriodic () const
Return the periodicity of the Grid.
bool GetPeriodic (size_t dim) const
Get the periodicity in a specific dimension.
size_t size () const
Get the size of the internal storage vector.
T * data ()
Get pointer to the internal data storage vector.
T const * data () const
Get pointer to const of the internal data storage vector.
std::vector< int > GetIndices (const std::vector< double > &x) const
Return the Grid indices for a given point.
int GetIndex (double x) const
Return the Grid index for a one-dimensional grid.
std::vector< double > GetCoordinates (const std::vector< int > &indices)
Return coordinates of the grid center points.
double GetCoordinate (int index)
Return center point of 1d-grid.
const T & at (const std::vector< int > &indices) const
Access Grid element read-only.
T & at (const std::vector< int > &indices)
Access Grid element read/write.
template<typename R >
const T & at (std::initializer_list< R > &&x) const
Const access of Grid element via initializer list.
template<typename R >
T & at (std::initializer_list< R > &&x)
Access Grid element via initializer list.
const T & at (int index) const
Access 1d Grid by index, read-only.
T & at (int index)
Access 1d Grid by index, read-write.
const T & at (const std::vector< double > &x) const
Access Grid element pertaining to a specific point – read-only.
T & at (const std::vector< double > &x)
Access Grid element pertaining to a specific point – read/write.
const T & at (double x) const
Access 1d-Grid by point - read-only.
T & at (double x)
Access 1d-Grid by point - read-write.
const T & operator[] (const std::vector< int > &indices) const
Access Grid element per [] read-only.
T & operator[] (const std::vector< int > &indices)
Access Grid element per [] read-write.
template<typename R >
const T & operator[] (std::initializer_list< R > &&x) const
Const access of Grid element via initializer list.
template<typename R >
T & operator[] (std::initializer_list< R > &&x)
Access Grid element via initializer list.
const T & operator[] (int index) const
Access 1d-Grid per [] operator, read-only.
T & operator[] (int index)
Access 1d-Grid per [] operator, read-write.
const T & operator[] (const std::vector< double > &x) const
Access Grid element pertaining to a specific point per [] read-only.
T & operator[] (const std::vector< double > &x)
Access Grid element pertaining to a specific point per [] read-write.
const T & operator[] (double x) const
Access 1d-Grid via specific point, read-only.
T & operator[] (double x)
Access 1d-Grid via specific point, read-write.
Public Member Functions inherited from SSAGES::Serializable
virtual ~Serializable ()
Destructor.
Static Public Member Functions
static Histogram< T > * BuildHistogram (const Json::Value &json)
Set up the histogram.
static Histogram< T > * BuildHistogram (const Json::Value &json, const std::string &path)
Set up the histogram.
Private Member Functions
size_t mapTo1d (const std::vector< int > &indices) const override
Map d-dimensional indices to 1-d data vector.
Additional Inherited Members
Protected Member Functions inherited from SSAGES::GridBase< T >
std::vector< int > wrapIndices (const std::vector< int > &indices) const
Wrap the index around periodic boundaries.
GridBase (std::vector< int > numPoints, std::vector< double > lower, std::vector< double > upper, std::vector< bool > isPeriodic)
Constructor.
Protected Attributes inherited from SSAGES::GridBase< T >
std::vector< T > data_
Internal storage of the data.
size_t dimension_
Dimension of the grid.
std::vector< int > numPoints_
Number of points in each dimension.
std::pair< std::vector< double >
, std::vector< double > > edges_
Edges of the Grid in each dimension.
std::vector< bool > isPeriodic_
Periodicity of the Grid.
Detailed Description
template<typename T>
class SSAGES::Histogram< T >
Basic Histogram.
Template Parameters
T type of data to be stored in the histogram.
A Histogram is a method to store data in SSAGES. It is used to discretize a continuous number, typically a collective variable, into number_points bins. For each bin, an arbitrary type of data can be stored, specified via the template parameter T.
The histogram can be of arbitrary dimension. For each dimension, the lower bound, the upper bound and the number of grid points need to be specified. Furthermore, the histogram can be defined as periodic or non-periodic in the respective dimension. By default, the histogram is non-periodic. The bins are indexed from 0 to number_points-1 following the standard C/C++ convention. In contrast to the Grid, a Histogram additionally includes an under- and an overflow bin in each non-periodic dimension. These can be accessed via the indices -1 an number_points (see below).
The bin width Delta is given by (upper - lower)/number_points. Thus, bin n corresponds to the interval [lower + n*Delta, lower + (n+1)*Delta). Note that n follows the C/C++ convention, i.e. n = 0 for the first interval. The bin indices pertaining to a given point can be obtained via GetIndices().
In non-periodic dimensions, an overflow and an underflow interval exist. The underflow interval corresponds to the interval (-infinity, lower), i.e. all points below lower. Similarly, the overflow interval corresponds to the interval [upper, infinity). The underflow grid point can be accessed via the index -1, the overflow grid point via the index number_points.
Definition at line 70 of file Histogram.h.
Constructor & Destructor Documentation
template<typename T> SSAGES::Histogram< T >::Histogram (std::vector< int > numPoints, std::vector< double > lower, std::vector< double > upper, std::vector< bool > isPeriodic) inline
Constructor.
Parameters
numPoints Number of grid points in each dimension.
lower Lower edges of the grid.
upper Upper edges of the grid.
isPeriodic Bools specifying the periodicity in the respective dimension.
The dimension of the grid is determined by the size of the parameter vectors.
Definition at line 122 of file Histogram.h.
Referenced by SSAGES::Histogram< int >::BuildHistogram().
       : GridBase<T>(numPoints, lower, upper, isPeriodic)
     {
         size_t data_size = 1;
         for (size_t d = 0; d < GridBase<T>::GetDimension(); ++d) {
             size_t storage_size = GridBase<T>::GetNumPoints(d);
             if (!GridBase<T>::GetPeriodic(d)) { storage_size += 2; }
             data_size *= storage_size;
         }
         GridBase<T>::data_.resize(data_size);
     }
Member Function Documentation
template<typename T> iterator SSAGES::Histogram< T >::begin () inline
Return iterator at first bin of histogram.
Returns
Iterator at first bin of the histogram.
The first bin is the bin that has the lowest allowed index in all dimensions, i.e. 0 in periodic and -1 in non-periodic dimensions.
Definition at line 564 of file Histogram.h.
Referenced by SSAGES::Basis::PrintBias(), and SSAGES::Basis::UpdateBias().
     {
         std::vector<int> indices(GridBase<T>::GetDimension());
         for (size_t i = 0; i < indices.size(); ++i) {
             if(GridBase<T>::GetPeriodic(i)) {
                 indices.at(i) = 0;
             } else {
                 indices.at(i) = -1;
             }
         }
         return iterator(indices, this);
     }
template<typename T> std::vector<T>::const_iterator SSAGES::Histogram< T >::begin () const inline
Return const iterator at first bin of histogram.
Returns
Const iterator at first bin of the histogram.
The first bin is the bin that has the lowest allowed index in all dimensions, i.e. 0 in periodic and -1 in non-periodic dimensions.
Definition at line 608 of file Histogram.h.
     {
         std::vector<int> indices(GridBase<T>::GetDimension());
         for (size_t i = 0; i < indices.size(); ++i) {
             if(GridBase<T>::GetPeriodic(i)) {
                 indices.at(i) = 0;
             } else {
                 indices.at(i) = -1;
             }
         }
         return iterator(indices, this);
     }
template<typename T> static Histogram<T>* SSAGES::Histogram< T >::BuildHistogram (const Json::Value & json) inline static
Set up the histogram.
Parameters
json JSON value containing all input information.
Returns
Pointer to the newly built histogram.
This function builds a histogram from a JSON node. It will return a nullptr if an unknown error occured, but generally, it will throw a BuildException of failure.
Definition at line 147 of file Histogram.h.
Referenced by SSAGES::Histogram< int >::BuildHistogram().
     {
         return BuildHistogram(json, "#/Histogram");
     }
template<typename T> static Histogram<T>* SSAGES::Histogram< T >::BuildHistogram (const Json::Value & json, const std::string & path) inline static
Set up the histogram.
Parameters
json JSON Value containing all input information.
path Path for JSON path specification.
Returns
Pointer to the newly built histogram.
This function builds a histogram from a JSON node. It will return a nullptr if an unknown error occured, but generally, it will throw a BuildException on failure.
Definition at line 162 of file Histogram.h.
     {
         Json::ObjectRequirement validator;
         Json::Value schema;
         Json::Reader reader;
         reader.parse(JsonSchema::grid, schema);
         validator.Parse(schema, path);
         // Validate inputs.
         validator.Validate(json, path);
         if (validator.HasErrors()) {
             throw BuildException(validator.GetErrors());
         }
         // Read in Lower Grid edges.
         std::vector<double> lower;
         for (auto &lv : json["lower"]) {
            lower.push_back(lv.asDouble());
         }
         size_t dimension = lower.size();
         // Read in upper grid edges.
         std::vector<double> upper;
         for (auto &uv : json["upper"]) {
             upper.push_back(uv.asDouble());
         }
         if (upper.size() != dimension) {
             throw BuildException({"Number of upper values does not match "
                                   "number of lower values!"});
         }
         // Read in number of points.
         std::vector<int> number_points;
         for (auto &np : json["number_points"]) {
             number_points.push_back(np.asInt());
         }
         if (number_points.size() != dimension) {
             throw BuildException({"Arrays \"lower\" and \"number_points\" do "
                                   "not have the same size!"});
         }
         // Read in periodicity.
         std::vector<bool> isPeriodic;
         for (auto &periodic : json["periodic"]) {
             isPeriodic.push_back(periodic.asBool());
         }
         if (isPeriodic.size() == 0) {
             isPeriodic = std::vector<bool>(dimension, false);
         } else if (isPeriodic.size() != dimension) {
             throw BuildException({"Arrays \"lower\" and \"periodic\" do not "
                                   "have the same size!"});
         }
         // Construct the grid.
         Histogram<T>* hist = new Histogram(number_points, lower, upper, isPeriodic);
         return hist;
     }
template<typename T> iterator SSAGES::Histogram< T >::end () inline
Return iterator after last valid bin.
Returns
Iterator after last valid bin.
The last valid bin is the bin that has the highest allowed index in all dimensions, i.e. num_points - 1 in periodic and num_points in non-periodic dimensions.
Definition at line 586 of file Histogram.h.
Referenced by SSAGES::Basis::PrintBias(), and SSAGES::Basis::UpdateBias().
     {
         std::vector<int> indices(GridBase<T>::GetDimension());
         for (size_t i = 0; i < indices.size(); ++i) {
             if (GridBase<T>::GetPeriodic(i)) {
                 indices.at(i) = GridBase<T>::GetNumPoints(i) - 1;
             } else {
                 indices.at(i) = GridBase<T>::GetNumPoints(i);
             }
         }
         iterator it(indices, this);
         return ++it;
     }
template<typename T> std::vector<T>::const_iterator SSAGES::Histogram< T >::end () const inline
Return const iterator after last valid bin.
Returns
Const iterator after last valid bin.
The last valid bin is the bin that has the highest allowed index in all dimensions, i.e. num_points - 1 in periodic and num_points in non-periodic dimensions.
Definition at line 630 of file Histogram.h.
     {
         std::vector<int> indices(GridBase<T>::GetDimension());
         for (size_t i = 0; i < indices.size(); ++i) {
             if (GridBase<T>::GetPeriodic(i)) {
                 indices.at(i) = GridBase<T>::GetNumPoints(i) - 1;
             } else {
                 indices.at(i) = GridBase<T>::GetNumPoints(i);
             }
         }
         iterator it(indices, this);
         return ++it;
     }
template<typename T> size_t SSAGES::Histogram< T >::mapTo1d (const std::vector< int > & indices) const inline override private virtual
Map d-dimensional indices to 1-d data vector.
Parameters
indices Vector specifying the grid point.
Returns
Index of 1d data vector.
Map a set of indices to the index of the 1d data vector. Keep in mind, that the data includes underflow (index -1) and overflow (index numPoints) bins in periodic dimension.
Implements SSAGES::GridBase< T >.
Definition at line 82 of file Histogram.h.
     {
         // Check if an index is out of bounds
         for (size_t i=0; i < GridBase<T>::GetDimension(); ++i) {
             int index = indices.at(i);
             bool periodic = GridBase<T>::GetPeriodic(i);
             int numpoints = GridBase<T>::GetNumPoints(i);
             if ( (periodic && (index < 0 || index >= numpoints)) ||
                  (periodic && (index < -1 || index > numpoints)) )
             {
                 throw std::out_of_range("Bin index out of range.");
             }
         }
         size_t idx = 0;
         size_t fac = 1;
         for (size_t i=0; i < GridBase<T>::GetDimension(); ++i) {
             if (GridBase<T>::GetPeriodic(i)) {
                 idx += indices.at(i) * fac;
                 fac *= GridBase<T>::GetNumPoints(i);
             } else {
                 idx += (indices.at(i) + 1) * fac;
                 fac *= GridBase<T>::GetNumPoints(i) + 2;
             }
         }
         return idx;
     }
template<typename T> void SSAGES::Histogram< T >::Serialize (Json::Value & json) const inline override virtual
Serialize the class.
Parameters
json JSON value to which the information is stored
Store all information pertaining to this class in the given JSON value. The information can then be used to restart or analyze the simulation
Warning
Serialization not yet implemented.
Reimplemented from SSAGES::GridBase< T >.
Definition at line 230 of file Histogram.h.
     {
     }
The documentation for this class was generated from the following file:
/home/cody/SSAGES/src/Grids/Histogram.h