SSAGES: Json::AllOfRequirement Class Reference
Json::AllOfRequirement Class Reference
Requires that all of a list of Requirements hold.
#include <AllOfRequirement.h>
Public Member Functions
AllOfRequirement ()
Constructor.
virtual void ClearErrors () override
Clear lists of errors for all Requirements.
virtual void ClearNotices () override
Clear lists of notices for all Requirements.
virtual void Reset () override
Reset all Requirements.
virtual void Parse (Value json, const std::string &path) override
Parse JSON value and add all loaded Requirements.
virtual void Validate (const Value &json, const std::string &path) override
Validate that all Requirements are met.
Public Member Functions inherited from Json::Requirement
bool HasErrors ()
Check if errors have occured.
std::vector< std::string > GetErrors ()
Get list of error messages.
virtual bool HasNotices ()
Check if notices have been queued.
std::vector< std::string > GetNotices ()
Get list of notices.
virtual ~Requirement ()
Destructor.
Private Attributes
RequireList reqs_
List of Requirements.
Additional Inherited Members
Protected Member Functions inherited from Json::Requirement
void PushError (const std::string &error)
Add error to list of error messages.
void PushNotice (const std::string &notice)
Add message to list of notices.
Detailed Description
Requires that all of a list of Requirements hold.
Definition at line 38 of file AllOfRequirement.h.
Member Function Documentation
Parse()
virtual void Json::AllOfRequirement::Parse (Value json, const std::string & path) inline override virtual
Parse JSON value and add all loaded Requirements.
Parameters
json JSON input value.
path Path for JSON path specification.
This function parses a JSON value and adds all Requirements that are in the "allOf" branch to the list of Requirements.
Implements Json::Requirement.
Definition at line 81 of file AllOfRequirement.h.
         {
             Reset();
             RequirementLoader loader;
             auto& head = json.isMember("allOf") ? json["allOf"] : json;
             for(auto& val : head)
                 if(auto req = loader.LoadRequirement(val))
                 {
                     reqs_.push_back(std::move(req));
                     reqs_.back()->Parse(val, path);
                 }
         }
References Json::RequirementLoader::LoadRequirement(), reqs_, and Reset().
Validate()
virtual void Json::AllOfRequirement::Validate (const Value & json, const std::string & path) inline override virtual
Validate that all Requirements are met.
Parameters
json JSON value to validate.
path Path for JSON path specification.
Implements Json::Requirement.
Definition at line 102 of file AllOfRequirement.h.
         {
             for(auto& r : reqs_)
             {
                 r->Validate(json, path);
                 if(r->HasErrors())
                     for(const auto& error : r->GetErrors())
                         PushError(error);
                 if(r->HasNotices())
                     for(const auto& notice : r->GetNotices())
                         PushNotice(notice);
             }
         }
References Json::Requirement::PushError(), Json::Requirement::PushNotice(), and reqs_.
The documentation for this class was generated from the following file:
/home/michael/development/SSAGES/src/Validator/AllOfRequirement.h