SSAGES: SSAGES::ANN Class Reference
SSAGES::ANN Class Reference
Methods
Artificial Neural Network Method.
#include <ANN.h>
Public Member Functions
ANN (const MPI_Comm &world, const MPI_Comm &comm, const Eigen::VectorXi &topol, Grid< Eigen::VectorXd > *fgrid, Grid< unsigned int > *hgrid, Grid< double > *ugrid, const std::vector< double > &lowerb, const std::vector< double > &upperb, const std::vector< double > &lowerk, const std::vector< double > &upperk, double temperature, double weight, unsigned int nsweep)
Constructor.
void PreSimulation (Snapshot *snapshot, const class CVManager &cvmanager) override
Method call prior to simulation initiation.
void PostIntegration (Snapshot *snapshot, const class CVManager &cvmanager) override
Method call post integration.
void PostSimulation (Snapshot *snapshot, const class CVManager &cvmanager) override
Method call post simulation.
void SetPrevWeight (double h)
Set previous history weight.
void SetOutput (const std::string &outfile)
Set name of output file.
void SetOutputOverwrite (bool overwrite)
Set overwrite flag on output file.
void SetConvergeIters (unsigned int citers)
Set number of iterations after which we turn on full weight.
void SetMaxIters (unsigned int iters)
Set maximum number of training iterations per sweep.
void SetMinLoss (double loss)
Set minimum loss function value (should be zero for production).
void ReadBias (const std::string &, const std::string &)
Load network state and bias from file.
Public Member Functions inherited from SSAGES::Method
Method (unsigned int frequency, const MPI_Comm &world, const MPI_Comm &comm)
Constructor.
void SetCVMask (const std::vector< unsigned int > &mask)
Sets the collective variable mask.
virtual ~Method ()
Destructor.
Public Member Functions inherited from SSAGES::EventListener
EventListener (unsigned int frequency)
Constructor.
unsigned int GetFrequency () const
Get frequency of event listener.
virtual ~EventListener ()
Destructor.
Static Public Member Functions
static ANN * Build (const Json::Value &json, const MPI_Comm &world, const MPI_Comm &comm, const std::string &path)
Build a derived method from JSON node.
Static Public Member Functions inherited from SSAGES::Method
static Method * BuildMethod (const Json::Value &json, const MPI_Comm &world, const MPI_Comm &comm, const std::string &path)
Build a derived method from JSON node.
Static Public Member Functions inherited from SSAGES::EventListener
static unsigned int GetWalkerID (const MPI_Comm &world, const MPI_Comm &comm)
Get walker ID number of specified communicator.
static unsigned int GetNumWalkers (const MPI_Comm &world, const MPI_Comm &comm)
Get total number of walkers in the simulation.
static bool IsMasterRank (const MPI_Comm &comm)
Check if current processor is master.
Private Member Functions
void TrainNetwork ()
Trains the neural network.
void WriteBias ()
Writes out the bias to file.
Private Attributes
Eigen::VectorXi topol_
Neural network topology.
unsigned int citers_
Number of iterations after which we turn on full weight.
nnet::neural_net net_
Neural network.
Grid< Eigen::VectorXd > * fgrid_
Force grid.
Grid< unsigned int > * hgrid_
Histogram grid.
Grid< double > * ugrid_
Unbiased histogram grid.
std::string outfile_
Output filename.
bool preloaded_
Is the network preloaded?
bool overwrite_
Overwrite outputs?
unsigned int sweep_
unsigned int nsweep_
double pweight_
double weight_
double temp_
double kbt_
Eigen::MatrixXd hist_
Eigen::MatrixXd bias_
Eigen::MatrixXd rbias_
std::vector< double > lowerb_
std::vector< double > upperb_
std::vector< double > lowerk_
std::vector< double > upperk_
Additional Inherited Members
Protected Attributes inherited from SSAGES::Method
mxx::comm world_
Global MPI communicator.
mxx::comm comm_
Local MPI communicator.
std::vector< unsigned int > cvmask_
Mask which identifies which CVs to act on.
Detailed Description
Artificial Neural Network Method.
Implementation of the Artificial Neural Network Method based on [3]
Definition at line 35 of file ANN.h.
Constructor & Destructor Documentation
ANN()
SSAGES::ANN::ANN (const MPI_Comm & world, const MPI_Comm & comm, const Eigen::VectorXi & topol, Grid< Eigen::VectorXd > * fgrid, Grid< unsigned int > * hgrid, Grid< double > * ugrid, const std::vector< double > & lowerb, const std::vector< double > & upperb, const std::vector< double > & lowerk, const std::vector< double > & upperk, double temperature, double weight, unsigned int nsweep)
Constructor.
Parameters
world MPI global communicator.
comm MPI local communicator.
topol Topology of network.
fgrid Grid containing biasing forces.
hgrid Grid containing histogram.
ugrid Grid containing unbiased histogram.
lowerb Lower bounds for CVs.
upperb Upper bounds for CVs.
lowerk Lower bound restraints for CVs.
upperk Upper bound restraints for CVs.
temperature Temperature of the simulation.
weight Relative weight of the statistics in sweep.
nsweep Number of iterations in the sweep.
Constructs an instance of Artificial Neural Network method.
Definition at line 34 of file ANN.cpp.
                                   :
     Method(1, world, comm), topol_(topol), sweep_(0), nsweep_(nsweep),
     citers_(0), net_(topol), pweight_(1.), weight_(weight), temp_(temperature),
     kbt_(0), fgrid_(fgrid), hgrid_(hgrid), ugrid_(ugrid), hist_(), bias_(),
     lowerb_(lowerb), upperb_(upperb), lowerk_(lowerk), upperk_(upperk),
     outfile_("ann.out"), preloaded_(false), overwrite_(true)
     {
         // Create histogram grid matrix.
         hist_.resize(hgrid_->size(), hgrid_->GetDimension());
         // Fill it up.
         size_t i = 0;
         for(auto it = hgrid_->begin(); it != hgrid_->end(); ++it)
         {
             auto coord = it.coordinates();
             for(size_t j = 0; j < coord.size(); ++j)
                 hist_(i, j) = coord[j];
             ++i;
         }
         // Initialize restraint reweight vector.
         rbias_.resize(hgrid_->size(), hgrid_->GetDimension());
         rbias_.fill(0);
         // Initialize FES vector.
         bias_.resize(hgrid_->size(), 1);
         net_.forward_pass(hist_);
         bias_.array() = net_.get_activation().col(0).array();
     }
References SSAGES::Grid< T >::begin(), SSAGES::Grid< T >::end(), SSAGES::GridBase< T >::GetDimension(), hgrid_, hist_, net_, and SSAGES::GridBase< T >::size().
Referenced by Build().
Member Function Documentation
Build()
ANN * SSAGES::ANN::Build (const Json::Value & json, const MPI_Comm & world, const MPI_Comm & comm, const std::string & path) static
Build a derived method from JSON node.
Parameters
json JSON Value containing all input information.
world MPI global communicator.
comm MPI local communicator.
path Path for JSON path specification.
Returns
Pointer to the Method built. nullptr if an unknown error occurred.
This function builds a registered method from a JSON node. The difference between this function and "Build" is that this automatically determines the appropriate derived type based on the JSON node information.
Note
Object lifetime is the caller's responsibility.
Definition at line 287 of file ANN.cpp.
     {
         ObjectRequirement validator;
         Value schema;
         CharReaderBuilder rbuilder;
         CharReader* reader = rbuilder.newCharReader();
         reader->parse(JsonSchema::ANNMethod.c_str(),
                       JsonSchema::ANNMethod.c_str() + JsonSchema::ANNMethod.size(),
                       &schema, nullptr);
         validator.Parse(schema, path);
         // Validate inputs.
         validator.Validate(json, path);
         if(validator.HasErrors())
             throw BuildException(validator.GetErrors());
         // Grid.
         auto* fgrid = Grid<VectorXd>::BuildGrid(json.get("grid", Json::Value()));
         auto* hgrid = Grid<unsigned int>::BuildGrid(json.get("grid", Json::Value()));
         auto* ugrid = Grid<double>::BuildGrid(json.get("grid", Json::Value()));
         // Topology.
         auto nlayers = json["topology"].size() + 2;
         VectorXi topol(nlayers);
         topol[0] = fgrid->GetDimension();
         topol[nlayers-1] = 1;
         for(int i = 0; i < static_cast<int>(json["topology"].size()); ++i)
             topol[i+1] = json["topology"][i].asInt();
         auto weight = json.get("weight", 1.).asDouble();
         auto temp = json["temperature"].asDouble();
         auto nsweep = json["nsweep"].asUInt();
         // Assume all vectors are the same size.
         std::vector<double> lowerb, upperb, lowerk, upperk;
         for(int i = 0; i < static_cast<int>(json["lower_bound_restraints"].size()); ++i)
         {
             lowerk.push_back(json["lower_bound_restraints"][i].asDouble());
             upperk.push_back(json["upper_bound_restraints"][i].asDouble());
             lowerb.push_back(json["lower_bounds"][i].asDouble());
             upperb.push_back(json["upper_bounds"][i].asDouble());
         }
         auto* m = new ANN(world, comm, topol, fgrid, hgrid, ugrid, lowerb, upperb, lowerk, upperk, temp, weight, nsweep);
         // Set optional params.
         m->SetPrevWeight(json.get("prev_weight", 1).asDouble());
         m->SetOutput(json.get("output_file", "ann.out").asString());
         m->SetOutputOverwrite( json.get("overwrite_output", true).asBool());
         m->SetConvergeIters(json.get("converge_iters", 0).asUInt());
         m->SetMaxIters(json.get("max_iters", 1000).asUInt());
         m->SetMinLoss(json.get("min_loss", 0).asDouble());
         if(json.isMember("net_state") && json.isMember("load_bias"))
             m->ReadBias(json["net_state"].asString(), json["load_bias"].asString());
         return m;
     }
References ANN(), SSAGES::Grid< T >::BuildGrid(), Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), and Json::ObjectRequirement::Validate().
PostIntegration()
void SSAGES::ANN::PostIntegration (Snapshot * snapshot, const class CVManager & cvmanager) override virtual
Method call post integration.
Parameters
snapshot Pointer to the simulation snapshot.
cvmanager Collective variable manager.
This function will be called after each integration step.
Implements SSAGES::Method.
Definition at line 113 of file ANN.cpp.
     {
         if(snapshot->GetIteration() && snapshot->GetIteration() % nsweep_ == 0)
         {
             // Switch to full blast.
             if(citers_ && snapshot->GetIteration() > citers_)
                 pweight_ = 1.0;
             TrainNetwork();
             if(IsMasterRank(world_))
                 WriteBias();
         }
         // Get CV vals.
         auto cvs = cvmanager.GetCVs(cvmask_);
         auto n = cvs.size();
         // Determine if we are in bounds.
         RowVectorXd vec(n);
         std::vector<double> val(n);
         bool inbounds = true;
         for(size_t i = 0; i < n; ++i)
         {
             val[i] = cvs[i]->GetValue();
             vec[i] = cvs[i]->GetValue();
             if(val[i] < hgrid_->GetLower(i) || val[i] > hgrid_->GetUpper(i))
                 inbounds = false;
         }
         // If in bounds, bias.
         VectorXd derivatives = VectorXd::Zero(n);
         if(inbounds)
         {
             // Record histogram hit and get gradient.
             // Only record hits on master processes since we will
             // reduce later.
             if(IsMasterRank(comm_))
                 hgrid_->at(val) += 1;
             //derivatives = (*fgrid_)[val];
             net_.forward_pass(vec);
             derivatives = net_.get_gradient(0);
         }
         else
         {
             if(IsMasterRank(comm_))
             {
                 std::cerr << "ANN (" << snapshot->GetIteration() << "): out of bounds ( ";
                 for(auto& v : val)
                     std::cerr << v << " ";
                 std::cerr << ")" << std::endl;
             }
         }
         // Restraints.
         for(size_t i = 0; i < n; ++i)
         {
             auto cval = cvs[i]->GetValue();
             if(cval < lowerb_[i])
                 derivatives[i] += lowerk_[i]*cvs[i]->GetDifference(lowerb_[i]);
             else if(cval > upperb_[i])
                 derivatives[i] += upperk_[i]*cvs[i]->GetDifference(upperb_[i]);
         }
         // Apply bias to atoms.
         auto& forces = snapshot->GetForces();
         auto& virial = snapshot->GetVirial();
         for(size_t i = 0; i < cvs.size(); ++i)
         {
             auto& grad = cvs[i]->GetGradient();
             auto& boxgrad = cvs[i]->GetBoxGradient();
             // Update the forces in snapshot by adding in the force bias from each
             // CV to each atom based on the gradient of the CV.
             for (size_t j = 0; j < forces.size(); ++j)
                 forces[j] -= derivatives[i]*grad[j];
             virial += derivatives[i]*boxgrad;
         }
     }
References SSAGES::GridBase< T >::at(), citers_, SSAGES::Method::comm_, SSAGES::Method::cvmask_, SSAGES::CVManager::GetCVs(), SSAGES::Snapshot::GetForces(), SSAGES::Snapshot::GetIteration(), SSAGES::GridBase< T >::GetLower(), SSAGES::GridBase< T >::GetUpper(), SSAGES::Snapshot::GetVirial(), hgrid_, SSAGES::EventListener::IsMasterRank(), lowerb_, lowerk_, net_, pweight_, TrainNetwork(), SSAGES::Method::world_, and WriteBias().
PostSimulation()
void SSAGES::ANN::PostSimulation (Snapshot * snapshot, const class CVManager & cvmanager) override virtual
Method call post simulation.
Parameters
snapshot Pointer to the simulation snapshot.
cvmanager Collective variable manager.
This function will be called after the end of the simulation run.
Implements SSAGES::Method.
Definition at line 194 of file ANN.cpp.
     {
     }
PreSimulation()
void SSAGES::ANN::PreSimulation (Snapshot * snapshot, const class CVManager & cvmanager) override virtual
Method call prior to simulation initiation.
Parameters
snapshot Pointer to the simulation snapshot.
cvmanager Collective variable manager.
This function will be called before the simulation is started.
Implements SSAGES::Method.
Definition at line 76 of file ANN.cpp.
     {
         auto ndim = hgrid_->GetDimension();
         kbt_ = snapshot->GetKb()*temp_;
         // Zero out forces and histogram.
         VectorXd vec = VectorXd::Zero(ndim);
         std::fill(hgrid_->begin(), hgrid_->end(), 0);
         if(preloaded_)
         {
             net_.forward_pass(hist_);
             bias_.array() = net_.get_activation().col(0).array();
             TrainNetwork();
         }
         else
             std::fill(ugrid_->begin(), ugrid_->end(), 1.0);
         // Fill in the reweighting matrix for restraints.
         auto cvs = cvmanager.GetCVs(cvmask_);
         auto ncvs = cvs.size();
         for(int i = 0; i < hist_.rows(); ++i)
         {
             auto cval = hist_.row(i);
             for(size_t j = 0; j < ncvs; ++j)
             {
                 if(cval[j] < lowerb_[j])
                     rbias_(i,j) = lowerk_[j]*(cval[j] - lowerb_[j])*(cval[j] - lowerb_[j]);
                 else if(cval[j] > upperb_[j])
                     rbias_(i,j) = upperk_[j]*(cval[j] - upperb_[j])*(cval[j] - upperb_[j]);
             }
         }
         std::fill(fgrid_->begin(), fgrid_->end(), vec);
     }
References SSAGES::Grid< T >::begin(), SSAGES::Method::cvmask_, SSAGES::Grid< T >::end(), fgrid_, SSAGES::CVManager::GetCVs(), SSAGES::GridBase< T >::GetDimension(), SSAGES::Snapshot::GetKb(), hgrid_, hist_, lowerb_, lowerk_, net_, preloaded_, temp_, TrainNetwork(), and ugrid_.
SetConvergeIters()
void SSAGES::ANN::SetConvergeIters (unsigned int citers) inline
Set number of iterations after which we turn on full weight.
Parameters
citers Number of iterations before full weight
Definition at line 175 of file ANN.h.
         {
             citers_ = citers;
         }
References citers_.
SetMaxIters()
void SSAGES::ANN::SetMaxIters (unsigned int iters) inline
Set maximum number of training iterations per sweep.
Parameters
iters Maximum iterations per sweep
Definition at line 184 of file ANN.h.
         {
             auto params = net_.get_train_params();
             params.max_iter = iters;
             net_.set_train_params(params);
         }
References net_.
SetMinLoss()
void SSAGES::ANN::SetMinLoss (double loss) inline
Set minimum loss function value (should be zero for production).
Parameters
loss Minimum loss function value
Definition at line 195 of file ANN.h.
         {
             auto params = net_.get_train_params();
             params.min_loss = loss;
             net_.set_train_params(params);
         }
References net_.
SetOutput()
void SSAGES::ANN::SetOutput (const std::string & outfile) inline
Set name of output file.
Parameters
outfile Output file
Definition at line 157 of file ANN.h.
         {
             outfile_ = outfile;
         }
References outfile_.
SetOutputOverwrite()
void SSAGES::ANN::SetOutputOverwrite (bool overwrite) inline
Set overwrite flag on output file.
Parameters
overwrite Boolean if output file should be overwritten
Definition at line 166 of file ANN.h.
         {
             overwrite_ = overwrite;
         }
References overwrite_.
SetPrevWeight()
void SSAGES::ANN::SetPrevWeight (double h) inline
Set previous history weight.
Parameters
h History weight
Definition at line 148 of file ANN.h.
         {
             pweight_ = h;
         }
References pweight_.
Member Data Documentation
hist_
Eigen::MatrixXd SSAGES::ANN::hist_ private
Eigen matrices of grids.
Definition at line 73 of file ANN.h.
Referenced by ANN(), PreSimulation(), ReadBias(), TrainNetwork(), and WriteBias().
lowerb_
std::vector<double> SSAGES::ANN::lowerb_ private
Bounds
Definition at line 78 of file ANN.h.
Referenced by PostIntegration(), and PreSimulation().
lowerk_
std::vector<double> SSAGES::ANN::lowerk_ private
Bound restraints.
Definition at line 83 of file ANN.h.
Referenced by PostIntegration(), and PreSimulation().
pweight_
double SSAGES::ANN::pweight_ private
Previous and current histogram weight.
Definition at line 54 of file ANN.h.
Referenced by PostIntegration(), SetPrevWeight(), and TrainNetwork().
sweep_
unsigned int SSAGES::ANN::sweep_ private
Number of iterations per sweep.
Definition at line 43 of file ANN.h.
Referenced by TrainNetwork(), and WriteBias().
temp_
double SSAGES::ANN::temp_ private
System temperature and energy units.
Definition at line 59 of file ANN.h.
Referenced by PreSimulation().
The documentation for this class was generated from the following files:
/home/michael/development/SSAGES/src/Methods/ANN.h
/home/michael/development/SSAGES/src/Methods/ANN.cpp