SSAGES: SSAGES::BuildException Class Reference
SSAGES::BuildException Class Reference
Exception to be thrown when building the Driver fails.
#include <DriverException.h>
Public Member Functions
BuildException (std::vector< std::string > errors)
Constructor.
virtual const char * what () const throw ()
Get generic error message.
std::vector< std::string > GetErrors ()
Get specific error message.
Private Attributes
std::vector< std::string > errors_
Error message.
Detailed Description
Exception to be thrown when building the Driver fails.
Definition at line 34 of file DriverException.h.
Constructor & Destructor Documentation
SSAGES::BuildException::BuildException (std::vector< std::string > errors) inline
Constructor.
Parameters
errors Error message
Definition at line 43 of file DriverException.h.
                                                     :
             std::runtime_error("Object build error"), errors_(errors)
         {
         }
Member Function Documentation
std::vector<std::string> SSAGES::BuildException::GetErrors () inline
Get specific error message.
Returns
Specific error message.
Definition at line 66 of file DriverException.h.
References errors_.
Referenced by SSAGES::Simulation::BuildConstraints(), SSAGES::Simulation::BuildCVs(), SSAGES::Simulation::BuildDriver(), SSAGES::Simulation::BuildMethod(), SSAGES::Simulation::BuildObservers(), and SSAGES::Simulation::BuildSimulation().
         {
             return errors_;
         }
virtual const char* SSAGES::BuildException::what () const throw () inline virtual
Get generic error message.
Returns
Generic error message.
Definition at line 52 of file DriverException.h.
         {
             std::ostringstream msg("");
             msg << runtime_error::what() << ": "
                 << "See errors for details.";
             return msg.str().c_str();
         }
The documentation for this class was generated from the following file:
/home/cody/SSAGES/src/Drivers/DriverException.h