SSAGES: Json::NotRequirement Class Reference
Json::NotRequirement Class Reference
Requires a given Requirement to fail.
#include <NotRequirement.h>
Public Member Functions
NotRequirement ()
Constructor.
virtual void ClearErrors () override
Clear list of error messages.
virtual void ClearNotices () override
Clear list of notices.
virtual void Reset () override
Reset Requirement.
virtual void Parse (Value json, const std::string &path) override
Parse JSON value and generate Requirement to be negated.
virtual void Validate (const Value &json, const std::string &path) override
Validate that JSON value fails the given Requirement.
Public Member Functions inherited from Json::Requirement
bool HasErrors ()
Check if errors have occured.
std::vector< std::string > GetErrors ()
Get list of error messages.
virtual bool HasNotices ()
Check if notices have been queued.
std::vector< std::string > GetNotices ()
Get list of notices.
virtual ~Requirement ()
Destructor.
Private Attributes
std::unique_ptr< Requirement > req_
Requirement to negate.
Additional Inherited Members
Protected Member Functions inherited from Json::Requirement
void PushError (const std::string &error)
Add error to list of error messages.
void PushNotice (const std::string &notice)
Add message to list of notices.
Detailed Description
Requires a given Requirement to fail.
Definition at line 37 of file NotRequirement.h.
Member Function Documentation
Parse()
virtual void Json::NotRequirement::Parse (Value json, const std::string & path) inline override virtual
Parse JSON value and generate Requirement to be negated.
Parameters
json JSON input value.
path Path for JSON path specification.
Implements Json::Requirement.
Definition at line 78 of file NotRequirement.h.
         {
             Reset();
             RequirementLoader loader;
             auto& head = json.isMember("not") ? json["not"] : json;
             if((req_ = loader.LoadRequirement(head)))
                 req_->Parse(head, path);
         }
References Json::RequirementLoader::LoadRequirement(), req_, and Reset().
Validate()
virtual void Json::NotRequirement::Validate (const Value & json, const std::string & path) inline override virtual
Validate that JSON value fails the given Requirement.
Parameters
json JSON value to validate.
path Path for JSON path specification.
Calls validate on the Requirement to be negated and checks if it has an error. If it has not, it passed the validation and an error is added to this Requirement.
Implements Json::Requirement.
Definition at line 97 of file NotRequirement.h.
         {
             req_->Validate(json, path);
             if(!req_->HasErrors())
                 PushError(path + ": Value must not validate against requirement.");
         }
References Json::Requirement::PushError(), and req_.
The documentation for this class was generated from the following file:
/home/michael/development/SSAGES/src/Validator/NotRequirement.h