SSAGES: SSAGES::SimObserver Class Reference
SSAGES::SimObserver Class Reference abstract
Base class for objects observing a simulation.
#include <SimObserver.h>
Public Member Functions
SimObserver (boost::mpi::communicator world, boost::mpi::communicator comm, int nws, int wid, unsigned int frequency=1)
Constructor.
void Update (const SimEvent &e)
Update observer when simulation has changed.
unsigned int GetFrequency () const
Get logging frequency.
virtual std::string GetName () const =0
Get name.
virtual void PreVisit ()
Called before visitors invokes.
virtual void PostVisit ()
Called after visitors complete.
virtual void Serialize (Json::Value &json) const =0
Serialize observer.
virtual ~SimObserver ()
Destructor.
Public Member Functions inherited from SSAGES::Visitor
virtual void Visit (const Driver &d)=0
Visit.
virtual ~Visitor ()
Destructor.
Public Member Functions inherited from SSAGES::Serializable
virtual ~Serializable ()
Destructor.
Static Public Member Functions
static SimObserver * BuildObserver (const Json::Value &json, boost::mpi::communicator world, boost::mpi::communicator comm, int numwalkers, int wid, const std::string &path)
Build the simulation observer.
static SimObserver * BuildObserver (const Json::Value &json, boost::mpi::communicator world, boost::mpi::communicator comm, int numwalkers, int wid)
Build the simulation observer.
static void BuildObservers (const Json::Value &json, boost::mpi::communicator world, boost::mpi::communicator comm, int numwalkers, int wid, ObserverList &ol)
Build list of observers.
Protected Member Functions
SimEvent & GetEvent ()
Get current simulation event.
unsigned int SetFrequency (int f)
Set logging frequency.
unsigned int GetIteration ()
Get current event iteration.
int GetObservableID ()
Get caller identifier.
Protected Attributes
boost::mpi::communicator world_
MPI global communicator.
boost::mpi::communicator comm_
MPI local communicator.
int numwalkers_
Number of walkers.
int wid_
ID of walker to be observed.
Private Attributes
unsigned int frequency_ = 1
Frequency of observation.
SimEvent event_
Simulation event to be observed.
Detailed Description
Base class for objects observing a simulation.
Definition at line 48 of file SimObserver.h.
Constructor & Destructor Documentation
SSAGES::SimObserver::SimObserver (boost::mpi::communicator world, boost::mpi::communicator comm, int nws, int wid, unsigned int frequency = 1) inline
Constructor.
Parameters
world MPI global communicator.
comm MPI local communicator.
nws Number of walkers.
wid ID of walker to observe.
frequency Logging frequency.
Initialize a SimObserver class with a specified observation frequency.
Definition at line 110 of file SimObserver.h.
                 : frequency_(frequency), event_(nullptr, 0),
                 world_(world), comm_(comm), numwalkers_(nws), wid_(wid){}
Member Function Documentation
SimObserver * SSAGES::SimObserver::BuildObserver (const Json::Value & json, boost::mpi::communicator world, boost::mpi::communicator comm, int numwalkers, int wid, const std::string & path) static
Build the simulation observer.
Parameters
json JSON value containing input information.
world MPI global communicator.
comm MPI local communicator.
numwalkers Number of walkers.
wid ID of the walker to observe.
path Path for JSON path specification.
Returns
Pointer to the newly created observer. nullptr in case of unknown error.
Static builder method for simobserver. If an unknown error occured, the return value is nullptr, but generally, this function will throw a BuildException on failure.
Note
Object lifetime is caller's responsibility!
Definition at line 60 of file SimObserver.cpp.
References Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), and Json::ObjectRequirement::Validate().
     {
         ObjectRequirement validator;
         Value schema;
         Reader reader;
         SimObserver* obs = nullptr;
         auto type = json.get("type", "none").asString();
         if(type == "JSON")
         {
             reader.parse(JsonSchema::JSONObserver, schema);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             // Initialize JSON specific options.
             auto prefix = json.get("file name", "unnamed").asString();
             auto frequency = json.get("frequency", 1).asInt();
             auto* dlm = new JSONObserver(prefix, world, comm, numwalkers, wid, frequency);
             obs = static_cast<SimObserver*>(dlm);
         }
         else
         {
             throw BuildException({path + ": Unknown observer type specified."});
         }
         return obs;
     }
SimObserver * SSAGES::SimObserver::BuildObserver (const Json::Value & json, boost::mpi::communicator world, boost::mpi::communicator comm, int numwalkers, int wid) static
Build the simulation observer.
Parameters
json JSON value containing input information.
world MPI global communicator.
comm MPI local communicator.
numwalkers Number of walkers.
wid ID of the walker to observe.
Returns
Pointer to the newly created observer. nullptr in case of unknown error.
Static builder method for simobserver. If an unknown error occured, the return value is nullptr, but generally, this function will throw a BuildException on failure.
Note
Object lifetime is caller's responsibility!
Definition at line 51 of file SimObserver.cpp.
     {
         return BuildObserver(json, world, comm, numwalkers, wid, "#/Observers");
     }
void SSAGES::SimObserver::BuildObservers (const Json::Value & json, boost::mpi::communicator world, boost::mpi::communicator comm, int numwalkers, int wid, ObserverList & ol) static
Build list of observers.
Parameters
json JSON value containing input information.
world MPI global communicator.
comm MPI local communicator.
numwalkers Number of walkers.
wid ID of the walker to be observed.
ol List of observers to which the new observers are appended.
Static builder method for sim observers. ObserverList is a vector which will be populated with initialized observers.
Note
Object lifetime is caller's responsibility!
Definition at line 100 of file SimObserver.cpp.
References Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ArrayRequirement::Parse(), and Json::ArrayRequirement::Validate().
Referenced by SSAGES::Driver::BuildObservers().
     {
         ArrayRequirement validator;
         Value schema;
         Reader reader;
         reader.parse(JsonSchema::Observers, schema);
         validator.Parse(schema, "#/Observers");
         // Validate high level schema.
         validator.Validate(json, "#/Observers");
         if(validator.HasErrors())
             throw BuildException(validator.GetErrors());
         // Loop through observers.
         int i = 0;
         for(auto& obs : json)
         {
             ol.push_back(BuildObserver(obs, world, comm, numwalkers, wid, "#/Observers/" + std::to_string(i)));
             ++i;
         }
     }
SimEvent& SSAGES::SimObserver::GetEvent () inline protected
Get current simulation event.
Returns
Current simulation event.
Definition at line 65 of file SimObserver.h.
References event_.
             {
                 return event_;
             }
unsigned int SSAGES::SimObserver::GetFrequency () const inline
Get logging frequency.
Returns
Logging frequency.
Definition at line 128 of file SimObserver.h.
References frequency_.
Referenced by SSAGES::LammpsDriver::ExecuteInputFile(), and SSAGES::JSONObserver::Serialize().
 { return frequency_; }
unsigned int SSAGES::SimObserver::GetIteration () inline protected
Get current event iteration.
Returns
Iteration of current event.
Definition at line 84 of file SimObserver.h.
References event_, and SSAGES::SimEvent::GetIteration().
             {
                 return event_.GetIteration();
             }
virtual std::string SSAGES::SimObserver::GetName () const pure virtual
Get name.
Returns
Name of the observer.
Implemented in SSAGES::JSONObserver.
int SSAGES::SimObserver::GetObservableID () inline protected
Get caller identifier.
Returns
0 always.
Definition at line 93 of file SimObserver.h.
             {
                 return 0;
             }
virtual void SSAGES::SimObserver::Serialize (Json::Value & json) const pure virtual
Serialize observer.
Parameters
json JSON value to store information to.
Implements SSAGES::Serializable.
Implemented in SSAGES::JSONObserver.
unsigned int SSAGES::SimObserver::SetFrequency (int f) inline protected
Set logging frequency.
Parameters
f New frequency.
Returns
New frequency.
Definition at line 75 of file SimObserver.h.
References frequency_.
             {
                 return frequency_ = f;
             }
void SSAGES::SimObserver::Update (const SimEvent & e)
Update observer when simulation has changed.
Parameters
e New simulation event.
Definition at line 39 of file SimObserver.cpp.
References SSAGES::SimEvent::ForceObserve(), and SSAGES::SimEvent::GetIteration().
     {
         // Only lock and proceed if we have to.
         if(e.GetIteration() % frequency_ == 0 || e.ForceObserve())
         {
             event_ = e;
             PreVisit();
             event_.GetObservable()->AcceptVisitor(*this);
             PostVisit();
         }
     };
The documentation for this class was generated from the following files:
/home/cody/SSAGES/src/Simulations/SimObserver.h
/home/cody/SSAGES/src/Simulations/SimObserver.cpp