SSAGES: SSAGES::Driver Class Reference
SSAGES::Driver Class Reference abstract
Core
Abstract driver class for creating driver objects.
#include <Driver.h>
Public Member Functions
Driver (boost::mpi::communicator &world, boost::mpi::communicator &comm, int walkerID)
Constructor.
virtual ~Driver ()
Destructor.
virtual void Run ()=0
Run simulation.
virtual void BuildDriver (const Json::Value &json, const std::string &path)=0
Build the driver, which will create the hook and so forth.
virtual void ExecuteInputFile (std::string contents)=0
Read in driver specific input file (e.g. Lammps.in)
std::string GetInputFile ()
Get the input file contents.
void SetInputFile (const std::string filename)
Set the input file.
void BuildCVs (const Json::Value &json, const std::string &path)
Build CVs.
void BuildConstraints (const Json::Value &json, const std::string &path)
void BuildMethod (const Json::Value &json, const std::string &path)
Build method(s).
void BuildObservers (const Json::Value &json, int nwalks)
Build observer(s).
void Finalize ()
Finalize the setup.
virtual void Serialize (Json::Value &json) const override
Serialize the class.
virtual void AcceptVisitor (Visitor &v) const override
Accept a visitor.
Public Member Functions inherited from SSAGES::SimObservable
virtual void AddObserver (SimObserver *observer)
Add simulation observer.
virtual void RemoveObserver (SimObserver *observer)
Remove simulation observer.
void NotifyObservers (const SimEvent &event)
Notify registered observers of a change.
virtual ~SimObservable ()
Destructor.
Public Member Functions inherited from SSAGES::Visitable
virtual ~Visitable ()
Destructor.
Public Member Functions inherited from SSAGES::Serializable
virtual ~Serializable ()
Destructor.
Protected Attributes
boost::mpi::communicator world_
MPI global communicator.
boost::mpi::communicator comm_
MPI local communicator.
const int wid_
The node id that this driver belongs to.
Hook * hook_
The hook that hooks into the MD simulation engine.
Snapshot * snapshot_
The snapshot of your system.
Method * method_
The Method that will be used.
CVList CVs_
The CVs that will be used.
int iterations_
Target number of iterations.
ObserverList observers_
The observers that will be used for this driver.
ConstraintList constraints_
List of constraints to use.
std::string inputfile_
Local input file.
std::string restartname_
MD engine Restart file name.
bool readrestart_
Read a restart file.
std::random_device rd_
Random number generators for setting seeds.
std::mt19937 gen_
Alternative random number generator.
Additional Inherited Members
Protected Member Functions inherited from SSAGES::SimObservable
void SerializeObservers (Json::Value &json) const
Serialize observers.
Detailed Description
Abstract driver class for creating driver objects.
Definition at line 46 of file Driver.h.
Constructor & Destructor Documentation
SSAGES::Driver::Driver (boost::mpi::communicator & world, boost::mpi::communicator & comm, int walkerID) inline
Constructor.
Parameters
world MPI global communicator.
comm MPI local communicator.
walkerID The walker node for this driver.
Definition at line 99 of file Driver.h.
                              :
         world_(world), comm_(comm), wid_(walkerID),
         hook_(nullptr), snapshot_(nullptr), method_(nullptr), CVs_(),
         iterations_(0), observers_(), inputfile_("none"), restartname_(),
         readrestart_(), rd_(), gen_(rd_())
          {}
Member Function Documentation
void SSAGES::Driver::BuildConstraints (const Json::Value & json, const std::string & path) inline
Parameters
json JSON Value containing input information.
path Path for JSON path specification.
Definition at line 183 of file Driver.h.
References SSAGES::Constraint::BuildConstraint(), comm_, and constraints_.
         {
             Constraint::BuildConstraint(json, constraints_, comm_, path);
         }
void SSAGES::Driver::BuildCVs (const Json::Value & json, const std::string & path) inline
Build CVs.
Parameters
json JSON Value containing input information.
path Path for JSON path specification.
Definition at line 173 of file Driver.h.
References SSAGES::CollectiveVariable::BuildCV(), and CVs_.
         {
             CollectiveVariable::BuildCV(json, CVs_, path);
         }
virtual void SSAGES::Driver::BuildDriver (const Json::Value & json, const std::string & path) pure virtual
Build the driver, which will create the hook and so forth.
Parameters
json JSON value containing input information.
path Path for JSON path specification.
Implemented in SSAGES::LammpsDriver, and SSAGES::GromacsDriver.
void SSAGES::Driver::BuildMethod (const Json::Value & json, const std::string & path) inline
Build method(s).
Parameters
json JSON value containing input information.
path Path for JSON path specification.
Definition at line 193 of file Driver.h.
References SSAGES::Method::BuildMethod(), comm_, method_, and world_.
         {
             method_ = Method::BuildMethod(json, world_, comm_, path);
         }
void SSAGES::Driver::BuildObservers (const Json::Value & json, int nwalks) inline
Build observer(s).
Parameters
json JSON value containing input information.
nwalks Number of walkers.
Definition at line 203 of file Driver.h.
References SSAGES::SimObservable::AddObserver(), SSAGES::SimObserver::BuildObservers(), comm_, observers_, wid_, and world_.
         {
             SimObserver::BuildObservers(json, world_, comm_, nwalks, wid_, observers_);
             for(auto& o : observers_)
                 this->AddObserver(o);
         }
virtual void SSAGES::Driver::ExecuteInputFile (std::string contents) pure virtual
Read in driver specific input file (e.g. Lammps.in)
Parameters
contents The contents of the input file.
Execute the contents of an input file. The input file should be loaded with SSAGES::GetFileContents() first.
Implemented in SSAGES::GromacsDriver, and SSAGES::LammpsDriver.
void SSAGES::Driver::Finalize () inline
Finalize the setup.
Create the snapshot and put all gathered values into the local hook. Set up listeners as well.
Definition at line 217 of file Driver.h.
References SSAGES::Hook::AddCV(), SSAGES::Hook::AddListener(), comm_, constraints_, CVs_, hook_, iterations_, method_, SSAGES::Hook::SetMDDriver(), SSAGES::Hook::SetSnapshot(), SSAGES::Snapshot::SetTargetIterations(), snapshot_, and wid_.
         {
             // Check that Hook is not a Null pointer
             if (!hook_) {
                 throw std::runtime_error(
                     "Trying to finalize simulation with invalid Hook."
                 );
             }
             // Initialize snapshot.
             snapshot_ = new Snapshot(comm_, wid_);
             snapshot_->SetTargetIterations(iterations_);
             /* Remove this later? */
             if(hook_ != nullptr)
             {
                 // Set the hook to snapshot
                 hook_->SetSnapshot(snapshot_);
                 //Set the driver in the hook
                 hook_->SetMDDriver(this);
                 if(method_)
                     hook_->AddListener(method_);
                 for(auto&c : constraints_)
                     hook_->AddListener(c);
                 for(auto&cv : CVs_)
                     hook_->AddCV(cv);
             }
         }
std::string SSAGES::Driver::GetInputFile () inline
Get the input file contents.
Returns
The contents of inputfile_.
This function returns the contents of the input file.
Note
This function does not load the input file. If the input file has not been loaded before, an empty string will be returned.
Definition at line 158 of file Driver.h.
References inputfile_.
 {return inputfile_;}
virtual void SSAGES::Driver::Serialize (Json::Value & json) const inline override virtual
Serialize the class.
Parameters
json JSON value to which the information is stored
Store all information pertaining to this class in the given JSON value. The information can then be used to restart or analyze the simulation
Implements SSAGES::Serializable.
Reimplemented in SSAGES::LammpsDriver, and SSAGES::GromacsDriver.
Definition at line 251 of file Driver.h.
References comm_, CVs_, inputfile_, method_, readrestart_, restartname_, SSAGES::Serializable::Serialize(), and SSAGES::SimObservable::SerializeObservers().
Referenced by SSAGES::GromacsDriver::Serialize(), SSAGES::LammpsDriver::Serialize(), and SSAGES::JSONObserver::Visit().
         {
             SerializeObservers(json["observers"]);
             method_->Serialize(json["method"]);
             auto& tmp = json["CVs"];
             for(unsigned int i = 0; i < CVs_.size();i++)
                 CVs_[i]->Serialize(tmp[i]);
             json["inputfile"] = inputfile_;
             json["number processors"] = comm_.size();
             json["restart file"] = restartname_;
             json["read restart"] = readrestart_;
         }
void SSAGES::Driver::SetInputFile (const std::string filename) inline
Set the input file.
Parameters
filename File name of the input file.
This function sets the name of the input file for the driver.
Definition at line 166 of file Driver.h.
References inputfile_.
 { inputfile_ = filename;}
The documentation for this class was generated from the following file:
/home/cody/SSAGES/src/Drivers/Driver.h