SSAGES: Json::Requirement Class Reference
Json::Requirement Class Reference abstract
Requirements on input files.
#include <Requirement.h>
Public Member Functions
virtual void Parse (Value json, const std::string &path)=0
Parse JSON value.
virtual void Validate (const Value &json, const std::string &path)=0
Validate that JSON value meets requirements.
virtual void Reset ()=0
Reset validator.
bool HasErrors ()
Check if errors have occured.
std::vector< std::string > GetErrors ()
Get list of error messages.
virtual void ClearErrors ()
Clear list of error messages.
virtual bool HasNotices ()
Check if notices have been queued.
std::vector< std::string > GetNotices ()
Get list of notices.
virtual void ClearNotices ()
Clear list of notice messages.
virtual ~Requirement ()
Destructor.
Protected Member Functions
void PushError (const std::string &error)
Add error to list of error messages.
void PushNotice (const std::string &notice)
Add message to list of notices.
Private Attributes
std::vector< std::string > errors_
List of error messages.
std::vector< std::string > notices_
List of messages.
Detailed Description
Requirements on input files.
Definition at line 39 of file Requirement.h.
Member Function Documentation
GetErrors()
std::vector<std::string> Json::Requirement::GetErrors () inline
Get list of error messages.
Returns
List of error messages.
Definition at line 92 of file Requirement.h.
 { return errors_; };
References errors_.
Referenced by SSAGES::BoxVolumeCV::Build(), SSAGES::GaussianPK::Build(), SSAGES::Logger::Build(), SSAGES::AngleCV::Build(), SSAGES::ParticlePositionCV::Build(), SSAGES::RationalSwitchPK::Build(), SSAGES::Umbrella::Build(), SSAGES::ParticleSeparationCV::Build(), SSAGES::ParticleCoordinateCV::Build(), SSAGES::ResourceHandler::Build(), SSAGES::Meta::Build(), SSAGES::RouseModeCV::Build(), SSAGES::PairwiseCV::Build(), SSAGES::ANN::Build(), SSAGES::StringMethod::Build(), SSAGES::TorsionalCV::Build(), SSAGES::AlphaRMSDCV::Build(), SSAGES::BFS::Build(), SSAGES::RMSDCV::Build(), SSAGES::ANNCV::Build(), SSAGES::GyrationTensorCV::Build(), SSAGES::Chebyshev::Build(), SSAGES::AntiBetaRMSDCV::Build(), SSAGES::ParallelBetaRMSDCV::Build(), SSAGES::ABF::Build(), SSAGES::CFF::Build(), SSAGES::Legendre::Build(), SSAGES::Fourier::Build(), SSAGES::ForwardFlux::Build(), SSAGES::Grid< Eigen::VectorXd >::BuildGrid(), SSAGES::Method::BuildMethod(), Json::ArrayRequirement::Validate(), and Json::ObjectRequirement::Validate().
GetNotices()
std::vector<std::string> Json::Requirement::GetNotices () inline
Get list of notices.
Returns
List of notice messages.
Definition at line 107 of file Requirement.h.
 {return notices_; };
References notices_.
Referenced by Json::ArrayRequirement::Validate(), and Json::ObjectRequirement::Validate().
HasErrors()
bool Json::Requirement::HasErrors () inline
Check if errors have occured.
Returns
True if the list of errors is not empty.
Definition at line 86 of file Requirement.h.
 { return errors_.size() != 0; };
References errors_.
Referenced by SSAGES::BoxVolumeCV::Build(), SSAGES::GaussianPK::Build(), SSAGES::Logger::Build(), SSAGES::AngleCV::Build(), SSAGES::ParticlePositionCV::Build(), SSAGES::RationalSwitchPK::Build(), SSAGES::Umbrella::Build(), SSAGES::ParticleSeparationCV::Build(), SSAGES::ParticleCoordinateCV::Build(), SSAGES::ResourceHandler::Build(), SSAGES::Meta::Build(), SSAGES::RouseModeCV::Build(), SSAGES::PairwiseCV::Build(), SSAGES::ANN::Build(), SSAGES::StringMethod::Build(), SSAGES::TorsionalCV::Build(), SSAGES::AlphaRMSDCV::Build(), SSAGES::BFS::Build(), SSAGES::RMSDCV::Build(), SSAGES::ANNCV::Build(), SSAGES::GyrationTensorCV::Build(), SSAGES::Chebyshev::Build(), SSAGES::AntiBetaRMSDCV::Build(), SSAGES::ParallelBetaRMSDCV::Build(), SSAGES::ABF::Build(), SSAGES::CFF::Build(), SSAGES::Legendre::Build(), SSAGES::Fourier::Build(), SSAGES::ForwardFlux::Build(), SSAGES::Grid< Eigen::VectorXd >::BuildGrid(), SSAGES::Method::BuildMethod(), and Json::ObjectRequirement::Validate().
HasNotices()
virtual bool Json::Requirement::HasNotices () inline virtual
Check if notices have been queued.
Returns
True if list of notices is not empty.
Definition at line 101 of file Requirement.h.
 {return notices_.size() != 0; };
References notices_.
Referenced by Json::ObjectRequirement::Validate().
Parse()
virtual void Json::Requirement::Parse (Value json, const std::string & path) pure virtual
Parse JSON value.
Parameters
json JSON value with input information.
path Path for JSON path specification.
Implemented in Json::BooleanRequirement, Json::NullRequirement, Json::ObjectRequirement, Json::ArrayRequirement, Json::AllOfRequirement, Json::AnyOfRequirement, Json::NotRequirement, Json::StringRequirement, Json::NumberRequirement, Json::OneOfRequirement, Json::IntegerRequirement, Json::DependencyRequirement, and Json::EnumRequirement.
PushError()
void Json::Requirement::PushError (const std::string & error) inline protected
Add error to list of error messages.
Parameters
error Error message.
This function adds an error message to the list of error messages. The list of error messages can be retrieved by Requirement::GetErrors()
Definition at line 53 of file Requirement.h.
 { errors_.push_back(error); }
References errors_.
Referenced by Json::BooleanRequirement::Validate(), Json::NullRequirement::Validate(), Json::EnumRequirement::Validate(), Json::DependencyRequirement::Validate(), Json::NotRequirement::Validate(), Json::OneOfRequirement::Validate(), Json::AnyOfRequirement::Validate(), Json::AllOfRequirement::Validate(), Json::IntegerRequirement::Validate(), Json::StringRequirement::Validate(), Json::NumberRequirement::Validate(), Json::ArrayRequirement::Validate(), and Json::ObjectRequirement::Validate().
PushNotice()
void Json::Requirement::PushNotice (const std::string & notice) inline protected
Add message to list of notices.
Parameters
notice Message string.
This function adds a new message to the list of messages. The list can be retrieved using Requirement::GetNotices().
Definition at line 62 of file Requirement.h.
 { notices_.push_back(notice); }
References notices_.
Referenced by Json::OneOfRequirement::Validate(), Json::AnyOfRequirement::Validate(), Json::AllOfRequirement::Validate(), Json::ArrayRequirement::Validate(), and Json::ObjectRequirement::Validate().
Validate()
virtual void Json::Requirement::Validate (const Value & json, const std::string & path) pure virtual
Validate that JSON value meets requirements.
Parameters
json JSON value to validate.
path Path for JSON path specification.
Implemented in Json::ObjectRequirement, Json::ArrayRequirement, Json::NumberRequirement, Json::StringRequirement, Json::IntegerRequirement, Json::AllOfRequirement, Json::AnyOfRequirement, Json::OneOfRequirement, Json::NotRequirement, Json::DependencyRequirement, Json::EnumRequirement, Json::BooleanRequirement, and Json::NullRequirement.
Referenced by Json::ObjectRequirement::Validate().
The documentation for this class was generated from the following file:
/home/michael/development/SSAGES/src/Validator/Requirement.h