SSAGES: SSAGES::ReadBackbone Class Reference
SSAGES::ReadBackbone Class Reference
Utility class to read protein backbone atoms from a reference file.
#include <ReadBackbone.h>
Static Public Member Functions
static std::vector< std::vector< std::string > > GetPdbBackbone (std::string refpdb, std::vector< int > resids)
Read protein backbone atoms from reference PDB file.
Detailed Description
Utility class to read protein backbone atoms from a reference file.
This utility class allows for the backbone atoms along a protein segment to be extracted from a reference file (most likely in a .pdb).
Supported filetypes:
PDB
Definition at line 42 of file ReadBackbone.h.
Member Function Documentation
GetPdbBackbone()
static std::vector< std::vector< std::string> > SSAGES::ReadBackbone::GetPdbBackbone (std::string refpdb, std::vector< int > resids) inline static
Read protein backbone atoms from reference PDB file.
Parameters
refpdb Name of reference PDB file.
resids Vector of residue numbers for which to find backbone atoms.
Returns
atomids Vector of atom numbers corresponding to specified residues.
Extract backbone atom from a reference PDB file, corresponding to a sequence of protein residues of interest. Five backbone atoms are extracted for each residue in the order: N CA CB C O. For Glycine residues, HA1 is located in place of CB.
Definition at line 57 of file ReadBackbone.h.
         {
             //std::vector<int> atomids;
             std::vector< std::vector< std::string > > atomids(2, std::vector<std::string> (0));
             //std::vector<int> atomnums;
             std::vector<std::string> atomnums;
             std::vector<std::string> atomtypes;
             std::vector<std::string> resnames;
             std::vector<std::string> chains;
             std::vector<int> resnums;
             //std::vector<int> tempatoms(5);
             std::vector<std::string> tempatoms(5);
             std::vector<std::string> backboneAtoms = {"N", "CA", "CB", "C", "O", "OT1"};
             std::vector<std::string> glycineAtoms = {"N", "CA", "HA1", "C", "O", "OT1"};
             std::string atomnum, resnum;
             std::string record, atomtype, resname, chain;
             std::ifstream pdbfile;
             pdbfile.open(refpdb, std::ios::in);
             std::string line;
             while(std::getline(pdbfile, line)){
                 if(line.length() < 26) line.append(26 - line.length(), ' ');
                 record = line.substr(0, 6);
                 atomnum = line.substr(6, 5);
                 atomtype = line.substr(12, 4);
                 resname = line.substr(17, 3);
                 chain = line.substr(21, 1);
                 resnum = line.substr(22, 4);
                 record.erase( std::remove( record.begin(), record.end(), ' '), record.end());
                 if((record == "ATOM") && ((std::stoi(resnum) - resids[0]) <= (resids.back() - resids[0]))){
                     atomtype.erase( std::remove( atomtype.begin(), atomtype.end(), ' '), atomtype.end());
                     resname.erase( std::remove( resname.begin(), resname.end(), ' '), resname.end());
                     if(resname == "GLY" && std::find(glycineAtoms.begin(), glycineAtoms.end(), atomtype) != glycineAtoms.end()){
                         //atomnums.push_back(std::stoi(atomnum));
                         atomnums.push_back(atomnum);
                         atomtypes.push_back(atomtype);
                         resnames.push_back(resname);
                         chains.push_back(chain);
                         resnums.push_back(std::stoi(resnum));
                     } else if(std::find(backboneAtoms.begin(), backboneAtoms.end(), atomtype) != backboneAtoms.end()){
                         //atomnums.push_back(std::stoi(atomnum));
                         atomnums.push_back(atomnum);
                         atomtypes.push_back(atomtype);
                         resnames.push_back(resname);
                         chains.push_back(chain);
                         resnums.push_back(std::stoi(resnum));
                     }
                 }
             }
             // atoms in PDB not necessarily in N CA CB C O order, fix that:
             for(size_t i = 0; i < resids.size(); i++){
                 for(size_t j = 5 * i; j < (5 * i + 5); j++){
                     if(atomtypes[j] == "N"){
                         tempatoms[0] = atomnums[j];
                         std::cout << "N  - Atom " << tempatoms[0] << " - Chain " << chains[j] << std::endl;
                     } else if(atomtypes[j] == "CA"){
                         tempatoms[1] = atomnums[j];
                         std::cout << "CA - Atom " << tempatoms[1] << " - Chain " << chains[j] << std::endl;
                     } else if(atomtypes[j] == "C"){
                         tempatoms[3] = atomnums[j];
                         std::cout << "C  - Atom " << tempatoms[3] << " - Chain " << chains[j] << std::endl;
                     } else if(atomtypes[j] == "O"){
                         tempatoms[4] = atomnums[j];
                         std::cout << "O  - Atom " << tempatoms[4] << " - Chain " << chains[j] << std::endl;
                     } else if(atomtypes[j] == "OT1"){
                         tempatoms[4] = atomnums[j];
                         std::cout << "OT1- Atom " << tempatoms[4] << " - Chain " << chains[j] << std::endl;
                     } else{
                         tempatoms[2] = atomnums[j];
                         std::cout << atomtypes[j] << " - Atom " << tempatoms[2] << " - Chain " << chains[j] << std::endl;
                     }
                     atomids[1].push_back(chains[j]);
                 }
                 //atomids.insert(atomids.end(), tempatoms.begin(), tempatoms.end());
                 atomids[0].insert(atomids[0].end(), tempatoms.begin(), tempatoms.end());
             }
             return atomids;
         }
Referenced by SSAGES::AlphaRMSDCV::Initialize(), SSAGES::AntiBetaRMSDCV::Initialize(), and SSAGES::ParallelBetaRMSDCV::Initialize().
The documentation for this class was generated from the following file:
/home/michael/development/SSAGES/src/Utility/ReadBackbone.h