SSAGES: Json::OneOfRequirement Class Reference
Json::OneOfRequirement Class Reference
Requires exactly one of a list of Requirements to hold.
#include <OneOfRequirement.h>
Public Member Functions
OneOfRequirement ()
Constructor.
virtual void ClearErrors () override
Clear list of error messages for all Requirements.
virtual void ClearNotices () override
Clear list of notices for all Requirements.
virtual void Reset () override
Reset requirement.
virtual void Parse (Value json, const std::string &path) override
Parse JSON value to generate Requirement.
virtual void Validate (const Value &json, const std::string &path) override
Validate that only one of the Requirements hold.
Public Member Functions inherited from Json::Requirement
bool HasErrors ()
Check if errors have occured.
std::vector< std::string > GetErrors ()
Get list of error messages.
virtual bool HasNotices ()
Check if notices have been queued.
std::vector< std::string > GetNotices ()
Get list of notices.
virtual ~Requirement ()
Destructor.
Private Attributes
RequireList reqs_
List of Requirements.
Additional Inherited Members
Protected Member Functions inherited from Json::Requirement
void PushError (const std::string &error)
Add error to list of error messages.
void PushNotice (const std::string &notice)
Add message to list of notices.
Detailed Description
Requires exactly one of a list of Requirements to hold.
Definition at line 37 of file OneOfRequirement.h.
Member Function Documentation
virtual void Json::OneOfRequirement::Parse (Value json, const std::string & path) inline override virtual
Parse JSON value to generate Requirement.
Parameters
json JSON input value.
path Path for JSON path specification.
Implements Json::Requirement.
Definition at line 77 of file OneOfRequirement.h.
References Json::RequirementLoader::LoadRequirement(), and Reset().
         {
             Reset();
             RequirementLoader loader;
             auto& head = json.isMember("oneOf") ? json["oneOf"] : json;
             for(auto& val : head)
                 if(auto req = loader.LoadRequirement(val))
                 {
                     reqs_.push_back(std::move(req));
                     reqs_.back()->Parse(val, path);
                 }
         }
virtual void Json::OneOfRequirement::Validate (const Value & json, const std::string & path) inline override virtual
Validate that only one of the Requirements hold.
Parameters
json JSON value to be validated.
path Path for JSON path specification.
Implements Json::Requirement.
Definition at line 98 of file OneOfRequirement.h.
References Json::Requirement::PushError(), and Json::Requirement::PushNotice().
         {
             int validated = 0;
             for(auto& r : reqs_)
             {
                 r->Validate(json, path);
                 if(!r->HasErrors())
                     ++validated;
             }
             if(validated > 1)
                 PushError(path + ": Input must validate against only one schema");
             else if(validated == 0)
                 for(auto& r : reqs_)
                 {
                     if(r->HasErrors())
                         for(const auto& error : r->GetErrors())
                             PushError(error);
                     if(r->HasNotices())
                         for(const auto& notice : r->GetNotices())
                             PushNotice(notice);
                 }
         }
The documentation for this class was generated from the following file:
/home/cody/SSAGES-public/src/Validator/OneOfRequirement.h