SSAGES: SSAGES::JSONObserver Class Reference
SSAGES::JSONObserver Class Reference
Core
Observer with JSON output.
#include <JSONObserver.h>
Public Member Functions
JSONObserver (const std::string &prefix, boost::mpi::communicator world, boost::mpi::communicator comm, int numwalkers, int wid, unsigned int frequency=1)
Constructor.
virtual std::string GetName () const override
Get Observer name.
std::string GetPrefix () const
Get filename prefix.
virtual void Visit (const Driver &d) override
Visit driver.
virtual void Serialize (Json::Value &json) const override
Serialize the class.
virtual void PreVisit () override
Operations before visiting.
virtual void PostVisit () override
Operations after visition.
~JSONObserver ()
Destructor.
Public Member Functions inherited from SSAGES::SimObserver
SimObserver (boost::mpi::communicator world, boost::mpi::communicator comm, int nws, int wid, unsigned int frequency=1)
Constructor.
void Update (const SimEvent &e)
Update observer when simulation has changed.
unsigned int GetFrequency () const
Get logging frequency.
virtual ~SimObserver ()
Destructor.
Public Member Functions inherited from SSAGES::Visitor
virtual ~Visitor ()
Destructor.
Public Member Functions inherited from SSAGES::Serializable
virtual ~Serializable ()
Destructor.
Private Attributes
std::unique_ptr< std::ofstream > jsonfs_
Output file pointer.
std::string prefix_
Prefix for output file.
Json::Value root_
JSON root value.
bool writetoother_
Indicate which json to write to.
Additional Inherited Members
Static Public Member Functions inherited from SSAGES::SimObserver
static SimObserver * BuildObserver (const Json::Value &json, boost::mpi::communicator world, boost::mpi::communicator comm, int numwalkers, int wid, const std::string &path)
Build the simulation observer.
static SimObserver * BuildObserver (const Json::Value &json, boost::mpi::communicator world, boost::mpi::communicator comm, int numwalkers, int wid)
Build the simulation observer.
static void BuildObservers (const Json::Value &json, boost::mpi::communicator world, boost::mpi::communicator comm, int numwalkers, int wid, ObserverList &ol)
Build list of observers.
Protected Member Functions inherited from SSAGES::SimObserver
SimEvent & GetEvent ()
Get current simulation event.
unsigned int SetFrequency (int f)
Set logging frequency.
unsigned int GetIteration ()
Get current event iteration.
int GetObservableID ()
Get caller identifier.
Protected Attributes inherited from SSAGES::SimObserver
boost::mpi::communicator world_
MPI global communicator.
boost::mpi::communicator comm_
MPI local communicator.
int numwalkers_
Number of walkers.
int wid_
ID of walker to be observed.
Detailed Description
Observer with JSON output.
JSON Observer class that creates a snapshot of the simulation and dumps it to a JSON file.
Definition at line 44 of file JSONObserver.h.
Constructor & Destructor Documentation
SSAGES::JSONObserver::JSONObserver (const std::string & prefix, boost::mpi::communicator world, boost::mpi::communicator comm, int numwalkers, int wid, unsigned int frequency = 1)
Constructor.
Parameters
prefix Prefix for output file.
world MPI global communicator.
comm MPI local communicator.
numwalkers Number of walkers.
wid ID of walker to observe.
frequency Frequency of observations.
Definition at line 52 of file JSONObserver.cpp.
References SSAGES::SimObserver::comm_, jsonfs_, prefix_, root_, SSAGES::SimObserver::wid_, and SSAGES::SimObserver::world_.
                                                         :
     SimObserver(world, comm, numwalkers, wid, frequency), prefix_(prefix), root_(), writetoother_(true)
     {
         if(comm_.rank() != 0)
             return;
         std::string Name = prefix_ + "_" + std::to_string(wid_) +".json";
         std::string BckupName = Name + "_backup";
         // Don't overwrite JSON file if same name exists
         int result = rename(Name.c_str(),(Name+"_copy").c_str());
         if(result == 0)
             std::cout<<"Same restart file name! Moving " + Name + " to " + Name + "_copy"<<std::endl;
         jsonfs_ = std::unique_ptr<std::ofstream>(
         new std::ofstream(Name));
         jsonfs_ = std::unique_ptr<std::ofstream>(
         new std::ofstream(BckupName));
         if(world_.rank()!=0)
         {
             return;
         }
         for(int i = 0; i<numwalkers; i++)
             root_["driver"][i] = "@include(" + prefix_ + "_" + std::to_string(i) + ".json)";
         jsonfs_ = std::unique_ptr<std::ofstream>(
             new std::ofstream(prefix_ + ".json")
         );
         jsonfs_->precision(20);
         *jsonfs_;
         Json::StreamWriterBuilder builder;
         builder["commentStyle"] = "None";
         builder["indentation"] = "\t";
         std::unique_ptr<Json::StreamWriter> writer(builder.newStreamWriter());
         writer->write(root_, &*jsonfs_);
         *jsonfs_ << std::endl;
         jsonfs_->close();
         root_.clear();
     }
Member Function Documentation
virtual std::string SSAGES::JSONObserver::GetName () const inline override virtual
Get Observer name.
Returns
String "JSON"
Implements SSAGES::SimObserver.
Definition at line 73 of file JSONObserver.h.
 { return "JSON"; }
std::string SSAGES::JSONObserver::GetPrefix () const inline
Get filename prefix.
Returns
Filename prefix.
Definition at line 79 of file JSONObserver.h.
References prefix_.
Referenced by SSAGES::LammpsDriver::ExecuteInputFile().
 {return prefix_;}
void SSAGES::JSONObserver::Serialize (Json::Value & json) const override virtual
Serialize the class.
Parameters
json JSON value to which the information is stored
Store all information pertaining to this class in the given JSON value. The information can then be used to restart or analyze the simulation
Implements SSAGES::SimObserver.
Definition at line 154 of file JSONObserver.cpp.
References SSAGES::SimObserver::GetFrequency(), and prefix_.
     {
         json["type"] = "JSON";
         json["frequency"] = GetFrequency();
         json["file name"] = prefix_;
     }
void SSAGES::JSONObserver::Visit (const Driver & d) override virtual
Visit driver.
Parameters
d Driver to visit.
Implements SSAGES::Visitor.
Definition at line 149 of file JSONObserver.cpp.
References root_, and SSAGES::Driver::Serialize().
     {
         d.Serialize(root_);
     }
The documentation for this class was generated from the following files:
/home/cody/SSAGES/src/Observers/JSONObserver.h
/home/cody/SSAGES/src/Observers/JSONObserver.cpp