SSAGES: SSAGES::Hook Class Reference
SSAGES::Hook Class Reference abstract
Base class for hooks into the simultion engines.
#include <Hook.h>
Public Member Functions
Hook ()
Constructor.
void SetSnapshot (class Snapshot *snapshot)
Sets the active snapshot.
void SetCVManager (class CVManager *cvmanager)
Sets the current CV manager.
void AddListener (EventListener *listener)
Add a listener to the hook.
void NotifyObservers ()
Notify observers of changes in the simulation.
void PreSimulationHook ()
Pre-simulation hook.
void PostIntegrationHook ()
Post-integration hook.
void PostStepHook ()
Post-step hook.
void PostSimulationHook ()
Post-simulation hook.
virtual ~Hook ()
Destructor.
Protected Member Functions
virtual void SyncToEngine ()=0
Synchronization to the simulation engine.
virtual void SyncToSnapshot ()=0
Synchronization to the snapshot.
Protected Attributes
class Snapshot * snapshot_
Local snapshot.
Private Attributes
std::vector< EventListener * > listeners_
Vector of event listeners.
class CVManager * cvmanager_
Collective variable manager.
Detailed Description
Base class for hooks into the simultion engines.
Abstract base class responsible for hooking into simulation engine and calling appropriate events.
Definition at line 35 of file Hook.h.
Constructor & Destructor Documentation
SSAGES::Hook::Hook () inline
Constructor.
Initialize a hook with world and walker communicators and corresponding walker ID.
Definition at line 68 of file Hook.h.
References AddListener(), NotifyObservers(), PostIntegrationHook(), PreSimulationHook(), SetCVManager(), and SetSnapshot().
                :
         listeners_(0), snapshot_(nullptr)
         {}
Member Function Documentation
void SSAGES::Hook::AddListener (EventListener * listener)
Add a listener to the hook.
Parameters
listener Pointer to the EventListener to be added to the Hook.
Does nothing if the listener is already added.
Definition at line 101 of file Hook.cpp.
References listeners_.
Referenced by SSAGES::ResourceHandler::ConfigureHook(), and Hook().
     {
         if(std::find(listeners_.begin(), listeners_.end(), listener) == listeners_.end())
             listeners_.push_back(listener);
     }
void SSAGES::Hook::PostIntegrationHook ()
Post-integration hook.
This function should be called by the Hook implementation within the integration routine such that the forces, position, velocities, etc.. will be updated.
Definition at line 50 of file Hook.cpp.
References SSAGES::Snapshot::Changed(), cvmanager_, SSAGES::CVManager::GetCVs(), SSAGES::Snapshot::GetIteration(), SSAGES::Snapshot::HasChanged(), listeners_, snapshot_, and SyncToEngine().
Referenced by Hook().
     {
         snapshot_->Changed(false);
         for(auto& cv : cvmanager_->GetCVs())
             cv->Evaluate(*snapshot_);
         for(auto& listener : listeners_)
             if(snapshot_->GetIteration() % listener->GetFrequency() == 0)
                 listener->PostIntegration(snapshot_, *cvmanager_);
         if(snapshot_->HasChanged())
             SyncToEngine();
         snapshot_->Changed(false);
     }
void SSAGES::Hook::PostSimulationHook ()
Post-simulation hook.
This method should be called by the Hook implementation at the end of the simulation.
Definition at line 67 of file Hook.cpp.
References SSAGES::Snapshot::Changed(), cvmanager_, SSAGES::CVManager::GetCVs(), SSAGES::Snapshot::HasChanged(), listeners_, snapshot_, and SyncToEngine().
Referenced by PostStepHook().
     {
         snapshot_->Changed(false);
         for(auto& cv : cvmanager_->GetCVs())
             cv->Evaluate(*snapshot_);
         for(auto& listener : listeners_)
             listener->PostSimulation(snapshot_, *cvmanager_);
         if(snapshot_->HasChanged())
             SyncToEngine();
         snapshot_->Changed(false);
     }
void SSAGES::Hook::PostStepHook () inline
Post-step hook.
This function should be called by the Hook implementation after the integration routine such that the forces, position, velocities, etc.. are done being updated.
Definition at line 116 of file Hook.h.
References PostSimulationHook().
         {
         }
void SSAGES::Hook::PreSimulationHook ()
Pre-simulation hook.
This should be called at the appropriate time by the Hook implementation.
Definition at line 30 of file Hook.cpp.
References SSAGES::Snapshot::Changed(), cvmanager_, SSAGES::CVManager::GetCVs(), SSAGES::Snapshot::HasChanged(), listeners_, snapshot_, and SyncToEngine().
Referenced by Hook().
     {
         snapshot_->Changed(false);
         // Initialize/evaluate CVs.
         for(auto& cv : cvmanager_->GetCVs())
         {
             cv->Initialize(*snapshot_);
             cv->Evaluate(*snapshot_);
         }
         // Call presimulation method on listeners.
         for(auto& listener : listeners_)
             listener->PreSimulation(snapshot_, *cvmanager_);
         // Sync snapshot to engine.
         if(snapshot_->HasChanged())
             SyncToEngine();
         snapshot_->Changed(false);
     }
void SSAGES::Hook::SetCVManager (class CVManager * cvmanager)
Sets the current CV manager.
Sets the active CV manager.
Parameters
cvmanager Collective variable manager.
Definition at line 90 of file Hook.cpp.
References cvmanager_.
Referenced by SSAGES::ResourceHandler::ConfigureHook(), and Hook().
     {
         cvmanager_ = cvmanager;
     }
void SSAGES::Hook::SetSnapshot (class Snapshot * snapshot)
Sets the active snapshot.
Parameters
snapshot Current snapshot.
Definition at line 84 of file Hook.cpp.
References snapshot_.
Referenced by SSAGES::ResourceHandler::ConfigureHook(), and Hook().
     {
         snapshot_ = snapshot;
     }
virtual void SSAGES::Hook::SyncToEngine () protected pure virtual
Synchronization to the simulation engine.
A Hook must implement this method. It takes data from the snapshot and updates the simulation engine with it.
Referenced by PostIntegrationHook(), PostSimulationHook(), and PreSimulationHook().
virtual void SSAGES::Hook::SyncToSnapshot () protected pure virtual
Synchronization to the snapshot.
A Hook must implement this method. It takes data from the simulation eingine and updates the snapshot with it.
The documentation for this class was generated from the following files:
/home/cody/SSAGES-public/src/Hook.h
/home/cody/SSAGES-public/src/Hook.cpp