SSAGES: SSAGES::Constraint Class Reference
SSAGES::Constraint Class Reference abstract
Interface for Constraint implementations.
#include <Constraint.h>
Public Member Functions
Constraint (unsigned int frequency, boost::mpi::communicator &comm)
Constructor.
virtual ~Constraint ()
Destructor.
virtual void PreSimulation (Snapshot *snapshot, const CVList &cvs) override=0
Method call prior to simulation initiation.
virtual void PostIntegration (Snapshot *snapshot, const CVList &cvs) override=0
Method call post integration.
virtual void PostSimulation (Snapshot *snapshot, const CVList &cvs) override=0
Method call post simulation.
Public Member Functions inherited from SSAGES::EventListener
EventListener (unsigned int frequency)
Constructor.
unsigned int GetFrequency () const
Get frequency of event listener.
virtual ~EventListener ()
Destructor.
Public Member Functions inherited from SSAGES::Serializable
virtual void Serialize (Json::Value &json) const =0
Serialize the class.
virtual ~Serializable ()
Destructor.
Static Public Member Functions
static Constraint * BuildConstraint (const Json::Value &json, boost::mpi::communicator &comm)
Build a constraint from a JSON node.
static Constraint * BuildConstraint (const Json::Value &json, boost::mpi::communicator &comm, const std::string &path)
Overloaded function allowing JSON path specification.
static void BuildConstraint (const Json::Value &json, ConstraintList &clist, boost::mpi::communicator &comm, const std::string &path)
Build constraint.
Protected Attributes
boost::mpi::communicator comm_
MPI global communicator.
Detailed Description
Interface for Constraint implementations.
Definition at line 41 of file Constraint.h.
Constructor & Destructor Documentation
SSAGES::Constraint::Constraint (unsigned int frequency, boost::mpi::communicator & comm) inline
Constructor.
Parameters
frequency Frequency of sampling.
comm MPI global communicator.
Note
Frequency of sampling must be specified by all methods.
Definition at line 55 of file Constraint.h.
                                         :
         EventListener(frequency), comm_(comm){}
Member Function Documentation
Constraint * SSAGES::Constraint::BuildConstraint (const Json::Value & json, boost::mpi::communicator & comm) static
Build a constraint from a JSON node.
Parameters
json JSON value containing input information.
comm MPI communicator.
Returns
Pointer to the new constraint. nullptr in case of an unknown error.
This function builds a constraint from a JSON node. Returns a pointer to the built constraint. If an unknown error occured, the return value is nullptr, but in general, a BuildException will be thrown on failure.
Note
Object lifetime is the caller's responsibility.
Definition at line 33 of file Constraint.cpp.
Referenced by SSAGES::Driver::BuildConstraints().
     {
         return BuildConstraint(json, comm, "#/Constraints");
     }
Constraint * SSAGES::Constraint::BuildConstraint (const Json::Value & json, boost::mpi::communicator & comm, const std::string & path) static
Overloaded function allowing JSON path specification.
Parameters
json JSON value containing input information.
comm MPI global communicator.
path Path for JSON path specification.
Returns
Pointer to the new constraint. nullptr in case of an unknown error.
Definition at line 39 of file Constraint.cpp.
References Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), and Json::ObjectRequirement::Validate().
     {
         ObjectRequirement validator;
         Value schema;
         Reader reader;
         Constraint* constraint = nullptr;
         // Random device for seed generation.
         // std::random_device rd;
         // auto maxi = std::numeric_limits<int>::max();
         // auto seed = json.get("seed", rd() % maxi).asUInt();
         // Get move type.
         std::string type = json.get("type", "none").asString();
         if(type == "COPSS")
         {
             reader.parse(JsonSchema::COPSSConstraint, schema);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             auto* c = new COPSS(comm, 1);
             constraint = static_cast<Constraint*>(c);
         }
         else if(type == "COPSSImage")
         {
             reader.parse(JsonSchema::COPSSImageConstraint, schema);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             double einner = json.get("einner",1).asDouble();
             int ion_type_start = json.get("ion_type_start",1).asInt();
             std::vector<double> atomTypeRadius;
             for(auto& atomType : json["atom type radius"])
                 atomTypeRadius.push_back(atomType.asDouble());
             auto* c = new COPSSImage(comm, 1, einner, ion_type_start, atomTypeRadius);
             constraint = static_cast<Constraint*>(c);
         }
         else
         {
             throw BuildException({path + ": Unknown constraint type specified."+type+" is not a valid type!"});
         }
         return constraint;
     }
void SSAGES::Constraint::BuildConstraint (const Json::Value & json, ConstraintList & clist, boost::mpi::communicator & comm, const std::string & path) static
Build constraint.
Parameters
json JSON value containing input information.
clist List of constraints.
comm MPI global communicator.
path Path for JSON path specification.
This function builds a new constraint and adds it to the specified list of constraints. On failure, an exception is thrown.
Note
Object lifetime management is caller's responsibility.
Definition at line 102 of file Constraint.cpp.
References BuildConstraint(), Json::Requirement::GetErrors(), Json::Requirement::HasErrors(), Json::ArrayRequirement::Parse(), and Json::ArrayRequirement::Validate().
Referenced by BuildConstraint().
     {
         ArrayRequirement validator;
         Value schema;
         Reader reader;
         reader.parse(JsonSchema::constraints, schema);
         validator.Parse(schema, path);
         // Validate high level schema.
         validator.Validate(json, path);
         if(validator.HasErrors())
             throw BuildException(validator.GetErrors());
         // Loop through CVs.
         int i = 0;
         for(auto& m : json)
         {
             clist.push_back(BuildConstraint(m, comm, path + "/" + std::to_string(i)));
             ++i;
         }
     }
virtual void SSAGES::Constraint::PostIntegration (Snapshot * snapshot, const CVList & cvs) override pure virtual
Method call post integration.
Parameters
snapshot Pointer to current snapshot.
cvs List of CVs.
Implements SSAGES::EventListener.
Implemented in SSAGES::COPSSImage, and SSAGES::COPSS.
virtual void SSAGES::Constraint::PostSimulation (Snapshot * snapshot, const CVList & cvs) override pure virtual
Method call post simulation.
Parameters
snapshot Pointer to current snapshot.
cvs List of CVs.
Implements SSAGES::EventListener.
Implemented in SSAGES::COPSSImage, and SSAGES::COPSS.
virtual void SSAGES::Constraint::PreSimulation (Snapshot * snapshot, const CVList & cvs) override pure virtual
Method call prior to simulation initiation.
Parameters
snapshot Simulation snapshot.
cvs List of CVs.
Implements SSAGES::EventListener.
Implemented in SSAGES::COPSSImage, and SSAGES::COPSS.
The documentation for this class was generated from the following files:
/home/cody/SSAGES/src/Constraints/Constraint.h
/home/cody/SSAGES/src/Constraints/Constraint.cpp