SSAGES: SSAGES::GyrationTensorCV Class Reference
SSAGES::GyrationTensorCV Class Reference
CVs
Collective variable on components of the gyration tensor.
#include <GyrationTensorCV.h>
Public Member Functions
GyrationTensorCV (const Label &atomids, GyrationTensor component)
Constructor.
GyrationTensorCV (const Label &atomids, GyrationTensor component, bool dimx, bool dimy, bool dimz)
Constructor.
void Initialize (const Snapshot &snapshot) override
Initialize necessary variables.
void Evaluate (const Snapshot &snapshot) override
Evaluate the CV.
Public Member Functions inherited from SSAGES::CollectiveVariable
CollectiveVariable ()
Constructor.
virtual ~CollectiveVariable ()
Destructor.
virtual void Initialize (const class Snapshot &)
Initialize CV.
virtual void Evaluate (const class Snapshot &)=0
Evaluate CV.
double GetValue () const
Get current value of the CV.
virtual double GetMinimumImage (double) const
Returns the minimum image of a CV based on the input location.
virtual double GetPeriodicValue (double location) const
Apply periodic boundaries to a given value.
const std::vector< Vector3 > & GetGradient () const
Get current gradient of the CV.
const Matrix3 & GetBoxGradient () const
Get gradient contribution to box.
const std::array< double, 2 > & GetBoundaries ()
Get CV boundaries.
virtual double GetDifference (double location) const
Static Public Member Functions
static GyrationTensorCV * Build (const Json::Value &json, const std::string &path)
Set up collective variable.
Static Public Member Functions inherited from SSAGES::CollectiveVariable
static CollectiveVariable * BuildCV (const Json::Value &json, const std::string &path)
Set up collective variable.
Private Attributes
Label atomids_
IDs of the atoms used for calculation.
GyrationTensor component_
Component of gyration tensor to compute.
Bool3 dim_
Each dimension determines if it is applied by the CV.
Additional Inherited Members
Protected Attributes inherited from SSAGES::CollectiveVariable
std::vector< Vector3 > grad_
Gradient vector dCv/dxi.
Matrix3 boxgrad_
Gradient w.r.t box vectors dCv/dHij.
double val_
Current value of CV.
std::array< double, 2 > bounds_
Bounds on CV.
Detailed Description
Collective variable on components of the gyration tensor.
Collective variable on components of gyration tensor. Depending on the user selection, this will specify a principal moment, radius of gyration, or another shape descriptor.
Definition at line 56 of file GyrationTensorCV.h.
Constructor & Destructor Documentation
GyrationTensorCV() [1/2]
SSAGES::GyrationTensorCV::GyrationTensorCV (const Label & atomids, GyrationTensor component) inline
Constructor.
Parameters
atomids IDs of the atoms defining gyration tensor.
component Specification of component to compute.
Construct a GyrationTensorCV.
Definition at line 74 of file GyrationTensorCV.h.
                                                                          :
         atomids_(atomids), component_(component), dim_{true, true, true}
         {
         }
Referenced by Build().
GyrationTensorCV() [2/2]
SSAGES::GyrationTensorCV::GyrationTensorCV (const Label & atomids, GyrationTensor component, bool dimx, bool dimy, bool dimz) inline
Constructor.
Parameters
atomids IDs of the atoms defining gyration tensor.
component Specification of component to compute.
dimx If True, include x dimension.
dimy If True, include y dimension.
dimz If True, include z dimension.
Construct a GyrationTensorCV.
Definition at line 90 of file GyrationTensorCV.h.
                                                                                                           :
         atomids_(atomids), component_(component), dim_{dimx, dimy, dimz}
         {
         }
Member Function Documentation
Build()
static GyrationTensorCV* SSAGES::GyrationTensorCV::Build (const Json::Value & json, const std::string & path) inline static
Set up collective variable.
Parameters
json JSON input value.
path Path for JSON path specification.
Returns
Pointer to the CV built by this function. nullptr in case of unknown error.
Builds a CV from a JSON node. Returns a pointer to the built cv. If an unknown error is encountered, this function will return a nullptr, but generally it will throw a BuildException on failure.
Warning
Object lifetime is the caller's responsibility.
Definition at line 246 of file GyrationTensorCV.h.
         {
             Json::ObjectRequirement validator;
             Json::Value schema;
             Json::CharReaderBuilder rbuilder;
             Json::CharReader* reader = rbuilder.newCharReader();
             reader->parse(JsonSchema::GyrationTensorCV.c_str(),
                           JsonSchema::GyrationTensorCV.c_str() + JsonSchema::GyrationTensorCV.size(),
                           &schema, nullptr);
             validator.Parse(schema, path);
             // Validate inputs.
             validator.Validate(json, path);
             if(validator.HasErrors())
                 throw BuildException(validator.GetErrors());
             std::vector<int> atomids;
             for(auto& s : json["atom_ids"])
                 atomids.push_back(s.asInt());
             GyrationTensor component = Rg;
             auto comp = json["component"].asString();
             if(comp == "Rg")
                 component = Rg;
             else if(comp == "principal1")
                 component = principal1;
             else if(comp == "principal2")
                 component = principal2;
             else if(comp == "principal3")
                 component = principal3;
             else if(comp == "asphericity")
                 component = asphericity;
             else if(comp == "acylindricity")
                 component = acylindricity;
             else if(comp == "shapeaniso")
                 component = shapeaniso;
             GyrationTensorCV* c;
             if(json.isMember("dimension"))
             {
                 auto dimx = json["dimension"][0].asBool();
                 auto dimy = json["dimension"][1].asBool();
                 auto dimz = json["dimension"][2].asBool();
                 c = new GyrationTensorCV(atomids, component, dimx, dimy, dimz);
             }
             else
                 c = new GyrationTensorCV(atomids, component);
             return c;
         }
References Json::Requirement::GetErrors(), GyrationTensorCV(), Json::Requirement::HasErrors(), Json::ObjectRequirement::Parse(), and Json::ObjectRequirement::Validate().
Referenced by SSAGES::CollectiveVariable::BuildCV().
Evaluate()
void SSAGES::GyrationTensorCV::Evaluate (const Snapshot & snapshot) inline override
Evaluate the CV.
Parameters
snapshot Current simulation snapshot.
Definition at line 128 of file GyrationTensorCV.h.
         {
             using namespace Eigen;
             // Get local atom indices and compute COM.
             std::vector<int> idx;
             snapshot.GetLocalIndices(atomids_, &idx);
             // Get data from snapshot.
             auto n = snapshot.GetNumAtoms();
             const auto& masses = snapshot.GetMasses();
             const auto& pos = snapshot.GetPositions();
             // Initialize gradient.
             std::fill(grad_.begin(), grad_.end(), Vector3{0,0,0});
             grad_.resize(n, Vector3{0,0,0});
             // Compute total and center of mass.
             auto masstot = snapshot.TotalMass(idx);
             Vector3 com = snapshot.CenterOfMass(idx);
             // Gyration tensor and temporary vector to store positions in inertial frame.
             Matrix3 S = Matrix3::Zero();
             std::vector<Vector3> ris;
             ris.reserve(idx.size());
             for(auto& i : idx)
             {
                 ris.emplace_back(snapshot.ApplyMinimumImage(pos[i] - com).cwiseProduct(dim_.cast<double>()));
                 S.noalias() += masses[i]*ris.back()*ris.back().transpose();
             }
             // Reduce gyration tensor across processors and normalize.
             MPI_Allreduce(MPI_IN_PLACE, S.data(), S.size(), MPI_DOUBLE, MPI_SUM, snapshot.GetCommunicator());
             S /= masstot;
             // Perform EVD. The columns are the eigenvectors.
             // SelfAdjoint solver sorts in ascending order.
             SelfAdjointEigenSolver<Matrix3> solver;
             solver.computeDirect(S);
             const auto& eigvals = solver.eigenvalues();
             const auto& eigvecs = solver.eigenvectors();
             // Assign variables for clarity. l1 is largest.
             auto l1 = eigvals[2],
                  l2 = eigvals[1],
                  l3 = eigvals[0];
             const auto& n1 = eigvecs.col(2),
                         n2 = eigvecs.col(1),
                         n3 = eigvecs.col(0);
             val_ = 0;
             auto sum = l1 + l2 + l3;
             auto sqsum = l1*l1 + l2*l2 + l3*l3;
             switch(component_)
             {
                 case Rg:
                     val_ = sum;
                     break;
                 case principal1:
                     val_ = l1;
                     break;
                 case principal2:
                     val_ = l2;
                     break;
                 case principal3:
                     val_ = l3;
                     break;
                 case asphericity:
                     val_ = l1 - 0.5*(l2 + l3);
                     break;
                 case acylindricity:
                     val_ = l2 - l3;
                     break;
                 case shapeaniso:
                     val_ = 1.5*sqsum/(sum*sum) - 0.5;
                     break;
             }
             // Compute gradient.
             size_t j = 0;
             for(auto& i : idx)
             {
                 // Compute derivative of each eigenvalue and use combos in components.
                 auto dl1 = 2.*masses[i]/masstot*(1.-masses[i]/masstot)*ris[j].dot(n1)*n1;
                 auto dl2 = 2.*masses[i]/masstot*(1.-masses[i]/masstot)*ris[j].dot(n2)*n2;
                 auto dl3 = 2.*masses[i]/masstot*(1.-masses[i]/masstot)*ris[j].dot(n3)*n3;
                 switch(component_)
                 {
                     case Rg:
                         grad_[i] = dl1 + dl2 + dl3;
                         break;
                     case principal1:
                         grad_[i] = dl1;
                         break;
                     case principal2:
                         grad_[i] = dl2;
                         break;
                     case principal3:
                         grad_[i] = dl3;
                         break;
                     case asphericity:
                         grad_[i] = dl1 - 0.5*(dl2 + dl3);
                         break;
                     case acylindricity:
                         grad_[i] = dl2 - dl3;
                         break;
                     case shapeaniso:
                         grad_[i] = 3.*(l1*dl1+l2*dl2+l3*dl3)/(sum*sum) -
                                    3.*sqsum*(dl1+dl2+dl3)/(sum*sum*sum);
                         break;
                 }
                 ++j;
             }
         }
References SSAGES::Snapshot::ApplyMinimumImage(), atomids_, SSAGES::Snapshot::CenterOfMass(), component_, dim_, SSAGES::Snapshot::GetCommunicator(), SSAGES::Snapshot::GetLocalIndices(), SSAGES::Snapshot::GetMasses(), SSAGES::Snapshot::GetNumAtoms(), SSAGES::Snapshot::GetPositions(), SSAGES::CollectiveVariable::grad_, SSAGES::Snapshot::TotalMass(), and SSAGES::CollectiveVariable::val_.
Initialize()
void SSAGES::GyrationTensorCV::Initialize (const Snapshot & snapshot) inline override
Initialize necessary variables.
Parameters
snapshot Current simulation snapshot.
Definition at line 99 of file GyrationTensorCV.h.
         {
             using std::to_string;
             auto n = atomids_.size();
             // Make sure atom ID's are on at least one processor.
             std::vector<int> found(n, 0);
             for(size_t i = 0; i < n; ++i)
             {
                 if(snapshot.GetLocalIndex(atomids_[i]) != -1)
                     found[i] = 1;
             }
             MPI_Allreduce(MPI_IN_PLACE, found.data(), n, MPI_INT, MPI_SUM, snapshot.GetCommunicator());
             unsigned ntot = std::accumulate(found.begin(), found.end(), 0, std::plus<int>());
             if(ntot != n)
                 throw BuildException({
                     "GyrationTensorCV: Expected to find " +
                     to_string(n) +
                     " atoms, but only found " +
                     to_string(ntot) + "."
                 });
         }
References atomids_, SSAGES::Snapshot::GetCommunicator(), and SSAGES::Snapshot::GetLocalIndex().
The documentation for this class was generated from the following file:
/home/michael/development/SSAGES/src/CVs/GyrationTensorCV.h