SSAGES: SSAGES Namespace Reference
SSAGES Namespace Reference
Classes
class AlphaRMSDCV
Collective variable to measure alpha helix secondary structure.
class AngleCV
Collective variable to calculate angle.
class ANNCV
ANN (artifical neural network) collective variables.
class AntiBetaRMSDCV
Collective variable to measure antiparallel beta secondary structure.
class BoxVolumeCV
Collective variable on the volume of a box.
class CollectiveVariable
Abstract class for a collective variable.
class CVManager
Collective variable manager.
class GyrationTensorCV
Collective variable on components of the gyration tensor.
class MockCV
Mock collective variable for testing purposes.
class PairwiseCV
Generalized collective variable based on pairwise properties of atoms.
class ParallelBetaRMSDCV
Collective variable to measure parallel beta sheet secondary structure.
class ParticleCoordinateCV
Collective variable on a particle coordinate.
class ParticlePositionCV
Collective variable on an particle position.
class ParticleSeparationCV
Collective variable on the distance between two particles' centers of mass.
class RMSDCV
Collective variable to calculate root mean square displacement.
class RouseModeCV
Collective variable is a Rouse mode for a polymer chain comprised of N particle groups.
class TorsionalCV
Collective variable on the torsion angles.
class BuildException
Exception to be thrown when building the Driver fails.
class EventListener
Base abstract class for listening in to events fired by "Hook".
class Grid
Basic Grid.
class GridBase
Base class for Grids.
class Hook
Base class for hooks into the simultion engines.
class JSONLoader
Class for loading JSON content from files.
class JSONLoaderPlugin
Abstract class for JSON loader plugins.
class IncludePlugin
Class for JSON loader include plugin.
class Logger
Base class for logging SSAGES data.
class ABF
Adaptive Biasing Force Algorithm.
class ANN
Artificial Neural Network Method.
class BFS
Basis Function Sampling Algorithm.
class CFF
Combined Force Frequency (CFF) Algorithm.
class DirectForwardFlux
ForwardFlux sampling method.
class ElasticBand
Multi-walker Elastic Band.
class FiniteTempString
Finite Temperature Spring Method.
class ForwardFlux
ForwardFlux sampling method.
struct Hill
Multidimensional hill.
class Meta
"Vanilla" multi-dimensional Metadynamics.
class Method
Interface for Method implementations.
class StringMethod
String base class for FTS, Swarm, and elastic band.
class Swarm
Swarm of Trajectories String Method.
class Umbrella
Umbrella sampling method.
class ResourceHandler
Class that handles SSAGES resources for a simulation.
class Snapshot
Class containing a snapshot of the current simulation in time.
struct BasisLUT
Look-up table for basis functions.
struct Map
Map for histogram and coefficients.
class BasisFunction
Abstract class for all BasisFunction inheritance.
class Chebyshev
Defines the class of Chebyshev polynomials.
class Legendre
Defines the class of Legendre polynomials.
class Fourier
Defines the class of Fourier polynomials.
class BasisEvaluator
Calculates the inner product of all the basis functions and the histogram.
class PairwiseKernel
Pairwise kernel base class.
class GaussianPK
Gaussian Function.
class RationalSwitchPK
Rational Switching Function.
class ReadBackbone
Utility class to read protein backbone atoms from a reference file.
class ReadFile
Utility class to read file.
Typedefs
using Vector = Eigen::VectorXd
Arbitrary length vector.
using Vector3 = Eigen::Vector3d
Three-dimensional vector.
using Bool3 = Eigen::Matrix< bool, 3, 1 >
Three-dimensional boolean.
using Integer3 = Eigen::Vector3i
Three-dimensional integer vector.
using Matrix3 = Eigen::Matrix3d
3x3 matrix.
using Matrix3N = Eigen::MatrixX3d
nx3 matrix.
using Label = std::vector< int >
List of integers.
using CVList = std::vector< CollectiveVariable * >
List of Collective Variables.
Enumerations
enum GyrationTensor {
Rg = 0 , principal1 = 1 , principal2 = 2 , principal3 = 3 ,
asphericity = 4 , acylindricity = 5 , shapeaniso = 6
}
Define components of gyration tensor.
enum class Dimension { x = 0 , y = 1 , z = 2 }
Enum for dimension.
Functions
void PrintBoldNotice (const std::string &notice, int msgw)
Print out Notice in bold text.
int DumpErrorsToConsole (const std::vector< std::string > &msgs, int notw)
Print a list of errors.
void DumpNoticesToConsole (const std::vector< std::string > &msgs, std::string prefix, int notw)
Print a list of notices.
std::string GetFileContents (const std::string filename)
Read contents from a file.
std::string GetFilePath (const std::string filename)
Gets file path from filename.
double gaussian (double dx, double sigma)
Evlauate Gaussian. Helper function.
double gaussianDerv (double dx, double sigma)
Evaluate Gaussian derivative. Helper function.
double roundf (double x)
Quick helper function to round a double.
Detailed Description
The global namespace for all SSAGES classes and functions.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2017 Ashley Guo azguo.nosp@m.@uch.nosp@m.icago.nosp@m..edu
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2016 Yamil Colon yamil.nosp@m.colo.nosp@m.n2015.nosp@m.@u.n.nosp@m.orthw.nosp@m.este.nosp@m.rn.ed.nosp@m.u Hythem Sidky hsidk.nosp@m.y@nd.nosp@m..edu
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2020 Wei Chen wei.h.nosp@m.erbe.nosp@m.rt.ch.nosp@m.en@g.nosp@m.mail..nosp@m.com
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2016 Hythem Sidky hsidk.nosp@m.y@nd.nosp@m..edu
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2016 Ben Sikora bsiko.nosp@m.ra90.nosp@m.6@gma.nosp@m.il.c.nosp@m.om Emre Sevgen sesev.nosp@m.gen@.nosp@m.uchic.nosp@m.ago..nosp@m.edu Yamil Colon yamil.nosp@m.colo.nosp@m.n2015.nosp@m.@u.n.nosp@m.orthw.nosp@m.este.nosp@m.rn.ed.nosp@m.u
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2017 Hythem Sidky hsidk.nosp@m.y@nd.nosp@m..edu
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2016 Ben Sikora bsiko.nosp@m.ra90.nosp@m.6@gma.nosp@m.il.c.nosp@m.om
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2017 Hythem Sidky hsidk.nosp@m.y@nd.nosp@m..edu Michael Quevillon mquev.nosp@m.ill@.nosp@m.nd.ed.nosp@m.u
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2017 Michael Webb xmweb.nosp@m.b@gm.nosp@m.ail.c.nosp@m.om
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2016 Hythem Sidky hsidk.nosp@m.y@nd.nosp@m..edu Ben Sikora bsiko.nosp@m.ra90.nosp@m.6@gma.nosp@m.il.c.nosp@m.om Emre Sevgen sesev.nosp@m.gen@.nosp@m.uchic.nosp@m.ago..nosp@m.edu
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file has been obtained from SAPHRON - Statistical Applied PHysics through Random On-the-fly Numerics https://github.com/hsidky/SAPHRON
Copyright 2017 Hythem Sidky
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2016-2017 Julian Helfferich julia.nosp@m.n.he.nosp@m.lffer.nosp@m.ich@.nosp@m.gmail.nosp@m..com
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2017 Julian Helfferich julia.nosp@m.n.he.nosp@m.lffer.nosp@m.ich@.nosp@m.gmail.nosp@m..com
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2016 Ben Sikora bsiko.nosp@m.ra90.nosp@m.6@gma.nosp@m.il.c.nosp@m.om Hythem Sidky hsidk.nosp@m.y@nd.nosp@m..edu
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2016 Hythem Sidky hsidk.nosp@m.y@nd.nosp@m..edu Ben Sikora bsiko.nosp@m.ra90.nosp@m.6@gma.nosp@m.il.c.nosp@m.om
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file has been adapted from SAPHRON - Statistical Applied PHysics through Random On-the-fly Numerics https://github.com/hsidky/SAPHRON
Copyright 2016 Hythem Sidky
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2016 Emre Sevgen sesev.nosp@m.gen@.nosp@m.uchic.nosp@m.ago..nosp@m.edu Joshua Moller jmoll.nosp@m.er@u.nosp@m.chica.nosp@m.go.e.nosp@m.du Hythem Sidky hsidk.nosp@m.y@nd.nosp@m..edu
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2016 Joshua Moller jmoll.nosp@m.er@u.nosp@m.chica.nosp@m.go.e.nosp@m.du 2017 Julian Helfferich julia.nosp@m.n.he.nosp@m.lffer.nosp@m.ich@.nosp@m.gmail.nosp@m..com
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced Generalized Ensemble Simulations
Copyright 2018 Emre Sevgen sesev.nosp@m.gen@.nosp@m.uchic.nosp@m.ago..nosp@m.edu and Hythem Sidky hsidk.nosp@m.y@nd.nosp@m..edu 2020 Elizabeth M.Y. Lee emlee.nosp@m.@uch.nosp@m.icago.nosp@m..edu and Boyuan Yu boyua.nosp@m.nyu@.nosp@m.uchic.nosp@m.ago..nosp@m.edu
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2016 Ben Sikora bsiko.nosp@m.ra90.nosp@m.6@gma.nosp@m.il.c.nosp@m.om Hythem Sidky hsidk.nosp@m.y@nd.nosp@m..edu Joshua Lequieu lequi.nosp@m.eu@u.nosp@m.chica.nosp@m.go.e.nosp@m.du Hadi Ramezani-Dakhel ramez.nosp@m.ani@.nosp@m.uchic.nosp@m.ago..nosp@m.edu
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2016 Ben Sikora bsiko.nosp@m.ra90.nosp@m.6@gma.nosp@m.il.c.nosp@m.om Joshua Lequieu lequi.nosp@m.eu@u.nosp@m.chica.nosp@m.go.e.nosp@m.du Hadi Ramezani-Dakhel ramez.nosp@m.ani@.nosp@m.uchic.nosp@m.ago..nosp@m.edu
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2016 Ben Sikora bsiko.nosp@m.ra90.nosp@m.6@gma.nosp@m.il.c.nosp@m.om Jonathan K. Whitmer jwhit.nosp@m.me1@.nosp@m.nd.ed.nosp@m.u
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2016 Ashley Guo azguo.nosp@m.@uch.nosp@m.icago.nosp@m..edu Ben Sikora bsiko.nosp@m.ra90.nosp@m.6@gma.nosp@m.il.c.nosp@m.om
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2016 Hythem Sidky hsidk.nosp@m.y@nd.nosp@m..edu Jonathan K. Whitmer jwhit.nosp@m.me1@.nosp@m.nd.ed.nosp@m.u Ben Sikora bsiko.nosp@m.ra90.nosp@m.6@gma.nosp@m.il.c.nosp@m.om
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2016 Ben Sikora bsiko.nosp@m.ra90.nosp@m.6@gma.nosp@m.il.c.nosp@m.om Ashley Guo azguo.nosp@m.@uch.nosp@m.icago.nosp@m..edu Cody Bezik bezik.nosp@m.@uch.nosp@m.icago.nosp@m..edu
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
* This file is part of
* SSAGES - Software Suite for Advanced General Ensemble Simulations
*
* Copyright 2016 Cody Bezik bezik.nosp@m.@uch.nosp@m.icago.nosp@m..edu
*
* SSAGES is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* SSAGES is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2017 Hythem Sidky hsidk.nosp@m.y@nd.nosp@m..edu Ben Sikora bsiko.nosp@m.ra90.nosp@m.6@gma.nosp@m.il.c.nosp@m.om
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
This file is part of SSAGES - Software Suite for Advanced General Ensemble Simulations
Copyright 2016 Yamil Colon yamil.nosp@m.colo.nosp@m.n2015.nosp@m.@u.n.nosp@m.orthw.nosp@m.este.nosp@m.rn.ed.nosp@m.u
SSAGES is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
SSAGES is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with SSAGES. If not, see http://www.gnu.org/licenses/.
Enumeration Type Documentation
GyrationTensor
enum SSAGES::GyrationTensor
Define components of gyration tensor.
Components of the gyration tensor. CV uses these definitions to determine what to calculate.
Definition at line 37 of file GyrationTensorCV.h.
     {
         Rg = 0, // Radius of gyration (squared)
         principal1 = 1, // First (largest) principal moment
         principal2 = 2, // Second (middle) principal moment
         principal3 = 3, // Third (smallest) principal moment
         asphericity = 4, // Asphericity
         acylindricity = 5, // Acylindricity
         shapeaniso = 6 // Relative shape anisotropy
     };
Function Documentation
DumpErrorsToConsole()
int SSAGES::DumpErrorsToConsole (const std::vector< std::string > & msgs, int notw) inline
Print a list of errors.
Parameters
msgs List of error messages.
notw Width of the messages.
Returns
-1 always.
Write a list of error messages to the console.
Definition at line 103 of file DriverException.h.
     {
         if(isatty(fileno(stdout)))
         {
             std::cout << std::setw(notw) << std::right << "\033[1;31mError(s)! See below.\033[0m\n";
         }
         else
         {
             std::cout << std::setw(notw) << std::right << "Error(s)! See below.\n";
         }
         for(auto& msg : msgs)
                 std::cout << " * " << msg << "\n";
         return -1;
     }
DumpNoticesToConsole()
void SSAGES::DumpNoticesToConsole (const std::vector< std::string > & msgs, std::string prefix, int notw) inline
Print a list of notices.
Parameters
msgs List of messages.
prefix Prefix to prepend to each message.
notw Width of the messages.
Definition at line 124 of file DriverException.h.
     {
         if(isatty(fileno(stdout)))
         {
             std::cout << std::setw(notw) << std::right << "\033[32mOK!\033[0m\n";
         }
         else
         {
             std::cout << std::setw(notw) << std::right << "OK!\n";
         }
         if(msgs.size() == 0)
             return;
         for(auto& msg : msgs)
             std::cout << prefix << " * " << msg << "\n";
     }
gaussian()
double SSAGES::gaussian (double dx, double sigma)
Evlauate Gaussian. Helper function.
Parameters
dx x-value.
sigma Width of Gaussian
Returns
Value at x of Gaussian with center at zero and width sigma.
Definition at line 42 of file Meta.cpp.
     {
         double arg = (dx * dx) / (2. * sigma * sigma);
         return exp(-arg);
     }
References gaussian().
Referenced by SSAGES::Meta::AddHill(), SSAGES::Meta::CalcBiasForce(), and gaussian().
gaussianDerv()
double SSAGES::gaussianDerv (double dx, double sigma)
Evaluate Gaussian derivative. Helper function.
Parameters
dx Value of x.
sigma Width of Gaussian.
Returns
Derivative at x of Gaussian with center at zero and width sigma.
Definition at line 54 of file Meta.cpp.
     {
         double arg =  (dx * dx) / (2. * sigma * sigma);
         double pre = - dx / (sigma * sigma);
         return pre * exp(-arg);
     }
References gaussianDerv().
Referenced by SSAGES::Meta::AddHill(), SSAGES::Meta::CalcBiasForce(), and gaussianDerv().
GetFileContents()
std::string SSAGES::GetFileContents (const std::string filename) inline
Read contents from a file.
Parameters
filename Name of the file to read from.
Returns
String containing the contents of the file.
Retrieves the contents of a file and returns them in a string. Throws exception on failure.
Definition at line 46 of file FileContents.h.
     {
         std::ifstream ifs(filename);
         if(ifs.is_open()) {
             std::string contents( (std::istreambuf_iterator<char>(ifs) ),
                                   (std::istreambuf_iterator<char>()    ) );
             return contents;
         }
         throw std::runtime_error("File " + filename + " does not exist.");
     }
Referenced by SSAGES::IncludePlugin::ApplyFilter(), and SSAGES::JSONLoader::LoadFile().
GetFilePath()
std::string SSAGES::GetFilePath (const std::string filename) inline
Gets file path from filename.
Parameters
filename String containing the absolute filename.
Returns
String containing only the directory path.
Definition at line 62 of file FileContents.h.
     {
         size_t found;
         found = filename.find_last_of("/\\");
         if(found == filename.npos)
             return "./";
         return filename.substr(0, found);
     }
Referenced by SSAGES::JSONLoader::LoadFile().
PrintBoldNotice()
void SSAGES::PrintBoldNotice (const std::string & notice, int msgw) inline
Print out Notice in bold text.
Parameters
notice Text to be written to console.
msgw Width of the message.
Definition at line 83 of file DriverException.h.
     {
         if(isatty(fileno(stdout)))
         {
             std::cout << std::setw(msgw + 8) << std::left << "\033[1m" + notice + "\033[0m";
         }
         else
         {
             std::cout << std::setw(msgw + 8) << std::left << notice;
         }
     }
roundf()
double SSAGES::roundf (double x) inline
Quick helper function to round a double.
Parameters
x Double to be rounded.
Returns
Rounded number as a double.
Definition at line 35 of file Snapshot.h.
     {
         return ( x >= 0 ) ? floor( x + 0.5 ) : ceil( x - 0.5 );
     }
Referenced by SSAGES::Snapshot::ApplyMinimumImage().